solver_interfaces Module Reference
Functions/Subroutines
subroutine, public ldu_face (A, b, x, itmax1, reps1, ilev1, itfin1, repsfin1, ll1, ll2, cond1, opcnt1, errcode1)
subroutine, public cg_face (A, b, x, itmax1, reps1, ilev1, itfin1, repsfin1, ll1, ll2, cond1, opcnt1, errcode1)
subroutine, public cg_normal_face (A, b, x, itmax1, reps1, ilev1, itfin1, repsfin1, ll1, ll2, cond1, opcnt1, errcode1)
subroutine, public jacobi_face (A, b, x, itmax1, reps1, ilev1, itfin1, repsfin1, ll1, ll2, cond1, opcnt1, errcode1)
subroutine, public null_problem (A, b)
Function/Subroutine Documentation
subroutine, public solver_interfaces::cg_face (class(matrix), intent(inout) A, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional itmax1, real(kind=rkind), intent(in), optional reps1, integer, intent(in), optional ilev1, integer(kind=ikind), intent(out), optional itfin1, real(kind=rkind), intent(out), optional repsfin1, real(kind=rkind), intent(out), optional ll1, real(kind=rkind), intent(out), optional ll2, real(kind=rkind), intent(out), optional cond1, type(tcount), intent(out), optional opcnt1, integer, intent(out), optional errcode1)
Parameters
in,out a matice soustavy
 musi poskytovat getn, getm, mul (nasobeni vektorem)
in b vektor prave strany
in,out x aproximace reseni, postupne menena
in itmax1 maximalni povoleny pocet iteraci, default = n (Rozmer matice)
in reps1 pozadovana relativni zmena rezidua, default = 1e-6
in ilev1 informacni podrobnost
0 ... pracuj tise
1 ... minimalni informace
10 ... maximalni ukecanost
out itfin1 skutecne provedeny pocet iteraci
out repsfin1 skutecne dosazena relativni zmena residua
out ll1 odhad nejvetsiho vlastniho cisla
out ll2 odhad nejmensiho vlastniho cisla
out cond1 odhad cisla podminenosti : cond1 = ll1/ll2
out opcnt1 celkovy pocet provedenych operaci a cas behu
out errcode1 kod pripadnr chyby
0 ... OK
1 ... matice neni ctvercova
2 ... nesouhlasi b
3 ... nesouhasi x
4 ... ani jeden z vektoru nesouhlasi
5 ... vycerpan povoleny pocet iteraci
6 ... prestalo klesat residuum i energie
Definition at line 75 of file solver_interfaces.f90.
References solvers::cg().
        use mtx
        use typy
        use sparsematrix
        use solvers
        implicit none
        class(matrix), intent(in out) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(in out) :: x
        integer(kind=ikind), intent(in), optional :: itmax1
        real(kind=rkind), intent(in), optional :: reps1
        integer, intent(in), optional :: ilev1
        integer(kind=ikind), intent(out), optional :: itfin1
        real(kind=rkind), intent(out), optional :: repsfin1
        real(kind=rkind), intent(out), optional :: ll1
        real(kind=rkind), intent(out), optional :: ll2
        real(kind=rkind), intent(out), optional :: cond1
        type(tcount), intent(out), optional :: opcnt1
        integer, intent(out), optional :: errcode1
        integer :: ilevel
        if (.not. present(ilev1)) then
          ilevel = 0
        else
          ilevel = ilev1
        end if
        call cg(a=a, b=b,x=x,ilev1=ilevel,itmax1=itmax1,reps1=reps1)
subroutine, public solver_interfaces::cg_normal_face (class(matrix), intent(inout) A, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional itmax1, real(kind=rkind), intent(in), optional reps1, integer, intent(in), optional ilev1, integer(kind=ikind), intent(out), optional itfin1, real(kind=rkind), intent(out), optional repsfin1, real(kind=rkind), intent(out), optional ll1, real(kind=rkind), intent(out), optional ll2, real(kind=rkind), intent(out), optional cond1, type(tcount), intent(out), optional opcnt1, integer, intent(out), optional errcode1)
Parameters
in,out a matice soustavy
 musi poskytovat getn, getm, mul (nasobeni vektorem)
in b vektor prave strany
in,out x aproximace reseni, postupne menena
in itmax1 maximalni povoleny pocet iteraci, default = n (Rozmer matice)
in reps1 pozadovana relativni zmena rezidua, default = 1e-6
in ilev1 informacni podrobnost
0 ... pracuj tise
1 ... minimalni informace
10 ... maximalni ukecanost
out itfin1 skutecne provedeny pocet iteraci
out repsfin1 skutecne dosazena relativni zmena residua
out ll1 odhad nejvetsiho vlastniho cisla
out ll2 odhad nejmensiho vlastniho cisla
out cond1 odhad cisla podminenosti : cond1 = ll1/ll2
out opcnt1 celkovy pocet provedenych operaci a cas behu
out errcode1 kod pripadnr chyby
0 ... OK
1 ... matice neni ctvercova
2 ... nesouhlasi b
3 ... nesouhasi x
4 ... ani jeden z vektoru nesouhlasi
5 ... vycerpan povoleny pocet iteraci
6 ... prestalo klesat residuum i energie
Definition at line 135 of file solver_interfaces.f90.
References solvers::cgnormal().
Referenced by manage_pointers::set_pointers().
        use mtx
        use typy
        use sparsematrix
        use solvers
        implicit none
        class(matrix), intent(in out) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(in out) :: x
        integer(kind=ikind), intent(in), optional :: itmax1
        real(kind=rkind), intent(in), optional :: reps1
        integer, intent(in), optional :: ilev1
        integer(kind=ikind), intent(out), optional :: itfin1
        real(kind=rkind), intent(out), optional :: repsfin1
        real(kind=rkind), intent(out), optional :: ll1
        real(kind=rkind), intent(out), optional :: ll2
        real(kind=rkind), intent(out), optional :: cond1
        type(tcount), intent(out), optional :: opcnt1
        integer, intent(out), optional :: errcode1
        integer :: ilevel
        if (.not. present(ilev1)) then
          ilevel = 0
        else
          ilevel = ilev1
        end if
        call cgnormal(a=a, b=b,x=x,ilev1=ilevel,itmax1=itmax1,reps1=reps1, itfin1=itfin1, repsfin1=repsfin1
      )
subroutine, public solver_interfaces::jacobi_face (class(matrix), intent(inout) A, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional itmax1, real(kind=rkind), intent(in), optional reps1, integer, intent(in), optional ilev1, integer(kind=ikind), intent(out), optional itfin1, real(kind=rkind), intent(out), optional repsfin1, real(kind=rkind), intent(out), optional ll1, real(kind=rkind), intent(out), optional ll2, real(kind=rkind), intent(out), optional cond1, type(tcount), intent(out), optional opcnt1, integer, intent(out), optional errcode1)
Parameters
in,out a matice soustavy
 musi poskytovat getn, getm, mul (nasobeni vektorem)
in b vektor prave strany
in,out x aproximace reseni, postupne menena
in itmax1 maximalni povoleny pocet iteraci, default = n (Rozmer matice)
in reps1 pozadovana relativni zmena rezidua, default = 1e-6
in ilev1 informacni podrobnost
0 ... pracuj tise
1 ... minimalni informace
10 ... maximalni ukecanost
out itfin1 skutecne provedeny pocet iteraci
out repsfin1 skutecne dosazena relativni zmena residua
out ll1 odhad nejvetsiho vlastniho cisla
out ll2 odhad nejmensiho vlastniho cisla
out cond1 odhad cisla podminenosti : cond1 = ll1/ll2
out opcnt1 celkovy pocet provedenych operaci a cas behu
out errcode1 kod pripadnr chyby
0 ... OK
1 ... matice neni ctvercova
2 ... nesouhlasi b
3 ... nesouhasi x
4 ... ani jeden z vektoru nesouhlasi
5 ... vycerpan povoleny pocet iteraci
6 ... prestalo klesat residuum i energie
Definition at line 194 of file solver_interfaces.f90.
References solvers::jacobi().
        use mtx
        use typy
        use solvers
        implicit none
        class(matrix), intent(in out) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(in out) :: x
        integer(kind=ikind), intent(in), optional :: itmax1
        real(kind=rkind), intent(in), optional :: reps1
        integer, intent(in), optional :: ilev1
        integer(kind=ikind), intent(out), optional :: itfin1
        real(kind=rkind), intent(out), optional :: repsfin1
        real(kind=rkind), intent(out), optional :: ll1
        real(kind=rkind), intent(out), optional :: ll2
        real(kind=rkind), intent(out), optional :: cond1
        type(tcount), intent(out), optional :: opcnt1
        integer, intent(out), optional :: errcode1
        
        call jacobi(a,b,x,itmax1, reps1)
subroutine, public solver_interfaces::ldu_face (class(matrix), intent(inout) A, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional itmax1, real(kind=rkind), intent(in), optional reps1, integer, intent(in), optional ilev1, integer(kind=ikind), intent(out), optional itfin1, real(kind=rkind), intent(out), optional repsfin1, real(kind=rkind), intent(out), optional ll1, real(kind=rkind), intent(out), optional ll2, real(kind=rkind), intent(out), optional cond1, type(tcount), intent(out), optional opcnt1, integer, intent(out), optional errcode1)
Parameters
in,out a matice soustavy
 musi poskytovat getn, getm, mul (nasobeni vektorem)
in b vektor prave strany
in,out x aproximace reseni, postupne menena
in itmax1 maximalni povoleny pocet iteraci, default = n (Rozmer matice)
in reps1 pozadovana relativni zmena rezidua, default = 1e-6
in ilev1 informacni podrobnost
0 ... pracuj tise
1 ... minimalni informace
10 ... maximalni ukecanost
out itfin1 skutecne provedeny pocet iteraci
out repsfin1 skutecne dosazena relativni zmena residua
out ll1 odhad nejvetsiho vlastniho cisla
out ll2 odhad nejmensiho vlastniho cisla
out cond1 odhad cisla podminenosti : cond1 = ll1/ll2
out opcnt1 celkovy pocet provedenych operaci a cas behu
out errcode1 kod pripadnr chyby
0 ... OK
1 ... matice neni ctvercova
2 ... nesouhlasi b
3 ... nesouhasi x
4 ... ani jeden z vektoru nesouhlasi
5 ... vycerpan povoleny pocet iteraci
6 ... prestalo klesat residuum i energie
Definition at line 12 of file solver_interfaces.f90.
References solvers::lduback(), and solvers::ldud().
Referenced by manage_pointers::set_pointers().
        use mtx
        use typy
        use solvers
        implicit none
        class(matrix), intent(in out) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(in out) :: x
        integer(kind=ikind), intent(in), optional :: itmax1
        real(kind=rkind), intent(in), optional :: reps1
        integer, intent(in), optional :: ilev1
        integer(kind=ikind), intent(out), optional :: itfin1
        real(kind=rkind), intent(out), optional :: repsfin1
        real(kind=rkind), intent(out), optional :: ll1
        real(kind=rkind), intent(out), optional :: ll2
        real(kind=rkind), intent(out), optional :: cond1
        type(tcount), intent(out), optional :: opcnt1
        integer, intent(out), optional :: errcode1
        
        integer(kind=ikind), dimension(:), allocatable, save :: p1, p2
        
        
        if (.not. allocated(p1)) then
          allocate(p1(ubound(b,1)))
          allocate(p2(ubound(b,1)))
        end if
    
         call ldud(a, pivtype=5, ilev=0, perm1=p1, perm2=p2)
         
         call lduback(a, b, x, p1=p1, p2=p2)
         
         if (present(itfin1)) then
           itfin1 = 1
         end if
subroutine, public solver_interfaces::null_problem (class(extsmtx), intent(inout) A, real(kind=rkind), dimension(:), intent(inout), optional b)
Definition at line 242 of file solver_interfaces.f90.
Referenced by femmat::assemble_mat(), decomposer::clear_subdomain(), schwarz_dd::locmat_assembler(), and schwarz_dd2subcyc::locmat_assembler().
      use typy
      use globals
      use sparsematrix
      class(extsmtx), intent(in out) :: a
      real(kind=rkind), dimension(:), intent(in out), optional :: b
      integer(kind=ikind) :: n_rows, m_rows
      
      n_rows = a%getn()
      m_rows = a%getm()
   
      call a%init(n_rows,m_rows)
      
      if (present(b)) then
        b = 0.0_rkind
      end if
      
      call a%rowsfilled%clear
      