bousspointers Module Reference
Functions/Subroutines
subroutine, public boussi (pde_loc)
Function/Subroutine Documentation
subroutine, public bousspointers::boussi (class(pde_str), intent(inout) pde_loc)
Definition at line 7 of file bousspointers.f90.
References boussfnc::bouss_adv(), boussfnc::bouss_bc(), boussfnc::bouss_cond(), boussfnc::bouss_elast(), boussfnc::boussicond(), boussfnc::boussreact(), boussread::boussreader(), boussfnc::darcy4bouss(), and pde_objs::pde.
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use boussglob
      use boussfnc
      use boussread
        
      class(pde_str), intent(in out) :: pde_loc
      integer(kind=ikind) :: i
      
      call boussreader(pde_loc)
      
      pde_loc%pde_fnc(pde_loc%order)%dispersion => bouss_cond
      pde_loc%pde_fnc(pde_loc%order)%convection => bouss_adv
      pde_loc%pde_fnc(pde_loc%order)%elasticity => bouss_elast
      pde_loc%pde_fnc(pde_loc%order)%zerord => boussreact
          
      do i=lbound(pde(1)%bc,1), ubound(pde(1)%bc,1)
        select case(pde_loc%bc(i)%code)
          case(1,2)
            pde_loc%bc(i)%value_fnc => bouss_bc
        end select
      end do
              
        
      pde_loc%flux => darcy4bouss
      pde_loc%initcond => boussicond
       