pde_objs Module Reference
Data Types
interface basic_subrt
interface bc_fnc
abstract interface for boundary value function
type boundary_vals
data structure to carry boundary value problem setup, allocation starts at 100
interface getval_str
interface icond_fnc
interface logical_fnc
interface matrix_solver
type pde_common_str
type pde_fnc
type pde_str
type definition for common quasilinear partial diferential equation in a format
 E(u)\frac{\partial u}{\partial t} = \nabla . D(u) \nabla u - \nabla . (c(u) u) + r(u) u 
interface scalar_fnc
abstract interface for scalar function
interface tensor_fnc
abstract interface for vector function
interface time_check
interface timeint_fnc
interface treat_pde_subrt
interface vector_fnc
abstract interface for vector function
Functions/Subroutines
subroutine, public getgradp1 (pde_loc, quadpnt, grad)
returns solution gradient for p1 approximation
real(kind=rkind) function, public getvalp1 (pde_loc, quadpnt)
returns solution value for p1 approximation
real(kind=rkind) function, private getvalp1loc (pde_loc, quadpnt, stopme)
in case of asynchronyous temporal integration this function is separated from getvalp1, if standard temporal integration used, then this function is called from the first line of getvalp1
subroutine get2dderivative (a, b, c, xder, yder)
subroutine, public do_nothing ()
Variables
type(pde_str), dimension(:), allocatable, public pde
type(pde_common_str), public pde_common
procedure(matrix_solver), pointer, public solve_matrix
Function/Subroutine Documentation
subroutine, public pde_objs::do_nothing ()
Definition at line 650 of file pde_objs.f90.
Referenced by drutes_init::pde_constructor(), and pde_objs::treat_pde_subrt::treat_pde_subrt().
    
subroutine pde_objs::get2dderivative (real(kind=rkind), dimension(:), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(in) c, real(kind=rkind), intent(out) xder, real(kind=rkind), intent(out) yder)
Parameters
in a 1st point of the plane
in b 2nd point of the plane
in c 3rd point of the plane
out xder resulting x derivate
out yder resulting y derivate
Definition at line 593 of file pde_objs.f90.
Referenced by getgradp1(), and getvalp1loc().
      use typy
      real(kind=rkind), dimension(:), intent(in) :: a
      real(kind=rkind), dimension(:), intent(in) :: b
      real(kind=rkind), dimension(:), intent(in) :: c
      real(kind=rkind), intent(out) :: xder
      real(kind=rkind), intent(out) :: yder
      !-------local variables--------------
      real(kind=rkind), dimension(3) :: u
      real(kind=rkind), dimension(3) :: v
      real(kind=rkind), dimension(3) :: n
      integer(kind=ikind) :: i
      real(kind=rkind) :: reps
      reps = epsilon(reps)
      !check if the plane is not horizontal
      if (abs(a(3) - b(3)) < reps*(abs(a(3))-abs(b(3))) .and. &
          abs(a(3) - c(3)) < reps*(abs(a(3))-abs(c(3))) .and. &
          abs(b(3) - c(3)) < reps*(abs(b(3))-abs(c(3)))) then
        xder = 0.0_rkind
        yder = 0.0_rkind
        RETURN
      else
        CONTINUE
      end if
      !creates the plane vectors
      do i=1,3
        u(i) = a(i) - b(i)
        v(i) = a(i) - c(i)
      end do
      ! the normal plane vector is defined as
      n(1) = u(2)*v(3) - v(2)*u(3)
      n(2) = u(3)*v(1) - v(3)*u(1)
      n(3) = u(1)*v(2) - v(1)*u(2)
      ! finally the derivate is as follows, the horizontality has been already checked
      ! the verticality check
      if (abs(n(3)) < 1e2*reps) then
        print *, "the mesh is wrong, base function can't be vertical"
        error stop
      end if
      xder = -n(1)/n(3)
      yder = -n(2)/n(3)
      
subroutine, public pde_objs::getgradp1 (class(pde_str), intent(in) pde_loc, type(integpnt_str), intent(in) quadpnt, real(kind=rkind), dimension(:), intent(out), allocatable grad)
returns solution gradient for p1 approximation
Definition at line 307 of file pde_objs.f90.
References globals::drutes_config, globals::elements, get2dderivative(), getvalp1(), globals::nodes, and globals::observation_array.
Referenced by pde_objs::treat_pde_subrt::treat_pde_subrt().
      use typy
      use decomp_vars
      
      class(pde_str), intent(in) :: pde_loc
      type(integpnt_str), intent(in) :: quadpnt
      type(integpnt_str), dimension(:), allocatable, save :: quadpntloc
      real(kind=rkind), dimension(:), allocatable, intent(out) :: grad
      real(kind=rkind), dimension(3) :: gradloc
      integer(kind=ikind), dimension(:), allocatable, save :: pts
      real(kind=rkind), dimension(3) :: a,b,c
      real(kind=rkind) :: dx
      integer(kind=ikind) :: i, el, top, j
      
      if (.not. allocated(grad)) then
        allocate(grad(drutes_config%dimen))
      else if (ubound(grad,1) /= drutes_config%dimen) then
        deallocate(grad)
        allocate(grad(drutes_config%dimen))
      end if
      
      if (.not. allocated(pts)) then
        allocate(pts(ubound(elements%data,2)))
        allocate(quadpntloc(ubound(elements%data,2)))
      end if
      
      select case(quadpnt%type_pnt)
        case("gqnd", "obpt")
          top = 1
        case("ndpt")
          !in case of ndpt the gradient is assumed as an average value of gradients at neighbourhood points
          top = nodes%element(quadpnt%order)%pos
        case default
          print *, "RUNTIME ERROR: incorrect quadpnt type definition (value quadpnt%type_pnt)"
          print *, "the value specified in code was:", quadpnt%type_pnt
          print *, "exited from pde_objs::getgradp1"
          error stop
          
          
      end select
      
      gradloc = 0
      do i=1, top
        select case(quadpnt%type_pnt)
          case("gqnd")
            el = quadpnt%element
          case("obpt")
            el = observation_array(quadpnt%order)%element
          case("ndpt")
            el = nodes%element(quadpnt%order)%data(i)
        end select
        
        pts = elements%data(el,:)
        
        quadpntloc(:) = quadpnt
        quadpntloc(:)%type_pnt = "ndpt"
        select case(drutes_config%dimen)
          case(1)
            dx = nodes%data(pts(2),1) - nodes%data(pts(1),1)
            quadpntloc(1)%order = pts(1)
            quadpntloc(2)%order = pts(2)
            gradloc(1) = gradloc(1) + (getvalp1(pde_loc,quadpntloc(2)) -
      getvalp1(pde_loc, quadpntloc(1)))/dx
          case(2)
            a(1:2) = nodes%data(pts(1),:)
            b(1:2) = nodes%data(pts(2),:)
            c(1:2) = nodes%data(pts(3),:)
            
            
            quadpntloc(1)%order = pts(1)
            quadpntloc(2)%order = pts(2)
            quadpntloc(3)%order = pts(3)
            
            
            
            a(3) = getvalp1(pde_loc, quadpntloc(1))
            b(3) = getvalp1(pde_loc, quadpntloc(2))
            c(3) = getvalp1(pde_loc, quadpntloc(3))
            call get2dderivative(a,b,c,grad(1), grad(2))
            gradloc(1:2) = gradloc(1:2) + grad
          case(3)
        end select
      end do
      
      grad = gradloc(1:drutes_config%dimen)/top
    
real(kind=rkind) function, public pde_objs::getvalp1 (class(pde_str), intent(in) pde_loc, type(integpnt_str), intent(in) quadpnt)
returns solution value for p1 approximation
Definition at line 398 of file pde_objs.f90.
References getvalp1loc(), decomp_vars::subdomain, globals::time, and globals::time_step.
Referenced by getgradp1(), re_total::getval_retot(), dual_por::getval_retot_dual(), drutes_init::pde_constructor(), re_pointers::re_std(), and pde_objs::treat_pde_subrt::treat_pde_subrt().
      use typy
      use decomp_vars
      
      class(pde_str), intent(in) :: pde_loc
      type(integpnt_str), intent(in) :: quadpnt
      real(kind=rkind) :: val
      real(kind=rkind) :: tmp
      
      type(integpnt_str) :: quadpntloc
      real(kind=rkind) :: valprev, timeprev, timeglob
      logical :: stopper=.false.
   
       val = getvalp1loc(pde_loc, quadpnt)
      if (quadpnt%globtime .or. quadpnt%column==1) then
        RETURN
      else
        quadpntloc = quadpnt
        quadpntloc%column = 4
        if (quadpnt%ddlocal) then
          timeglob = subdomain(quadpnt%subdom)%time
          timeprev = subdomain(quadpnt%subdom)%time - subdomain(quadpnt%subdom)%time_step
        else
          timeglob = time
          timeprev = time-time_step
        end if
        valprev = getvalp1loc(pde_loc, quadpntloc)
        tmp=val
        val = (val-valprev)/(timeglob-timeprev)*(quadpnt%time4eval-timeprev)+valprev
      end if
        
    
real(kind=rkind) function, private pde_objs::getvalp1loc (class(pde_str), intent(in) pde_loc, type(integpnt_str), intent(in) quadpnt, logical, intent(in), optional stopme) [private]
in case of asynchronyous temporal integration this function is separated from getvalp1, if standard temporal integration used, then this function is called from the first line of getvalp1
Definition at line 439 of file pde_objs.f90.
References globals::drutes_config, globals::elements, globals::gauss_points, get2dderivative(), globals::nodes, globals::observation_array, pde_common, and decomp_vars::subdomain.
Referenced by getvalp1(), and pde_objs::treat_pde_subrt::treat_pde_subrt().
      use typy
      use decomp_vars
      
      class(pde_str), intent(in) :: pde_loc
      type(integpnt_str), intent(in) :: quadpnt
      logical, intent(in), optional :: stopme
      real(kind=rkind) :: val
      
      integer(kind=ikind), dimension(:), allocatable, save :: pts, ppts
      real(kind=rkind), dimension(:), allocatable, save :: ndvals
      integer(kind=ikind) :: i, edge, el, j, order
      real(kind=rkind) :: xder, yder
      real(kind=rkind), dimension(3,3) :: a
      
      if (.not. allocated(pde_common%xvect)) then
        print *, "runtime error, you are probably calling getval function too early, vector with solution
       is not yet allocated"
        print *, "contact Michal -> michalkuraz@gmail.com"
        error stop
      end if
      
            
      
     select case(quadpnt%type_pnt)
        case("gqnd", "obpt")
            if (.not. allocated(pts)) then
              allocate(pts(ubound(elements%data,2)))
              allocate(ppts(ubound(elements%data,2)))
              allocate(ndvals(ubound(elements%data,2)))
            end if
            
            
            select case(quadpnt%type_pnt)
              case("gqnd")
                el = quadpnt%element
              case("obpt")
                el = observation_array(quadpnt%order)%element
            end select
              
            pts = elements%data(el,:)
            ppts = pde_loc%permut(pts)
            
                
            if (quadpnt%ddlocal) then
              if (.not. quadpnt%extended) then
                where (ppts /= 0)
                  ppts = subdomain(quadpnt%subdom)%invpermut(ppts)
                end where
              else
                where (ppts /= 0)
                  ppts = subdomain(quadpnt%subdom)%extinvpermut(ppts)
                end where
              end if
            end if
            
            do i=1, ubound(elements%data,2)
        
              if (ppts(i) > 0) then
                if (.not. quadpnt%ddlocal) then
                  ndvals(i) = pde_common%xvect(ppts(i), quadpnt%column)
                else
                  if (.not. quadpnt%extended) then
                    ndvals(i) = subdomain(quadpnt%subdom)%xvect(ppts(i), quadpnt%column)
                  else
                    ndvals(i) = subdomain(quadpnt%subdom)%extxvect(ppts(i), quadpnt%column)
                  end if
                end if
              else
                edge = nodes%edge(pts(i))
                
                call pde_loc%bc(edge)%value_fnc(pde_loc, el, i, ndvals(i))
                
              end if
            end do
       
            select case(quadpnt%type_pnt)
              case("gqnd")
                select case(drutes_config%dimen)
                  case(1)
                    val = (ndvals(2) - ndvals(1))*gauss_points%point(quadpnt%order,1) + ndvals(1)
                  case(2)
                    call get2dderivative((/0.0_rkind, 0.0_rkind, ndvals(1)/), (/1.0_rkind, 0.0_rkind,
      ndvals(2)/), (/0.0_rkind, &
                                   1.0_rkind, ndvals(3)/), xder, yder)
                    val = ndvals(1) + xder*gauss_points%point(quadpnt%order,1) + yder*
      gauss_points%point(quadpnt%order,2)
                end select
              case("obpt")
                select case(drutes_config%dimen)
                  case(1)
                     val = (ndvals(2) - ndvals(1))/(nodes%data(pts(2),1) - nodes%data(pts(1),1))*(
      observation_array(quadpnt%order)%xyz(1) - &
                           nodes%data(pts(1),1)) + ndvals(1)
                  case(2)
                    do i=1,3
                      do j=1,2
                        a(i,j) = nodes%data(pts(i),j)
                      end do
                      a(i,3) = ndvals(i)
                    end do
                            
                    call get2dderivative(a(1,:), a(2,:), a(3,:), xder, yder)
                    
                    val = ndvals(1) + xder*(observation_array(quadpnt%order)%xyz(1) - a(1,1)) + &
                          yder * (observation_array(quadpnt%order)%xyz(2) - a(1,2))
                end select
          end select
                    
        case("ndpt")
            i = pde_loc%permut(quadpnt%order)
            if (i > 0) then
              if (.not. quadpnt%ddlocal) then
                val = pde_common%xvect(i, quadpnt%column)
              else
              
                if (.not. quadpnt%extended) then
                  i = subdomain(quadpnt%subdom)%invpermut(i)
                  val = subdomain(quadpnt%subdom)%xvect(i, quadpnt%column)
                else
                  i = subdomain(quadpnt%subdom)%extinvpermut(i)
                  val = subdomain(quadpnt%subdom)%extxvect(i, quadpnt%column)
                end if
              end if
            else
              edge = nodes%edge(quadpnt%order)
              el = nodes%element(quadpnt%order)%data(1)
              do i=1, ubound(elements%data,2)
                if (elements%data(el,i) == quadpnt%order) then
                  order = i
                  EXIT
                end if
              end do
              call pde_loc%bc(edge)%value_fnc(pde_loc, el, order, val)
            end if
        case default
            print *, "RUNTIME ERROR: incorrect quadpnt type definition (value quadpnt%type_pnt)"
            print *, "the value specified in code was:", quadpnt%type_pnt
            print *, "exited from pde_objs::getvalp1"
            error stop
      end select
          
Variable Documentation
type(pde_str), dimension(:), allocatable, public pde_objs::pde
Definition at line 297 of file pde_objs.f90.
Referenced by decomp_tools::addlevel(), ade_fnc::ade_convection(), ade_fnc::ade_cscl_react(), ade_fnc::ade_cscs_react(), ade_fnc::ade_flux(), ade_fnc::ade_mass(), ade_fnc::ade_reaction(), ade_fnc::ade_tder_coef(), ade_fnc::ade_tder_cscl(), ade_fnc::ade_zerorder(), ade_fnc::adecs_mass(), ade_fnc::adedispersion(), ade_pointers::adekinsorb(), femmat::assemble_mat(), bousspointers::boussi(), boussfnc::boussicond(), stiffmat::build_bvect(), decomp_tools::build_coarsemtx(), stiffmat::build_stiff_np(), fem::close_all_observe(), decomp_tools::collect_matrices(), dual_coup::dual_coup_min(), dual_coup::dual_coupling(), dual_tab::dual_coupling_tab(), re_dual_bc::dual_freedrainage(), feminittools::feminit(), heat_pointers::heat_source(), fem_tools::icond4neumann(), capmat::impl_euler_np_diag(), capmat::impl_euler_np_nondiag(), fem_tools::in2global(), decomposer::init_decomp(), feminittools::init_integ(), drutes_init::init_observe(), decomposer::init_subdomain(), schwarz_dd::locmat_assembler(), schwarz_dd2subcyc::locmat_assembler(), postpro::make_print(), geom_tools::map1d2d(), geom_tools::map1d2dj(), drutes_init::pde_constructor(), decomp_tools::print_domains(), postpro::print_gmsh(), postpro::print_pure(), postpro::print_scilab(), re_constitutive::rcza_check_old(), re_dual_pointers::re_fracture(), re_dual_pointers::re_matrix(), read_inputs::read_scilab(), objfnc::reader(), feminittools::reorder(), femmat::results_extractor(), subcycling::results_extractor(), schwarz_dd::results_extractor(), schwarz_dd_time_test::results_extractor(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarz_picard_tt(), schwarz_dd2subcyc::schwarz_subcyc(), schwarz_dd_time_test::schwarzloc(), subcycling::search_error_cluster(), schwarz_dd::search_error_cluster(), schwarz_dd2subcyc::search_error_cluster(), schwarz_dd_time_test::search_error_cluster_tt(), manage_pointers::set_pointers(), decomposer::set_subdomains(), femmat::solve_picard(), subcycling::subcyc_schwarz(), postpro::write_obs(), and re_constitutive::zone_error_val().
  type(pde_str), dimension(:), allocatable, public :: pde
type(pde_common_str), public pde_objs::pde_common
Definition at line 298 of file pde_objs.f90.
Referenced by re_pointers::allrepointers(), femmat::assemble_mat(), boussread::boussreader(), subcycling::build_xvect(), schwarz_dd::build_xvect(), schwarz_dd_time_test::build_xvect(), schwarz_dd2subcyc::build_xvect_loc(), decomp_tools::collect_matrices(), schwarz_dd2subcyc::combinevals(), feminittools::feminit(), decomp_tools::get_residual(), decomp_tools::get_residual_old(), getvalp1loc(), heat_pointers::heat(), fem_tools::icond4neumann(), decomposer::init_subdomain(), schwarz_dd::locmat_assembler(), schwarz_dd2subcyc::locmat_assembler(), core_tools::mesh_allocater(), drutes_init::parse_globals(), decomp_tools::print_domains(), re_constitutive::rcza_check_old(), re_constitutive::re_atmospheric(), re_constitutive::re_neumann_bc(), read_inputs::read_2dmesh_gmsh(), read_inputs::read_global(), feminittools::reorder(), femmat::results_extractor(), subcycling::results_extractor(), schwarz_dd::results_extractor(), schwarz_dd_time_test::results_extractor(), re_total::retot_seepage(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarz_picard_tt(), schwarz_dd_time_test::schwarzloc(), drutes_init::set_global_vars(), manage_pointers::set_pointers(), fem::solve_pde(), femmat::solve_picard(), schwarz_dd2subcyc::solve_subdomain(), and subcycling::subcyc_schwarz().
  type(pde_common_str), public :: pde_common
procedure(matrix_solver), pointer, public pde_objs::solve_matrix
Definition at line 299 of file pde_objs.f90.
Referenced by schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarzloc(), manage_pointers::set_pointers(), femmat::solve_picard(), schwarz_dd2subcyc::solve_subdomain(), and subcycling::subcyc_schwarz().
  procedure(matrix_solver), pointer, public :: solve_matrix