linalg Module Reference
obsahuje:
Functions/Subroutines
subroutine, public print_matrix (A, nc, width)
vytiskne matici
subroutine, public print_vector (V, nc)
vytiskne vektor
subroutine, public gem (a, b, x)
Gaussova eliminace.
subroutine, public ludecomp (A, p, q)
LU rozklad.
subroutine, private fmax (A, i, imax, jmax)
subroutine, public lumul (LU, A)
Detailed Description
obsahuje:
I/O operace pro linearni algebru
reseni soustavy linearnich rovnic
Function/Subroutine Documentation
subroutine, private linalg::fmax (real(kind=rkind), dimension(:,:), intent(in) A, integer(kind=ikind), intent(in) i, integer(kind=ikind), intent(out) imax, integer(kind=ikind), intent(out) jmax) [private]
Definition at line 289 of file linalg.f90.
Referenced by ludecomp().
    use typy
    Real(kind=rkind),dimension(:,:), intent(in) :: a
    Integer(kind=ikind), intent(in) :: i
    Integer(kind=ikind), intent(out) :: imax,jmax
  
    Real(kind=rkind) :: maxv,wrk
    Integer(kind=ikind) :: j, k, n
 
    n = ubound(a,1)
    maxv = abs(a(i,i))
    imax = i
    jmax = i
    do j=i,n
      do k=1,n
        wrk = abs(a(j,k))
        if (wrk > maxv) then
          imax = j
          jmax = i
          maxv = wrk
        end if
      end do
    end do
subroutine, public linalg::gem (real(kind=rkind), dimension(:,:), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(out) x)
Gaussova eliminace.
Gaussova eliminace
Definition at line 136 of file linalg.f90.
Referenced by geom_tools::gravity_center(), and integral::setup().
    use typy
    real(kind=rkind), dimension(:,:), intent(in) :: a
    !realny 2rozmer pole je to parametr a vstupni parametr
    real(kind=rkind), dimension(:), intent(in) :: b
    real(kind=rkind), dimension(:), intent(out) :: x
    real(kind=rkind), dimension(:), allocatable :: aradek
    !matice a pochazi z main, nemuzu ji tedy menit,
    !proto si definuju matici aa, do ktery zapisu matici a
    real(kind=rkind), dimension(:,:), allocatable :: aa
    real(kind=rkind) :: wrk
    integer :: asizev, asizeh,i,j
    integer :: bsize, n,k, maxindex
    integer :: mm
    integer :: xsize
    asizev=ubound(a,1)
    !priradi rozmer horizontalni
    asizeh=ubound(a,2)
    !priradi rozmer vertikalni
    bsize=ubound(b,1)
    xsize=ubound(x,1)
    !print *, asizeH , asizeV , bsize , xsize
    if (asizeh==xsize .AND. asizev==bsize) then
      ! print *, "zatim ok"
      if (asizeh/=asizev) then
        ! print *, "matice neni |_|"
      else
        ! print *, "jdeme pocitat"
        allocate(aa(asizev,asizeh+1))
        allocate(aradek(1:asizeh+1))
        aa(1:asizeh,1:asizev)=a
        aa(:,asizev+1)=b
        ! x=aa(:,asizeV+1) -pokus pro vypis vektoru vysledu
        n=asizeh
        do i=1,n-1
          !prvni hodnata UDAVA RADKY, DRUHA SLOUPEC
          !MAXINDEX je poloha max. cisla z radky i az n a sloupec i
          maxindex = i
          wrk = abs(aa(i,i))
          do j=i+1,n
            if (abs(aa(j,i)) > wrk) then
              wrk = abs(aa(j,i))
              maxindex = j
            end if
          end do
          !jestlize se maxindex rovna i nic neni treba delat,
          !je-li ruzny, tzn. > nez i je treba vymenit i radek a maxindex radek
          !klasicka zamena prvku
          if (maxindex > i) then
            !a radek priradim zkoumany radek (pouze uschova)
            aradek=aa(i,:)
            !priradim radek s maximalni hodnoutou do reseneho radku...
            aa(i,:)=aa(maxindex,:)
            aa(maxindex,:)=aradek
            if (aa(i,i) == 0) then
              !print *,"matice je singularni..."
              return
            endif
          endif
          !vydelim reseny radek hodnotu nejvetsiho prvku
          !(ktery sme predtim umistili na diagonalu)
          wrk=aa(i,i)
          aa(i,i:)=aa(i,i:)/wrk
          do j= i+1,n
            !vezmu j-ty radek i-ty sloupec
            wrk=aa(j,i)
            !aa(j,:) - vybiram cely j-ty radek
            aa(j,:)=aa(j,:)-wrk*aa(i,:)
          end do
          !call printmatrix(aa)
        enddo
        aa(n,n+1)=aa(n,n+1)/aa(n,n)
        do i=n-1, 1, -1
          !dotproduct - funkce provedejici skalarni soucin
          aa(i,n+1)=(aa(i,n+1)- dot_product(aa(i,i+1:n),aa(i+1:n,n+1)))/aa(i,i)
        end do
        !aa(:,n+1) je vektor reseni soustavy
        x=aa(:,n+1)
        deallocate(aa)
        deallocate(aradek)
      endif
    else
      ! print *, "co delas??"
    endif
subroutine, public linalg::ludecomp (real(kind=rkind), dimension(:,:), intent(inout) A, integer(kind=ikind), dimension(:), intent(out) p, integer(kind=ikind), dimension(:), intent(out) q)
LU rozklad.
LU rozklad s uplnym vyberem hlavniho prvku
 ! realne behem rozkladu presouva prvky tedy L a U jsou opravdu trojuhelniky
Parameters
in,out a ctvercova matice - vstup: rozkladana matice
 ..................vystup: LU faktory
out p radkova permutace, vystupni parametr
out q sloupcova permutace, vystupni parametr
Definition at line 234 of file linalg.f90.
References fmax().
    use typy
    Real(kind=rkind),dimension(:,:), intent(in out) :: a
    Integer(kind=ikind), dimension(:), intent(out) :: p
    Integer(kind=ikind), dimension(:), intent(out) :: q
    
    
    Integer(kind=ikind) :: n,n1,n2,i,j,k,imax,jmax
    Real(kind=rkind) :: wrk
    ! zjistim rozmery matice
    n1 = ubound(a,1)
    n2 = ubound(a,2)
    !print *, "n1,n2=", n1,n2
    if (n1 == n2) then ! je to ctvercova matice, jdu na to
      n = n1
      p = (/ (i,i=1,n) /) ! priprava zaznamu o permutaci
      q = p ! napred zadna
      !print *,p
      do i=1,n-1
        call fmax(a,i,imax,jmax) ! najdi nejvetsi prvek
        n1 = p(imax) ! zaznamenej presun
        p(imax)= p(i)
        p(i) = n1
        n1 = q(jmax)
        q(jmax)= q(i)
        q(i) = n1
        do j=1,n !a opravdu presun
          wrk = a(i,j)
          a(i,j) = a(imax,j)
          a(imax,j) = wrk
        end do
        do j=1,n
          wrk = a(j,i)
          a(j,i) = a(j,jmax)
          a(j,jmax) = wrk
        end do
        ! ted jiz opravdu rozkladej
        a(i+1:,i) = a(i+1:,i)/a(i,i)
        do j=i+1,n
          a(i+1:,j) = a(i+1:,j) - a(i,j)*a(i+1:,i)
        end do
      end do
    else
      print *, "neco divneho"
      stop
    end if
subroutine, public linalg::lumul (real(kind=rkind), dimension(:,:), intent(in) LU, real(kind=rkind), dimension(:,:), intent(out) A)
Definition at line 314 of file linalg.f90.
    use typy
    Real(kind=rkind), dimension(:,:), intent(in) :: lu
    Real(kind=rkind), dimension(:,:), intent(out) :: a
    Real(kind=rkind) :: wrk
    Integer(kind=ikind) :: i,j,k,n,kmax
    a = 0
    n = ubound(a,1)
    do i=1,n
      do j=1,n
        wrk = 0
        if (i<=j) then
          kmax = i-1
          wrk = lu(i,j)
        else
          kmax = j
        end if
        do k=1,kmax
          wrk = wrk + lu(i,k)*lu(k,j)
        end do
        a(i,j) = wrk
      end do
    end do
subroutine, public linalg::print_matrix (real(kind=rkind), dimension(:,:), intent(in) A, integer(kind=ikind), intent(in), optional nc, integer, intent(in), optional width)
vytiskne matici
Parameters
in a matice k tisknuti
in nc pocet tistenych sloupcu,nepovinny, default = 6
in width sirka cisel
Definition at line 26 of file linalg.f90.
   ! vytiskne matici, pocet sloupcu tisku je nc
   use typy
   !vytiskne matici
   ! simuluje format tisku matic Matlabu
      real(kind=rkind), dimension(:,:), intent(in) :: a
      integer(kind=ikind), intent(in), optional :: nc
      integer, intent(in), optional :: width
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !lokalni promenne
      integer(kind=ikind) :: nc1
      integer(kind=ikind) :: ncol
      integer(kind=ikind) :: nrow
      integer(kind=ikind) :: i
      integer(kind=ikind) :: j
      integer(kind=ikind) :: col1
      integer(kind=ikind) :: col2
      integer :: w1
      character(len=200):: fm!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !vlastni kod
      !vyridime defaulty
      if (present(nc)) then
        nc1 = nc
      else
        nc1 = 6
      end if
      
      if (present(width)) then
         w1 = width
      else
         w1 = 20
      end if
      !ted opravdu tisknem
      ncol = ubound(a,2)
      nrow = ubound(a,1)
      do i=1,ncol/nc1
        col1 = (i-1)*nc1+1
        col2 = i*nc1
        write(unit=fm,fmt="(A1,I0,A2,I0,A1,I0,A1)") "(",nc1,"Es",w1+8,".",w1,")"
        print *, "tisknu sloupce : (",col1,",",col2,")"
        do j=1,nrow
          print fm, a(j,col1:col2)
        end do
        print *, " "
      end do
      if (modulo(ncol,nc1) /= 0) then
        col1 = (ncol/nc1)*nc1+1
        col2 = ncol
        print *, "tisknu sloupce : (",col1,",",col2,")"
        do j=1,nrow
          print "(100E30.20)", a(j,col1:col2)
        end do
        print *, " "
      end if
subroutine, public linalg::print_vector (real(kind=rkind), dimension(:), intent(in) V, integer(kind=ikind), intent(in), optional nc)
vytiskne vektor
Parameters
in v tisteny vektor
in nc pocet tistenych sloupcu, default = 6
Definition at line 90 of file linalg.f90.
   ! vytiskne vektor, pocet sloupcu tisku je nc
     use typy
     !parametry
      real(kind=rkind), dimension(:), intent(in) :: v
      integer(kind=ikind), intent(in), optional :: nc
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !lokalni promenne
      integer(kind=ikind) :: nc1, ncol, i, col1, col2
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !vlastni kod
      !vyridime defaulty
      if (present(nc)) then
        nc1 = nc
      else
        nc1 = 6
      end if
      !ted opravdu tisknem
      ncol = ubound(v,1)
      do i=1,ncol/nc1
        col1 = (i-1)*nc1+1
        col2 = i*nc1
        print *, "tisknu usek : (",col1,",",col2,")"
        print "(100E30.20)", v(col1:col2)
        print *, " "
      end do
      if (modulo(ncol,nc1) /= 0) then
        col1 = (ncol/nc1)*nc1+1
        col2 = ncol
        print *, "tisknu usek : (",col1,",",col2,")"
        print "(100E30.20)", v(col1:col2)
        print *, " "
      end if