mtxiotools Module Reference
V/V nastroje.
Data Types
interface read_vector
interface write_vector
Functions/Subroutines
subroutine, public read_matrix (A, name, fil, ilev, ierr, mode)
precte matici ze souboru
subroutine, public write_matrix (A, name, fil, ilev, ierr, mode)
zapise matici ze souboru
subroutine read_vector_real (x, name, fil, ilev, ierr, mode, rlen)
precte vektor ze souboru
subroutine write_vector_real (x, name, fil, ilev, ierr, mode)
zapise vektor do souboru
subroutine read_vector_int (x, name, fil, ilev, ierr, mode, rlen)
precte vektor ze souboru
subroutine write_vector_int (x, name, fil, ilev, ierr, mode)
zapise vektor do souboru
Detailed Description
V/V nastroje.
Matice:
 format je nezavisly na typu matice tisknou se jen nenulove prvky
prvni radek: pocet_radku pocet_nenul
dalsi radky: radek sloupec hodnota
 Vektor:
prvni radek: pocet_prvku
dalsi radky: hodnota
Function/Subroutine Documentation
subroutine, public mtxiotools::read_matrix (class(matrix), intent(inout) A, character(len=*), intent(in), optional name, integer, intent(in), optional fil, integer, intent(in), optional ilev, integer, intent(in), optional ierr, integer, intent(in), optional mode)
precte matici ze souboru
Parameters
in,out a matice
in name jmeno souboru, je-li zadano name i fil musi identifikovat totez
in fil identifikator kanalu, je-li zadano name i fil musi identifikovat totez
in ilev stupen podrobnosti informaci
in ierr chybovy kod
in mode operacni mod
0 ... tise a v pripade problemu je ignoruj a zapis hlasku do ierr
1 ... problem se soubory znamena interaktivni dotaz
2 ... problem se soubory - uprednostni fil a pripadne zhavaruj
3 ... problem se soubory - uprednostni name a pripadne zhavaruj
4 ... problem se soubory - zhavaruj
Definition at line 43 of file mtxiotools.f90.
References pmatools::get_free_unit(), pmatools::pockej(), and pmatools::safe_open_read().
        use typy
        use mtx
        use pmatools
        implicit none
        class(matrix), intent(inout) :: a
        character(len=*), intent(in), optional ::name
        integer, intent(in), optional :: fil
        integer, intent(in), optional :: ilev
        integer, intent(in), optional :: ierr
        integer, intent(in), optional :: mode
        character(len=200) :: name1
        integer :: mode1
        integer :: fil1
        integer(kind=ikind) :: n, nz, i, j, k, maxi, maxj
        real(kind=rkind) :: val
        ! checknout parametry
        mode1 = 1
        call get_free_unit(fil1)
        call safe_open_read(name1,fil1,mode1)
        print *,"otevreno"
        read(fil1,*) n,nz
        print *,"n=",n," nz=",nz
        call a%init(n,n)
        print *,"realokovano"
        maxi = 0
        maxj = 0
        do k=1,nz
            if (i>maxi) maxi=i
            if (j>maxj) maxj=j
            read(fil1,*) i,j,val
            call a%set(val,i,j)
        end do
        call pockej("ctecka")
        call a%spy
subroutine mtxiotools::read_vector_int (integer(kind=ikind), dimension(:), intent(inout) x, character(len=*), intent(in), optional name, integer, intent(in), optional fil, integer, intent(in), optional ilev, integer, intent(in), optional ierr, integer, intent(in), optional mode, integer(kind=ikind), intent(out), optional rlen)
precte vektor ze souboru
Parameters
in,out x vektor
in name jmeno souboru, je-li zadano name i fil musi identifikovat totez
in fil identifikator kanalu, je-li zadano name i fil musi identifikovat totez
in ilev stupen podrobnosti informaci
in ierr chybovy kod
in mode operacni mod
0 ... tise a v pripade problemu je ignoruj a zapis hlasku do ierr
1 ... problem se soubory znamena interaktivni dotaz
2 ... problem se soubory - uprednostni fil a pripadne zhavaruj
3 ... problem se soubory - uprednostni name a pripadne zhavaruj
4 ... problem se soubory - zhavaruj
out rlen skutecna delka dat pokud delka vektoru a dat nesouhlasi a rlen neni zadano, dojde k ukonceni
Definition at line 178 of file mtxiotools.f90.
        use typy
        use mtx
        implicit none
        integer(kind=ikind), dimension(:), intent(inout) :: x
        character(len=*), intent(in), optional ::name
        integer, intent(in), optional :: fil
        integer, intent(in), optional :: ilev
        integer, intent(in), optional :: ierr
        integer, intent(in), optional :: mode
        integer(kind=ikind), intent(out), optional :: rlen
subroutine mtxiotools::read_vector_real (real(kind=rkind), dimension(:), intent(inout) x, character(len=*), intent(in), optional name, integer, intent(in), optional fil, integer, intent(in), optional ilev, integer, intent(in), optional ierr, integer, intent(in), optional mode, integer(kind=ikind), intent(out), optional rlen)
precte vektor ze souboru
Parameters
in,out x vektor
in name jmeno souboru, je-li zadano name i fil musi identifikovat totez
in fil identifikator kanalu, je-li zadano name i fil musi identifikovat totez
in ilev stupen podrobnosti informaci
in ierr chybovy kod
in mode operacni mod
0 ... tise a v pripade problemu je ignoruj a zapis hlasku do ierr
1 ... problem se soubory znamena interaktivni dotaz
2 ... problem se soubory - uprednostni fil a pripadne zhavaruj
3 ... problem se soubory - uprednostni name a pripadne zhavaruj
4 ... problem se soubory - zhavaruj
out rlen skutecna delka dat pokud delka vektoru a dat nesouhlasi a rlen neni zadano, dojde k ukonceni
Definition at line 124 of file mtxiotools.f90.
        use typy
        use mtx
        implicit none
        real(kind=rkind), dimension(:), intent(inout) :: x
        character(len=*), intent(in), optional ::name
        integer, intent(in), optional :: fil
        integer, intent(in), optional :: ilev
        integer, intent(in), optional :: ierr
        integer, intent(in), optional :: mode
        integer(kind=ikind), intent(out), optional :: rlen
subroutine, public mtxiotools::write_matrix (class(matrix), intent(in) A, character(len=*), intent(in), optional name, integer, intent(in), optional fil, integer, intent(in), optional ilev, integer, intent(in), optional ierr, integer, intent(in), optional mode)
zapise matici ze souboru
Parameters
in a matice
in name jmeno souboru, je-li zadano name i fil musi identifikovat totez
in fil identifikator kanalu, je-li zadano name i fil musi identifikovat totez
in ilev stupen podrobnosti informaci
in ierr chybovy kod
in mode operacni mod
0 ... tise a v pripade problemu je ignoruj a zapis hlasku do ierr
1 ... problem se soubory znamena interaktivni dotaz
2 ... problem se soubory - uprednostni fil a pripadne zhavaruj
3 ... problem se soubory - uprednostni name a pripadne zhavaruj
4 ... problem se soubory - zhavaruj
Definition at line 98 of file mtxiotools.f90.
        use typy
        use mtx
        implicit none
        class(matrix), intent(in) :: a
        character(len=*), intent(in), optional ::name
        integer, intent(in), optional :: fil
        integer, intent(in), optional :: ilev
        integer, intent(in), optional :: ierr
        integer, intent(in), optional :: mode
subroutine mtxiotools::write_vector_int (integer(kind=ikind), dimension(:), intent(in) x, character(len=*), intent(in), optional name, integer, intent(in), optional fil, integer, intent(in), optional ilev, integer, intent(in), optional ierr, integer, intent(in), optional mode)
zapise vektor do souboru
Parameters
in x vektor
in name jmeno souboru, je-li zadano name i fil musi identifikovat totez
in fil identifikator kanalu, je-li zadano name i fil musi identifikovat totez
in ilev stupen podrobnosti informaci
in ierr chybovy kod
in mode operacni mod
0 ... tise a v pripade problemu je ignoruj a zapis hlasku do ierr
1 ... problem se soubory znamena interaktivni dotaz
2 ... problem se soubory - uprednostni fil a pripadne zhavaruj
3 ... problem se soubory - uprednostni name a pripadne zhavaruj
4 ... problem se soubory - zhavaruj
Definition at line 207 of file mtxiotools.f90.
        use typy
        use mtx
        use pmatools
        implicit none
        integer(kind=ikind), dimension(:), intent(in) :: x
        character(len=*), intent(in), optional ::name
        integer, intent(in), optional :: fil
        integer, intent(in), optional :: ilev
        integer, intent(in), optional :: ierr
        integer, intent(in), optional :: mode
        !call safe_open_write(name1,fil1,mode1)
subroutine mtxiotools::write_vector_real (real(kind=rkind), dimension(:), intent(in) x, character(len=*), intent(in), optional name, integer, intent(in), optional fil, integer, intent(in), optional ilev, integer, intent(in), optional ierr, integer, intent(in), optional mode)
zapise vektor do souboru
Parameters
in x vektor
in name jmeno souboru, je-li zadano name i fil musi identifikovat totez
in fil identifikator kanalu, je-li zadano name i fil musi identifikovat totez
in ilev stupen podrobnosti informaci
in ierr chybovy kod
in mode operacni mod
0 ... tise a v pripade problemu je ignoruj a zapis hlasku do ierr
1 ... problem se soubory znamena interaktivni dotaz
2 ... problem se soubory - uprednostni fil a pripadne zhavaruj
3 ... problem se soubory - uprednostni name a pripadne zhavaruj
4 ... problem se soubory - zhavaruj
Definition at line 153 of file mtxiotools.f90.
        use typy
        use mtx
        implicit none
        real(kind=rkind), dimension(:), intent(in) :: x
        character(len=*), intent(in), optional ::name
        integer, intent(in), optional :: fil
        integer, intent(in), optional :: ilev
        integer, intent(in), optional :: ierr
        integer, intent(in), optional :: mode