ade_globals Module Reference
Data Types
type solutexsoil
ADE solute/material parameters array.
type sorption_str
parameters of sorption model
Variables
type(solutexsoil), dimension(:), allocatable, public adepar
structure of solute parameters
integer(kind=ikind), public isotherm
type of used sorption isotherm 0 - linear 1 - Friedrich exponential 2 - Langmuir
logical, public with_richards
integer, public file_contaminant
Variable Documentation
type(solutexsoil), dimension(:), allocatable, public ade_globals::adepar
structure of solute parameters
Definition at line 39 of file ADE_globals.f90.
Referenced by ade_fnc::ade_convection(), ade_fnc::ade_cscl_react(), ade_fnc::ade_cscs_react(), ade_fnc::ade_flux(), ade_fnc::ade_icond(), ade_fnc::ade_mass(), ade_fnc::ade_reaction(), ade_reader::ade_read(), ade_fnc::ade_tder_coef(), ade_fnc::ade_tder_cscl(), ade_fnc::ade_zerorder(), ade_fnc::adecs_mass(), ade_fnc::adedispersion(), and heat_pointers::heat_source().
  type(solutexsoil), dimension(:), allocatable, public :: adepar
integer, public ade_globals::file_contaminant
Definition at line 52 of file ADE_globals.f90.
Referenced by ade_reader::ade_read().
  integer, public :: file_contaminant
integer(kind=ikind), public ade_globals::isotherm
type of used sorption isotherm 0 - linear 1 - Friedrich exponential 2 - Langmuir
Definition at line 47 of file ADE_globals.f90.
  integer(kind=ikind), public :: isotherm
logical, public ade_globals::with_richards
Definition at line 49 of file ADE_globals.f90.
Referenced by ade_reader::ade_read().
  logical, public :: with_richards