pmatools Module Reference
nektere nastroje
Data Types
interface readint
Functions/Subroutines
subroutine, public getyesno (message, choice)
vytiskne zpravu a ziska odpoved
subroutine, public pockej (message)
pozastavi vypocet a pripadne zastavi
subroutine, public get_free_unit (fil)
nalezne prvni volne cislo zarizeni
subroutine, public safe_open_write (name, fil, mode)
Otevre soubor k zapisu.
subroutine, public safe_open_read (name, fil, mode)
Otevre soubor na cteni.
character(len=:, kind=chkind) function, allocatable, public read_line (unit, ierr)
precte jednu radku ze souboru pripojeneho k jednotce unit. prodpoklada se soubor otevreny s encoding='UTF-8'
character(len=:) function, allocatable, public filetostr (name)
integer function, public findsubstr (Line, Str, mode)
subroutine readdir (StrList, Prefix, Files)
subroutine readinti (I, low1, high1, fil1)
subroutine readintl (I, low1, high1, fil1)
real(kind=rkind) function dot_product (x, y)
subroutine tools_test
Variables
character, private dirsep =``
Detailed Description
nektere nastroje
Function/Subroutine Documentation
real(kind=rkind) function pmatools::dot_product (real(kind=rkind), dimension(:), intent(in) x, real(kind=rkind), dimension(:), intent(in) y)
Definition at line 460 of file pmatools.f90.
        use typy
        implicit none
        real(kind=rkind), dimension(:), intent(in) :: x,y
        real(kind=rkind) :: r
        integer(kind=ikind) :: i
        r = 0
        do i = lbound(x,1), ubound(x,1)
            r = r + x(i)*y(i)
        end do
character(len=:) function, allocatable, public pmatools::filetostr (character(len=*), intent(in) name)
Definition at line 246 of file pmatools.f90.
References read_line(), and safe_open_read().
        use typy
        implicit none
        character(Len=*), intent(in) :: name
        character(len=:), allocatable :: ret, wrk, name1
        integer :: ierr, fil
        name1= name
        call safe_open_read(name1,fil)
        ret = ""
        do
            wrk = read_line(fil,ierr)
            if (ierr == 2) then
            print *,"chybicka se vloudila"
            else if (ierr == 1) then
                exit ! doslo se na konec souboru
            end if
            ret = ret // wrk
        end do
integer function, public pmatools::findsubstr (character(kind=chkind, len=*), intent(in) Line, character(kind=chkind, len=*), intent(in) Str, integer, intent(in), optional mode)
Parameters
in line prohledavany radek
in str hledany retezec
in mode kam unisti nalezeny inndex
0 ... pred prvni znak nalezenoho retezce
1 ... za posledni znak nalezeneho retezce
Returns
navratova hodnota
nezaporna hodnota nalezena pozice
-1 ... nalezeny retezec nebyl nalezen !!! pozor: nalezena pozice muze byt i o jedna nizsi, nebo vyssi nez jsou rozmery retezce
Definition at line 267 of file pmatools.f90.
        use typy
        implicit none
        character(kind=chkind, len=*), intent(in) :: line
        character(kind=chkind, len=*), intent(in) :: str
        integer, optional, intent(in) :: mode
        integer :: pos, md
        if (present(mode)) then
        md = mode
        else
            md = 0
        end if
        pos = index(line,str)
        if (pos == 0) then
            pos = -1
            return
        end if
        if (md == 0) then
        pos = pos - 1
        else
            pos = pos + len(str)
        end if
subroutine, public pmatools::get_free_unit (integer, intent(out) fil)
nalezne prvni volne cislo zarizeni
v soucasnosti je lepsi uzit newunit
Parameters
out fil hledane cislo zarizeni
Definition at line 65 of file pmatools.f90.
Referenced by mtxiotools::read_matrix().
        integer, intent(out) :: fil
        logical :: ex,op
        fil = 101
        do
            inquire(unit=fil,exist=ex,opened=op)
            if (.not. ex) then
            fil = fil + 1 !jednotka vubec neexistuje, tak dalsi
            else
                if (op) then
                fil = fil + 1 !existuje, ale je otevrena
                else
                    exit !existuje a neni otevrena
                end if
            end if
        end do
subroutine, public pmatools::getyesno (character(len=*), intent(in) message, logical, intent(out) choice)
vytiskne zpravu a ziska odpoved
Parameters
in message zprava
out choice odpoved
Definition at line 24 of file pmatools.f90.
Referenced by pockej(), safe_open_read(), and safe_open_write().
        character(len=*), intent(in) :: message
        logical, intent(out) :: choice
        character(len=1) :: z
        do
            print *, message
            print *,"zvol y nebo n (y..yes, n .. no)"
            read(unit=*,fmt=*) z
            if (z == "y" .or. z == "Y") then
                choice = .true.
            exit
            else if (z == "n" .or. z == "N") then
                choice = .false.
            exit
            else
                print *, "chybna volba"
            end if
        end do
subroutine, public pmatools::pockej (character(len=*), intent(in), optional message)
pozastavi vypocet a pripadne zastavi
Parameters
in message zprava
Definition at line 47 of file pmatools.f90.
References getyesno().
Referenced by mtxiotools::read_matrix().
        implicit none
        character(len=*),optional, intent(in) :: message
        logical :: volba
        if (present(message)) then
        call getyesno(message // "Preruseni, pokracovat?",volba)
        else
            call getyesno("Preruseni, pokracovat?",volba)
        end if
        if (.not. volba) stop "Program prerusen v pause"
character(len=:,kind=chkind) function, allocatable, public pmatools::read_line (integer, intent(in) unit, integer, intent(out), optional ierr)
precte jednu radku ze souboru pripojeneho k jednotce unit. prodpoklada se soubor otevreny s encoding='UTF-8'
Returns
fdf
Parameters
in unit cislo jednotky s pripojenym souborem
out ierr nepovinna promenna pro chybovou zpravu
0 ... OK
1 ... konec souboru
2 ... chyba
Returns
precteny obsah radku
Definition at line 199 of file pmatools.f90.
Referenced by filetostr(), and readdir().
        use typy
        implicit none
        integer, intent(in) :: unit
        integer, intent(out), optional :: ierr
        character(len=:,kind=chkind), allocatable :: txt
        character(len=2000, kind=chkind) :: wrk
        character(len=2048) :: msg
        integer :: ln,aln, chyba
        ln = 0
        txt = ""
        do
            read(unit=unit,advance='no',fmt="(a2000)",eor=1, err=2,end=3,&
            size=aln, iostat=chyba, iomsg=msg) wrk
            txt = txt // wrk
            ln = ln + aln
            !print *, txt
            cycle
            1 continue
            !print *, "konec radku"
            txt = txt // wrk(1:aln)
            ln = ln+aln
            !print *, "celkem ", ln, " znaku"
            !print *, "text: ",txt
            if (present(ierr)) ierr = 0
            return
        end do
        3 continue
        !print *, "konec souboru"
        if (present(ierr)) ierr = 1
        !print *, msg
        return
        2 print *, "chybicka se vloudila"
        if (present(ierr)) ierr = 2
        print *, chyba, msg
subroutine pmatools::readdir (type(stringlist), intent(out) StrList, character(len=*), intent(in), optional Prefix, logical, intent(in), optional Files)
Definition at line 306 of file pmatools.f90.
References dirsep, and read_line().
        use typy
        implicit none
        type(stringlist), intent(out) :: strlist
        character(len=*), intent(in), optional :: prefix
        logical, optional, intent(in) :: files
        integer :: fil, i, ierr, cnt, delka, status
        character(len=:), allocatable :: nm,pr1
        logical :: fl
        if (present(prefix)) then
        pr1 = prefix
        else
            pr1 = ""
        end if
        if (present(files)) then
        fl = files
        else
            fl = .true.
        end if
        if (fl) then
        call system("dir /B " // pr1 // "> lst.txt",status)
        else
            call system("dir /B /AD " // pr1 // "> lst.txt",status)
        end if
        print *,"status",status
        if (status==0) then
            open(newunit=fil, file="lst.txt")
            cnt = 0
            do
                nm = read_line(fil,ierr)
                if (ierr==1) exit
                cnt = cnt + 1
                print *,cnt, nm
            end do
            rewind(fil)
            strlist%pocet = cnt
            allocate(strlist%name(1:cnt))
            allocate(strlist%delka(1:cnt))
            do i=1,cnt
                nm = read_line(fil,ierr)
                delka = len(nm)
                strlist%name(i)(1:delka) = nm
                strlist%delka(i) = delka
            end do
        close(fil)
        else
            print *,"prvni pokus nevysel, zkusim linuxovou variantu"
            dirsep = "/"
            call system("ls -aF " // pr1 // "> lst.txt",status)
            if (status == 0) then
                open(newunit=fil, file="lst.txt")
                cnt = 0
                do
                    nm = read_line(fil,ierr)
                    if (ierr==1) exit
                    if (nm(len(nm):len(nm))/="/") then
                        if (fl) then
                            cnt = cnt + 1
                            !print *,cnt, nm
                        end if
                    else
                        if (.not. fl) then
                            cnt = cnt + 1
                            !print *,cnt, nm
                        end if
                    end if
                end do
                rewind(fil)
                strlist%pocet = cnt
                !print *, "pocet radku=",cnt
                allocate(strlist%name(1:cnt))
                allocate(strlist%delka(1:cnt))
                i = 0
                do
                    nm = read_line(fil,ierr)
                    delka = len(nm)
                    !print *,i,delka, nm
                    if(nm(delka:delka)/="/") then
                        if (fl) then
                            i = i+1
                            strlist%name(i)(1:delka) = nm
                            strlist%delka(i) = delka
                        end if
                    else
                        if (.not. fl) then
                            i = i+1
                            strlist%name(i)(1:delka-1) = nm
                            strlist%delka(i) = delka-1
                        end if
                    end if
                    if (i==cnt) exit
                end do
                close(fil)
            else
                stop "neuspech pri cteni adresare"
            end if
        end if
subroutine pmatools::readinti (integer, intent(out) I, integer, intent(in), optional low1, integer, intent(in), optional high1, integer, intent(in), optional fil1)
Definition at line 413 of file pmatools.f90.
        use typy
        implicit none
        integer, intent(out) :: i
        integer, intent(in), optional ::low1, high1
        integer ::low, high
        integer, intent(in), optional :: fil1
        integer :: fil
        fil = 5
        low = -huge(low)
        high = huge(high)
        if (present(fil1)) fil = fil1
        if (present(low1)) low = low1
        if (present(high1)) high = high1
        do
            read(unit=fil, fmt=*, err = 5) i
            if ((i<low).or. (i>high)) goto 5
            return
            5 print *, "ocekavam cele cislo v intervalu <",low,",",high,">"
        end do
subroutine pmatools::readintl (integer(kind=likind), intent(out) I, integer(kind=likind), intent(in), optional low1, integer(kind=likind), intent(in), optional high1, integer, intent(in), optional fil1)
Definition at line 436 of file pmatools.f90.
        use typy
        implicit none
        integer(kind=likind), intent(out) :: i
        integer(kind=likind), intent(in), optional ::low1, high1
        integer(kind=likind) ::low, high
        integer, intent(in), optional :: fil1
        integer :: fil
        fil = 5
        low = -huge(low)
        high = huge(high)
        if (present(fil1)) fil = fil1
        if (present(low1)) low = low1
        if (present(high1)) high = high1
        do
            read(unit=fil, fmt=*, err = 5) i
            if ((i<low).or. (i>high)) goto 5
            return
            5 print *, "ocekavam cele cislo v intervalu <",low,",",high,">"
        end do
subroutine, public pmatools::safe_open_read (character(len=*), intent(inout) name, integer, intent(in) fil, integer, intent(in), optional mode)
Otevre soubor na cteni.
V pripade neexistence zkusit se zeptat Rozhoduje o tom hodnota parametru mode
Parameters
in,out name jmeno oteviraneho souboru , muze se zmenit, pokud neexistuje
in fil cislo jednotky
in mode mod chovani (neni-li zadan plati 0)
0 neptej se a skonci
1 pozadej o pomoc
Definition at line 147 of file pmatools.f90.
References getyesno().
Referenced by filetostr(), and mtxiotools::read_matrix().
        character(len=*), intent(in out) :: name
        character(len=200) :: name1
        integer, intent(in) :: fil
        integer, intent(in), optional :: mode
        integer :: mode1
        logical :: ex, choice
        if (present(mode)) then
        mode1 = mode
        else
            mode1 = 0
        end if
        name1 = name
        do
            inquire(file=name1, exist=ex)
            if (.not. ex) then
                md: if (mode1==0) then
                stop "soubor neexistuje - nelze pokracovat"
                else if (mode1==1) then
                    call getyesno(&
                    "soubor s udanym jmenem neexistuje. Zadat jine jmeno?",choice)
                    chc: if (.not. choice) then
                    stop "soubor neexistuje - nelze pokracovat"
                    else
                        print *, "zadej jmeno souboru"
                        read(unit=*,fmt=*) name1
                        print *,"jmeno:", name1
                    end if chc
                else
                    open(unit=fil, file=name1,action="read")
                    print *,"otevreno"
                    exit
                end if md
            else
                print *,"oteviram"
                open(unit=fil, file=name1, action="read")
                exit
            end if
        end do
        name = name1
subroutine, public pmatools::safe_open_write (character(len=*), intent(inout) name, integer, intent(in) fil, integer, intent(in), optional mode)
Otevre soubor k zapisu.
V pripade pokusu o prepis muze pozadat o schvaleni. Rozhoduje o tom hodnota parametru mode
Parameters
in,out name jmeno oteviraneho souboru , muze se zmenit, pokud uz existuje
in fil cislo jednotky
in mode mod chovani (neni-li zadan plati 0)
0 neptej se a skonci
1 pozadej o pomoc
2 neptej se a prepis
Definition at line 89 of file pmatools.f90.
References getyesno().
        character(len=*), intent(in out) :: name
        character(len=200) :: name1
        integer, intent(in) :: fil
        integer, intent(in), optional :: mode
        integer :: mode1
        logical :: ex, choice
        if (present(mode)) then
        mode1 = mode
        else
            mode1 = 0
        end if
        name1 = name
        do
            inquire(file=name1, exist=ex)
            if (ex) then
                md: if (mode1==0) then
                stop "soubor uz existuje, neprepisuji"
                else if (mode1==1) then
                    call getyesno(&
                    " soubor s udanym jmenem existuje. Prepsat?",choice)
                    chc: if (choice) then
                        !! tohle by byt melo
                        !open(unit=fil, file=name1,status="replace",&
                        !action="write")
                        !! zatim nahradime
                        call unlink(name1)
                        open(unit=fil, file=name1,action="write")
                    exit
                    else
                        print *, "zadej jmeno souboru"
                        read(unit=*,fmt=*) name1
                    end if chc
                else
                    !print *, " podivne"
                    open(unit=fil, file=name1,status="replace",&
                    action="write")
                    exit
                end if md
            else
                open(unit=fil, file=name1,status="new", action="write")
                exit
            end if
        end do
        name = name1
subroutine pmatools::tools_test ()
Definition at line 474 of file pmatools.f90.
Variable Documentation
character, private pmatools::dirsep =`` [private]
Definition at line 6 of file pmatools.f90.
Referenced by readdir().
    character, private :: dirsep=""