heat_fnc Module Reference
Functions/Subroutines
subroutine, public heat_conduct (pde_loc, layer, quadpnt, x, tensor, scalar)
subroutine, public heat_convect (pde_loc, layer, quadpnt, x, vector_in, vector_out, scalar)
real(kind=rkind) function, public heat_elast (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public heat_source (pde_loc, layer, quadpnt, x)
subroutine, public heat_dirichlet (pde_loc, el_id, node_order, value, code)
subroutine, public heat_neumann (pde_loc, el_id, node_order, value, code)
subroutine, public heat_flux (pde_loc, layer, quadpnt, x, grad, flux, flux_length)
subroutine, public heat_icond (pde_loc)
Function/Subroutine Documentation
subroutine, public heat_fnc::heat_conduct (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:,:), intent(out), optional tensor, real(kind=rkind), intent(out), optional scalar)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
out tensor return tensor
out scalar relative scalar value of the nonlinear function
Definition at line 12 of file heat_fnc.f90.
References globals::drutes_config, and heat_globals::heatpar.
Referenced by heat_pointers::heat().
      use typy
      use global_objs
      use pde_objs
      use globals
      use heat_globals
      use debug_tools
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:,:), intent(out), optional :: tensor
      real(kind=rkind), intent(out), optional :: scalar
      integer(kind=ikind) :: d, i
      
     
      d = drutes_config%dimen
      
      if (present(tensor)) then
        tensor = heatpar(layer)%lambda
      end if
      
    
subroutine, public heat_fnc::heat_convect (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional vector_in, real(kind=rkind), dimension(:), intent(out), optional vector_out, real(kind=rkind), intent(out), optional scalar)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
in vector_in input vector
out vector_out output vector
out scalar relative scalar value of the nonlinear function
Definition at line 46 of file heat_fnc.f90.
References heat_globals::heatpar, and typy::norm2().
Referenced by heat_pointers::heat().
      use typy
      use global_objs
      use pde_objs
      use heat_globals
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: vector_in
      real(kind=rkind), dimension(:), intent(out), optional :: vector_out
      real(kind=rkind), intent(out), optional :: scalar
      
      
        if (present(vector_out)) then
          vector_out = heatpar(layer)%C_w*heatpar(layer)%convection
        end if
        
        
        if (present(scalar)) then
          scalar = norm2(heatpar(layer)%C_w*heatpar(layer)%convection)
        end if
   
      
subroutine, public heat_fnc::heat_dirichlet (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 134 of file heat_fnc.f90.
References globals::elements, globals::nodes, and globals::time.
Referenced by heat_pointers::heat().
      use typy
      use globals
      use global_objs
      use pde_objs
      use debug_tools
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      
      integer(kind=ikind) :: edge_id, i, j, proc
      real(kind=rkind) :: tempval
      
      edge_id = nodes%edge(elements%data(el_id, node_order))
      
      if (present(value)) then
        if (pde_loc%bc(edge_id)%file) then
          do i=1, ubound(pde_loc%bc(edge_id)%series,1)
            if (pde_loc%bc(edge_id)%series(i,1) > time) then
              if (i > 1) then
                j = i-1
              else
                j = i
              end if
              tempval = pde_loc%bc(edge_id)%series(j,2)
              EXIT
            end if
          end do
        else
          tempval = pde_loc%bc(edge_id)%value
        end if
        value = tempval
      end if
      
      if (present(code)) then
        code = 1
      end if
      
real(kind=rkind) function, public heat_fnc::heat_elast (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting system elasticity
Definition at line 78 of file heat_fnc.f90.
References heat_globals::heatpar.
Referenced by heat_pointers::heat().
      use typy
      use heat_globals
      use pde_objs
      use core_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: e
       
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen_elast"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::vangen_elast"
        error stop
      end if
      e = heatpar(layer)%C
      
subroutine, public heat_fnc::heat_flux (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional grad, real(kind=rkind), dimension(:), intent(out), optional flux, real(kind=rkind), intent(out), optional flux_length)
Parameters
in grad this value is optional, because it is required by the vector_fnc procedure pointer global definition
Definition at line 228 of file heat_fnc.f90.
References heat_globals::heatpar, and typy::norm2().
Referenced by heat_pointers::heat().
      use typy
      use pde_objs
      use global_objs
      use debug_tools
      use heat_globals
       
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), intent(in), dimension(:), optional :: x
      real(kind=rkind), dimension(:), intent(in), optional :: grad
      real(kind=rkind), dimension(:), intent(out), optional :: flux
      real(kind=rkind), intent(out), optional :: flux_length
    
      real(kind=rkind), dimension(:), allocatable, save :: gradt
      
      
      if (present(quadpnt) .and. (present(grad) .or. present(x))) then
        print *, "ERROR: the function can be called either with integ point or x value definition and
       gradient, not both of them"
        print *, "exited from heat_fnc::heat_flux"
        error stop
      else if ((.not. present(grad) .or. .not. present(x)) .and. .not. present(quadpnt)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from heat_fnc::heat_flux"
        error stop
      end if
      if (.not. allocated(gradt)) allocate(gradt(drutes_config%dimen))
      if (present(quadpnt)) then
        call pde_loc%getgrad(quadpnt, gradt)
      else
        gradt = grad
      end if
      
      
      if (present(flux)) then
        flux = matmul(heatpar(layer)%lambda, gradt)
      end if
      
      if (present(flux_length)) then
        flux_length = norm2(matmul(heatpar(layer)%lambda, gradt))
      end if
    
subroutine, public heat_fnc::heat_icond (class(pde_str), intent(inout) pde_loc)
Definition at line 278 of file heat_fnc.f90.
References globals::elements, heat_globals::heatpar, and globals::nodes.
Referenced by heat_pointers::heat().
      use typy
      use globals
      use global_objs
      use pde_objs
      use heat_globals
      
      class(pde_str), intent(in out) :: pde_loc
      integer(kind=ikind) :: i, j, k,l, m, layer, d
      real(kind=rkind) :: value
      
   
      do i=1, elements%kolik
        layer = elements%material(i,1)
        do j=1, ubound(elements%data,2)
          k = elements%data(i,j)
          l = nodes%edge(k)
          m = pde_loc%permut(k)
          if (m == 0) then
            call pde_loc%bc(l)%value_fnc(pde_loc, i, j, value)
            pde_loc%solution(k) = value
          else
            pde_loc%solution(k) = heatpar(layer)%Tinit
          end if
        end do
      end do
    
    
subroutine, public heat_fnc::heat_neumann (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 180 of file heat_fnc.f90.
References globals::elements, globals::nodes, and globals::time.
Referenced by heat_pointers::heat().
      use typy
      use globals
      use global_objs
      use pde_objs
      use debug_tools
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      
      integer(kind=ikind) :: edge_id, i, j, proc
      real(kind=rkind) :: tempval
      
      edge_id = nodes%edge(elements%data(el_id, node_order))
      
      if (present(value)) then
        if (pde_loc%bc(edge_id)%file) then
          do i=1, ubound(pde_loc%bc(edge_id)%series,1)
            if (pde_loc%bc(edge_id)%series(i,1) > time) then
              if (i > 1) then
                j = i-1
              else
                j = i
              end if
              tempval = pde_loc%bc(edge_id)%series(j,2)
              EXIT
            end if
          end do
        else
          tempval = pde_loc%bc(edge_id)%value
        end if
        value = tempval
      end if
      
      if (present(code)) then
        code = 2
      end if
      
real(kind=rkind) function, public heat_fnc::heat_source (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 112 of file heat_fnc.f90.
References heat_globals::heatpar.
Referenced by heat_pointers::heat().
      use typy
      use global_objs
      use pde_objs
      use heat_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      
      val = heatpar(layer)%source
      
      