globals1d Module Reference
contains specific variables for 1D problem
Variables
real(kind=rkind), public length_1d
1D mesh data
real(kind=rkind), dimension(:,:), allocatable, public deltax_1d
1D domain discretization array
real(kind=rkind), dimension(:,:), allocatable, public materials_1d
1D materials
integer(kind=ikind), dimension(:), allocatable, public permut_vector
permutation array - how-to permutate, for 1D
integer(kind=ikind), dimension(:), allocatable, public permut_inverse
Detailed Description
contains specific variables for 1D problem
Variable Documentation
real(kind=rkind), dimension(:,:), allocatable, public globals1d::deltax_1d
1D domain discretization array
Definition at line 24 of file globals1D.f90.
Referenced by read_inputs::read_1dmesh_int(), and simegen::simegen1d().
  real(kind=rkind), dimension(:,:), allocatable, public :: deltax_1d
real(kind=rkind), public globals1d::length_1d
1D mesh data
Definition at line 22 of file globals1D.f90.
Referenced by read_inputs::read_1dmesh_int().
  real(kind=rkind), public :: length_1d
real(kind=rkind), dimension(:,:), allocatable, public globals1d::materials_1d
1D materials
Definition at line 26 of file globals1D.f90.
Referenced by read_inputs::read_1dmesh_int(), and simegen::simegen1d().
  real(kind=rkind), dimension(:,:), allocatable, public :: materials_1d
integer(kind=ikind), dimension(:), allocatable, public globals1d::permut_inverse
Definition at line 29 of file globals1D.f90.
  integer(kind=ikind), dimension(:), allocatable, public :: permut_inverse
integer(kind=ikind), dimension(:), allocatable, public globals1d::permut_vector
permutation array - how-to permutate, for 1D
Definition at line 28 of file globals1D.f90.
  integer(kind=ikind), dimension(:), allocatable, public :: permut_vector