re_constitutive Module Reference
Functions/Subroutines
subroutine, private intoverflow ()
real(kind=rkind) function, public vangen (pde_loc, layer, quadpnt, x)
Van Genuchten relation
 \theta = f(pressure) 
 \theta_e = \frac{1}{(1+(\alpha*h)^n)^m} 
 water content is considered as absolute value not the relative one
 see
 \theta_e = \frac{\theta - \theta_r}{\theta_s-\theta_r} 
.
real(kind=rkind) function, public gardner_wc (pde_loc, layer, quadpnt, x)
Gardner relation
 \theta = f(pressure) 
 \theta = \frac{1}{(1+(\alpha*h)^n)^m} 
.
real(kind=rkind) function, public inverse_vangen (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public vangen_tab (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public vangen_elast (pde_loc, layer, quadpnt, x)
so-called retention water capacity, it is a derivative to retention curve function E(h) = C(h) + {(h)}{}S_s ] where
 C(h) = \left\{ \begin{array}{l l}\frac{m n \alpha (-h \alpha )^{-1+n}}{\left(1+(-h \alpha )^n\right)^{1+m}}(\theta_s - \theta_r) , & \quad \mbox{$\forall$ $h \in (-\infty, 0 )$}\\ 0, & \quad \mbox{$\forall$ $h \in \langle 0, + \infty )$}\\ \end{array} \right. 
 and
 \theta(h) = \left\{ \begin{array}{l l} \frac{\theta_s -\theta_r}{(1+(-\alpha h)^n_{vg})^m_{vg}} + \theta_r, & \quad \mbox{$\forall$ $h \in (-\infty, 0 )$}\\ \theta_S, & \quad \mbox{$\forall$ $h \in \langle 0, + \infty )$}\\ \end{array} \right. 
real(kind=rkind) function, public gardner_elast (pde_loc, layer, quadpnt, x)
so-called retention water capacity, it is a derivative to retention curve function
 E(h) = \left\{ \begin{array}{l l} \alpha (\theta_s - \theta_r) exp(\alpha h) , & \quad \mbox{$\forall$ $h \in (-\infty, 0 )$}\\ 0, & \quad \mbox{$\forall$ $h \in \langle 0, + \infty )$}\\ \end{array} \right. 
real(kind=rkind) function, public vangen_elast_tab (pde_loc, layer, quadpnt, x)
subroutine, public mualem (pde_loc, layer, quadpnt, x, tensor, scalar)
Mualem's fucntion for unsaturated hydraulic conductivity with van Genuchten's water content substitution
 K(h) = \left\{ \begin{array}{l l} K_s\frac{\left( 1- (-\alpha h)^{n_{vg}m_{vg}} \left( 1+ (-\alpha h)^{n_{vg}} \right)^{-m_{vg}} \right)^2}{\left(1+(-\alpha h)^{n_{vg}} \right)^{\frac{m_{vg}}{2}}}, & \mbox{$\forall$ $h \in$ $(-\infty,0)$}\\ K_s, \mbox{$\forall$ $h \in$ $\langle 0, +\infty)$}\\ \end{array} \right. 
.
subroutine, public gardner_ks (pde_loc, layer, quadpnt, x, tensor, scalar)
Gardner's fucntion for unsaturated hydraulic conductivity
 K(h) = K_s exp(\alpha h), \mbox{$\forall$ $h \in$ $(-\infty,0)$}\\ K_s, \mbox{$\forall$ $h \in$ $\langle 0, +\infty)$}. 
.
subroutine, public mualem_tab (pde_loc, layer, quadpnt, x, tensor, scalar)
subroutine, public dmualem_dh (pde_loc, layer, quadpnt, x, vector_in, vector_out, scalar)
derivative of Mualem's function with van Genuchten's substitution for water content function
 \frac{\textrm{d} K(h)}{\textrm{d} h} = \left\{ \begin{array}{l l} K_s \frac{1}{2} \alpha (-\alpha h)^{(-1 + n)} (1 + (-\alpha h)^n)^{(-1 - m/ 2)} (1 - (-\alpha h)^{(m n)} (1 + (-\alpha h)^n)^{-m})^2 m n + 2 (1 + (-\alpha h)^n)^{(-m/2)} (1 - (-\alpha h)^{(m n)} (1 + (-\alpha h)^n)^{-m}) (-\alpha (-\alpha h)^{(-1 + n + m n)} (1 + (-\alpha h)^n)^{(-1 - m)} m n + \alpha (-\alpha h)^{(-1 + m n)} (1 + (-a h)^n)^{-m} m n), \quad \mbox{$\forall$ $h \in$ $(-\infty,0)$}\\ 0, \quad \mbox{$\forall$ $h \in$ $\langle 0, +\infty)$}\\ \end{array} \right. 
real(kind=rkind) function, public derkz (pde_loc, layer, quadpnt, x)
subroutine, public convection_rerot (pde_loc, layer, quadpnt, x, vector_in, vector_out, scalar)
convection term for the Richards equation for axisymmetric problems the vertical convection is equal as for the Richards equatio in standard coordinates, the horizontal convection equals [\ {1}{r}K(h)
real(kind=rkind) function, public sinkterm (pde_loc, layer, quadpnt, x)
subroutine, public dmualem_dh_tab (pde_loc, layer, quadpnt, x, vector_in, vector_out, scalar)
subroutine, public darcy_law (pde_loc, layer, quadpnt, x, grad, flux, flux_length)
subroutine tabvalues (pde_loc, Kfnc, dKdhfnc, Cfnc, thetafnc)
creates a table of values of constitutive functions for the Richards equation to be linearly approximated
subroutine, public domainswitch (domain)
subroutine, public init_zones (vg)
real(kind=rkind) function, private zone_error_val (h, htest, taylor_max)
pure real(kind=rkind) function, private secondder_retc (h)
logical function, private rcza_check_old ()
logical function, public rcza_check (pde_loc)
subroutine, public re_dirichlet_bc (pde_loc, el_id, node_order, value, code)
subroutine, public re_null_bc (pde_loc, el_id, node_order, value, code)
subroutine, public re_dirichlet_height_bc (pde_loc, el_id, node_order, value, code)
subroutine, public re_neumann_bc (pde_loc, el_id, node_order, value, code)
subroutine re_atmospheric (pde_loc, el_id, node_order, value, code)
subroutine, public re_initcond (pde_loc)
subroutine, private setmatflux ()
Variables
real(kind=rkind), dimension(:,:), pointer, public ktab
real(kind=rkind), dimension(:,:), pointer, public dkdhtab
real(kind=rkind), dimension(:,:), pointer, public warecatab
real(kind=rkind), dimension(:,:), pointer, public watcontab
real(kind=rkind), dimension(:,:,:), allocatable, target, public ktab_all
real(kind=rkind), dimension(:,:,:), allocatable, target, public dkdhtab_all
real(kind=rkind), dimension(:,:,:), allocatable, target, public warecatab_all
real(kind=rkind), dimension(:,:,:), allocatable, target, public watcontab_all
type(soilpar), private van_gen_coeff
integer(kind=ikind), private this_layer
logical, private tabwarning = .false.
character(len=4096), private tabmsg = `DRUtES requested values of the constitutive functions out of the range of your precalculated table, the function will be evaluated directly, it will slow down your computation, is everything ok? If yes, increase the length of interval for precaculating the constitutive functions in your config files`
logical, private intwarning = .false.
Function/Subroutine Documentation
subroutine, public re_constitutive::convection_rerot (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional vector_in, real(kind=rkind), dimension(:), intent(out), optional vector_out, real(kind=rkind), intent(out), optional scalar)
convection term for the Richards equation for axisymmetric problems the vertical convection is equal as for the Richards equatio in standard coordinates, the horizontal convection equals [\ {1}{r}K(h)
Parameters
in x pressure head
in vector_in this argument is required by the global vector_fnc procedure pointer, unused in this procedure
out scalar relative unsaturated hydraulic conductivity derivative in respect to h, scalar value
Definition at line 963 of file re_constitutive.f90.
References dmualem_dh(), dmualem_dh_tab(), globals::drutes_config, and geom_tools::getcoor().
Referenced by re_pointers::re_rot(), and re_pointers::reroth().
      use typy
      use globals
      use global_objs
      use pde_objs
      use re_globals
      use geom_tools
      use debug_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), dimension(:), intent(in), optional :: x
      real(kind=rkind), dimension(:), intent(in), optional :: vector_in
      real(kind=rkind), dimension(:), intent(out), optional :: vector_out
      real(kind=rkind), intent(out), optional :: scalar
      
      real(kind=rkind), dimension(2) :: coord
      real(kind=rkind) :: a,n,m, tmp, h, k, flux
      integer :: proc
      type(integpnt_str) :: quadpnt_loc
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::dmualem_dh"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::dmualem_dh"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::dmualem_dh"
          error stop
        end if
        h = x(1)
      end if
      
      select case (drutes_config%name)
        case("RE_rot")
          if (drutes_config%fnc_method == 0) then
            call dmualem_dh(pde_loc, layer, x=(/h/), vector_out = vector_out)
          else
            call dmualem_dh_tab(pde_loc, layer, x=(/h/), vector_out = vector_out)
          end if
        case("RErotH")
          vector_out = 0
      end select
      
      tmp = vector_out(2)
      
      call getcoor(quadpnt, coord)
      
      call pde_loc%flux(layer, quadpnt, vector_out=vector_out)
      
      vector_out(2) = tmp
      
! if (abs(coord(2)) < -12.5) then
        vector_out(1) = 1.0_rkind/coord(1)*vector_out(1)
! else
! vector_out(1) = 0
! end if
subroutine, public re_constitutive::darcy_law (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional grad, real(kind=rkind), dimension(:), intent(out), optional flux, real(kind=rkind), intent(out), optional flux_length)
Parameters
in grad this value is optional, because it is required by the vector_fnc procedure pointer global definition
Definition at line 1161 of file re_constitutive.f90.
Referenced by re_pointers::re_rot(), and re_pointers::re_std().
      use typy
      use pde_objs
      use global_objs
       
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), intent(in), dimension(:), optional :: x
      real(kind=rkind), dimension(:), intent(in), optional :: grad
      real(kind=rkind), dimension(:), intent(out), optional :: flux
      real(kind=rkind), intent(out), optional :: flux_length
      real(kind=rkind), dimension(3,3) :: k
      integer :: d
      integer(kind=ikind) :: i
      integer(kind=ikind), dimension(3) :: nablaz
      real(kind=rkind), dimension(3) :: gradh
      real(kind=rkind), dimension(3) :: vct
      real(kind=rkind) :: h
      real(kind=rkind), dimension(:), allocatable :: gradient
      type(integpnt_str) :: quadpnt_loc
      
      
      
      if (present(quadpnt) .and. (present(grad) .or. present(x))) then
        print *, "ERROR: the function can be called either with integ point or x value definition and
       gradient, not both of them"
        error stop
      else if ((.not. present(grad) .or. .not. present(x)) .and. .not. present(quadpnt)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::darcy_law"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
        call pde_loc%getgrad(quadpnt, gradient)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::darcy_law"
          error stop
        end if
        h = x(1)
        allocate(gradient(ubound(grad,1)))
        gradient = grad
      end if
      
      d = drutes_config%dimen
      nablaz = 0
      nablaz(d) = 1
      
      gradh(1:d) = gradient(1:d) + nablaz(1:d)
      call pde_loc%pde_fnc(1)%dispersion(pde_loc, layer, x=(/h/), tensor=k(1:d, 1:d))
      vct(1:d) = matmul(-k(1:d,1:d), gradh(1:d))
      if (present(flux_length)) then
        select case(d)
          case(1)
                flux_length = vct(1)
          case(2)
                flux_length = sqrt(vct(1)*vct(1) + vct(2)*vct(2))
          case(3)
                flux_length = sqrt(vct(1)*vct(1) + vct(2)*vct(2) + vct(3)*vct(3))
        end select
      end if
      if (present(flux)) then
        flux(1:d) = vct(1:d)
      end if
real(kind=rkind) function, public re_constitutive::derkz (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting system elasticity
Definition at line 859 of file re_constitutive.f90.
References geom_tools::plane_derivative().
      use typy
      use re_globals
      use pde_objs
      use geom_tools
      use debug_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: dkdz
      real(kind=rkind), dimension(3,3) :: ktmp
      
      
      real(kind=rkind) :: dkdx
      real(kind=rkind), dimension(:,:), allocatable, save :: pts
      type(integpnt_str) :: quadpnt_loc
      integer(kind=ikind) :: layer_loc, vecino, i, d
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen_elast"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::vangen_elast"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          error stop
        end if
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::vangen_elast"
          error stop
        end if
        h = x(1)
      end if
      
      
      if (.not. allocated(pts)) then
        allocate(pts(drutes_config%dimen+1, ubound(elements%data,2)))
      end if
      
      quadpnt_loc%type_pnt = "ndpt"
      quadpnt_loc%element = quadpnt%element
      quadpnt_loc%column = 2
      d = drutes_config%dimen
     
      do i=1, ubound(elements%data,2)
        quadpnt_loc%order = elements%data(quadpnt%element,i)
        vecino = elements%neighbours(quadpnt%element,i)
        if (vecino > 0) then
          layer_loc = elements%material(vecino,1)
        else
          layer_loc = elements%material(quadpnt%element,1)
        end if
        quadpnt_loc%order = elements%data(quadpnt%element, i)
        call pde_loc%pde_fnc(1)%dispersion(pde_loc, layer_loc, quadpnt_loc, tensor=ktmp(1:d, 1:d))
        pts(d+1, i) = ktmp(d,d)
        pts(1:d,i) = nodes%data(elements%data(quadpnt%element,i),1:d)
      end do
      
      
      
      select case(drutes_config%dimen)
        case(1)
          if (pts(1,2)-pts(1,1) > 0) then
            dkdz = (pts(2,2)-pts(2,1))/(pts(1,2)-pts(1,1))
          else
            dkdz = (pts(2,1)-pts(2,2))/(pts(1,1)-pts(1,2))
          end if
        case(2)
          call plane_derivative(pts(1,:), pts(2,:), pts(3,:), dkdx, dkdz)
      end select
      
      dkdz = -dkdz
        
      
    
subroutine, public re_constitutive::dmualem_dh (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional vector_in, real(kind=rkind), dimension(:), intent(out), optional vector_out, real(kind=rkind), intent(out), optional scalar)
derivative of Mualem's function with van Genuchten's substitution for water content function
 \frac{\textrm{d} K(h)}{\textrm{d} h} = \left\{ \begin{array}{l l} K_s \frac{1}{2} \alpha (-\alpha h)^{(-1 + n)} (1 + (-\alpha h)^n)^{(-1 - m/ 2)} (1 - (-\alpha h)^{(m n)} (1 + (-\alpha h)^n)^{-m})^2 m n + 2 (1 + (-\alpha h)^n)^{(-m/2)} (1 - (-\alpha h)^{(m n)} (1 + (-\alpha h)^n)^{-m}) (-\alpha (-\alpha h)^{(-1 + n + m n)} (1 + (-\alpha h)^n)^{(-1 - m)} m n + \alpha (-\alpha h)^{(-1 + m n)} (1 + (-a h)^n)^{-m} m n), \quad \mbox{$\forall$ $h \in$ $(-\infty,0)$}\\ 0, \quad \mbox{$\forall$ $h \in$ $\langle 0, +\infty)$}\\ \end{array} \right. 
Parameters
in x pressure head
in vector_in this argument is required by the global vector_fnc procedure pointer, unused in this procedure
out scalar relative unsaturated hydraulic conductivity derivative in respect to h, scalar value
Definition at line 783 of file re_constitutive.f90.
References globals::drutes_config, and re_globals::vgset.
Referenced by re_pointers::allrepointers(), convection_rerot(), dmualem_dh_tab(), re_pointers::re_rot(), and re_pointers::re_std().
      use typy
      use globals
      use pde_objs
      use re_globals
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), dimension(:), intent(in), optional :: x
      real(kind=rkind), dimension(:), intent(in), optional :: vector_in
      real(kind=rkind), dimension(:), intent(out), optional :: vector_out
      real(kind=rkind), intent(out), optional :: scalar
      real(kind=rkind) :: a,n,m, tmp, h
      type(integpnt_str) :: quadpnt_loc
      
         
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::dmualem_dh"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::dmualem_dh"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::dmualem_dh"
          error stop
        end if
        h = x(1)
      end if
      
      if (h < 0) then
        a = vgset(layer)%alpha
        n = vgset(layer)%n
        m = vgset(layer)%m
        tmp = ((a*(-(a*h))**(-1 + n)*(1 + (-(a*h))**n)**(-1 - m/2.0)* &
            (1 - (-(a*h))**(m*n)/(1 + (-(a*h))**n)**m)**2*m*n)/2.0 + &
         (2*(1 - (-(a*h))**(m*n)/(1 + (-(a*h))**n)**m)* &
            (-(a*(-(a*h))**(-1 + n + m*n)*(1 + (-(a*h))**n)**(-1 - m)*m*n) + &
              (a*(-(a*h))**(-1 + m*n)*m*n)/(1 + (-(a*h))**n)**m))/ &
          (1 + (-(a*h))**n)**(m/2.0))
      else
        tmp = 0
      end if
      if (present(vector_out)) then
        ! must be negative, because the commnon scheme of the CDE problem has negative convection, but RE
       has positive convection
        vector_out = -vgset(layer)%Ks(drutes_config%dimen,:) * tmp
      end if
      if (present(scalar)) then
        scalar = tmp
      end if
subroutine, public re_constitutive::dmualem_dh_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional vector_in, real(kind=rkind), dimension(:), intent(out), optional vector_out, real(kind=rkind), intent(out), optional scalar)
Parameters
in x pressure head
in vector_in this argument is required by the global vector_fnc procedure pointer, unused in this procedure
out scalar relative unsaturated hydraulic conductivity derivative in respect to h
Definition at line 1068 of file re_constitutive.f90.
References dkdhtab, dmualem_dh(), globals::drutes_config, intoverflow(), intwarning, tabmsg, tabwarning, re_globals::vgset, and core_tools::write_log().
Referenced by convection_rerot(), re_pointers::re_rot(), and re_pointers::re_std().
      use typy
      use globals
      use pde_objs
      use re_globals
      use core_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), dimension(:), intent(in), optional :: x
      real(kind=rkind), dimension(:), intent(in), optional :: vector_in
      real(kind=rkind), dimension(:), intent(out), optional :: vector_out
      real(kind=rkind), intent(out), optional :: scalar
      integer(kind=ikind) :: pos
      real(kind=rkind) :: res, dist, tmp, h
      type(integpnt_str) :: quadpnt_loc
      
    
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen_tab"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::dmualem_dh_tab"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::dmualem_dh_tab"
          error stop
        end if
        h = x(1)
      end if
      
      if (h<0) then
        if (h/drutes_config%fnc_discr_length < 0.1*huge(1)) then
        
          pos = int(-h/drutes_config%fnc_discr_length)+1
          if (pos <= ubound(dkdhtab,2)-1) then
            dist = -h - (pos - 1)*drutes_config%fnc_discr_length
            tmp = (dkdhtab(layer,pos+1)-dkdhtab(layer,pos))/drutes_config%fnc_discr_length*
      dist + dkdhtab(layer,pos)
          else
            if (present(quadpnt)) call dmualem_dh(pde_loc, layer, quadpnt, scalar=tmp)
            if (present(x)) call dmualem_dh(pde_loc, layer, x=x, scalar=tmp)
            if (.not. tabwarning) then
              call write_log(trim(tabmsg))
              tabwarning = .true.
            end if
          end if
        else
          if (.not. intwarning) then
            call intoverflow()
            intwarning = .true.
          end if
          if (present(quadpnt))call dmualem_dh(pde_loc, layer, quadpnt_loc, scalar=tmp)
          if (present(x))call dmualem_dh(pde_loc, layer, x=x, scalar=tmp)
        end if
          
      else
        tmp = 0
      end if
      
      if (present(vector_out)) then
        ! must be negative, because the commnon scheme of the CDE problem has negative convection, but RE
       has positive convection
        vector_out = -vgset(layer)%Ks(drutes_config%dimen,:) * tmp
      end if
      if (present(scalar)) then
        scalar = tmp
      end if
subroutine, public re_constitutive::domainswitch (character(len=1), intent(in) domain)
Definition at line 1367 of file re_constitutive.f90.
References dkdhtab, dkdhtab_all, ktab, ktab_all, re_globals::vgfractures, re_globals::vgmatrix, re_globals::vgset, warecatab, warecatab_all, watcontab, and watcontab_all.
Referenced by re_pointers::allrepointers(), and tabvalues().
      use re_globals
 
      character(len=1), intent(in) :: domain
      if (domain == "m") then
        vgset => vgmatrix
        ktab => ktab_all(1,:,:)
        dkdhtab => dkdhtab_all(1,:,:)
        warecatab => warecatab_all(1,:,:)
        watcontab => watcontab_all(1,:,:)
      else if (domain == "f") then
        vgset => vgfractures
        ktab => ktab_all(2,:,:)
        dkdhtab => dkdhtab_all(2,:,:)
        warecatab => warecatab_all(2,:,:)
        watcontab => watcontab_all(2,:,:)
      else
        error stop "runtime error, invalid argument in RE_constitutive::domainswitch() procedure"
      end if
        
real(kind=rkind) function, public re_constitutive::gardner_elast (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
so-called retention water capacity, it is a derivative to retention curve function
 E(h) = \left\{ \begin{array}{l l} \alpha (\theta_s - \theta_r) exp(\alpha h) , & \quad \mbox{$\forall$ $h \in (-\infty, 0 )$}\\ 0, & \quad \mbox{$\forall$ $h \in \langle 0, + \infty )$}\\ \end{array} \right. 
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting system elasticity
Definition at line 408 of file re_constitutive.f90.
References re_globals::vgset.
      use typy
      use re_globals
      use pde_objs
      use core_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: e
      real(kind=rkind) :: c, a, tr, ts
      type(integpnt_str) :: quadpnt_loc
          
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen_elast"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::gardner_elast"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: Gardner function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          error stop
        end if
        if (ubound(x,1) /=1) then
          print *, "ERROR: Gardner function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::gardner_elast"
          error stop
        end if
        h = x(1)
      end if
      if (h < 0) then
        a = vgset(layer)%alpha
        tr = vgset(layer)%Thr
        ts = vgset(layer)%Ths
        e = a*(-tr + ts)*exp(a*h)
      else
        e = 0
        RETURN
      end if
subroutine, public re_constitutive::gardner_ks (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:,:), intent(out), optional tensor, real(kind=rkind), intent(out), optional scalar)
Gardner's fucntion for unsaturated hydraulic conductivity
 K(h) = K_s exp(\alpha h), \mbox{$\forall$ $h \in$ $(-\infty,0)$}\\ K_s, \mbox{$\forall$ $h \in$ $\langle 0, +\infty)$}. 
.
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
out tensor second order tensor of the unsaturated hydraulic conductivity
out scalar relative hydraulic conductivity, (scalar value)
Definition at line 623 of file re_constitutive.f90.
References re_globals::vgset.
      use typy
      use re_globals
      use pde_objs
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), dimension(:,:), intent(out), optional :: tensor
      real(kind=rkind) :: h
      real(kind=rkind), intent(out), optional :: scalar
      real(kind=rkind) :: tmp
      type(integpnt_str) :: quadpnt_loc
      
  
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::gardner_ks"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::gardner_ks"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::gardner_ks"
          error stop
        end if
        h = x(1)
      end if
      
      
      if (h >= 0) then
        tmp = 1
      else
        tmp = exp(vgset(layer)%alpha*h)
      end if
        
      if (present(tensor)) then
        tensor = tmp* vgset(layer)%Ks
      end if
      if (present(scalar)) then
        scalar = tmp
      end if
real(kind=rkind) function, public re_constitutive::gardner_wc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Gardner relation
 \theta = f(pressure) 
 \theta = \frac{1}{(1+(\alpha*h)^n)^m} 
.
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting water content
Definition at line 126 of file re_constitutive.f90.
References re_globals::vgset.
      use typy
      use re_globals
      use pde_objs
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: theta
      type(integpnt_str) :: quadpnt_loc
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::gardner_wc"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::gardner_wc"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::gardner_wc"
          error stop
        end if
        h = x(1)
      end if
      
      
      if (h >=0.0_rkind) then
          theta = vgset(layer)%Ths
          RETURN
      else
          theta = vgset(layer)%Thr+(vgset(layer)%Ths - vgset(layer)%Thr)*exp(
      vgset(layer)%alpha*h)
      end if
subroutine, public re_constitutive::init_zones (type(soilpar), dimension(:), intent(inout) vg)
Definition at line 1394 of file re_constitutive.f90.
References globals::drutes_config, globals::maxpress, printtools::progressbar(), secondder_retc(), geom_tools::solve_bisect(), globals::terminal, this_layer, re_globals::vgset, and zone_error_val().
Referenced by re_pointers::allrepointers().
      use typy
      use globals
      use re_globals
      use geom_tools
      use printtools
      use debug_tools
      
      
      
      type(soilpar), intent(in out), dimension(:) :: vg
      integer(kind=ikind) :: i, j, k, l
      integer :: i_err
      logical :: increased, overzero
      real(kind=rkind) :: theta, htest, htest2, h, hprev, tmp1, tmp2, m, inflex_point
      integer, dimension(:,:), allocatable :: images_run
      real(kind=rkind), dimension(:,:,:), allocatable :: cotable[:]
      character(len=7) :: procentas
      integer(kind=ikind) :: n
      logical :: backward
      n = int(maxpress/drutes_config%fnc_discr_length)+1
      do i=1, ubound(vg,1)
        if (vg(i)%rcza_set%use) then
         allocate(vg(i)%rcza_set%tab(n, 3))
         vg(i)%rcza_set%tab = 0
        end if
      end do
      i_err = 0
      htest = 0.0
    
        
      allocate(images_run(num_images(),2))
      
      images_run(1,1) = 1
      images_run(1,2) = int(ubound(vgset,1)/num_images()) + modulo(ubound(vgset,1), num_images())
      allocate(cotable(images_run(1,2), n, 3)[*])
! do i=2, NUM_IMAGES()
! images_run(i,1) = images_run(i-1,2) + 1
! if (images_run(i,1) + int(ubound(vgset,1)/NUM_IMAGES()) <= ubound(vgset,1)) then
! images_run(i,2) = images_run(i,1) + int(ubound(vgset,1)/NUM_IMAGES())
! else
! images_run(i,2) = images_run(i,1)
! end if
! end do
    
      layers: do j=images_run(this_image(),1), images_run(this_image(),2)
                if (vgset(j)%rcza_set%use) then
                  k = j - images_run(this_image(),1) + 1
                  !backward
                  write(unit=terminal, fmt=*) "preparing layer:", j
                  this_layer = j
                  call solve_bisect(-epsilon(h), -maxpress, secondder_retc, 0.001_rkind, i_err,
      inflex_point)
                  print *, "inflex point of the layer:", j, "found at:", inflex_point
                  
                  levels: do i=1, ubound(cotable,2)
                            if (this_image() == 1) then
                              call progressbar(int(50*i/ubound(cotable,2)))
                            end if
                            h = -drutes_config%fnc_discr_length*i
                            if (i < 2) then
                              htest = -drutes_config%fnc_discr_length
                              hprev = -drutes_config%fnc_discr_length
                            else
                              htest = cotable(k,i-1,2)[this_image()]
                              hprev = htest
                            end if
                            rough: do
                                    if (zone_error_val(h, htest, vgset(j)%rcza_set%val) > 0) then
                                                  cotable(k,i,1)[this_image()] = h
                                                  cotable(k,i,2)[this_image()] = htest
                                                  exit rough
                                    else
                                      htest = htest - drutes_config%fnc_discr_length
                                      if (htest < -2*maxpress) then
                                        cotable(k,i:ubound(cotable,2),2)[this_image()] = htest
                                        do l= i, ubound(cotable,2)
                                          cotable(k,l,1)[this_image()] = -
      drutes_config%fnc_discr_length*l
                                        end do
                                        exit levels
                                      end if
                                    end if
                            end do rough
                  end do levels
    ! !forward
                  levels2: do i=1, ubound(cotable,2)
                            if (this_image() == 1) then
                              call progressbar(int(50*i/ubound(cotable,2)+50))
                            end if
                            h = -drutes_config%fnc_discr_length*i
                            if (i < 2) then
                              htest = -drutes_config%fnc_discr_length
                              hprev = -drutes_config%fnc_discr_length
                              backward = .false.
                            else
                              if (cotable(k,i-1,3)[this_image()] > inflex_point-5*
      drutes_config%fnc_discr_length) then
                                htest = h
                                hprev = h
                                backward = .false.
                              else
                                htest = cotable(k,i-1,3)[this_image()]
                                hprev = htest
                                backward = .true.
                              end if
                            end if
                            rough2: do
                                      if ((zone_error_val(h, htest, vgset(j)%rcza_set%val) > epsilon(0.0
      _rkind) .and. .not.(backward)) .or. &
                                        (zone_error_val(h, htest, vgset(j)%rcza_set%val) < 0 .and. backward
      )) then
                                      cotable(k,i,3)[this_image()] = htest
                                      exit rough2
                                    else
                                        if (htest < 0) then
                                          if (backward) then
                                            l = -1
                                          else
                                            l = 1
                                          end if
                                          htest = htest + l*drutes_config%fnc_discr_length
                                        else
                                          cotable(k,i,3)[this_image()] = huge(1.0_rkind)
                                          exit rough2
                                        end if
                                      end if
                                    end do rough2
                  end do levels2
                  if (this_image() == 1) then
                    print *, " "
                    call flush(6)
                  end if
          end if
        end do layers
        ! sync data
        sync all
        
          
        do i=1, ubound(images_run,1)
          do j=images_run(i,1), images_run(i,2)
            vg(j)%rcza_set%tab = cotable(j,:,:)[i]
          end do
        end do
         sync all
        
        deallocate(images_run)
        deallocate(cotable)
subroutine, private re_constitutive::intoverflow () [private]
Definition at line 39 of file re_constitutive.f90.
References postpro::make_print(), and core_tools::write_log().
Referenced by dmualem_dh_tab(), mualem_tab(), vangen_elast_tab(), and vangen_tab().
      use core_tools
      use postpro
      character(len=4096) :: msg
      
      write(msg, fmt=*) "You are probably experiencing oscilations", &
              "(probably convective dominance), I will print your data. Your computation (just for a case)
       is not", &
              "interrupted, but the results are probably not reliable anymore.", &
              "We will probably experience a crash soon.:) Check your model configuration to avoid", &
              "convective dominant problems."
              
      call write_log(msg)
      
      call make_print("separately")
              
      
real(kind=rkind) function, public re_constitutive::inverse_vangen (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x water content
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting pressure head
Definition at line 182 of file re_constitutive.f90.
References re_globals::vgset, and core_tools::write_log().
Referenced by re_initcond(), and re_total::retot_initcond().
      use typy
      use re_globals
      use pde_objs
      use core_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: theta
      real(kind=rkind) :: hpress
      
      
      real(kind=rkind) :: a,n,m
      type(integpnt_str) :: quadpnt_loc
      
 
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::vangen"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        theta = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::vangen"
          error stop
        end if
        theta = x(1)
      end if
      
      
      
      a = vgset(layer)%alpha
      n = vgset(layer)%n
      m = vgset(layer)%m
      
      if (abs(theta - vgset(layer)%Ths) < epsilon(theta)) then
        hpress = 0
      else
        if (theta > vgset(layer)%Ths + 10*epsilon(theta)) then
          call write_log("theta is greater then theta_s, exiting")
          print *, "called from re_constitutive::inverse_vangen"
          error stop
        else if (theta < 0) then
          call write_log("theta is negative strange, exiting")
          print *, "called from re_constitutive::inverse_vangen"
          error stop
        end if
        hpress = ((((vgset(layer)%Ths - vgset(layer)%Thr)/(theta-vgset(layer)%Thr))**(1.0_rkind/m)-1) &
        **(1.0_rkind/n))/(-a)
      end if
      
subroutine, public re_constitutive::mualem (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:,:), intent(out), optional tensor, real(kind=rkind), intent(out), optional scalar)
Mualem's fucntion for unsaturated hydraulic conductivity with van Genuchten's water content substitution
 K(h) = \left\{ \begin{array}{l l} K_s\frac{\left( 1- (-\alpha h)^{n_{vg}m_{vg}} \left( 1+ (-\alpha h)^{n_{vg}} \right)^{-m_{vg}} \right)^2}{\left(1+(-\alpha h)^{n_{vg}} \right)^{\frac{m_{vg}}{2}}}, & \mbox{$\forall$ $h \in$ $(-\infty,0)$}\\ K_s, \mbox{$\forall$ $h \in$ $\langle 0, +\infty)$}\\ \end{array} \right. 
.
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
out tensor second order tensor of the unsaturated hydraulic conductivity
out scalar relative hydraulic conductivity, (scalar value)
Definition at line 552 of file re_constitutive.f90.
References re_globals::vgset.
Referenced by re_pointers::allrepointers(), and mualem_tab().
      use typy
      use re_globals
      use pde_objs
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), dimension(:,:), intent(out), optional :: tensor
      real(kind=rkind) :: h
      real(kind=rkind), intent(out), optional :: scalar
      real(kind=rkind) :: a,n,m, tmp
      type(integpnt_str) :: quadpnt_loc
      
  
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::mualem"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::mualem"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::mualem"
          error stop
        end if
        h = x(1)
      end if
      
      
      if (h >= 0) then
        tmp = 1
      else
        a = vgset(layer)%alpha
        n = vgset(layer)%n
        m = vgset(layer)%m
        tmp = (1 - (-(a*h))**(m*n)/(1 + (-(a*h))**n)**m)**2/(1 + (-(a*h))**n)**(m/2.0_rkind)
      end if
        
      if (present(tensor)) then
        tensor = tmp* vgset(layer)%Ks
      end if
      if (present(scalar)) then
        scalar = tmp
      end if
subroutine, public re_constitutive::mualem_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:,:), intent(out), optional tensor, real(kind=rkind), intent(out), optional scalar)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
out tensor second order tensor of the unsaturated hydraulic conductivity
out scalar relative hydraulic conductivity, (scalar value)
Definition at line 687 of file re_constitutive.f90.
References intoverflow(), intwarning, ktab, mualem(), tabmsg, tabwarning, re_globals::vgset, and core_tools::write_log().
Referenced by re_pointers::allrepointers().
      use typy
      use re_globals
      use pde_objs
      use core_tools
      use debug_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), dimension(:,:), intent(out), optional :: tensor
      real(kind=rkind), intent(out), optional :: scalar
      real(kind=rkind) :: h
      integer(kind=ikind) :: pos
      real(kind=rkind) :: res, dist, tmp
      type(integpnt_str) :: quadpnt_loc
      
   
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::mualem_tab"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::mualem_tab"
        error stop
      end if
      
      
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::mualem_tab"
          error stop
        end if
        h = x(1)
      end if
      
      
      
      if (h<0) then
        if (-h/drutes_config%fnc_discr_length < 0.1*huge(1)) then
          pos = int(-h/drutes_config%fnc_discr_length)+1
          if (pos <= ubound(ktab,2)-1) then
            dist = -h - (pos - 1)*drutes_config%fnc_discr_length
            tmp = (ktab(layer,pos+1)-ktab(layer,pos))/drutes_config%fnc_discr_length*
      dist + ktab(layer,pos)
          else
            if (present(quadpnt)) call mualem(pde_loc, layer, quadpnt, scalar = tmp)
            if (present(x)) call mualem(pde_loc, layer, x=x, scalar = tmp)
            if (.not. tabwarning) then
              call write_log(trim(tabmsg))
              tabwarning = .true.
            end if
          end if
        else
          if (.not. intwarning) then
            call intoverflow()
            intwarning = .true.
          end if
          if (present(quadpnt)) call mualem(pde_loc, layer, quadpnt_loc, scalar = tmp)
          if (present(x)) call mualem(pde_loc, layer, x=x, scalar = tmp)
        end if
         
      else
        tmp = 1
      end if
      if (present(tensor)) then
        tensor = tmp* vgset(layer)%Ks
      end if
      if (present(scalar)) then
        scalar = tmp
      end if
logical function, public re_constitutive::rcza_check (class(pde_str), intent(in) pde_loc)
Definition at line 1666 of file re_constitutive.f90.
References globals::drutes_config, globals::elements, globals::nodes, and re_globals::vgset.
Referenced by re_pointers::allrepointers().
        use typy
        use globals
        use global_objs
        use re_globals
        use pde_objs
        class(pde_str),intent(in) :: pde_loc
        integer(kind=ikind) :: el, pos, mat
        logical :: passed
        integer(kind=ikind) :: i, position, nd
        real(kind=rkind) :: low, high, hprev, h
        type(integpnt_str) :: quadpnt
        
        quadpnt%type_pnt = "ndpt"
               
        do i=1, ubound(pde_loc%solution,1)
          el = nodes%element(i)%data(1)
          mat = elements%material(el,1)
            
          quadpnt%order = i
          quadpnt%column = 1
          quadpnt%preproc=.true.
          hprev = pde_loc%getval(quadpnt)
          quadpnt%column = 2
          h = pde_loc%getval(quadpnt)
          if (vgset(mat)%rcza_set%use) then
            if (hprev<0) then
              position = int(-hprev/drutes_config%fnc_discr_length)+1
              low = vgset(mat)%rcza_set%tab(position,2)
              high = vgset(mat)%rcza_set%tab(position,3)
              if (h < low .or. h > high) then
                passed = .false.
                RETURN
              end if
              end if
           end if
         end do
        passed = .true.
logical function, private re_constitutive::rcza_check_old () [private]
Definition at line 1627 of file re_constitutive.f90.
References globals::drutes_config, pde_objs::pde, pde_objs::pde_common, and re_globals::vgset.
        use typy
        use globals
        use global_objs
        use re_globals
        use pde_objs
        integer(kind=ikind) :: process
        logical :: passed
        integer(kind=ikind) :: i, j, position
        real(kind=rkind) :: low, high, hprev, h
        process = pde_common%current_proc
        do i=1, ubound(vgset,1)
          if (vgset(i)%rcza_set%use) then
            do j=pde(process)%procbase_fnc(1), pde(process)%procbase_fnc(2)
              hprev = pde_common%xvect(j,1)
              h = pde_common%xvect(j,3)
              if (h<0) then
                position = int(-hprev/drutes_config%fnc_discr_length)+1
                low = vgset(i)%rcza_set%tab(position,2)
                high = vgset(i)%rcza_set%tab(position,3)
! print *, low, h, high
                if (h < low .or. h > high) then
                  passed = .false.
                  RETURN
                end if
              end if
            end do
          end if
        end do
        passed = .true.
subroutine re_constitutive::re_atmospheric (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 1896 of file re_constitutive.f90.
References globals::drutes_config, globals::elements, globals::nodes, pde_objs::pde_common, and globals::time.
      use typy
      use globals
      use global_objs
      use pde_objs
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      
      real(kind=rkind), dimension(3,3) :: k
      
      real(kind=rkind), dimension(3) :: gravflux, bcflux
      
      type(integpnt_str) :: quadpnt
      integer(kind=ikind) :: layer
      real(kind=rkind) :: theta, bcval
      integer(kind=ikind) :: i, edge_id, j
  
  
      if (present(code)) then
        code = 2
      end if
      
      if (present(value)) then
        edge_id = nodes%edge(elements%data(el_id, node_order))
        i = pde_loc%permut(elements%data(el_id, node_order))
        call pde_loc%pde_fnc(1)%dispersion(pde_loc, elements%material(el_id,1), x=(/
      pde_common%xvect(i,2)/), &
                              tensor=k(1:drutes_config%dimen, 1:drutes_config%dimen))
        gravflux(1:drutes_config%dimen) = k(drutes_config%dimen, 1:drutes_config%dimen)*
      elements%nvect_z(el_id, node_order)
        if (pde_loc%bc(edge_id)%file) then
          do i=1, ubound(pde_loc%bc(edge_id)%series,1)
            if (pde_loc%bc(edge_id)%series(i,1) > time) then
              if (i > 1) then
                j = i-1
              else
                j = i
              end if
              bcval = pde_loc%bc(edge_id)%series(j,2)
              EXIT
            end if
          end do
        else
          bcval = pde_loc%bc(edge_id)%value
        end if
        
        if (bcval < 0) then
          quadpnt%type_pnt = "ndpt"
          quadpnt%order = elements%data(el_id,node_order)
          layer = elements%material(el_id,1)
          theta = pde_loc%mass(layer, quadpnt)
          bcval = bcval*(theta*theta)**(1.0_rkind/3.0_rkind)
        end if
          
          
         select case(drutes_config%dimen)
            case(1)
              value = bcval - gravflux(1)
            case(2)
              bcflux(1) = sqrt(1-elements%nvect_z(el_id, node_order)*elements%nvect_z(el_id, node_order))*
      bcval
              bcflux(2) = elements%nvect_z(el_id, node_order)*bcval
              bcflux = bcflux + gravflux
              value = sqrt(bcflux(1)*bcflux(1) + bcflux(2)*bcflux(2))
  ! print *, value, gravflux, el_id, elements%data(el_id,:) ; stop
          end select
        
        
      end if
      
      
subroutine, public re_constitutive::re_dirichlet_bc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 1712 of file re_constitutive.f90.
References globals::elements, globals::nodes, and globals::time.
Referenced by re_pointers::re_pressheadbc().
        use typy
        use globals
        use global_objs
        use pde_objs
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: el_id, node_order
        real(kind=rkind), intent(out), optional :: value
        integer(kind=ikind), intent(out), optional :: code
        integer(kind=ikind) :: edge_id, i, j
        
        edge_id = nodes%edge(elements%data(el_id, node_order))
        if (present(value)) then
          if (pde_loc%bc(edge_id)%file) then
            do i=1, ubound(pde_loc%bc(edge_id)%series,1)
              if (pde_loc%bc(edge_id)%series(i,1) > time) then
                if (i > 1) then
                  j = i-1
                else
                  j = i
                end if
                value = pde_loc%bc(edge_id)%series(j,2)
                EXIT
              end if
            end do
          else
            value = pde_loc%bc(edge_id)%value
          end if
        end if
        if (present(code)) then
          code = 1
        end if
subroutine, public re_constitutive::re_dirichlet_height_bc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 1775 of file re_constitutive.f90.
References globals::drutes_config, globals::elements, globals::nodes, and globals::time.
Referenced by re_pointers::re_pressheadbc().
        use typy
        use globals
        use global_objs
        use pde_objs
        use debug_tools
        
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: el_id, node_order
        real(kind=rkind), intent(out), optional :: value
        integer(kind=ikind), intent(out), optional :: code
        
        integer(kind=ikind) :: edge_id, i, j
        real(kind=rkind) :: tempval, node_height
        
        if (present(value)) then
          edge_id = nodes%edge(elements%data(el_id, node_order))
          node_height = nodes%data(elements%data(el_id, node_order),
      drutes_config%dimen)
          if (pde_loc%bc(edge_id)%file) then
            do i=1, ubound(pde_loc%bc(edge_id)%series,1)
              if (pde_loc%bc(edge_id)%series(i,1) > time) then
                if (i > 1) then
                  j = i-1
                else
                  j = i
                end if
                tempval = pde_loc%bc(edge_id)%series(j,2)
                EXIT
              end if
            end do
          else
            tempval = pde_loc%bc(edge_id)%value
          end if
          
          value = tempval - node_height
        end if
        
        if (present(code)) then
          code = 1
        end if
        
subroutine, public re_constitutive::re_initcond (class(pde_str), intent(inout) pde_loc)
Definition at line 1976 of file re_constitutive.f90.
References globals::drutes_config, globals::elements, inverse_vangen(), geom_tools::map1d2dj(), globals::nodes, and re_globals::vgset.
Referenced by re_pointers::re_rot(), and re_pointers::re_std().
        use typy
        use globals
        use global_objs
        use pde_objs
        use re_globals
        use geom_tools
        
        class(pde_str), intent(in out) :: pde_loc
        integer(kind=ikind) :: i, j, k,l, m, layer, d
        real(kind=rkind) :: value
        
        d = drutes_config%dimen
        select case (vgset(1_ikind)%icondtype)
          case("input")
            call map1d2dj(pde_loc,"drutes.conf/water.conf/hini.in")
        end select
        
        do i=1, elements%kolik
          layer = elements%material(i,1)
          do j=1, ubound(elements%data,2)
            k = elements%data(i,j)
            l = nodes%edge(k)
            m = pde_loc%permut(k)
            if (m == 0) then
              call pde_loc%bc(l)%value_fnc(pde_loc, i, j, value)
              pde_loc%solution(k) = value
            else
              select case (vgset(layer)%icondtype)
                case("H_tot")
                  pde_loc%solution(k) = vgset(layer)%initcond - nodes%data(k,d)
                case("hpres")
                  pde_loc%solution(k) = vgset(layer)%initcond
                case("theta")
                  value = inverse_vangen(pde_loc, layer, x=(/vgset(layer)%initcond/))
                  pde_loc%solution(k) = value
              end select
            end if
          end do
        end do
        
        
subroutine, public re_constitutive::re_neumann_bc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 1827 of file re_constitutive.f90.
References globals::drutes_config, globals::elements, globals::nodes, pde_objs::pde_common, and globals::time.
Referenced by re_pointers::re_pressheadbc().
        use typy
        use globals
        use global_objs
        use pde_objs
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: el_id, node_order
        real(kind=rkind), intent(out), optional :: value
        integer(kind=ikind), intent(out), optional :: code
        
        real(kind=rkind), dimension(3,3) :: k
        integer(kind=ikind) :: i, edge_id, j
        real(kind=rkind), dimension(3) :: gravflux, bcflux
        real(kind=rkind) :: bcval, gfluxval
        integer :: i1
      
        if (present(value)) then
          edge_id = nodes%edge(elements%data(el_id, node_order))
          i = pde_loc%permut(elements%data(el_id, node_order))
          call pde_loc%pde_fnc(1)%dispersion(pde_loc, elements%material(el_id,1), x=(/
      pde_common%xvect(i,2)/), &
                              tensor=k(1:drutes_config%dimen, 1:drutes_config%dimen))
          gravflux(1:drutes_config%dimen) = k(drutes_config%dimen, 1:
      drutes_config%dimen)*elements%nvect_z(el_id, node_order)
          
          if (pde_loc%bc(edge_id)%file) then
            do i=1, ubound(pde_loc%bc(edge_id)%series,1)
              if (pde_loc%bc(edge_id)%series(i,1) > time) then
                if (i > 1) then
                  j = i-1
                else
                  j = i
                end if
                bcval = pde_loc%bc(edge_id)%series(j,2)
                EXIT
              end if
            end do
          else
            bcval = pde_loc%bc(edge_id)%value
          end if
          
          
          select case(drutes_config%dimen)
            case(1)
              value = bcval - gravflux(1)
            case(2)
              bcflux(1) = sqrt(1-elements%nvect_z(el_id, node_order)*elements%nvect_z(el_id, node_order))*
      bcval
              bcflux(2) = elements%nvect_z(el_id, node_order)*bcval
              bcflux = bcflux + gravflux
              value = sqrt(bcflux(1)*bcflux(1) + bcflux(2)*bcflux(2))
  ! print *, value, gravflux, el_id, elements%data(el_id,:) ; stop
          end select
        end if
        
       if (present(code)) then
          code = 2
        end if
subroutine, public re_constitutive::re_null_bc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 1752 of file re_constitutive.f90.
Referenced by re_dual_pointers::re_fracture(), re_dual_pointers::re_matrix(), re_pointers::re_pressheadbc(), and re_pointers::re_totheadbc().
        use typy
        use globals
        use global_objs
        use pde_objs
        
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: el_id, node_order
        real(kind=rkind), intent(out), optional :: value
        integer(kind=ikind), intent(out), optional :: code
        if (present(value)) then
          value = 0.0_rkind
        end if
        if (present(code)) then
          code = 2
        end if
        
pure real(kind=rkind) function, private re_constitutive::secondder_retc (real(kind=rkind), intent(in) h) [private]
Parameters
in h input pressure head, van genuchten's parameters are obtained from variable van_gen_coeff
Returns
resulting curvature
Definition at line 1595 of file re_constitutive.f90.
References this_layer, and re_globals::vgset.
Referenced by init_zones().
        use typy
        use re_globals
        real(kind=rkind), intent(in) :: h
        real(kind=rkind) :: curvature
        !!!!--local variables------
        real(kind=rkind) :: a, n, m, tr, ts
        a = vgset(this_layer)%alpha
        n = vgset(this_layer)%n
        m = vgset(this_layer)%m
        tr = vgset(this_layer)%Thr
        ts = vgset(this_layer)%Ths
        if(h < 0.0_rkind) then
          curvature = -(a**2*(-(a*h))**(-2 + n)*(1 + (-(a*h))**n)**(-1 - m)*m*(-1 + n)*n* &
              (-tr + ts)) - a**2*(-(a*h))**(-2 + 2*n)*(1 + (-(a*h))**n)**(-2 - m)*(-1 - m)* &
            m*n**2*(-tr + ts)
        else
          curvature = 0.0_rkind
        end if
        
subroutine, private re_constitutive::setmatflux () [private]
Definition at line 2023 of file re_constitutive.f90.
References globals::elements, and globals::nodes.
        use typy
        use globals
        use global_objs
        use pde_objs
        use debug_tools
        
        integer(kind=ikind) :: i, j, vecino, id, k, l, nd, ndvec
        
        id = maxval(nodes%edge) + 100
        do i=1, elements%kolik
          do j=1, ubound(elements%neighbours,2)
            vecino = elements%neighbours(i,j)
            if (vecino /= 0) then
              if (elements%material(i,1) /= elements%material(vecino,1)) then
                do k=1, ubound(elements%data,2)
                  nd = elements%data(i, k)
                  do l=1, ubound(elements%data,2)
                    ndvec = elements%data(vecino, l)
                    if (nd == ndvec) then
                      nodes%edge(nd) = -id
                    end if
                  end do
                end do
              end if
            end if
          end do
        end do
        
      
real(kind=rkind) function, public re_constitutive::sinkterm (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 1045 of file re_constitutive.f90.
References re_globals::vgset.
Referenced by re_pointers::allrepointers().
      use typy
      use global_objs
      use pde_objs
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      
      val = vgset(layer)%sinkterm
     
    
    
subroutine re_constitutive::tabvalues (class(pde_str), intent(in) pde_loc, Kfnc, dKdhfnc, Cfnc, thetafnc)
creates a table of values of constitutive functions for the Richards equation to be linearly approximated
Definition at line 1249 of file re_constitutive.f90.
References dkdhtab, dkdhtab_all, domainswitch(), globals::drutes_config, ktab, ktab_all, globals::maxpress, printtools::progressbar(), re_globals::vgmatrix, re_globals::vgset, warecatab, warecatab_all, watcontab, watcontab_all, and core_tools::write_log().
Referenced by re_pointers::allrepointers().
real(kind=rkind) function, public re_constitutive::vangen (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Van Genuchten relation
 \theta = f(pressure) 
 \theta_e = \frac{1}{(1+(\alpha*h)^n)^m} 
 water content is considered as absolute value not the relative one
 see
 \theta_e = \frac{\theta - \theta_r}{\theta_s-\theta_r} 
.
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting water content
Definition at line 62 of file re_constitutive.f90.
References re_globals::vgset.
Referenced by re_pointers::allrepointers(), vangen_elast(), vangen_tab(), and zone_error_val().
      use typy
      use re_globals
      use pde_objs
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: theta
      real(kind=rkind) :: a,n,m, theta_e
      type(integpnt_str) :: quadpnt_loc
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::vangen"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::vangen"
          error stop
        end if
        h = x(1)
      end if
      
      
      
      a = vgset(layer)%alpha
      n = vgset(layer)%n
      m = vgset(layer)%m
      
      if (h >=0.0_rkind) then
          theta = vgset(layer)%Ths
          RETURN
      else
          theta_e = 1/(1+(a*(abs(h)))**n)**m
          theta = theta_e*(vgset(layer)%Ths-vgset(layer)%Thr)+vgset(layer)%Thr
      end if
real(kind=rkind) function, public re_constitutive::vangen_elast (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
so-called retention water capacity, it is a derivative to retention curve function E(h) = C(h) + {(h)}{}S_s ] where
 C(h) = \left\{ \begin{array}{l l}\frac{m n \alpha (-h \alpha )^{-1+n}}{\left(1+(-h \alpha )^n\right)^{1+m}}(\theta_s - \theta_r) , & \quad \mbox{$\forall$ $h \in (-\infty, 0 )$}\\ 0, & \quad \mbox{$\forall$ $h \in \langle 0, + \infty )$}\\ \end{array} \right. 
 and
 \theta(h) = \left\{ \begin{array}{l l} \frac{\theta_s -\theta_r}{(1+(-\alpha h)^n_{vg})^m_{vg}} + \theta_r, & \quad \mbox{$\forall$ $h \in (-\infty, 0 )$}\\ \theta_S, & \quad \mbox{$\forall$ $h \in \langle 0, + \infty )$}\\ \end{array} \right. 
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting system elasticity
Definition at line 338 of file re_constitutive.f90.
References vangen(), and re_globals::vgset.
Referenced by re_pointers::allrepointers(), vangen_elast_tab(), and zone_error_val().
      use typy
      use re_globals
      use pde_objs
      use core_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: e
      real(kind=rkind) :: c, a, m, n, tr, ts
      type(integpnt_str) :: quadpnt_loc
          
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen_elast"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::vangen_elast"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          error stop
        end if
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::vangen_elast"
          error stop
        end if
        h = x(1)
      end if
      if (h < 0) then
        a = vgset(layer)%alpha
        n = vgset(layer)%n
        m = vgset(layer)%m
        tr = vgset(layer)%Thr
        ts = vgset(layer)%Ths
        c = a*m*n*(-tr + ts)*(-(a*h))**(-1 + n)*(1 + (-(a*h))**n)**(-1 - m)
      else
        e = vgset(layer)%Ss
        RETURN
      end if
      e = c + vangen(pde_loc, layer, x=(/h/))/vgset(layer)%Ths*vgset(layer)%Ss
real(kind=rkind) function, public re_constitutive::vangen_elast_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting system elasticity
Definition at line 471 of file re_constitutive.f90.
References intoverflow(), intwarning, tabmsg, tabwarning, vangen_elast(), re_globals::vgset, warecatab, and core_tools::write_log().
Referenced by re_pointers::allrepointers().
      use typy
      use re_globals
      use pde_objs
      use core_tools
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: e
      integer(kind=ikind) :: pos
      real(kind=rkind) :: res, dist
      type(integpnt_str) :: quadpnt_loc
         
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen_elast_tab"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::vangen_elast_tab"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::vangen_elast_tab"
          error stop
        end if
        h = x(1)
      end if
      if (h<0) then
        if (h/drutes_config%fnc_discr_length < 0.1*huge(1)) then
          pos = int(-h/drutes_config%fnc_discr_length)+1
          if (pos <= ubound(warecatab,2)-1) then
            dist = -h - (pos - 1)*drutes_config%fnc_discr_length
            e = (warecatab(layer,pos+1)-warecatab(layer,pos))/drutes_config%fnc_discr_length*
      dist + warecatab(layer,pos)
          else
            if (present(quadpnt)) e = vangen_elast(pde_loc, layer, quadpnt)
            if (present(x)) e = vangen_elast(pde_loc, layer, x=x)
            if (.not. tabwarning) then
              call write_log(trim(tabmsg))
              tabwarning = .true.
            end if
          end if
        else
         
          if (.not. intwarning) then
            call intoverflow()
            intwarning = .true.
          end if
          if (present(quadpnt)) e = vangen_elast(pde_loc, layer, quadpnt_loc)
          if (present(x)) e = vangen_elast(pde_loc, layer, x=x)
        
        end if
      else
        e = vgset(layer)%Ss
      end if
real(kind=rkind) function, public re_constitutive::vangen_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting water content
Definition at line 251 of file re_constitutive.f90.
References intoverflow(), intwarning, tabmsg, tabwarning, vangen(), re_globals::vgset, watcontab, and core_tools::write_log().
Referenced by re_pointers::allrepointers().
      use typy
      use re_globals
      use pde_objs
      use core_tools
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: theta
      integer(kind=ikind) :: pos
      real(kind=rkind) :: res, dist
      type(integpnt_str) :: quadpnt_loc
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen_tab"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::vangen_tab"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::vangen_tab"
          error stop
        end if
        h = x(1)
      end if
      if (h<0) then
        if (h/drutes_config%fnc_discr_length < 0.1*huge(1)) then
          
          pos = int(-h/drutes_config%fnc_discr_length)+1
          if (pos <= ubound(watcontab,2)-1) then
            dist = -h - (pos - 1)*drutes_config%fnc_discr_length
            theta = (watcontab(layer,pos+1)-watcontab(layer,pos))/drutes_config%fnc_discr_length*
      dist + watcontab(layer,pos)
          else
            if (present(quadpnt)) theta = vangen(pde_loc, layer, quadpnt)
            if (present(x)) theta = vangen(pde_loc, layer, x=x)
            if (.not. tabwarning) then
              call write_log(trim(tabmsg))
              tabwarning = .true.
            end if
          end if
        else
        
          if (.not. intwarning) then
            call intoverflow()
            intwarning = .true.
          end if
        
          if (present(quadpnt)) theta = vangen(pde_loc, layer, quadpnt)
          if (present(x)) theta = vangen(pde_loc, layer, x=x)
          
        end if
        
      else
        theta = vgset(layer)%Ths
      end if
      
      
real(kind=rkind) function, private re_constitutive::zone_error_val (real(kind=rkind), intent(in) h, real(kind=rkind), intent(in) htest, real(kind=rkind), intent(in) taylor_max) [private]
Parameters
in h starting point
in htest point to be evaluated
in taylor_max maximal error of taylor series
Returns
error value of first order taylor approximation starting at point h and evaluating at point htest
Definition at line 1570 of file re_constitutive.f90.
References pde_objs::pde, this_layer, vangen(), and vangen_elast().
Referenced by init_zones().
        use typy
        use pde_objs
        real(kind=rkind), intent(in) :: h
        real(kind=rkind), intent(in) :: htest
        real(kind=rkind), intent(in) :: taylor_max
        real(kind=rkind) :: err_val
        err_val=abs(vangen(pde(1), this_layer, x=(/h/)) + vangen_elast(pde(1),
      this_layer, x=(/htest/))*(htest-h)- &
                vangen(pde(1), this_layer, x=(/htest/))) - taylor_max
Variable Documentation
real(kind=rkind), dimension(:,:), pointer, public re_constitutive::dkdhtab
Definition at line 21 of file re_constitutive.f90.
Referenced by dmualem_dh_tab(), domainswitch(), and tabvalues().
real(kind=rkind), dimension(:,:,:), allocatable, target, public re_constitutive::dkdhtab_all
Definition at line 22 of file re_constitutive.f90.
Referenced by domainswitch(), and tabvalues().
logical, private re_constitutive::intwarning = .false. [private]
Definition at line 32 of file re_constitutive.f90.
Referenced by dmualem_dh_tab(), mualem_tab(), vangen_elast_tab(), and vangen_tab().
  logical, private :: intwarning = .false.
real(kind=rkind), dimension(:,:), pointer, public re_constitutive::ktab
Definition at line 21 of file re_constitutive.f90.
Referenced by domainswitch(), mualem_tab(), and tabvalues().
  real(kind=rkind), dimension(:,:), pointer, public :: ktab, dkdhtab, warecatab,
      watcontab
real(kind=rkind), dimension(:,:,:), allocatable, target, public re_constitutive::ktab_all
Definition at line 22 of file re_constitutive.f90.
Referenced by domainswitch(), and tabvalues().
  real(kind=rkind), dimension(:,:,:), allocatable, target, public :: ktab_all,
      dkdhtab_all, warecatab_all, watcontab_all
character(len=4096), private re_constitutive::tabmsg = `DRUtES requested values of the constitutive functions out of the range of your precalculated table, the function will be evaluated directly, it will slow down your computation, is everything ok? If yes, increase the length of interval for precaculating the constitutive functions in your config files` [private]
Definition at line 27 of file re_constitutive.f90.
Referenced by dmualem_dh_tab(), mualem_tab(), vangen_elast_tab(), and vangen_tab().
  character(len=4096), private :: tabmsg = "DRUtES requested values of the constitutive functions out of
       the range of &
                                            your precalculated table, the function will be evaluated
       directly, it will &
                                            slow down your computation, is everything ok? If yes, increase
       the &
                                            length of interval for precaculating the constitutive functions
       in your config files"
logical, private re_constitutive::tabwarning = .false. [private]
Definition at line 26 of file re_constitutive.f90.
Referenced by dmualem_dh_tab(), mualem_tab(), vangen_elast_tab(), and vangen_tab().
  logical, private :: tabwarning = .false.
integer(kind=ikind), private re_constitutive::this_layer [private]
Definition at line 24 of file re_constitutive.f90.
Referenced by init_zones(), secondder_retc(), and zone_error_val().
  integer(kind=ikind), private :: this_layer
type(soilpar), private re_constitutive::van_gen_coeff [private]
Definition at line 23 of file re_constitutive.f90.
  type(soilpar), private :: van_gen_coeff
real(kind=rkind), dimension(:,:), pointer, public re_constitutive::warecatab
Definition at line 21 of file re_constitutive.f90.
Referenced by domainswitch(), tabvalues(), and vangen_elast_tab().
real(kind=rkind), dimension(:,:,:), allocatable, target, public re_constitutive::warecatab_all
Definition at line 22 of file re_constitutive.f90.
Referenced by domainswitch(), and tabvalues().
real(kind=rkind), dimension(:,:), pointer, public re_constitutive::watcontab
Definition at line 21 of file re_constitutive.f90.
Referenced by domainswitch(), tabvalues(), and vangen_tab().
real(kind=rkind), dimension(:,:,:), allocatable, target, public re_constitutive::watcontab_all
Definition at line 22 of file re_constitutive.f90.
Referenced by domainswitch(), and tabvalues().