readtools Module Reference
Data Types
interface fileread
Functions/Subroutines
subroutine, private read_int (i, fileid, errmsg, ranges, minimal, maximal, noexit)
subroutine, private read_int_std (i, fileid, errmsg, ranges, noexit)
subroutine, private read_int_array (r, fileid, ranges, errmsg, checklen, noexit)
subroutine, private read_real (r, fileid, ranges, errmsg, noexit)
subroutine, private read_real_array (r, fileid, ranges, errmsg, checklen, noexit)
subroutine, private read_char (ch, fileid, errmsg, options, noexit)
subroutine read_logical (l, fileid, errmsg, noexit)
subroutine, public file_error (iunit, message)
subroutine, public comment (Unit)
subroutine, public set_tensor (values, angle, tensor)
this procedure set up an anisothropy tensor, the local anisothrophy values are supllied in values array, angle is the angle between the local and global system, tensor is the resulting secodn order tensor
subroutine, public readbcvals (unitW, struct, dimen, dirname)
Function/Subroutine Documentation
subroutine, public readtools::comment (integer, intent(in) Unit)
Definition at line 526 of file readtools.f90.
Referenced by ade_reader::ade_read(), boussread::boussreader(), geom_tools::map1d2d(), geom_tools::map1d2dj(), re_dual_reader::re_dual_readf(), re_dual_reader::re_dual_readm(), re_dual_reader::re_dual_var(), read_inputs::read_1dmesh_int(), read_inputs::read_2dmesh_int(), read_inputs::read_2dmesh_t3d(), read_char(), decomposer::read_coarse_mesh(), read_int(), read_int_array(), read_int_std(), read_logical(), read_real(), read_real_array(), readbcvals(), objfnc::reader(), and re_reader::res_read().
          
      integer, intent(in) :: unit
      !character(len=1), intent(in), optional :: mark
      character(len=1) :: symbol
      character(len=1) :: string
      integer :: i_err
      
          
      !if (present(mark)) then
      ! symbol = mark
      !else
        symbol = "#"
    ! end if
        
      do
        read(unit=unit,fmt = *, iostat = i_err) string
        if (i_err < 0) then
          RETURN
        end if
        if (string == symbol) then
          CONTINUE
        else
          backspace unit
          RETURN
        endif
      end do
          
subroutine, public readtools::file_error (integer, intent(in) iunit, character(len=*), intent(in), optional message)
Definition at line 461 of file readtools.f90.
References globals::terminal.
Referenced by ade_reader::ade_read(), decomposer::init_decomp(), geom_tools::map1d2d(), geom_tools::map1d2dj(), re_dual_reader::re_dual_var(), read_inputs::read_1dmesh_int(), read_inputs::read_2dmesh_int(), read_char(), read_inputs::read_global(), read_int(), read_int_array(), read_int_std(), read_logical(), read_real(), read_real_array(), readbcvals(), objfnc::reader(), re_reader::res_read(), and simegen::simegen1d().
      use core_tools
      use globals
      integer, intent(in) :: iunit
      character(len=*), intent(in), optional :: message
      character(len=512) :: filename
      character(len=256) :: iaction, numero
      integer :: line, i, i_err, i3, i4, i5, fileid, err_read
      integer(4) :: i1, i2
      character(len=4096) :: string
      string = "last value"
      i1=-100
      i2=-100
      inquire(unit=iunit, name=filename, action=iaction)
      line = 1
      backspace(unit=iunit, iostat = i_err)
      read(unit=iunit, fmt=*, iostat = err_read) string
      
      
      do
        i1 = ftell(iunit)
        backspace(unit=iunit, iostat=i_err)
        line = line + 1
        i2 = ftell(iunit)
        if (i1 == i2) then
          EXIT
        end if
      end do
      if (line <= 2) then
        print *, "-------------------------------------------------------------------"
        print *, "WARNING: the line number was identified incorrectly, "
        print *, "likely it is a compiler error in ftell function, "
        print *, "find the input error on your own. :("
      end if
      print *, "-------------------------------------------------------------------"
      print *, " "
      print *, " " //achar(27)//'[91m', "!!ERROR!!" //achar(27)//'[0m', &
                  " in reading from file: ", trim(filename), " near line: ", line-1, &
                      " opened with status: ", trim(iaction), " -> exiting DRUtES"
      print *, " "
      
! if (i_err == 0) then
        if (err_read == 0) write(unit=terminal, fmt=*) "the value you have typed is: ", trim(string)
        write(unit=terminal, fmt=*) "--------------------------------"
! end if
      
      
      if (present(message)) then
        write(unit=terminal, fmt=*) " " //achar(27)//'[91m', trim(message) //achar(27)//'[0m'
      end if
        
      
      error stop
subroutine, private readtools::read_char (character(len=*), intent(out) ch, integer, intent(in) fileid, character(len=*), intent(in), optional errmsg, character(len=*), dimension(:), intent(in), optional options, logical, intent(in), optional noexit) [private]
Definition at line 369 of file readtools.f90.
References comment(), and file_error().
      character(len=*), intent(out) :: ch
      integer, intent(in) :: fileid
      character(len=*), intent(in), optional :: errmsg
      character(len=*), dimension(:), intent(in), optional :: options
      logical, intent(in), optional :: noexit
      integer :: ierr, i
      logical :: ok
      
      call comment(fileid)
      
      read(unit=fileid, fmt="(a)", iostat=ierr) ch
      
      if (present(options)) then
        ok = .false.
        do i=1, ubound(options, 1)
          if (adjustl(trim(ch)) == adjustl(trim(options(i)))) then
            ok = .true.
            EXIT
          end if
        end do
      else
        ok = .true.
      end if
      
      if (ierr /= 0 .or. .not.(ok) .and. (.not. present(noexit) .or. .not. noexit)) then
        if (.not. ok) then
          print *, "the value in your input file was: ", trim(ch)
          print *, "however the allowed options for this field are:"
          do i=1, ubound(options,1)
            print *, "- ", adjustl(trim(options(i)))
          end do
        end if
        if (present(errmsg)) then
          call file_error(fileid,errmsg)
        end if
        if (present(errmsg)) then
          call file_error(fileid,errmsg)
        else
          call file_error(fileid)
        end if
      end if
      
      
      
      
subroutine, private readtools::read_int (integer(kind=ikind), intent(out) i, integer, intent(in) fileid, character(len=*), intent(in), optional errmsg, integer(kind=ikind), dimension(:), intent(in), optional ranges, integer, intent(in), optional minimal, integer, intent(in), optional maximal, logical, intent(in), optional noexit) [private]
Definition at line 22 of file readtools.f90.
References comment(), file_error(), and globals::terminal.
      use typy
      use globals
      integer(kind=ikind), intent(out) :: i
      integer, intent(in) :: fileid
      character(len=*), intent(in), optional :: errmsg
      integer(kind=ikind), dimension(:), intent(in), optional :: ranges
      integer, intent(in), optional :: minimal, maximal
      logical, intent(in), optional :: noexit
      !local vars
      integer :: ierr
      call comment(fileid)
      read(unit=fileid, fmt=*, iostat=ierr) i
      if (ierr /= 0) then
        if (present(errmsg)) then
          call file_error(fileid, errmsg)
        end if
        call file_error(fileid)
      end if
      if (present(ranges)) then
        if (i<ranges(1) .or. i> ranges(2)) then
          write(unit=terminal, fmt=*) " " //achar(27)//'[91m', "incorrect ranges of input parameter(s)" //
      achar(27)//'[0m'
          if (.not. present(noexit) .or. .not. noexit) then
            if (present(errmsg)) then
              call file_error(fileid,errmsg)
            else
              call file_error(fileid)
            end if
          end if
        end if
      end if
subroutine, private readtools::read_int_array (integer(kind=ikind), dimension(:), intent(out) r, integer, intent(in) fileid, integer(kind=ikind), dimension(:), optional ranges, character(len=*), intent(in), optional errmsg, logical, intent(in), optional checklen, logical, intent(in), optional noexit) [private]
Parameters
in checklen checks if the array length is equal to the length of line in file
Definition at line 109 of file readtools.f90.
References comment(), file_error(), and globals::terminal.
      use typy
      use globals
      integer(kind=ikind), dimension(:), intent(out) :: r
      integer, intent(in) :: fileid
      integer(kind=ikind), dimension(:), optional :: ranges
      character(len=*), intent(in), optional :: errmsg
      logical, intent(in), optional :: checklen
      logical, intent(in), optional :: noexit
      
            !logical vars
      integer :: ierr, ierr2
      integer(kind=ikind) :: i, i1, i2, arraybound, current_pos, chpos
      real(kind=rkind), dimension(:), allocatable :: tmpdata
      
      call comment(fileid)
      
      arraybound=1
      
      allocate(tmpdata(arraybound))
      
      if (present(checklen)) then
        if (checklen) then
          current_pos = ftell(fileid)
          do
            call comment(fileid)
            read(unit=fileid, fmt=*, iostat=ierr) tmpdata(1:arraybound-1)
            i1=ftell(fileid)
            backspace fileid
            call comment(fileid)
            read(unit=fileid, fmt=*, iostat=ierr) tmpdata(1:arraybound)
            i2 = ftell(fileid)
            backspace fileid
           
            if (ierr /= 0) then
              arraybound = arraybound - 1
              do
                chpos = ftell(fileid)
                if (chpos == current_pos) then
                  EXIT
                else
                  backspace(unit=fileid, iostat=ierr2)
                end if
              end do
              deallocate(tmpdata)
              EXIT
            end if
            
            if (i1 == i2) then
              arraybound = arraybound + 1
              if (ubound(tmpdata,1) < arraybound) then
                deallocate(tmpdata)
                allocate(tmpdata(2*arraybound))
              end if
            else
              arraybound = arraybound - 1
              do
                chpos = ftell(fileid)
                if (chpos == current_pos) then
                  EXIT
                else
                  backspace(unit=fileid, iostat=ierr2)
                end if
              end do
              deallocate(tmpdata)
              EXIT
            end if
          end do
  
          if (arraybound /= ubound(r,1)) then
            write(unit=terminal, fmt=*) " " //achar(27)//'[91m', "the line in your input file has &
               incorrect number of values, check your inputs" //achar(27)//'[0m'
            call file_error(fileid, errmsg)
         end if
        end if
      end if
      
      call comment(fileid)
      read(unit=fileid, fmt=*, iostat=ierr) r
    
      
      
      if (ierr /= 0) then
        if (present(errmsg)) then
          call file_error(fileid,errmsg)
        end if
        if (.not. present(noexit) .or. .not. noexit) then
          if (present(errmsg)) then
            call file_error(fileid,errmsg)
          else
            call file_error(fileid)
          end if
        end if
      end if
      
      if (present(ranges)) then
        do i=1, ubound(r,1)
          if (r(i) < ranges(1) .or. r(i) > ranges(2)) then
            write(unit=terminal, fmt=*) " " //achar(27)//'[91m', "incorrect ranges of input parameter(s)" /
      /achar(27)//'[0m'
            call file_error(fileid, errmsg)
          end if
        end do
      end if
      
      
subroutine, private readtools::read_int_std (integer(kind=lowikind), intent(out) i, integer, intent(in) fileid, character(len=*), intent(in), optional errmsg, integer(kind=ikind), dimension(:), intent(in), optional ranges, logical, intent(in), optional noexit) [private]
Definition at line 62 of file readtools.f90.
References comment(), file_error(), and globals::terminal.
      use typy
      use globals
      integer(kind=lowikind), intent(out) :: i
      integer, intent(in) :: fileid
      character(len=*), intent(in), optional :: errmsg
      integer(kind=ikind), dimension(:), intent(in), optional :: ranges
      logical, intent(in), optional :: noexit
      !local vars
      integer :: ierr
      call comment(fileid)
      read(unit=fileid, fmt=*, iostat=ierr) i
      if (ierr /= 0) then
        if (present(errmsg)) then
          call file_error(fileid,errmsg)
        end if
        if (.not. present(noexit) .or. .not. noexit) then
          if (present(errmsg)) then
            call file_error(fileid,errmsg)
          else
            call file_error(fileid)
          end if
        end if
      end if
      
      
       if (present(ranges)) then
        if (i<ranges(1) .or. i> ranges(2)) then
          write(unit=terminal, fmt=*) " " //achar(27)//'[91m', "incorrect ranges of input parameter(s)" //
      achar(27)//'[0m'
          if (.not. present(noexit) .or. .not. noexit) then
            if (present(errmsg)) then
              call file_error(fileid,errmsg)
            else
              call file_error(fileid)
            end if
          end if
        end if
      end if
subroutine readtools::read_logical (logical, intent(out) l, integer, intent(in) fileid, character(len=*), intent(in), optional errmsg, logical, intent(in), optional noexit)
Definition at line 418 of file readtools.f90.
References comment(), file_error(), and globals::terminal.
      use globals
      logical, intent(out) :: l
      integer, intent(in) :: fileid
      character(len=*), intent(in), optional :: errmsg
      logical, intent(in), optional :: noexit
      integer :: ierr
      character(len=1) :: ch
      
      call comment(fileid)
      
      read(unit=fileid, fmt=*, iostat=ierr) ch
      if (ierr == 0) then
        select case(ch)
          case("y")
            l = .true.
          case("n")
            l = .false.
          case default
            ierr = -1
            write(unit=terminal, fmt=*) " " //achar(27)//'[91m', "You have defined incorrect value for
       logical parameter)" &
             //achar(27)//'[0m'
         end select
       end if
      
      if (ierr /= 0 .and. (.not. present(noexit) .or. .not. noexit)) then
        if (present(errmsg)) then
          call file_error(fileid,errmsg)
        end if
        if (present(errmsg)) then
          call file_error(fileid,errmsg)
        else
          call file_error(fileid)
        end if
      end if
      
      
subroutine, private readtools::read_real (real(kind=rkind), intent(out) r, integer, intent(in) fileid, real(kind=rkind), dimension(:), optional ranges, character(len=*), intent(in), optional errmsg, logical, intent(in), optional noexit) [private]
Definition at line 219 of file readtools.f90.
References comment(), file_error(), and globals::terminal.
      use typy
      use globals
      real(kind=rkind), intent(out) :: r
      integer, intent(in) :: fileid
      real(kind=rkind), dimension(:), optional :: ranges
      character(len=*), intent(in), optional :: errmsg
      logical, intent(in), optional :: noexit
      
      !logical vars
      integer :: ierr
      
      call comment(fileid)
      
      read(unit=fileid, fmt=*, iostat=ierr) r
      
      if (present(ranges)) then
        if (r < ranges(1) .or. r > ranges(2)) then
          write(unit=terminal, fmt=*) " " //achar(27)//'[91m', "incorrect ranges of input parameter(s)" //
      achar(27)//'[0m'
          ierr = -1
        end if
      end if
      
      if (ierr /= 0) then
        if (present(errmsg)) then
          call file_error(fileid,errmsg)
        end if
        if (.not. present(noexit) .or. .not. noexit) then
          if (present(errmsg)) then
            call file_error(fileid,errmsg)
          else
            call file_error(fileid)
          end if
        end if
      end if
subroutine, private readtools::read_real_array (real(kind=rkind), dimension(:), intent(out) r, integer, intent(in) fileid, real(kind=rkind), dimension(:), optional ranges, character(len=*), intent(in), optional errmsg, logical, intent(in), optional checklen, logical, intent(in), optional noexit) [private]
Parameters
in checklen checks if the array length is equal to the length of line in file
Definition at line 259 of file readtools.f90.
References comment(), file_error(), and globals::terminal.
      use typy
      use globals
      real(kind=rkind), dimension(:), intent(out) :: r
      integer, intent(in) :: fileid
      real(kind=rkind), dimension(:), optional :: ranges
      character(len=*), intent(in), optional :: errmsg
      logical, intent(in), optional :: checklen
      logical, intent(in), optional :: noexit
      
            !logical vars
      integer :: ierr, ierr2
      integer(kind=ikind) :: i, i1, i2, arraybound, current_pos, chpos
      real(kind=rkind), dimension(:), allocatable :: tmpdata
      
      call comment(fileid)
      
      arraybound=1
      
      allocate(tmpdata(arraybound))
      
      if (present(checklen)) then
        if (checklen) then
          current_pos = ftell(fileid)
          do
            call comment(fileid)
            read(unit=fileid, fmt=*, iostat=ierr) tmpdata(1:arraybound-1)
            i1=ftell(fileid)
            backspace fileid
            call comment(fileid)
            read(unit=fileid, fmt=*, iostat=ierr) tmpdata(1:arraybound)
            i2 = ftell(fileid)
            backspace fileid
           
            if (ierr /= 0) then
              arraybound = arraybound - 1
              do
                chpos = ftell(fileid)
                if (chpos == current_pos) then
                  EXIT
                else
                  backspace(unit=fileid, iostat=ierr2)
                end if
              end do
              deallocate(tmpdata)
              EXIT
            end if
            
            if (i1 == i2) then
              arraybound = arraybound + 1
              if (ubound(tmpdata,1) < arraybound) then
                deallocate(tmpdata)
                allocate(tmpdata(2*arraybound))
              end if
            else
              arraybound = arraybound - 1
              do
                chpos = ftell(fileid)
                if (chpos == current_pos) then
                  EXIT
                else
                  backspace(unit=fileid, iostat=ierr2)
                end if
              end do
              deallocate(tmpdata)
              EXIT
            end if
          end do
  
          if (arraybound /= ubound(r,1)) then
            write(unit=terminal, fmt=*) " " //achar(27)//'[91m', "the line in your input file has &
               incorrect number of values, check your inputs" //achar(27)//'[0m'
            call file_error(fileid, errmsg)
         end if
        end if
      end if
      
      call comment(fileid)
      read(unit=fileid, fmt=*, iostat=ierr) r
    
      
      
      if (ierr /= 0) then
        if (present(errmsg)) then
          call file_error(fileid,errmsg)
        end if
        if (.not. present(noexit) .or. .not. noexit) then
          if (present(errmsg)) then
            call file_error(fileid,errmsg)
          else
            call file_error(fileid)
          end if
        end if
      end if
      
      if (present(ranges)) then
        do i=1, ubound(r,1)
          if (r(i) < ranges(1) .or. r(i) > ranges(2)) then
            write(unit=terminal, fmt=*) " " //achar(27)//'[91m', "incorrect ranges of input parameter(s)" /
      /achar(27)//'[0m'
            call file_error(fileid, errmsg)
          end if
        end do
      end if
      
      
subroutine, public readtools::readbcvals (integer, intent(in) unitW, type(boundary_vals), dimension(:), intent(out), allocatable struct, integer(kind=ikind), intent(in) dimen, character(len=*), intent(in) dirname)
Parameters
in dirname directory name, where data with boundary condition are stored
Definition at line 603 of file readtools.f90.
References comment(), globals::end_time, file_error(), core_tools::find_unit(), globals::measured_pts, and globals::nodes.
Referenced by ade_reader::ade_read(), boussread::boussreader(), heat_reader::heat_read(), re_dual_reader::re_dual_readf(), re_dual_reader::re_dual_readm(), and re_reader::res_read().
      use typy
      use globals
      use global_objs
      use pde_objs
      use core_tools
      use debug_tools
      integer, intent(in) :: unitw
      type(boundary_vals), dimension(:), allocatable, intent(out) :: struct
      integer(kind=ikind), intent(in) :: dimen
      character(len=*), intent(in) :: dirname
      integer(kind=ikind) :: i, j, n
      character(len=3) :: ch
      character(len=1) :: y_file, y_cond
      integer :: ierr, fileid
      integer(kind=ikind) :: counter, counter2
      character(len=256) :: filename
      real(kind=rkind) :: tmp
      character(len=1024) :: msg
      real(kind=rkind), dimension(:), allocatable :: tester
      
      
      if (.not. allocated(struct)) then
        allocate(struct(101:101+dimen-1))
      else
        print *, "W: strange bc struct already allocated with bounds:", lbound(struct,1), ":", ubound(
      struct,1)
      end if
      
      if (maxval(nodes%edge) /= ubound(struct,1)) then
        inquire(unit=unitw, name=filename)
        if (maxval(nodes%edge)-100 - dimen == ubound(measured_pts,1)) then
          write(unit=msg, fmt="(a)") "There is an inconsistent boundary description, it seems like you have
       forgot &
               to include the points with measurement into boundary definition"
        else if (maxval(nodes%edge) < 100) then
          write(unit=msg, fmt=*) "Your mesh does not define any boundaries, you are completely wrong!!"
        else !a,I3,a,I3,a,I3,a,I3,a,I3,a
          write(unit=msg, fmt="(a,I3,a,I3,a,I3,a,a,a,I3,a)") "There is an inconsistent boundary
       description, &
                                                                  the mesh configuration defines "&
          , maxval(nodes%edge)-100 - ubound(measured_pts,1) , " boundary(ies), your measurement points
       define an extra", &
          ubound(measured_pts,1), " boundary(ies), thus in total you need:", &
          maxval(nodes%edge)-100, " boundary(ies), however the input model file: ", &
          trim(filename), " defines ", dimen, " boundary(ies)."
        end if
        call file_error(unitw, trim(msg))
      end if
      do i = lbound(struct,1), ubound(struct,1)
        call comment(unitw)
        read(unit=unitw, fmt=*, iostat=ierr) struct(i)%ID, struct(i)%code, y_file, struct(i)%value, struct(
      i)%layer
        select case(y_file)
          case("y")
            struct(i)%file = .true.
          case("n")
            struct(i)%file = .false.
          case default
            call file_error(unitw, &
            "set [y/n] value for file in boundary condition description, see file info bellow")
        end select
        struct(i)%icond4neumann = .false.
        if (ierr /= 0) then
          inquire(unit=unitw, name=filename)
          write(unit=msg, fmt=*) "HINT: check number of boundary records in file: ", trim(filename)
          call file_error(unitw, trim(msg))
        end if
        if (struct(i)%file) then
          call find_unit(fileid)
          write(unit=filename, fmt="(a, I3, a)") trim(dirname), i, ".bc"
          open(unit=fileid, file=trim(filename), action="read", status="old", iostat=ierr)
          if (ierr /= 0) then
            write(unit=msg, fmt=*) "ERROR: if using unsteady boundary value data, you must supply the file
       with data!", &
            "ERROR: file required:", trim(filename)
            call file_error(unitw, msg)
          end if
          counter = 0
          do
            counter = counter + 1
            call comment(fileid)
            read(unit=fileid, fmt=*, iostat=ierr) tmp
            if (ierr /= 0) then
              EXIT
            end if
          end do
          
          close(fileid)
          counter = counter - 1
 
          open(unit=fileid, file=trim(filename), action="read", status="old", iostat=ierr)
          allocate(struct(i)%series(counter,2))
          do j=1, counter
            write(msg, *) "Incorrect data in file: ", trim(filename), " at line:", j
            call fileread(struct(i)%series(j,:), fileid, checklen=.true., errmsg=msg)
          end do
          struct(i)%series_pos = 1
       
          if (struct(i)%series(counter,1) < end_time) then
            call file_error(fileid, &
            "ERROR: end time in unsteady boundary data must be equal or higher than the simulation end
       time")
          end if
          close(fileid)
        end if
      end do
      
subroutine, public readtools::set_tensor (real(kind=rkind), dimension(:), intent(in) values, real(kind=rkind), dimension(:), intent(in) angle, real(kind=rkind), dimension(:,:), intent(out) tensor)
this procedure set up an anisothropy tensor, the local anisothrophy values are supllied in values array, angle is the angle between the local and global system, tensor is the resulting secodn order tensor
Parameters
in values local anisothoropy values with respect to local x, local y and local z
in angle angle between the local and global system of coordinates
out tensor resulting second order tensor with respect to the global system of coordinates
Definition at line 558 of file readtools.f90.
References globals::drutes_config.
Referenced by ade_reader::ade_read(), heat_reader::heat_read(), re_dual_reader::re_dual_var(), and re_reader::res_read().
      use typy
      use globals
      use global_objs
      real(kind=rkind), dimension(:), intent(in) :: values
      real(kind=rkind), dimension(:), intent(in) :: angle
      real(kind=rkind), dimension(:,:), intent(out) :: tensor
      real(kind=rkind), dimension(:,:), allocatable :: t
      integer(kind=ikind) :: i,j
      allocate(t(drutes_config%dimen, drutes_config%dimen))
      select case(drutes_config%dimen)
        case(1)
          tensor(1,1) = values(1)
          RETURN
        case(2)
          t(1,1) = cos(4.0_dprec*atan(1.0_dprec)/180.0_rkind*angle(1))
          t(1,2) = cos(4.0_dprec*atan(1.0_dprec)/180.0_rkind*(90-angle(1)))
          t(2,1) = cos(4.0_dprec*atan(1.0_dprec)/180.0_rkind*(90+angle(1)))
          t(2,2) = cos(4.0_dprec*atan(1.0_dprec)/180.0_rkind*(angle(1)))
        case(3)
          print *, "tensors not implemented in 3D"
          error stop
      end select
      tensor = 0
      do i=1, ubound(tensor,1)
        tensor(i,i) = values(i)
      end do
      tensor = matmul(matmul(t, tensor), transpose(t))
      deallocate(t)