integral Module Reference
Data Types
type formulka
Functions/Subroutines
subroutine, public init_integration_formulas (n, ierr)
pure subroutine, public getform (n, a, h, ierr)
real(kind=rkind) function, public integ1 (a, b, f, n)
pure real(kind=rkind) function, private integ2 (a, b, f, n)
pure recursive subroutine, public integs (a, b, f, n, rel_chyba, i_err, counter, hloubka, ilvl, cislo)
real(kind=rkind) function, public integ (a, b, f, n, rel_chyba, counter, hloubka, ilvl)
pure subroutine, private setup (n, a, h, ierr)
pure real(kind=rkind) function, private dohledej (xl, xp, p)
real(kind=rkind) function, private horner (p, x)
simple horner's scheme (zero derivatives only)
Variables
type(formulka), dimension(:), pointer, private group => null()
integer, private prep_forms = 0
Function/Subroutine Documentation
pure real(kind=rkind) function, private integral::dohledej (real(kind=rkind), intent(in) xl, real(kind=rkind), intent(in) xp, real(kind=rkind), dimension(:), intent(in) p) [private]
Definition at line 570 of file integral.f90.
References horner().
Referenced by setup().
      use typy
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!111111111111111111111111111
      !parametry
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!111111111111111111111111111
      real(kind=rkind), intent(in) :: xl,xp
      real(kind=rkind),dimension(:), intent(in) :: p
      real(kind=rkind) :: x
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! xl ... levy krajni bod intervalu s korenem
      ! xp ... pravy krajni bod intervalu s korenem
      ! p ... polynom
      !
      ! x ... navratova hodnota - nalezeny koren
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      real(kind=rkind) :: x1,x2,x3,y1,y2,y3,y4,y5
      x1 = xl
      x2 = xp
      y1 = horner(p,x1)
      y2 = horner(p,x2)
      y4 = x2-x1
      do
        x = (x2+x1)/2
        y3 = horner(p,x)
        if (y3*y1< 0) then
          x2 = x
          y2 = y3
        else
          x1 = x
          y1 = y3
        end if
        y5 = y4
        y4 = x2-x1
        if (y5==y4) then
          exit
        end if
      end do
pure subroutine, public integral::getform (integer(kind=ikind), intent(in) n, real(kind=rkind), dimension(:), intent(out) a, real(kind=rkind), dimension(:), intent(out) h, integer(kind=ikind), intent(out), optional ierr)
Definition at line 70 of file integral.f90.
References group, prep_forms, and setup().
Referenced by feminittools::init_integ(), integ1(), integ2(), and integs().
      use typy
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! parametery
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      real(kind=rkind), dimension(:), intent(out) :: a,h
      integer(kind=ikind), intent(in) :: n
      integer(kind=ikind), intent(out), optional :: ierr
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! n ... pocet bodu kvadr. vzorce - vstupni parametr
      ! a ... uzly kvadraturniho vzorce
      ! h ... vahy kvdraturniho vzorce
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! lokalni promenne
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      integer(kind=ikind) :: ierr1
      real(kind=rkind), dimension(:), pointer :: a1,h1
      
      if ((n>=1) .and. (n<=prep_forms)) then
        a = group(n)%a
        h = group(n)%h
        ierr1 = 0
      else
        call setup(n,a1,h1,ierr1)
        a = a1
        h = h1
        deallocate(a1,h1)
      end if
      if (present(ierr)) then
        ierr = ierr1
      end if
real(kind=rkind) function, private integral::horner (real(kind=rkind), dimension(:), intent(in) p, real(kind=rkind), intent(in) x) [private]
simple horner's scheme (zero derivatives only)
Definition at line 613 of file integral.f90.
Referenced by dohledej(), and setup().
      use typy
      integer(kind=ikind) :: i
      real(kind=rkind), intent(in) :: x
      real(kind=rkind) :: px
      real(kind=rkind), intent(in), dimension(:) :: p
      px=0
      do i=ubound(p,1), 1, -1
        px=px*x+p(i)
      end do
subroutine, public integral::init_integration_formulas (integer(kind=ikind), intent(in) n, integer(kind=ikind), intent(out), optional ierr)
Definition at line 34 of file integral.f90.
References group, prep_forms, and setup().
      use typy
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! parametry
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      integer(kind=ikind), intent(in) :: n
      integer(kind=ikind), intent(out), optional :: ierr
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! n ... naximalni rad generovane formule
      ! ierr .. chybove hlaseni
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      
      
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! lokalni promenne
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      integer(kind=ikind) :: i, ierr1
      real(kind=rkind), dimension(:), pointer :: wrk
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! vypocet
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      allocate(group(1:n))
      do i=1,n
        call setup(i,group(i)%a, group(i)%h, ierr1)
        if (ierr1 > 0)then
          exit
        end if
      end do
      prep_forms = n
      if (present(ierr)) then
        ierr = ierr1
      end if
real(kind=rkind) function, public integral::integ (real(kind=rkind), intent(in) a, real(kind=rkind), intent(in) b, f, integer(kind=ikind), intent(in), optional n, real(kind=rkind), intent(in), optional rel_chyba, integer(kind=ikind), intent(in), optional counter, integer(kind=ikind), intent(in), optional hloubka, integer(kind=ikind), intent(in), optional ilvl)
Definition at line 354 of file integral.f90.
References integs().
real(kind=rkind) function, public integral::integ1 (real(kind=rkind), intent(in) a, real(kind=rkind), intent(in) b, f, integer(kind=ikind), intent(in) n)
Definition at line 107 of file integral.f90.
References getform().
pure real(kind=rkind) function, private integral::integ2 (real(kind=rkind), intent(in) a, real(kind=rkind), intent(in) b, f, integer(kind=ikind), intent(in) n) [private]
Definition at line 160 of file integral.f90.
References getform().
Referenced by integs().
pure recursive subroutine, public integral::integs (real(kind=rkind), intent(in) a, real(kind=rkind), intent(in) b, f, integer(kind=ikind), intent(in), optional n, real(kind=rkind), intent(in), optional rel_chyba, integer(kind=ikind), intent(out), optional i_err, integer(kind=ikind), intent(in), optional counter, integer(kind=ikind), intent(in), optional hloubka, integer(kind=ikind), intent(in), optional ilvl, real(kind=rkind), intent(out) cislo)
Definition at line 208 of file integral.f90.
References getform(), and integ2().
Referenced by integ().
pure subroutine, private integral::setup (integer(kind=ikind), intent(in) n, real(kind=rkind), dimension(:), pointer a, real(kind=rkind), dimension(:), pointer h, integer(kind=ikind), intent(out), optional ierr) [private]
Definition at line 411 of file integral.f90.
References dohledej(), linalg::gem(), and horner().
Referenced by getform(), and init_integration_formulas().
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ! slouzi k vytvorenu uzlu a koeficientu pro
    ! Gaussovu kvadraturu
      use typy
      use linalg
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! parrametry
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      real(kind=rkind), dimension(:), pointer :: a,h
      integer(kind=ikind), intent(in) :: n
      integer(kind=ikind), intent(out), optional :: ierr
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! n ... pocet bodu kvadr. vzorce
      ! a ... uzly kvadraturniho
      ! h ... vahy kbadraturniho vzorce
      ! ierr ... chybova zprava - nepovinna
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ! lokalni promenne
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      real(kind=rkind), allocatable, dimension(:) :: p, b
      ! p ... n-ty ortogonalni polynom,
      ! b ... prava strany soustavy, kterou budeme vyrabet
      real(kind=rkind) :: x,y, x0, y0, x1, y1, step
      integer(kind=ikind) :: i,k, ik,ik1, m, nn
      !indexy, m=n/2
      real(kind=rkind), allocatable, dimension(:,:) :: matice
      ! matice ... matice soustavy, pro polynom a vahy
      logical :: sud
      ! sud ... sudost/lichost n
      real(kind=rkind), allocatable, dimension(:,:) :: intervaly
      integer(kind=ikind) :: pocet, ierr1
      ierr1 = 0
      ! najdu n-ty ortogonalni polynom
      ! tvorim jen nenulove koeficienty
      if (modulo(n,2_ikind)==0) then ! je to sude
        sud=.true.
        m=n/2+1
        allocate(matice(n/2,n/2), b(n/2), p(n/2+1))
        !print *, "jsme v sude casti"
        do k=1,n/2
          do i=1,n/2
            matice(k,i)=2.0_rkind/(2*(i+k)-3)
          end do
          b(k)=-2.0_rkind/(n+2*k-1)
        end do
        call gem(matice,b,p(1:n/2))
        p(n/2+1)=1.0_rkind
        deallocate(matice,b)
      else
        sud=.false.
        m=n/2+1
        if (n>1_ikind) then
          allocate(matice(n/2,n/2), b(n/2), p(n/2+1))
          ! n/2 se rizne o pulku dolu
          do k=1,n/2
            do i=1,n/2
              matice(k,i)=2.0_rkind/(2*(i+k)-1)
            end do
            b(k)=-2.0_rkind/(n+2*k)
          end do
          call gem(matice,b,p(1:n/2))
          p(n/2+1)=1.0_rkind
          deallocate(matice,b)
            else !tim vyresime problem je-li p stupne jedna
          allocate(p(1))
          p(1)=1.0_rkind
        end if
      end if
      ! mam ortogonalni polynom
      !jdu hledat koereny
      if (sud) then
        allocate(a(m-1))
      else
        allocate(a(m))
        a(m)=0 ! v lichem pripade je 0 vzdy korenem
      end if
      !je naolokovano jdeme na koreny, najdu jejich ctverce
      select case(m)
        case(1)
          continue !je to nula a to uz je dano vyse
        case(2)
          a(1) = -p(1) !ve skutecnosti to je -p(1)/p(2)
        case(3)
          a(1) = (-p(2)+sqrt(p(2)*p(2)-4*p(1)*p(3)))/(2*p(3))
          a(2) = p(1)/p(3)/a(1)
        case default
          allocate(intervaly(2,m-1))
          nn=10*m
          do
            step = 1.0_rkind/nn
            pocet = 0
            x0 = step
            y0 = horner(p,x0)
            do i=1, nn
              x1 = x0
              y1 = y0
              x0 = x0+step
              y0 = horner(p,x0)
              if (y0*y1 <= 0) then
                pocet = pocet + 1
                intervaly(:,(m-pocet))= (/ x1, x0 /)
              end if
            end do
            if (pocet == m-1) then
              exit
            else
              nn=5*nn
            end if
          end do
          do i=1,m-1
            a(i)=dohledej(intervaly(1,i),intervaly(2,i),p)
          end do
      end select
      ! ted to odmocnime
      a = sqrt(a)
      ! a ted spocitam vahy
      if (modulo(n,2_ikind)==0) then !suda vetev
        allocate(matice(n/2,n/2))
        allocate(b(n/2))
        allocate(h(n/2))
        matice(1,:) = 1.0_rkind
        b = a*a
        do i=2, n/2
          matice(i,:) = matice(i-1,:)*b
        end do
        do i=1, n/2
          b(i) = 1.0_rkind/(2*i-1)
        end do
        call gem(matice,b,h)
      else !licha vetev
        allocate(matice(n/2+1, n/2+1))
        allocate(b(n/2+1))
        allocate(h(n/2+1))
        matice(1,:) = 2.0_rkind
        matice(1,ubound(matice,2)) = 1.0_rkind
        b = a*a
        do i=2, ubound(matice,1)
          matice(i,:) = matice(i-1,:)*b
        end do
        do i=1, ubound(b,1)
          b(i) = 2.0_rkind/(2*i-1)
        end do
        call gem(matice,b,h)
      end if
      if (present(ierr)) then
        ierr = ierr1
      end if
Variable Documentation
type(formulka), dimension(:), pointer, private integral::group => null() [private]
Definition at line 12 of file integral.f90.
Referenced by getform(), and init_integration_formulas().
  type(formulka), dimension(:), pointer, private :: group => null()
integer, private integral::prep_forms = 0 [private]
Definition at line 29 of file integral.f90.
Referenced by getform(), and init_integration_formulas().
  integer, private :: prep_forms = 0