decomp_vars Module Reference
Data Types
type cluster
type ddinfo_str
type disjoint_nd_str
array map with a disjoint map of subdomains,
type resvct_str
type subdomain_str
Functions/Subroutines
real(kind=rkind) function, private returnval (subdom, i, subtime)
Variables
type(cluster), dimension(:), allocatable ddcoarse_mesh
type(node), public coarse_nodes
type(element), public coarse_elements
type(subdomain_str), dimension(:), allocatable subdomain
type(ddinfo_str), public ddinfo
type(extsmtx), public prolong_mtx
type(extsmtx), public coarse_mtx
type(extsmtx), public coarse2
type(extsmtx), public prolongt
type(extsmtx), public tmpmat
real(kind=rkind), dimension(:), allocatable, public bcoarse
real(kind=rkind), dimension(:), allocatable, public xcoarse
real(kind=rkind), public inner_criterion
inner Ax=b criterion
logical, public use_coarselev
integer, public file_decomp
integer, public file_ddinfo
integer, public file_dt
Function/Subroutine Documentation
real(kind=rkind) function, private decomp_vars::returnval (class(subdomain_str), intent(in) subdom, integer(kind=ikind), intent(in) i, real(kind=rkind), intent(in) subtime) [private]
Parameters
in i local index
Definition at line 172 of file decomp_vars.f90.
        use typy
        use globals
        
        class(subdomain_str), intent(in) :: subdom
        integer(kind=ikind), intent(in) :: i
        real(kind=rkind), intent(in) :: subtime
        real(kind=rkind) :: value
        
        if (abs(subtime-subdom%time) < epsilon(subtime)) then
          value = subdom%xvect(i,2)
        else
          value = (subdom%xvect(i,2) - subdom%xvect(i,1))/subdom%time_step*(subtime-subdom%time)+subdom
      %xvect(i,2)
        end if
        
Variable Documentation
real(kind=rkind), dimension(:), allocatable, public decomp_vars::bcoarse
Definition at line 156 of file decomp_vars.f90.
Referenced by decomp_tools::build_coarsemtx(), and schwarz_dd::schwarz_picard().
  real(kind=rkind), dimension(:), allocatable, public :: bcoarse
type(extsmtx), public decomp_vars::coarse2
Definition at line 152 of file decomp_vars.f90.
  type(extsmtx), public :: coarse2
type(element), public decomp_vars::coarse_elements
Definition at line 145 of file decomp_vars.f90.
Referenced by decomp_tools::addlevel(), decomp_tools::init_addlevel(), decomposer::init_decomp(), decomposer::make_quadmesh(), decomp_tools::print_domains(), decomp_tools::print_elements_dd(), decomposer::read_coarse_mesh(), schwarz_dd_time_test::schwarz_picard_tt(), and decomposer::set_subdomains().
  type(element), public :: coarse_elements
type(extsmtx), public decomp_vars::coarse_mtx
Definition at line 150 of file decomp_vars.f90.
Referenced by decomp_tools::build_coarsemtx(), and schwarz_dd::schwarz_picard().
  type(extsmtx), public :: coarse_mtx
type(node), public decomp_vars::coarse_nodes
Definition at line 144 of file decomp_vars.f90.
Referenced by decomposer::init_decomp(), decomposer::make_quadmesh(), decomp_tools::print_domains(), and decomposer::read_coarse_mesh().
  type(node), public :: coarse_nodes
type(cluster), dimension(:), allocatable decomp_vars::ddcoarse_mesh [private]
Definition at line 142 of file decomp_vars.f90.
Referenced by decomp_tools::add_el(), decomp_tools::addlevel(), decomp_tools::init_addlevel(), decomposer::init_decomp(), decomposer::make_quadmesh(), decomp_tools::print_domains(), decomp_tools::print_elements_dd(), decomposer::read_coarse_mesh(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarz_picard_tt(), schwarz_dd2subcyc::schwarz_subcyc(), subcycling::search_error_cluster(), schwarz_dd::search_error_cluster(), schwarz_dd2subcyc::search_error_cluster(), schwarz_dd_time_test::search_error_cluster_tt(), decomposer::set_subdomains(), and subcycling::subcyc_schwarz().
  type(cluster), dimension(:), allocatable :: ddcoarse_mesh
type(ddinfo_str), public decomp_vars::ddinfo
Definition at line 147 of file decomp_vars.f90.
Referenced by decomp_tools::addlevel(), schwarz_dd2subcyc::combinevals(), decomp_tools::init_addlevel(), decomposer::init_decomp(), schwarz_dd2subcyc::locmat_assembler(), decomp_tools::print_domains(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarzloc(), decomposer::set_subdomains(), and schwarz_dd2subcyc::solve_subdomain().
  type(ddinfo_str), public :: ddinfo
integer, public decomp_vars::file_ddinfo
Definition at line 166 of file decomp_vars.f90.
Referenced by decomposer::init_decomp(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarzloc(), and subcycling::subcyc_schwarz().
  integer, public :: file_ddinfo, file_dt
integer, public decomp_vars::file_decomp
Definition at line 165 of file decomp_vars.f90.
Referenced by decomposer::init_decomp(), and decomposer::set_subdomains().
  integer, public :: file_decomp
integer, public decomp_vars::file_dt
Definition at line 166 of file decomp_vars.f90.
Referenced by schwarz_dd_time_test::schwarz_picard_tt(), and fem::solve_pde().
real(kind=rkind), public decomp_vars::inner_criterion
inner Ax=b criterion
Definition at line 160 of file decomp_vars.f90.
Referenced by schwarz_dd::schwarz_picard(), schwarz_dd2subcyc::schwarz_subcyc(), schwarz_dd_time_test::schwarzloc(), and subcycling::subcyc_schwarz().
  real(kind=rkind), public :: inner_criterion
type(extsmtx), public decomp_vars::prolong_mtx
Definition at line 149 of file decomp_vars.f90.
Referenced by decomp_tools::addlevel(), decomp_tools::build_coarsemtx(), subcycling::build_xvect(), schwarz_dd::build_xvect(), schwarz_dd_time_test::build_xvect(), schwarz_dd2subcyc::build_xvect_loc(), schwarz_dd2subcyc::combinevals(), schwarz_dd::schwarz_picard(), and subcycling::update_domain().
  type(extsmtx), public :: prolong_mtx
type(extsmtx), public decomp_vars::prolongt
Definition at line 153 of file decomp_vars.f90.
  type(extsmtx), public :: prolongt
type(subdomain_str), dimension(:), allocatable decomp_vars::subdomain
Definition at line 146 of file decomp_vars.f90.
Referenced by decomp_tools::addlevel(), decomp_tools::build_coarsemtx(), subcycling::build_xvect(), schwarz_dd::build_xvect(), schwarz_dd_time_test::build_xvect(), schwarz_dd2subcyc::build_xvect_loc(), decomp_tools::collect_matrices(), schwarz_dd2subcyc::combinevals(), subcycling::domains_solved(), schwarz_dd::domains_solved(), schwarz_dd2subcyc::domains_solved(), schwarz_dd_time_test::domains_solved(), decomp_tools::get_residual(), decomp_tools::get_residual_old(), pde_objs::getvalp1(), pde_objs::getvalp1loc(), schwarz_dd2subcyc::locmat_assembler(), decomp_tools::mulax_dd(), subcycling::ndofs_solved(), schwarz_dd::ndofs_solved(), schwarz_dd2subcyc::ndofs_solved(), schwarz_dd_time_test::ndofs_solved(), decomp_tools::print_domains(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarz_picard_tt(), schwarz_dd2subcyc::schwarz_subcyc(), schwarz_dd_time_test::schwarzloc(), decomposer::set_subdomains(), schwarz_dd2subcyc::solve_subdomain(), subcycling::subcyc_schwarz(), subcycling::update_domain(), and schwarz_dd_time_test::vyreseno().
  type(subdomain_str), dimension(:), allocatable :: subdomain
type(extsmtx), public decomp_vars::tmpmat
Definition at line 154 of file decomp_vars.f90.
  type(extsmtx), public :: tmpmat
logical, public decomp_vars::use_coarselev
Definition at line 163 of file decomp_vars.f90.
Referenced by decomposer::init_decomp(), and schwarz_dd::schwarz_picard().
  logical, public :: use_coarselev
real(kind=rkind), dimension(:), allocatable, public decomp_vars::xcoarse
Definition at line 157 of file decomp_vars.f90.
Referenced by decomp_tools::build_coarsemtx(), and schwarz_dd::schwarz_picard().
  real(kind=rkind), dimension(:), allocatable, public :: xcoarse