heat_globals Module Reference
Data Types
type heatpars_str
ADE solute/material parameters array.
Variables
type(heatpars_str), dimension(:), allocatable, public heatpar
structure of solute parameters
integer, public file_heat
Variable Documentation
integer, public heat_globals::file_heat
Definition at line 20 of file heat_globals.f90.
Referenced by heat_reader::heat_read().
  integer, public :: file_heat
type(heatpars_str), dimension(:), allocatable, public heat_globals::heatpar
structure of solute parameters
Definition at line 19 of file heat_globals.f90.
Referenced by heat_fnc::heat_conduct(), heat_fnc::heat_convect(), heat_fnc::heat_elast(), heat_fnc::heat_flux(), heat_fnc::heat_icond(), heat_reader::heat_read(), and heat_fnc::heat_source().
  type(heatpars_str), dimension(:), allocatable, public :: heatpar