boussglob Module Reference
Variables
type(smartarray_real), dimension(2), public bouss_slopes
type(smartarray_real), dimension(2), public bouss_k
type(smartarray_real), dimension(2), public bouss_rain
real(kind=rkind), public bouss_por
real(kind=rkind), public bouss_icond
Variable Documentation
real(kind=rkind), public boussglob::bouss_icond
Definition at line 9 of file boussglob.f90.
Referenced by boussfnc::boussicond(), and boussread::boussreader().
  real(kind=rkind), public :: bouss_icond
type(smartarray_real), dimension(2), public boussglob::bouss_k
Definition at line 6 of file boussglob.f90.
Referenced by boussfnc::bouss_cond(), and boussread::boussreader().
  type(smartarray_real), dimension(2), public :: bouss_k
real(kind=rkind), public boussglob::bouss_por
Definition at line 8 of file boussglob.f90.
Referenced by boussfnc::bouss_elast(), and boussread::boussreader().
  real(kind=rkind), public :: bouss_por
type(smartarray_real), dimension(2), public boussglob::bouss_rain
Definition at line 7 of file boussglob.f90.
Referenced by boussfnc::bouss_adv(), boussfnc::boussreact(), and boussread::boussreader().
  type(smartarray_real), dimension(2), public :: bouss_rain
type(smartarray_real), dimension(2), public boussglob::bouss_slopes
Definition at line 5 of file boussglob.f90.
Referenced by boussfnc::bouss_adv(), boussfnc::bouss_elast(), boussread::boussreader(), and boussfnc::darcy4bouss().
  type(smartarray_real), dimension(2), public :: bouss_slopes