simegen Module Reference
simple mesh generator
Functions/Subroutines
subroutine, public simegen1d ()
subroutine, public simegen2d (lx, ly, density, edges_xy, center_coor)
Detailed Description
simple mesh generator
Function/Subroutine Documentation
subroutine, public simegen::simegen1d ()
Definition at line 9 of file simegen.f90.
References core_tools::avg(), globals1d::deltax_1d, globals::elements, readtools::file_error(), globals::file_mesh, globals1d::materials_1d, core_tools::mesh_allocater(), and globals::nodes.
Referenced by read_inputs::read_1dmesh_int().
      use typy
      use global_objs
      use globals
      use globals1d
      use core_tools
      use readtools
      use debug_tools
      integer(kind=ikind) :: pocet1
      integer(kind=ikind), dimension(:), allocatable :: pocty, sumy
      real(kind=rkind) :: dx1
      integer(kind=ikind) :: i,j, last, n
      logical, dimension(:), allocatable :: testmat
      logical :: err_mat = .false.
      allocate(pocty(ubound(deltax_1d,1)))
      allocate(sumy(0:ubound(deltax_1d,1)))
      
     
      pocet1 = 0
      do i = 1, ubound(deltax_1d,1)
        if (abs((int((deltax_1d(i,3) - deltax_1d(i,2))/deltax_1d(i,1)) - &
                  ((deltax_1d(i,3) - deltax_1d(i,2))/deltax_1d(i,1)))) > 100*epsilon(dx1)) then
          n = int((deltax_1d(i,3) - deltax_1d(i,2))/deltax_1d(i,1)) + 1
        else
          n = int((deltax_1d(i,3) - deltax_1d(i,2))/deltax_1d(i,1))
        end if
        deltax_1d(i,1) = (deltax_1d(i,3) - deltax_1d(i,2))/(1.0_rkind*n)
        if (i == 1) then
          n = n + 1
        end if
        pocty(i) = n
        pocet1 = pocet1 + n
        sumy(i) = pocet1
      end do
      
      nodes%kolik=pocet1
      elements%kolik = nodes%kolik - 1
      call mesh_allocater()
      sumy(0) = 0
      deltax_1d(0,:) = 0
      deltax_1d(0,3) = deltax_1d(1,2)
      
        
      do i=1, ubound(pocty,1)
        do j=1, pocty(i)
          if (i == 1) then
            nodes%data(j+sumy(i-1),1) = deltax_1d(i-1,3) + (j-1)*deltax_1d(i,1)
          else
            nodes%data(j+sumy(i-1),1) = deltax_1d(i-1,3) + j*deltax_1d(i,1)
          end if
        end do
      end do
        
      elements%data(1,1) = 1
      elements%data(1,2) = 2
      do i=2, elements%kolik
        elements%data(i,1) = elements%data(i-1,2)
        elements%data(i,2) = i+1
      end do
      do i=1, elements%kolik
        do j=1,ubound(materials_1d,1)
          if (avg(nodes%data(elements%data(i,1),1), nodes%data(elements%data(i,2),1)) >
      materials_1d(j,2) .and. &
              avg(nodes%data(elements%data(i,1),1), nodes%data(elements%data(i,2),1)) <=
      materials_1d(j,3)) then
              
              elements%material(i, :) = nint(materials_1d(j,1))
              EXIT
          end if
        end do
      end do
      if (minval(elements%material) == 0) then
        print *, "check file drutes.conf/mesh/drumesh1d.conf, seems like the material description does not
       cover the entire domain"
        error stop
      end if
      
      allocate(testmat(nint(maxval(materials_1d(:,1)))))
      
      testmat = .false.
      
      do i=1, ubound(elements%material,1)
        testmat(elements%material(i,1)) = .true.
      end do
      
      do i=1, ubound(testmat,1)
        if (.not. testmat(i)) then
          print *, "ERROR! material with ID", i, "undefined in drutes.conf/mesh.conf/drumesh1d.conf"
          err_mat = .true.
        end if
      end do
      
      if (err_mat) call file_error(file_mesh, "ERROR!! check your material description")
      nodes%edge = 0
      if (nodes%data(1,1) < nodes%data(nodes%kolik,1)) then
        nodes%edge(1) = 101
        nodes%edge(ubound(nodes%edge,1)) = 102
      else
        nodes%edge(1) = 102
        nodes%edge(ubound(nodes%edge,1)) = 101
      end if
subroutine, public simegen::simegen2d (real(kind=rkind), intent(in) lx, real(kind=rkind), intent(in) ly, real(kind=rkind), intent(in) density, real(kind=rkind), dimension(:,:,:), intent(in) edges_xy, real(kind=rkind), dimension(:), intent(in) center_coor)
Parameters
in lx mesh parameters
in ly mesh parameters
in density mesh parameters
in edges_xy description of the mesh edges
Definition at line 127 of file simegen.f90.
References globals::elements, geom_tools::inline(), core_tools::mesh_allocater(), and globals::nodes.
Referenced by read_inputs::read_2dmesh_int().
      use typy
      use globals
      use globals2d
      use geom_tools
      use core_tools
      use debug_tools
      real(kind=rkind), intent(in) :: lx, ly, density
      real(kind=rkind), dimension(:,:,:), intent(in) :: edges_xy
      real(kind=rkind), dimension(:), intent(in) :: center_coor
      real(kind=rkind) :: step1, step2, tmp1, tmp2, reps
      real(kind=rkind), dimension(2) :: a,b
      
      integer :: i,j, counter, m, count1, count2, k, l
      real(kind=rkind), dimension(2) :: c
      integer(kind=ikind), dimension(:,:), allocatable :: cpus
      
      
      count1 = int(lx/density)
      
      step1 = lx/count1
      
      count2 = int(ly/density)
      
      step2 = ly/count2
      
      nodes%kolik = (count1+1)*(count2+1)
      elements%kolik = 2*count1*count2
      
      call mesh_allocater()
      counter = 1_ikind
      
      do i=0, count2
        do j=0, count1
          nodes%data(counter,1) = j*step1
          nodes%data(counter,2) = i*step2
          counter = counter + 1
        end do
      end do
      
      j = 1_ikind
      m = 0_ikind
      do i=1, elements%kolik - 1, 2
        if (m >= count1) then
          j = j+1
          m = 0_ikind
        end if
        m = m + 1
        elements%data(i,1) = int(i/2) + j
        elements%data(i,2) = int(i/2) + j+1 + count1
        elements%data(i,3) = int(i/2) + j+1 + count1 + 1
        elements%data(i+1,1) = int(i/2) + j
        elements%data(i+1,2) = int(i/2) + j+1
        elements%data(i+1,3) = int(i/2) + j+1 + count1 + 1
      end do
! do i=1, elements%kolik
! if (nodes%data(elements%data(i,1),2) > 50) then
! elements%material(i,:) = 1
! else
! elements%material(i,:) = 2
! end if
! end do
      elements%material = 1
      
      do i=1, nodes%kolik
        nodes%data(i,:) = nodes%data(i,:) + center_coor
      end do
      
      reps = epsilon(reps)
      
      nodes%edge = 0_ikind
      
    
      do i=1, nodes%kolik
        do j=1, ubound(edges_xy,1)
          a = edges_xy(j,1,:)
          b = edges_xy(j,2,:)
          c = nodes%data(i,:)
          if (inline(a,b,c)) then
                nodes%edge(i) = j+100
           end if
          end do
        end do
        
! nodes%data(2,:) = (/0,1/)
! nodes%data(3,:) = (/0,2/)
! nodes%data(4,:) = (/1,0/)
! nodes%data(5,:) = (/1,1/)
! nodes%data(6,:) = (/1,2/)
!
! elements%data(1,:) = (/1,4,5/)
! elements%data(2,:) = (/1,5,2/)
! elements%data(3,:) = (/2,5,6/)
! elements%data(4,:) = (/2,6,3/)
!
! nodes%edge = 0
! nodes%edge(1) = 101
! nodes%edge(4) = 101
! if (num_images() > 1) then
! allocate(cpus(num_images(),2))
! i = elements%kolik/num_images()
!
! do j=1, num_images()-1
! cpus(j,1) = (j-1)*i+1
! cpus(j,2) = j*i
! end do
!
!
! cpus(num_images(),1) = cpus(num_images()-1,2)+1
! cpus(num_images(),2) = elements%kolik
!
! i=1
! do j=1, elements%kolik
! do
! if (j >= cpus(i,1) .and. j <= cpus(i,2)) then
! elements%CPU(j) = i
! EXIT
! else
! i = i+1
! end if
! end do
! end do
!
! deallocate(cpus)
! else
! elements%CPU = 1
! end if
    
  ! do i=1, nodes%kolik
  ! do j=lbound(waterbc_m,1), lbound(waterbc_m,1)
  ! do k=1, ubound(waterbc_m(j)%x,1)-1
  ! a = (/waterbc_m(j)%x(k), waterbc_m(j)%y(k)/)
  ! b = (/waterbc_m(j)%x(k+1), waterbc_m(j)%y(k+1)/)
  ! print *, a,b
  ! print *, nodes%data(i,:)
  ! if (inline(a,b,nodes%data(i,:))) then
  ! nodes%edge(i) = waterbc_m(j)%ID
  ! EXIT
  ! end if
  ! end do
  ! end do
  ! end do
                
              
    
  ! do i=1, nodes%kolik
  ! if (abs(nodes%data(i,2) - ly) < reps) then
  ! nodes%bc_c(i, :) = 1_ikind
  ! else
  ! nodes%bc_c(i,:) = 0_ikind
  ! end if
  ! end do
  !
  !
  ! do i=1, ubound(nodes%data,1)
  ! print *, i, nodes%data(i,:), "edge", nodes%edge(i)
  ! end do
  ! stop
  ! stop
  ! do i=1, nodes%kolik
  ! print *, i, nodes%data(i,:), nodes%bc(i,:)
  ! end do
  ! !
  ! do i=1, elements%kolik
  ! print *, i, elements%data(i,:)
  ! end do
  ! stop