re_dual_pointers Module Reference
This module contains the pointers used for dual permeability model.
Functions/Subroutines
subroutine, public re_matrix ()
Links to releveant subroutines for matrix domain.
subroutine, public re_fracture ()
Links to releveant subroutines for fracture domain.
Detailed Description
This module contains the pointers used for dual permeability model.
Function/Subroutine Documentation
subroutine, public re_dual_pointers::re_fracture ()
Links to releveant subroutines for fracture domain.
Definition at line 84 of file Re_dual_pointers.f90.
References dual_por::darcy_law_d(), globals::drutes_config, re_dual_bc::dual_atmospheric(), dual_coup::dual_coup_min(), dual_coup::dual_coup_min_neg(), dual_coup::dual_coupling(), dual_coup::dual_coupling_k(), dual_coup::dual_coupling_neg(), dual_tab::dual_coupling_neg_tab(), dual_tab::dual_coupling_tab(), re_dual_bc::dual_freedrainage(), dual_por::dual_inicond(), dual_por::dual_mualem(), dual_tab::dual_mualem_tab(), re_dual_bc::dual_neumann_bc(), dual_por::dual_ret_cap(), dual_tab::dual_ret_cap_tab(), dual_tab::dual_tabvalues(), dual_por::getval_retot_dual(), re_dual_bc::inf_neumann_bc(), pde_objs::pde, re_dual_reader::re_dual_readf(), re_constitutive::re_null_bc(), re_total::retot_dirichlet_bc(), re_total::retot_dirichlet_height_bc(), dual_por::vangen_d(), and dual_tab::vangen_d_tab().
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use dual_por
      use re_dual_reader
      use re_constitutive
      use debug_tools
      use dual_tab
      use dual_coup
      use re_total
      use re_dual_bc
      integer(kind=ikind) :: i
      
      pde(2)%getval => getval_retot_dual
      call re_dual_readf(pde(2))
      pde(2)%initcond => dual_inicond
      
     if (drutes_config%fnc_method == 0) then
            pde(2)%pde_fnc(2)%dispersion => dual_mualem
            select case(coup_model)
             case(1:3)
               pde(2)%pde_fnc(2)%reaction => dual_coupling_neg
               pde(2)%pde_fnc(1)%reaction => dual_coupling
             case(4:5)
               pde(2)%pde_fnc(2)%reaction =>dual_coup_min_neg
               pde(2)%pde_fnc(1)%reaction =>dual_coup_min
             case default
             stop
            end select
            pde(2)%pde_fnc(2)%elasticity => dual_ret_cap
            pde(2)%mass => vangen_d
      else
            call dual_tabvalues(pde(2), kfnc=dual_mualem, cfnc=dual_ret_cap,&
            thetafnc=vangen_d,ex_k_fnc=dual_coupling_k)
            pde(2)%pde_fnc(2)%dispersion => dual_mualem_tab
            pde(2)%pde_fnc(2)%reaction => dual_coupling_neg_tab
            pde(2)%pde_fnc(1)%reaction => dual_coupling_tab
            pde(2)%pde_fnc(2)%elasticity => dual_ret_cap_tab
            pde(2)%mass => vangen_d_tab
      end if
      
      pde(2)%flux => darcy_law_d
      
      do i=lbound(pde(2)%bc,1), ubound(pde(2)%bc,1)
        select case(pde(2)%bc(i)%code)
          case(-1)
            pde(2)%bc(i)%value_fnc => retot_dirichlet_height_bc
          case(0)
            pde(2)%bc(i)%value_fnc => re_null_bc
          case(1)
            pde(2)%bc(i)%value_fnc => retot_dirichlet_bc
          case(2)
            pde(2)%bc(i)%value_fnc => dual_neumann_bc
          case(3)
            pde(2)%bc(i)%value_fnc => dual_freedrainage
          case(4)
            pde(2)%bc(i)%value_fnc => dual_atmospheric
          case(5)
            pde(2)%bc(i)%value_fnc => inf_neumann_bc
          case default
                print *, "ERROR! You have specified an unsupported boundary type definition for the
       Richards equation"
                print *, "the incorrect boundary code specified is:", pde(2)%bc(i)%code
                error stop
        end select
      end do
     
subroutine, public re_dual_pointers::re_matrix ()
Links to releveant subroutines for matrix domain.
Definition at line 8 of file Re_dual_pointers.f90.
References dual_por::darcy_law_d(), globals::drutes_config, re_dual_bc::dual_atmospheric(), dual_coup::dual_coup_min(), dual_coup::dual_coup_min_neg(), dual_coup::dual_coupling(), dual_coup::dual_coupling_k(), dual_coup::dual_coupling_neg(), dual_tab::dual_coupling_neg_tab(), dual_tab::dual_coupling_tab(), re_dual_bc::dual_freedrainage(), dual_por::dual_inicond(), dual_por::dual_mualem(), dual_tab::dual_mualem_tab(), re_dual_bc::dual_neumann_bc(), dual_por::dual_ret_cap(), dual_tab::dual_ret_cap_tab(), dual_tab::dual_tabvalues(), dual_por::getval_retot_dual(), re_dual_bc::inf_neumann_bc(), pde_objs::pde, re_dual_reader::re_dual_readm(), re_dual_reader::re_dual_var(), re_constitutive::re_null_bc(), re_total::retot_dirichlet_bc(), re_total::retot_dirichlet_height_bc(), dual_por::vangen_d(), and dual_tab::vangen_d_tab().
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use dual_por
      use re_dual_reader
      use re_constitutive
      use debug_tools
      use dual_tab
      use dual_coup
      use re_total
      use re_dual_bc
      integer(kind=ikind) :: i
           
      pde(1)%getval => getval_retot_dual
      call re_dual_readm(pde(1))
      call re_dual_var()
      pde(1)%initcond => dual_inicond
      pde(1)%flux => darcy_law_d
      if (drutes_config%fnc_method == 0) then
            pde(1)%pde_fnc(1)%dispersion => dual_mualem
            select case(coup_model)
             case(1:3)
               pde(1)%pde_fnc(1)%reaction => dual_coupling_neg
               pde(1)%pde_fnc(2)%reaction => dual_coupling
             case(4:5)
               pde(1)%pde_fnc(1)%reaction => dual_coup_min_neg
               pde(1)%pde_fnc(2)%reaction => dual_coup_min
             case default
             stop
            end select
            
            pde(1)%pde_fnc(1)%elasticity => dual_ret_cap
            pde(1)%mass => vangen_d
      else
            call dual_tabvalues(pde(1), kfnc=dual_mualem, cfnc=dual_ret_cap,&
            thetafnc=vangen_d,ex_k_fnc=dual_coupling_k)
            pde(1)%pde_fnc(1)%dispersion => dual_mualem_tab
            pde(1)%pde_fnc(1)%reaction => dual_coupling_neg_tab
            pde(1)%pde_fnc(2)%reaction => dual_coupling_tab
            pde(1)%pde_fnc(1)%elasticity => dual_ret_cap_tab
            pde(1)%mass => vangen_d_tab
      end if
      
      ! boundary condition defined as different type boundary_vals
      do i=lbound(pde(1)%bc,1), ubound(pde(1)%bc,1)
        select case(pde(1)%bc(i)%code)
          case(-1)
              pde(1)%bc(i)%value_fnc => retot_dirichlet_height_bc
          case(0)
            pde(1)%bc(i)%value_fnc => re_null_bc
          case(1)
            pde(1)%bc(i)%value_fnc => retot_dirichlet_bc
          case(2)
            pde(1)%bc(i)%value_fnc => dual_neumann_bc
          case(3)
            pde(1)%bc(i)%value_fnc => dual_freedrainage
          case(4)
            pde(1)%bc(i)%value_fnc => dual_atmospheric
          case(5)
            pde(1)%bc(i)%value_fnc => inf_neumann_bc
          case default
                print *, "ERROR! You have specified an unsupported boundary type definition for the
       Richards equation"
                print *, "the incorrect boundary code specified is:", pde(1)%bc(i)%code
                error stop
        end select
      end do
   