re_pointers Module Reference
Functions/Subroutines
subroutine, public reroth (pde_loc)
subroutine, public re_rot (pde_loc)
subroutine, public re_std (pde_loc)
subroutine, public restdh (pde_loc)
subroutine, public re_pressheadbc (pde_loc)
subroutine, public re_totheadbc (pde_loc)
subroutine, public allrepointers (pde_loc)
Function/Subroutine Documentation
subroutine, public re_pointers::allrepointers (class(pde_str), intent(inout) pde_loc)
Definition at line 179 of file re_pointers.f90.
References re_constitutive::dmualem_dh(), re_constitutive::domainswitch(), globals::drutes_config, re_constitutive::init_zones(), re_constitutive::mualem(), re_constitutive::mualem_tab(), pde_objs::pde_common, re_constitutive::rcza_check(), re_reader::res_read(), re_constitutive::sinkterm(), re_constitutive::tabvalues(), re_constitutive::vangen(), re_constitutive::vangen_elast(), re_constitutive::vangen_elast_tab(), re_constitutive::vangen_tab(), and re_globals::vgmatrix.
Referenced by re_rot(), re_std(), reroth(), and restdh().
      use typy
      use globals
      use global_objs
      use pde_objs
      use re_globals
      use re_constitutive
      use re_reader
      
      class(pde_str), intent(in out) :: pde_loc
      integer(kind=ikind) :: i
      logical, save :: read=.false.
      
      ! read inputs
      if (.not. read) then
        call res_read(pde_loc)
        read = .true.
      end if
      
      
      call domainswitch("m")
      pde_common%nonlinear = .true.
      if (drutes_config%fnc_method == 0) then
        pde_loc%pde_fnc(pde_loc%order)%dispersion => mualem
        pde_loc%pde_fnc(pde_loc%order)%elasticity => vangen_elast
        pde_loc%mass => vangen
      else
        call tabvalues(pde_loc, kfnc=mualem, dkdhfnc = dmualem_dh, cfnc=
      vangen_elast, thetafnc=vangen)
        pde_loc%pde_fnc(pde_loc%order)%dispersion => mualem_tab
        pde_loc%pde_fnc(pde_loc%order)%elasticity => vangen_elast_tab
        pde_loc%mass => vangen_tab
      end if
      
      do i=1, ubound(vgmatrix,1)
        if (vgmatrix(i)%rcza_set%use) then
          call init_zones(vgmatrix)
          pde_loc%dt_check => rcza_check
          EXIT
        end if
      end do
      
      pde_loc%pde_fnc(pde_loc%order)%zerord => sinkterm
      
      
      
    
subroutine, public re_pointers::re_pressheadbc (class(pde_str), intent(inout) pde_loc)
Definition at line 106 of file re_pointers.f90.
References re_constitutive::re_dirichlet_bc(), re_constitutive::re_dirichlet_height_bc(), re_constitutive::re_neumann_bc(), and re_constitutive::re_null_bc().
Referenced by re_rot(), and re_std().
      use typy
      use globals
      use global_objs
      use pde_objs
      use re_globals
      use re_constitutive
      
      class(pde_str), intent(in out) :: pde_loc
      
      integer(kind=ikind) :: i
      
      
      do i=lbound(pde_loc%bc,1), ubound(pde_loc%bc,1)
        select case(pde_loc%bc(i)%code)
          case(-1)
              pde_loc%bc(i)%value_fnc => re_dirichlet_height_bc
          case(0)
                pde_loc%bc(i)%value_fnc => re_null_bc
          case(1)
                pde_loc%bc(i)%value_fnc => re_dirichlet_bc
          case(2)
                pde_loc%bc(i)%value_fnc => re_neumann_bc
          case(3)
                pde_loc%bc(i)%value_fnc => re_null_bc
          case default
                print *, "ERROR! You have specified an unsupported boundary type definition for the
       Richards equation"
                print *, "the incorrect boundary code specified is:", pde_loc%bc(i)%code
                error stop
        end select
      end do
        
subroutine, public re_pointers::re_rot (class(pde_str), intent(inout) pde_loc)
Definition at line 30 of file re_pointers.f90.
References allrepointers(), re_constitutive::convection_rerot(), re_constitutive::darcy_law(), re_constitutive::dmualem_dh(), re_constitutive::dmualem_dh_tab(), globals::drutes_config, re_constitutive::re_initcond(), and re_pressheadbc().
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use re_globals
      use re_constitutive
      
      class(pde_str), intent(in out) :: pde_loc
      
      call allrepointers(pde_loc)
      call re_pressheadbc(pde_loc)
      
      pde_loc%pde_fnc(pde_loc%order)%convection => convection_rerot
      
      if (drutes_config%fnc_method == 0) then
        pde_loc%pde_fnc(pde_loc%order)%convection => dmualem_dh
      else
        pde_loc%pde_fnc(pde_loc%order)%convection => dmualem_dh_tab
      end if
      pde_loc%flux => darcy_law
      pde_loc%initcond => re_initcond
     
    
subroutine, public re_pointers::re_std (class(pde_str), intent(inout) pde_loc)
Definition at line 57 of file re_pointers.f90.
References allrepointers(), re_constitutive::darcy_law(), re_constitutive::dmualem_dh(), re_constitutive::dmualem_dh_tab(), globals::drutes_config, pde_objs::getvalp1(), re_constitutive::re_initcond(), and re_pressheadbc().
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use re_globals
      use re_constitutive
      
      class(pde_str), intent(in out) :: pde_loc
      
      call allrepointers(pde_loc)
      call re_pressheadbc(pde_loc)
       
      pde_loc%getval => getvalp1
      
      if (drutes_config%fnc_method == 0) then
        pde_loc%pde_fnc(pde_loc%order)%convection => dmualem_dh
      else
        pde_loc%pde_fnc(pde_loc%order)%convection => dmualem_dh_tab
      end if
        
      pde_loc%flux => darcy_law
      pde_loc%initcond => re_initcond
     
    
subroutine, public re_pointers::re_totheadbc (class(pde_str), intent(inout) pde_loc)
Definition at line 141 of file re_pointers.f90.
References re_constitutive::re_null_bc(), re_total::retot_dirichlet_bc(), re_total::retot_dirichlet_height_bc(), re_total::retot_freedrainage(), re_total::retot_neumann_bc(), and re_total::retot_seepage().
Referenced by reroth(), and restdh().
      use typy
      use globals
      use global_objs
      use pde_objs
      use re_globals
      use re_constitutive
      use re_total
      
      class(pde_str), intent(in out) :: pde_loc
      integer(kind=ikind) :: i
      
      do i=lbound(pde_loc%bc,1), ubound(pde_loc%bc,1)
        select case(pde_loc%bc(i)%code)
          case(-1)
              pde_loc%bc(i)%value_fnc => retot_dirichlet_height_bc
          case(0)
                pde_loc%bc(i)%value_fnc => re_null_bc
          case(1)
                pde_loc%bc(i)%value_fnc => retot_dirichlet_bc
          case(2)
                pde_loc%bc(i)%value_fnc => retot_neumann_bc
          case(3)
                pde_loc%bc(i)%value_fnc => retot_freedrainage
          case(4)
                pde_loc%bc(i)%value_fnc => retot_seepage
          case default
                print *, "ERROR! You have specified an unsupported boundary type definition for the
       Richards equation"
                print *, "the incorrect boundary code specified is:", pde_loc%bc(i)%code
                error stop
        end select
      end do
    
    
subroutine, public re_pointers::reroth (class(pde_str), intent(inout) pde_loc)
Definition at line 9 of file re_pointers.f90.
References allrepointers(), re_constitutive::convection_rerot(), re_total::darcy4toth(), re_total::getval_retot(), re_totheadbc(), and re_total::retot_initcond().
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use re_globals
      use re_constitutive
      use re_total
      
      class(pde_str), intent(in out) :: pde_loc
      
      call allrepointers(pde_loc)
      call re_totheadbc(pde_loc)
      
      pde_loc%pde_fnc(pde_loc%order)%convection => convection_rerot
      pde_loc%getval => getval_retot
      pde_loc%flux => darcy4toth
      pde_loc%initcond => retot_initcond
subroutine, public re_pointers::restdh (class(pde_str), intent(inout) pde_loc)
Definition at line 84 of file re_pointers.f90.
References allrepointers(), re_total::darcy4toth(), re_total::getval_retot(), re_totheadbc(), and re_total::retot_initcond().
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use re_globals
      use re_constitutive
      use re_total
      
      class(pde_str), intent(in out) :: pde_loc
      
      call allrepointers(pde_loc)
      call re_totheadbc(pde_loc)
      pde_loc%getval => getval_retot
      
      pde_loc%flux => darcy4toth
      pde_loc%initcond => retot_initcond
    