geom_tools Module Reference
Functions/Subroutines
integer(kind=ikind) function, public get_layer (quadpnt)
subroutine, public getcoor (quadpnt, array)
subroutine, public interpolate (vals, points)
returns the solution values on gaussian nodes positions
subroutine, public plane_derivative (a, b, c, xder, yder)
specify the x and y derivates of a plane defined by three points
subroutine, public init_transform (aT, bT, cT, matrix)
procedure to create transformation matrix
 \left( \begin{array}{c} e \\ f \end{array} \right) + \left( \begin{array}{cc} a & b \\ c & d \end{array}\right) \left( \begin{array}{c} x \\ y \end{array} \right) = \left( \begin{array}{c} x^T \\ y^T \end{array} \right) 
 where (e,f) is the vector of move and the matrix
 \left( \begin{array}{cc} a & b \\ c & d \end{array}\right) 
 is the matrix of rotation each line represents the element id, the first column in row represents numbers e,f,a,b the second column reprerents numbers f,c,d
real(kind=rkind) function, public get_nz (el_id, order1, order2)
function that provides z coordinate of boundary normal vector, the boundary is defined by two points: bod1, bod2
logical function, public inside (domain, bod)
subroutine, private shoot (bod, k, domain, inter, valid)
real(kind=rkind) function, public triarea (a, b, c)
real(kind=rkind) function, public dist (A, B)
real(kind=rkind) function, public angle (A, B, C)
logical function, public inline (A, B, bod)
function to determine whether the third point is on line formed by the first two points
subroutine, public solve_bisect (xmin, xmax, f, reps, ierr, solution)
bisecton method searching for a root of function f on defined intervals xmin and xmax
logical function, private aboveline (a, b, c)
function to determine if the point C lies above or below the line defined by points A and B result is logical value nad, if true point lies above if false it lies below if the line is vertical, then if true the point lies on the left hand side from the line, if false the point lies on the right hand side from the line.
subroutine, public getnormal (bcpoints, thirdpt, nvect)
this function returns outer normal boundary vector bcpoints - nodes ids at the element boundary, integer, dimension(2) thirdpt - coordinates of a point at at element, which lies out of the boundary. It is important in order to obtain proper positive direction of the normal vector
subroutine, public najdi_bod (a, b, c, bod)
subroutine seeking for the point which is on line identified by points a and b, and line between this point and c is rectangular to the line <a,b>
subroutine, public max_height (a, b, c, height)
subroutine searching for the maximum height on triangle element
real(kind=rkind) function, dimension(2) gravity_center (a, b, c)
subroutine, public find_neighbours (el, nd)
subroutine, public map1d2d (filename)
subroutine, public map1d2dj (pde_loc, filename)
Function/Subroutine Documentation
logical function, private geom_tools::aboveline (real(kind=rkind), dimension(:), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(in) c) [private]
function to determine if the point C lies above or below the line defined by points A and B result is logical value nad, if true point lies above if false it lies below if the line is vertical, then if true the point lies on the left hand side from the line, if false the point lies on the right hand side from the line.
Definition at line 681 of file geom_tools.f90.
Referenced by get_nz(), and getnormal().
    use typy
    use globals
    use globals2d
    real(kind=rkind), dimension(:), intent(in) :: a,b,c
    logical :: nad
    real(kind=rkind) :: xa1, yb1, q1, xa2, yb2, q2, x_int, y_int
    !first define the coefficient of the line equation defined by A and B
    
    if (abs(b(1)-a(1)) > 100*epsilon(xa1) .and. abs(b(2)-a(2)) > 100*epsilon(xa1)) then
      xa1 = (b(2) - a(2))/(b(1) - a(1))
      
      yb1 = -1.0_rkind
      
      q1 = -xa1*a(1) - yb1*a(2)
      xa2 = yb1
      
      yb2 = -xa1
      
      q2 = -xa2*c(1) - yb2*c(2)
      
      x_int = (-q1 + yb1*q2/yb2)/(xa1 - yb1*xa2/yb2)
      
      y_int = (-q2 - xa2*x_int)/yb2
      
      
      if (y_int >= c(2)) then
        nad = .false.
      else
        nad = .true.
      end if
    else
      if (abs(b(1)-a(1)) < 100*epsilon(xa1)) then ! vertical line
 
        if (c(1) >= b(1)) then
          nad = .false.
        else
          nad = .true.
        end if
        
      end if
      
      if (abs(b(2)-a(2)) < 100*epsilon(xa1)) then ! horizontal line
        
        if (c(2) >= b(2)) then
          nad = .true.
        else
          nad = .false.
        end if
      end if
    end if
      
real(kind=rkind) function, public geom_tools::angle (real(kind=rkind), dimension(:), intent(in) A, real(kind=rkind), dimension(:), intent(in) B, real(kind=rkind), dimension(:), intent(in) C)
Definition at line 569 of file geom_tools.f90.
References dist().
Referenced by feminittools::search_bnd_nodes().
    use typy
    
    real(kind=rkind), dimension(:), intent(in) :: a, b, c
    real(kind=rkind) :: gamma
    real(kind=rkind) :: la, lb, lc
    
    lc = dist(a,b)
    lb = dist(a,c)
    la = dist(b,c)
    
    if (la > 10*epsilon(la) .and. lb > 10*epsilon(la)) then
      gamma = acos(min((lc**2-la**2-lb**2)/(-2.0_rkind*la*lb),1.0_rkind))
    else
      gamma = acos(1.0_dprec)
    end if
real(kind=rkind) function, public geom_tools::dist (real(kind=rkind), dimension(:), intent(in) A, real(kind=rkind), dimension(:), intent(in) B)
Definition at line 552 of file geom_tools.f90.
References globals::drutes_config.
Referenced by angle(), getcoor(), drutes_init::init_measured(), inline(), inside(), max_height(), and feminittools::surface_integ().
    use typy
    use globals
    
    real(kind=rkind), dimension(:), intent(in) :: a,b
    real(kind=rkind) :: l
    
    select case(drutes_config%dimen)
      case(1)
        l = abs(a(1) - b(1))
      case(2)
        l = sqrt((a(1)-b(1))*(a(1)-b(1)) + (a(2)-b(2))*(a(2)-b(2)))
    end select
  
subroutine, public geom_tools::find_neighbours (type(element), intent(inout) el, type(node), intent(in) nd)
Definition at line 939 of file geom_tools.f90.
References globals::drutes_config, globals::elements, and printtools::progressbar().
Referenced by decomposer::make_quadmesh(), decomposer::read_coarse_mesh(), and feminittools::surface_integ().
      use typy
      use globals
      use global_objs
      use printtools
      use core_tools
      use debug_tools
      use debug_tools
      type(element), intent(in out) :: el
      type(node), intent(in) :: nd
      
      integer(kind=ikind) :: i,j,k,l,m,upward,downward,pos, n, o
      
      el%neighbours = 0_ikind
      
      select case(drutes_config%dimen)
        case(1)
          do i=1, el%kolik - 1
            el%neighbours(i,1) = i-1
            el%neighbours(i,2) = i+1
           end do
           el%neighbours(elements%kolik,1) = elements%kolik - 1
           el%neighbours(elements%kolik,2) = 0
        case(2)
            !set neighbours
            do i=1, el%kolik
              pos = 0
              j = i
              k = i
              call progressbar(int(100*i/el%kolik))
              okoli: do
                        j = min(j+1, el%kolik+1)
                        k = max(k-1, 0_ikind)
                        if (j <= el%kolik) then
                          upward = 0
                          moje1: do l=1,ubound(el%data,2)
                                    nasel1: do m=1,ubound(el%data,2)
                                            if (el%data(i,l) == el%data(j,m) .and. i/=j) then
                                              upward = upward + 1
                                              if (upward == 2) then
                                                pos = pos + 1
                                                el%neighbours(i,pos) = j
                                                EXIT nasel1
                                              end if
                                            end if
                                  end do nasel1
                          end do moje1
                        end if
                        if (k > 0) then
                          downward = 0
                          moje2: do l=1,ubound(el%data,2)
                                  nasel2: do m=1,ubound(el%data,2)
                                            if (el%data(i,l) == el%data(k,m) .and. i /= k) then
                                              downward = downward + 1
                                              if (downward == 2) then
                                                pos = pos + 1
                                                el%neighbours(i,pos) = k
                                                EXIT nasel2
                                              end if
                                            end if
                                  end do nasel2
                          end do moje2
                        end if
                        if (pos == ubound(el%data,2) .or. (j == el%kolik+1 .and. k == 0_ikind)) then
                          EXIT okoli
                        end if
              end do okoli
            end do
            
        end select
      
integer(kind=ikind) function, public geom_tools::get_layer (type(integpnt_str), intent(in) quadpnt)
Definition at line 40 of file geom_tools.f90.
References globals::elements, and globals::nodes.
Referenced by re_total::getval_retot().
    use typy
    use globals
    use global_objs
    
    type(integpnt_str), intent(in) :: quadpnt
    integer(kind=ikind) :: layer
    integer(kind=ikind) :: el
    
    select case(quadpnt%type_pnt)
      case("ndpt")
        el = nodes%element(quadpnt%order)%data(1)
        layer=elements%material(el,1)
      case("obpt", "gqnd")
        el = quadpnt%element
        if (.not. (el >= 1 .and. el<=elements%kolik)) then
          print *, "error in quadpnt data", el, quadpnt%type_pnt
          print *, "called from geom_tools::get_layer"
          print *, "contact Michal -> michalkuraz@gmail.com"
          error stop
        end if
        layer = elements%material(el,1)
      case default
          print *, "err or in quadpnt data"
          print *, "called from geom_tools::get_layer"
          print *, "contact Michal -> michalkuraz@gmail.com"
          error stop
    end select
  
real(kind=rkind) function, public geom_tools::get_nz (integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) order1, integer(kind=ikind), intent(in) order2)
function that provides z coordinate of boundary normal vector, the boundary is defined by two points: bod1, bod2
Definition at line 332 of file geom_tools.f90.
References aboveline(), globals::elements, and globals::nodes.
Referenced by feminittools::surface_integ().
    use typy
    use globals
    use global_objs
    integer(kind=ikind), intent(in) :: el_id, order1, order2
    real(kind=rkind), dimension(2) :: bod1, bod2
    real(kind=rkind) :: zcoord
    real(kind=rkind) :: tg
    integer(kind=ikind) :: order3
    bod1 = nodes%data(elements%data(el_id,order1),:)
    bod2 = nodes%data(elements%data(el_id,order2),:)
    if (abs(bod1(1)-bod2(1)) > epsilon(tg)) then
      tg = (abs(bod2(2)-bod1(2))/abs(bod1(1)-bod2(1)))
      zcoord = 1/sqrt(1+tg*tg)
    else
      zcoord = 0
    end if
    select case(order1+order2)
      case(3)
        order3=3
      case(4)
        order3=2
      case(5)
        order3=1
    end select
    if (.not. aboveline(bod1, bod2, nodes%data(elements%data(el_id, order3),:))) then
      zcoord = -zcoord
    end if
subroutine, public geom_tools::getcoor (type(integpnt_str), intent(in) quadpnt, real(kind=rkind), dimension(:), intent(out) array)
Definition at line 72 of file geom_tools.f90.
References dist(), globals::drutes_config, globals::elements, globals::gauss_points, globals::nodes, and globals::observation_array.
Referenced by boussfnc::bouss_adv(), boussfnc::bouss_cond(), boussfnc::bouss_elast(), re_constitutive::convection_rerot(), boussfnc::darcy4bouss(), re_total::getval_retot(), dual_por::getval_retot_dual(), and re_total::retot_dirichlet_bc().
    use typy
    use pde_objs
    use globals
    use debug_tools
    
    type(integpnt_str), intent(in) :: quadpnt
    real(kind=rkind), dimension(:), intent(out) :: array
    integer(kind=ikind), dimension(3) :: nd
    integer(kind=ikind) :: el, i
    real(kind=rkind) :: dist1, dist2, r1, r2, k1, k2, q1, q2
    real(kind=rkind), dimension(2) :: r,k,q,d
    real(kind=rkind), dimension(3,2) :: triagpnt
    real(kind=rkind), dimension(2,2) :: midpnt
    logical, dimension(2) :: vert
     
    
    select case(quadpnt%type_pnt)
      case("gqnd")
        select case (drutes_config%dimen)
          case(1)
            el = quadpnt%element
            nd(1:2) = elements%data(el,1:2)
            dist1 = nodes%data(nd(2),1) - nodes%data(nd(1),1)
            array(1) = nodes%data(nd(1),1) + dist1*gauss_points%point(quadpnt%order,1)
           case(2)
           
! triag scheme
! triag(3)
! |\
! | \
! | \
! | \
! | \
! | \
! | \
! | \
! midpnt(1)|...x \
! | . \
! d(1)| . \
! | . d(2) \
! triag(1) -------------\ triag(2)
! midpnt(2)
          
          
            vert = .false.
            el = quadpnt%element
            do i=1,3
              triagpnt(i,:) = nodes%data(elements%data(el,i),:)
            end do
            d(1) = dist(triagpnt(1,:), triagpnt(3,:))
            d(2) = dist(triagpnt(1,:), triagpnt(2,:))
            !z distance on unit triangle
            r(1) = gauss_points%point(quadpnt%order,2)
            !x distance on unit triangle
            r(2) = gauss_points%point(quadpnt%order,1)
            
            midpnt(1,:) = triagpnt(1,:) + (triagpnt(3,:) - triagpnt(1,:)) * r(1)
            
            midpnt(2,:) = triagpnt(1,:) + (triagpnt(2,:) - triagpnt(1,:)) * r(2)
            
            if (abs(midpnt(2,1)-triagpnt(1,1)) > 100*epsilon(k1)) then
              k(1) = (midpnt(2,2) - triagpnt(1,2))/(midpnt(2,1)-triagpnt(1,1))
            else
              vert(1) = .true.
            end if
            
            if (abs(midpnt(1,1)-triagpnt(1,1)) > 100*epsilon(k1)) then
              k(2) = (midpnt(1,2) - triagpnt(1,2))/(midpnt(1,1)-triagpnt(1,1))
            else
              vert(2) = .true.
            end if
            
            where (.not.(vert))
              q(:) = midpnt(:,2) - k(:)*midpnt(:,1)
            end where
            
! print *, "----beg-------"
! print *, midpnt(1,:)
! print *, midpnt(2,:)
! print *, k
! print *, vert
! print *, "-----end-----"
            
            
            if (.not. vert(1) .and. .not. vert(2)) then
              array(1) = (q(1)- q(2))/(k(2)-k(1))
              if (abs(k(1) - k(2)) <= epsilon(k1)) then
                print *, "there must be a bug, both lines have equal tangent, or your mesh is really bad"
                print *, "interrupted from geom_tools::getcoor"
                error stop
              end if
              array(2) = k(1)*array(1) + q(1)
            else
              if (vert(1) .and. .not. (vert(2))) then
                array(1) = midpnt(1,1)
                array(2) = midpnt(2,2) + k(2)*(midpnt(1,1)-midpnt(2,1))
              else if (.not.vert(1) .and. (vert(2))) then
                array(1) = midpnt(2,1)
                array(2) = midpnt(1,2) + k(1)*(midpnt(2,1) - midpnt(1,1))
              else if (vert(1) .and. vert(2)) then
                print *, "there must be a bug, both lines are vertical"
                print *, "interrupted from geom_tools::getcoor"
                error stop
              end if
            end if
        end select
      case("obpt")
        array = observation_array(quadpnt%order)%xyz
      case("ndpt")
        array = nodes%data(quadpnt%order,:)
    end select
subroutine, public geom_tools::getnormal (real(kind=rkind), dimension(:,:), intent(in) bcpoints, real(kind=rkind), dimension(:), intent(in) thirdpt, real(kind=rkind), dimension(:), intent(out), allocatable nvect)
this function returns outer normal boundary vector bcpoints - nodes ids at the element boundary, integer, dimension(2) thirdpt - coordinates of a point at at element, which lies out of the boundary. It is important in order to obtain proper positive direction of the normal vector
Definition at line 741 of file geom_tools.f90.
References aboveline(), and globals::drutes_config.
Referenced by re_total::retot_seepage().
    use typy
    use globals
    
    real(kind=rkind), dimension(:,:), intent(in) :: bcpoints
    real(kind=rkind), dimension(:), intent(in) :: thirdpt
    real(kind=rkind), dimension(:), allocatable, intent(out) :: nvect
    
    real(kind=rkind) :: k
    
    if (drutes_config%dimen == 1) then
      print *, "RUNTIME ERROR, function geomtools::getnormal is called for 1D problem"
      print *, "if (desporate) contact Michal -> michalkuraz@gmail.com"
      error stop
    end if
    
    if (.not. allocated(nvect)) allocate(nvect(drutes_config%dimen))
  
    if (abs(bcpoints(1,1)-bcpoints(2,1)) > 100*epsilon(bcpoints(1,1)) .and. &
      abs(bcpoints(1,2)-bcpoints(2,2)) > 100*epsilon(bcpoints(1,1))) then
     
      k = (bcpoints(1,2)-bcpoints(2,2))/(bcpoints(1,1)-bcpoints(2,1))
     
      if (aboveline(bcpoints(1,:), bcpoints(2,:), thirdpt)) then
        nvect(2) = -1
      else
        nvect(2) = 1
      end if
      
      ! change x for y
      if (aboveline((/bcpoints(1,2), bcpoints(1,1)/), (/bcpoints(2,2), bcpoints(2,1)/), (/thirdpt(2),
      thirdpt(1)/))) then
        nvect(1) = -abs(1.0_rkind/k)
      else
        nvect(1) = abs(1.0_rkind/k)
      end if
      
      nvect = nvect/(sqrt(nvect(1)*nvect(1)+nvect(2)*nvect(2)))
     
    !vertical line
    else if (abs(bcpoints(1,1)-bcpoints(2,1)) < 100*epsilon(bcpoints(1,1)) .and. &
       abs(bcpoints(1,2)-bcpoints(2,2)) > 100*epsilon(bcpoints(1,1))) then
       
       if (aboveline(bcpoints(1,:), bcpoints(2,:), thirdpt)) then
         nvect(1) = 1
       else
         nvect(1) = -1
       end if
       
       nvect(2) = 0
       
     !horizontal line
    else if (abs(bcpoints(1,1)-bcpoints(2,1)) > 100*epsilon(bcpoints(1,1)) .and. &
       abs(bcpoints(1,2)-bcpoints(2,2)) < 100*epsilon(bcpoints(1,1))) then
       
       if (aboveline(bcpoints(1,:), bcpoints(2,:), thirdpt)) then
         nvect(2) = -1
       else
         nvect(2) = 1
       end if
       
       nvect(1) = 0
     else
       print *, "runtime error, exited from geomtools::getnormal seems like your boundary is defined by a
       single point"
       print *, "check your mesh, if your mesh is ok, then contact Michal -> michalkuraz@gmail.com"
       error stop
     end if
  
real(kind=rkind) function, dimension(2) geom_tools::gravity_center (real(kind=rkind), dimension(:), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(in) c)
Definition at line 871 of file geom_tools.f90.
References linalg::gem().
Referenced by decomposer::init_decomp(), and read_inputs::read_2dmesh_gmsh().
    use typy
    use linalg
    real(kind=rkind), dimension(:), intent(in) :: a,b,c
    real(kind=rkind), dimension(2) :: gc
    real(kind=rkind), dimension(2,2) :: line_pars, matrix
    real(kind=rkind), dimension(2) :: point, bside
    integer(kind=ikind) :: i
    logical :: vertical
    
    point = (b+c)/2.0_rkind
    
    if (abs(a(1)-point(1)) > 1000*epsilon(a(1))) then
      bside(1) = a(2)
      bside(2) = point(2)
      matrix(:,2) = 1.0_rkind
      matrix(1,1) = a(1)
      matrix(2,1) = point(1)
      call gem(matrix, bside, line_pars(1,:))
      vertical = .false.
    else
      gc(1) = (a(1)+point(1))/2.0_rkind
      vertical = .true.
      i = 2
    end if
      
    
    point = (a + c)/2.0_rkind
   
    if (abs(b(1)-point(1)) > 1000*epsilon(a(1))) then
      bside(1) = b(2)
      bside(2) = point(2)
      matrix(:,2) = 1
      matrix(1,1) = b(1)
      matrix(2,1) = point(1)
    
      call gem(matrix, bside, line_pars(2,:))
    else
      gc(1) = (b(1)+point(1))/2.0_rkind
      vertical = .true.
      i = 1
    end if
      
    if (.not.(vertical)) then
      bside = -line_pars(:,2)
      matrix(:,1) = line_pars(:,1)
      matrix(:,2) = -1.0_rkind
      call gem(matrix, bside, gc)
    else
      gc(2) = line_pars(i,1)*gc(1) + line_pars(i,2)
    end if
    
subroutine, public geom_tools::init_transform (real(kind=rkind), dimension(:), intent(in) aT, real(kind=rkind), dimension(:), intent(in) bT, real(kind=rkind), dimension(:), intent(in) cT, real(kind=rkind), dimension(:,:), intent(out) matrix)
procedure to create transformation matrix
 \left( \begin{array}{c} e \\ f \end{array} \right) + \left( \begin{array}{cc} a & b \\ c & d \end{array}\right) \left( \begin{array}{c} x \\ y \end{array} \right) = \left( \begin{array}{c} x^T \\ y^T \end{array} \right) 
 where (e,f) is the vector of move and the matrix
 \left( \begin{array}{cc} a & b \\ c & d \end{array}\right) 
 is the matrix of rotation each line represents the element id, the first column in row represents numbers e,f,a,b the second column reprerents numbers f,c,d
Parameters
in at nodes of triangle
out matrix to store the transformation matrix
Definition at line 279 of file geom_tools.f90.
    use typy
    real(kind=rkind), dimension(:), intent(in) :: at
    real(kind=rkind), dimension(:), intent(in) :: bt
    real(kind=rkind), dimension(:), intent(in) :: ct
    real(kind=rkind), dimension(:,:), intent(out) :: matrix
    real(kind=rkind) :: a,b,c,d,e,f
    integer(kind=ikind) :: i
    
    
    !shape of the unit triangle
! [0,1]
! |\
! | \
! | \
! | \
! | \
! | \
! | \
! |----7|---8|---9|--\
! | | | | \
! |----4|---5|---6|--- \
! | | | | \
! |----1|---2|---3|----- -\
! | | | | \
! | | | | \
! -----------------------------------------
! [0,0] [1,0]
    e = at(1)
    f = at(2)
    a = bt(1) - e
    c = bt(2) - f
    b = ct(1) - e
    d = ct(2) - f
      
    matrix(1,1) = e
    matrix(1,2) = f
    matrix(2,1) = a
    matrix(2,2) = c
    matrix(3,1) = b
    matrix(3,2) = d
logical function, public geom_tools::inline (real(kind=rkind), dimension(:), intent(in) A, real(kind=rkind), dimension(:), intent(in) B, real(kind=rkind), dimension(:), intent(in) bod)
function to determine whether the third point is on line formed by the first two points
Definition at line 590 of file geom_tools.f90.
References dist().
Referenced by inside(), shoot(), and simegen::simegen2d().
    use typy
    real(kind=rkind), dimension(:), intent(in) :: bod, a,b
    real(kind=rkind) :: precision
    logical :: true
    
    precision = 1000*epsilon(precision)
    if (abs(dist(a,b) - dist(a,bod) - dist(b,bod)) < precision) then
      true = .true.
    else
      true = .false.
    end if
    
logical function, public geom_tools::inside (real(kind=rkind), dimension(:,:), intent(in) domain, real(kind=rkind), dimension(:), intent(in) bod)
Definition at line 372 of file geom_tools.f90.
References dist(), globals::drutes_config, inline(), and shoot().
Referenced by decomposer::init_decomp(), drutes_init::init_observe(), and read_inputs::read_2dmesh_gmsh().
    use typy
    use globals
    use global_objs
    use debug_tools
    
    real(kind=rkind), dimension(:), intent(in) :: bod
    real(kind=rkind), dimension(2) :: a,b
    real(kind=rkind), dimension(:,:,:), allocatable :: inter
    real(kind=rkind), dimension(:,:), intent(in) :: domain
    integer(kind=ikind) :: zasah, i, l, p, j, k
    integer(kind=ikind), dimension(:), allocatable :: checked
    logical, dimension(:), allocatable :: valid
    logical :: true
    real(kind=rkind), dimension(:), allocatable :: smer
    
    select case(drutes_config%dimen)
      case(1)
        if ((domain(1,1) <= bod(1) .and. domain(2,1) >= bod(1)) .or. &
            (domain(1,1) >= bod(1) .and. domain(2,1) <= bod(1))) then
          true = .true.
        else
          true = .false.
        end if
      case(2)
        allocate(smer(ubound(domain,1)+1))
        allocate(inter(ubound(smer,1),ubound(domain,1),2))
        allocate(valid(ubound(domain,1)))
        allocate(checked(ubound(smer,1)))
        checked = 0
        do i=1, ubound(domain,1)
          if (i < ubound(domain,1)) then
            l = i
            p = i+1
          else
            l = i
            p = 1
          end if
          
          a = domain(l,:)
    
          b = domain(p,:)
          
          if (inline(domain(l,:), domain(p,:), bod)) then
            true = .true.
            RETURN
          end if
          do j=1, ubound(smer,1)
            smer(j) = rand() + 0.25
            call shoot(bod, smer(j), domain, inter(j,:,:), valid)
            zasah = 0
            do k=1, ubound(domain,1)
              if (valid(k)) then
                if (dist(a,inter(j,k,:)) > 10*epsilon(smer(1)) .and. dist(b,inter(j,k,:)) > 10*epsilon(smer
      (1))) then
                  zasah = zasah + 1
                else
                  print *, inter(j,k,:), a, b, dist(a,inter(j,k,:)) , dist(b,inter(j,k,:))
                  checked(j) = -1
                end if
              end if
            end do
            
            if (checked(j) /= -1) then
              if (modulo(zasah,2) /= 0 .and. zasah /= ubound(domain,1)) then
                checked(j) = 1
              end if
            end if
                  
              
          end do
        end do
        j=0
        do i=1, ubound(checked,1)
          if (checked(i) == 0) then
            true = .false.
            RETURN
          end if
          j = j + checked(i)
        end do
        
        if (j == -ubound(checked,1)) then
          print *, "bug in geom_tools::inside, contact developer with a full bug report"
          error stop
        end if
        
        true = .true.
      
      case default
        error stop "generated from geom_tools::inside"
    end select
subroutine, public geom_tools::interpolate (real(kind=rkind), dimension(:), intent(in) vals, real(kind=rkind), dimension(:), intent(out) points)
returns the solution values on gaussian nodes positions
Definition at line 187 of file geom_tools.f90.
References globals::drutes_config, globals::gauss_points, and plane_derivative().
    use typy
    use globals
    use global_objs
    use globals2d
    real(kind=rkind), dimension(:), intent(in) :: vals
    real(kind=rkind), dimension(:), intent(out) :: points
    integer(kind=ikind) :: i
    real(kind=rkind) :: xder, yder
    select case(drutes_config%dimen)
      case(1)
        do i=1, ubound(gauss_points%weight,1)
          points(i) = (vals(2) - vals(1))*gauss_points%point(i,1) + vals(1)
        end do
      case(2)
        call plane_derivative((/0.0_rkind, 0.0_rkind, vals(1)/), (/1.0_rkind, 0.0_rkind, vals(2)/), (/0.0
      _rkind, &
                         1.0_rkind, vals(3)/), xder, yder)
        do i=1, ubound(gauss_points%weight,1)
          points(i) = vals(1) + xder*gauss_points%point(i,1) + yder*gauss_points%point(i,2)
        end do
    end select
subroutine, public geom_tools::map1d2d (character(len=*), intent(in) filename)
Definition at line 1020 of file geom_tools.f90.
References readtools::comment(), core_tools::cut(), globals::elements, readtools::file_error(), core_tools::find_unit(), globals::nodes, and pde_objs::pde.
      use typy
      use global_objs
      use globals
      use pde_objs
      use core_tools
      use readtools
      use debug_tools
      
      character(len=*), intent(in) :: filename
      
      integer :: fileid, ierr
      integer(kind=ikind) :: i, counter, k, l, m, proc, j, ii
      real(kind=rkind), dimension(:,:), allocatable :: input
      real(kind=rkind) :: tmp, value, grad
      logical :: val_defined
      
      call find_unit(fileid)
      
      
      open(unit=fileid, file=cut(filename), action="read", iostat=ierr)
      
      if (ierr /= 0) then
        print *, "unable to open file with the vertical distribution of the initial condition, exiting...."
        print *, "called from map1d2d::drutes_init"
        error stop
      end if
      
      counter = 0
      
      do
        call comment(fileid)
        read(fileid, fmt=*, iostat=ierr) tmp
        if (ierr /= 0) then
          EXIT
        else
          counter = counter + 1
        end if
      end do
      
      allocate(input(counter, ubound(pde,1)+1))
      
      close(fileid)
      
      open(unit=fileid, file=cut(filename), action="read")
      
      do i=1, counter
        call fileread(input(i,:), fileid)
      end do
            
      do i=1, elements%kolik
        do j=1, ubound(elements%data,2)
          k = elements%data(i,j)
          l = nodes%edge(k)
          do proc=1, ubound(pde,1)
            m = pde(proc)%permut(k)
            if (m == 0) then
              if (l>100) then
                call pde(proc)%bc(l)%value_fnc(pde(proc), i, j, value)
                val_defined=.true.
              else
                print *, "runtime error, exited from map1d2d::drutes_init"
                error stop
              end if
            else
              val_defined=.false.
              do ii=1, ubound(input,1)-1
                if (nodes%data(k,2) >= input(ii,1) .and. nodes%data(k,2) <= input(ii+1,1)) then
                  grad = (input(ii+1,proc+1) - input(ii,proc+1))/(input(ii+1,1) - input(ii,1))
                  value = input(ii,proc+1) + grad*(nodes%data(k,2) - input(ii,1))
                  val_defined=.true.
                  if (isnan(value)) then
                    call file_error(fileid, "bad input file with initial conditions")
                  end if
                  EXIT
                end if
              end do
              if (.not. val_defined) then
                if (nodes%data(k,2) < minval(input(:,1))) then
                  value = input(minloc(input(:,1),1), proc)
                  val_defined=.true.
                end if
                if (nodes%data(k,2) < maxval(input(:,1))) then
                  value = input(maxloc(input(:,1),1), proc)
                  val_defined=.true.
                end if
                if (.not. val_defined) then
                  call file_error(fileid, "Have you covered the entire vertical profile with data for the
       initial condition?")
                end if
              end if
            end if
            pde(proc)%solution(k) = value
          end do
        end do
      end do
            
      close(fileid)
 
      
subroutine, public geom_tools::map1d2dj (class(pde_str), intent(inout) pde_loc, character(len=*), intent(in) filename)
Definition at line 1122 of file geom_tools.f90.
References readtools::comment(), core_tools::cut(), globals::drutes_config, globals::elements, readtools::file_error(), core_tools::find_unit(), globals::nodes, and pde_objs::pde.
Referenced by dual_por::dual_inicond(), re_constitutive::re_initcond(), and re_total::retot_initcond().
      use typy
      use global_objs
      use globals
      use pde_objs
      use core_tools
      use readtools
      use debug_tools
      
      character(len=*), intent(in) :: filename
      class(pde_str), intent(in out) :: pde_loc
      integer :: fileid, ierr
      integer(kind=ikind) :: i, counter, k, l, m, proc, j, ii, d
      real(kind=rkind), dimension(:,:), allocatable :: input
      real(kind=rkind) :: tmp, value, grad
      logical :: val_defined
      
      
      d = drutes_config%dimen
      call find_unit(fileid)
      
      
      open(unit=fileid, file=cut(filename), action="read", iostat=ierr)
      
      if (ierr /= 0) then
        print *, "unable to open file with the vertical distribution of the initial condition, exiting...."
        print *, "called from map1d2dJ::drutes_init"
        error stop
      end if
      
      counter = 0
      
      do
        call comment(fileid)
        read(fileid, fmt=*, iostat=ierr) tmp
        if (ierr /= 0) then
          EXIT
        else
          counter = counter + 1
        end if
      end do
      
      allocate(input(counter, 3))
      
      close(fileid)
      
      open(unit=fileid, file=cut(filename), action="read")
      
      do i=1, counter
        call fileread(input(i,:), fileid)
      end do
      do i=1, elements%kolik
        do j=1, ubound(elements%data,2)
          k = elements%data(i,j)
          l = nodes%edge(k)
            m = pde_loc%permut(k)
            if (m == 0) then
              if (l>100) then
                do ii=1, ubound(input,1)-1
    
                  if (nodes%data(k,d) >= input(ii,2) .and. nodes%data(k,d) <= input(ii+1,2)) then
                    grad = (input(ii+1,3) - input(ii,3))/(input(ii+1,2) - input(ii,2))
                    value = input(ii,3) + grad*(nodes%data(k,d) - input(ii,2))
                    val_defined=.true.
                    if (isnan(value)) then
                      call file_error(fileid, "bad input file with initial conditions")
                    end if
                    EXIT
                   end if
                 end do
                 if(.not. val_defined) then
                   call pde(proc)%bc(l)%value_fnc(pde(proc), i, j, value)
                   val_defined=.true.
                 end if
              else
                print *, "runtime error, exited from map1d2dJ::drutes_init"
                error stop
              end if
            else
              val_defined=.false.
              do ii=1, ubound(input,1)-1
                if (nodes%data(k,d) >= input(ii,2) .and. nodes%data(k,d) <= input(ii+1,2)) then
                  
                  grad = (input(ii+1,3) - input(ii,3))/(input(ii+1,2) - input(ii,2))
                  value = input(ii,3) + grad*(nodes%data(k,d) - input(ii,2))
                  val_defined=.true.
                  if (isnan(value)) then
                    call file_error(fileid, "bad input file with initial conditions")
                  end if
                  EXIT
                end if
              end do
              if (.not. val_defined) then
                if (nodes%data(k,d) < minval(input(:,2))) then
                  value = input(minloc(input(:,2),1),3)
                  val_defined=.true.
                end if
                if (nodes%data(k,d) > maxval(input(:,2))) then
                  value = input(maxloc(input(:,2),1), 3)
                  val_defined=.true.
                end if
                if (.not. val_defined) then
                  print *, nodes%data(k,d) ; stop
                  call file_error(fileid, "Have you covered the entire vertical profile with data for the
       initial condition?")
                end if
              end if
            end if
            pde_loc%solution(k) = value+nodes%data(k,d)
        end do
      end do
        
      close(fileid)
      
subroutine, public geom_tools::max_height (real(kind=rkind), dimension(:), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(in) c, real(kind=rkind), intent(out) height)
subroutine searching for the maximum height on triangle element
Parameters
in a input element edges
in b input element edges
in c input element edges
out height the maximal element height
Definition at line 841 of file geom_tools.f90.
References dist(), and najdi_bod().
    use typy
    real(kind=rkind), dimension(:), intent(in) :: a,b,c
    real(kind=rkind), intent(out) :: height
    
    real(kind=rkind), dimension(2) :: bod
    real(kind=rkind) :: ha,hb,hc
    real(kind=rkind) :: la, lb, lc
    
    
    call najdi_bod(a,b,c, bod)
    
    hc = dist(c,bod)
    
    lc = dist(a,b)
    la = dist(c,b)
    lb = dist(a,c)
    
    ha = la/lc*hc
    hb = lb/lc*hc
    
    height = max(ha,hb,hc)
! height = (ha + hb + hc)/3
    
  
subroutine, public geom_tools::najdi_bod (real(kind=rkind), dimension(:), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(in) c, real(kind=rkind), dimension(:), intent(out) bod)
subroutine seeking for the point which is on line identified by points a and b, and line between this point and c is rectangular to the line <a,b>
Parameters
in a element points
in b element points
in c element points
out bod the rectangular pointer
Definition at line 812 of file geom_tools.f90.
Referenced by max_height().
    use typy
    real(kind=rkind), dimension(:), intent(in) :: a,b,c
    real(kind=rkind), dimension(:), intent(out) :: bod
    real(kind=rkind) :: k, q, q2
    if (abs(b(1) - a(1)) > 100*epsilon(a(1))) then
      k = (b(2)-a(2))/(b(1)-a(1))
      q = a(2) - k*a(1)
      q2 = -c(1) - k*c(2)
      bod(2) = (-k*q2+q)/(k*k+1)
      bod(1) = -k*bod(2)-q2
    else
      bod(1) = a(1)
      bod(2) = c(2)
    end if
      
subroutine, public geom_tools::plane_derivative (real(kind=rkind), dimension(:), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(in) c, real(kind=rkind), intent(out) xder, real(kind=rkind), intent(out) yder)
specify the x and y derivates of a plane defined by three points
Parameters
in a 1st point of the plane
in b 2nd point of the plane
in c 3rd point of the plane
out xder resulting x derivate
out yder resulting y derivate
Definition at line 216 of file geom_tools.f90.
Referenced by re_constitutive::derkz(), feminittools::feminit(), feminittools::init_integ(), interpolate(), and decomposer::set_subdomains().
    use typy
    real(kind=rkind), dimension(:), intent(in) :: a
    real(kind=rkind), dimension(:), intent(in) :: b
    real(kind=rkind), dimension(:), intent(in) :: c
    real(kind=rkind), intent(out) :: xder
    real(kind=rkind), intent(out) :: yder
    !-------local variables--------------
    real(kind=rkind), dimension(3) :: u
    real(kind=rkind), dimension(3) :: v
    real(kind=rkind), dimension(3) :: n
    integer(kind=ikind) :: i
    real(kind=rkind) :: reps
    reps = epsilon(reps)
    !check if the plane is not horizontal
    if (abs(a(3) - b(3)) < reps*(abs(a(3))-abs(b(3))) .and. &
        abs(a(3) - c(3)) < reps*(abs(a(3))-abs(c(3))) .and. &
        abs(b(3) - c(3)) < reps*(abs(b(3))-abs(c(3)))) then
      xder = 0.0_rkind
      yder = 0.0_rkind
      RETURN
    else
      CONTINUE
    end if
    !creates the plane vectors
    do i=1,3
      u(i) = a(i) - b(i)
      v(i) = a(i) - c(i)
    end do
    ! the normal plane vector is defined as
    n(1) = u(2)*v(3) - v(2)*u(3)
    n(2) = u(3)*v(1) - v(3)*u(1)
    n(3) = u(1)*v(2) - v(1)*u(2)
    ! finally the derivate is as follows, the horizontality has been already checked
    ! the verticality check
    if (abs(n(3)) < 1e2*reps) then
      print *, "the mesh is wrong, base function can't be vertical"
      print *, abs(n(3))
      error stop
    end if
    xder = -n(1)/n(3)
    yder = -n(2)/n(3)
    
subroutine, private geom_tools::shoot (real(kind=rkind), dimension(:), intent(in) bod, real(kind=rkind), intent(in) k, real(kind=rkind), dimension(:,:), intent(in) domain, real(kind=rkind), dimension(:,:), intent(out) inter, logical, dimension(:), intent(out) valid) [private]
Definition at line 473 of file geom_tools.f90.
References inline().
Referenced by inside().
    use typy
    real(kind=rkind), dimension(:), intent(in) :: bod
    real(kind=rkind), intent(in) :: k
    real(kind=rkind), dimension(:,:), intent(in) :: domain
    real(kind=rkind), dimension(:,:), intent(out) :: inter
    logical, dimension(:), intent(out) :: valid
    
    real(kind=rkind) :: q, qq, kk
    real(kind=rkind), dimension(2) :: a,b
    integer(kind=ikind) :: l,p, i
    
    q = bod(2) - k*bod(1)
    
    do i=1, ubound(domain,1)
      if (i < ubound(domain,1)) then
        l = i
        p = i+1
      else
        l = i
        p = 1
      end if
      
      a = domain(l,:)
    
      b = domain(p,:)
      
      if (abs(a(1)-b(1)) > 10*epsilon(a(1))) then
        kk = (b(2) - a(2))/(b(1)-a(1))
        qq = b(2) - b(1)*kk
        if (abs(k-kk) > 10*epsilon(k)) then
          inter(i,1) = (qq-q)/(k-kk)
          inter(i,2) = k*inter(i,1) + q
        else
          if (abs(q-qq) > 10*epsilon(q)) then
            inter(i,:) = (/huge(k), huge(k)/)
          else
            if (a(1) > b(1)) then
              inter(i,:) = a
            else
              inter(i,:) = b
            end if
          end if
        end if
      else
        inter(i,1) = a(1)
        inter(i,2) = k*inter(i,1) + q
      end if
      if (inline(a,b, inter(i,:)) .and. inter(i,1) > bod(1)) then
        valid(i) = .true.
      else
        valid(i) = .false.
      end if
    end do
    
 
        
subroutine, public geom_tools::solve_bisect (real(kind=rkind), intent(in) xmin, real(kind=rkind), intent(in) xmax, f, real(kind=rkind), intent(in) reps, integer, intent(out) ierr, real(kind=rkind), intent(out) solution)
bisecton method searching for a root of function f on defined intervals xmin and xmax
Parameters
in xmin a interval where the root is searched
in xmax a interval where the root is searched
in reps accuracy
out ierr error code output
out solution the result
Definition at line 612 of file geom_tools.f90.
References core_tools::write_log().
Referenced by re_constitutive::init_zones().
real(kind=rkind) function, public geom_tools::triarea (real(kind=rkind), dimension(:), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(in) c)
Parameters
in a triangle points
in b triangle points
in c triangle points
Returns
result
Definition at line 533 of file geom_tools.f90.
Referenced by feminittools::feminit().
    use typy
    real(kind=rkind), dimension(:), intent(in) :: a,b,c
    real(kind=rkind) :: area
    real(kind=rkind) :: la,lb,lc
    
    lc = sqrt((a(1) - b(1))**2 + (a(2) - b(2))**2)
    
    lb = sqrt((a(1) - c(1))**2 + (a(2) - c(2))**2)
    
    la = sqrt((b(1) - c(1))**2 + (b(2) - c(2))**2)
    
    area = 0.25*sqrt((la+lb+lc)*(lb + lc - la)*(lc + la - lb)*(la + lb - lc))
  