globals Module Reference
Variables
type(version), public version_id
version id variable
integer, public file_global
file units ----------------------------------------------------------------------
integer, public file_mesh
integer, public file_itcg
integer, public file_wwwglob
integer, public logfile
log file unit
integer, public debugfile
debug file unit (put there whatever you like)
integer, public terminal = 6
terminal ID, the print_level sets its value
logical, public terminal_assigned = .false.
real(kind=rkind), dimension(:,:), allocatable, public gauss_integ
array of the gauss quadrature formula roots
type(configuration), public drutes_config
program configuration
integer(kind=ikind), public max_itcount
maximal number of iterations of Picard method for nonlinear problems
real(kind=rkind), public iter_criterion
Picard iteration threshold value.
real(kind=rkind), public init_dt
an intial dt
real(kind=rkind), public end_time
simulation end time
real(kind=rkind), public dtmin
minimal dt
real(kind=rkind), public dtmax
maximal dt
character(len=5), public time_units
time units
real(kind=rkind), public maxpress
maximal pressure to precalculate (tabelarise) the unsaturated hydraulic conductivity value
integer(kind=ikind) outer_boundaries
number of outer boundaries
integer(kind=ikind), public print_level
output print level 0 = standard output 1 = screen goes to out/screen.log -1 = does goes to /dev/null, not suitable for m$ hell
integer, public info_level
level of informations that are supplied to the user 0 the default level, only information about the time step solution is displayed 1 the detailed information about each iteration is displayed 2 extra detailed, even the information about the iterations of the conjugate gradient solver is displayed
type(observe_time_str), dimension(:), allocatable, public observe_time
observation time array
type(observe_info_str), public observe_info
type(observation), dimension(:), allocatable, public observation_array
the number of observation points each row defines each point, the row is labeled in [observation] structure as [xyz] each row has an integer value, this value defines the element number to which this observation point belongs
type(measured), dimension(:), allocatable, public measured_pts
the number of points with observation data
real(kind=rkind), public backup_time
code defining the example type in format XYZ 10 - Richards equation in single regime and 1D 11 - Richards equation in dual regime and 1D 20 - Richards equation in single regime and 2D 21 - Richards equation in dual regime and 2D 100 - Richards equation and transport ADE equation in single regime and 1D 110 - Richards equation and transport ADE equation in dual regime and 1D 200 - Richards equation and transport ADE equation in single regime and 2D 210 - Richards equation and transport ADE equation in dual regime and 2D
integer(kind=ikind), public backup_runs
stores the number of performed backups
character(len=256), public dir_name
current directory name
real, public start_time
CPU start time value.
integer(kind=ikind), public solver_call
number of linear algebra solver calls
type(node), public nodes
type(element), public elements
real(kind=rkind), dimension(:,:), allocatable, public cap_mat
local capacity matrix and local stiffness matrix
real(kind=rkind), dimension(:,:), allocatable, public stiff_mat
real(kind=rkind), dimension(:), allocatable, public bside
local matrix vector
type(integnodes), public gauss_points
points for gauss quadrature on line
 component point is node's coordinate
 component weight is gaussian weight
 this array is derived for the unit length 1 and interval <0,1>, thus it differs from the init_gauss procedure, see init_gauss documentation
integer(kind=ikind), public integ_method
code defining gauss quadrature integration method 10 - 1 point formula, 20 - 2 point formula 30 - 3 point formula 40 - 4 point formula 50 - 5 point formula 60 - 6 point formula 70 - 7 point formula 90 - 9 point formula (in 2-dimensions derived from 3 point formula, ask Michal Kuraz :)) 120 - 12 point formula
type(dirglob_str), public dirglob
defines directory with global configuration files
real(kind=rkind), dimension(:,:), allocatable, public base_fnc
values of base function on gauss quadrature nodes
real(kind=rkind), public time
the total time value
real(kind=rkind), public time_step
time step value
real(kind=rkind), public time4solve
equals to the actual time level plus time step which is being processed
real(kind=rkind), public dtprev
previous time step
real(kind=rkind), public minimal_dt
minimal adjusted time step
type(extsmtx), save, public spmatrix
sparse matrix
type(extsmtx), save, public spmatrix2
sparse matrix
integer(kind=ikind), public global_row_id
current position in the global stiffness matrix
logical, public debug_print =.false.
logical, public debugmode
logical, public coupled_problem
integer(kind=ikind), public postpro_run
the amount of postprocess runs
integer(kind=ikind), public postpro_dec
the amount of decimal numbers in postproces runs
character(len=1024), public backup_file
real(kind=rkind), dimension(:,:), allocatable integnode_now
real(kind=rkind), dimension(:,:), allocatable integnode_prev
real(kind=rkind), dimension(:), allocatable elnode_prev
logical, public www = .false.
logical, public optim =.false.
real(kind=rkind), public cpu_max_time
logical, public cpu_time_limit = .false.
integer(kind=ikind), public itcum
Variable Documentation
character(len=1024), public globals::backup_file
Definition at line 172 of file globals.f90.
Referenced by feminittools::feminit(), and read_inputs::read_global().
  character(len=1024), public :: backup_file
integer(kind=ikind), public globals::backup_runs
stores the number of performed backups
Definition at line 97 of file globals.f90.
Referenced by drutes_init::set_global_vars().
  integer(kind=ikind), public :: backup_runs
real(kind=rkind), public globals::backup_time
code defining the example type in format XYZ 10 - Richards equation in single regime and 1D 11 - Richards equation in dual regime and 1D 20 - Richards equation in single regime and 2D 21 - Richards equation in dual regime and 2D 100 - Richards equation and transport ADE equation in single regime and 1D 110 - Richards equation and transport ADE equation in dual regime and 1D 200 - Richards equation and transport ADE equation in single regime and 2D 210 - Richards equation and transport ADE equation in dual regime and 2D
the time period in hours between each backup
Definition at line 95 of file globals.f90.
  real(kind=rkind), public :: backup_time
real(kind=rkind), dimension(:,:), allocatable, public globals::base_fnc
values of base function on gauss quadrature nodes
Definition at line 135 of file globals.f90.
Referenced by stiffmat::build_stiff_np(), capmat::impl_euler_np_diag(), capmat::impl_euler_np_nondiag(), and feminittools::init_integ().
  real(kind=rkind), dimension(:,:), allocatable, public :: base_fnc
real(kind=rkind), dimension(:), allocatable, public globals::bside
local matrix vector
Definition at line 110 of file globals.f90.
Referenced by stiffmat::build_bvect(), feminittools::feminit(), capmat::impl_euler_np_diag(), capmat::impl_euler_np_nondiag(), and fem_tools::in2global().
  real(kind=rkind), dimension(:), allocatable, public :: bside
real(kind=rkind), dimension(:,:), allocatable, public globals::cap_mat
local capacity matrix and local stiffness matrix
Definition at line 108 of file globals.f90.
Referenced by femmat::assemble_mat(), feminittools::feminit(), capmat::impl_euler_np_diag(), capmat::impl_euler_np_nondiag(), schwarz_dd::locmat_assembler(), schwarz_dd2subcyc::locmat_assembler(), and capmat::steady_state_int().
  real(kind=rkind), dimension(:,:), allocatable, public :: cap_mat, stiff_mat
logical, public globals::coupled_problem
Definition at line 164 of file globals.f90.
  logical, public :: coupled_problem
real(kind=rkind), public globals::cpu_max_time
Definition at line 178 of file globals.f90.
Referenced by drutes_init::get_cmd_options(), and fem::solve_pde().
  real(kind=rkind), public :: cpu_max_time
logical, public globals::cpu_time_limit = .false.
Definition at line 179 of file globals.f90.
Referenced by drutes_init::get_cmd_options(), and fem::solve_pde().
  logical, public :: cpu_time_limit = .false.
logical, public globals::debug_print =.false.
Definition at line 160 of file globals.f90.
  logical, public :: debug_print=.false.
integer, public globals::debugfile
debug file unit (put there whatever you like)
Definition at line 29 of file globals.f90.
Referenced by drutes_init::parse_globals().
  integer, public :: debugfile
logical, public globals::debugmode
Definition at line 162 of file globals.f90.
Referenced by drutes_init::parse_globals(), and read_inputs::read_global().
  logical, public :: debugmode
character(len=256), public globals::dir_name
current directory name
Definition at line 99 of file globals.f90.
Referenced by drutes_init::get_cmd_options(), main(), and fem::terminal_info().
  character(len=256), public :: dir_name
type(dirglob_str), public globals::dirglob
defines directory with global configuration files
Definition at line 132 of file globals.f90.
Referenced by drutes_init::get_cmd_options(), and drutes_init::parse_globals().
  type(dirglob_str), public :: dirglob
type(configuration), public globals::drutes_config
program configuration
Definition at line 39 of file globals.f90.
Referenced by decomp_tools::addlevel(), ade_fnc::ade_icond(), ade_reader::ade_read(), ade_fnc::adedispersion(), re_pointers::allrepointers(), stiffmat::build_stiff_np(), re_constitutive::convection_rerot(), simplelinalg::diag_precond(), geom_tools::dist(), re_constitutive::dmualem_dh(), re_constitutive::dmualem_dh_tab(), re_dual_bc::dual_freedrainage(), dual_por::dual_inicond(), dual_tab::dual_tabvalues(), feminittools::feminit(), geom_tools::find_neighbours(), geom_tools::getcoor(), pde_objs::getgradp1(), geom_tools::getnormal(), pde_objs::getvalp1loc(), heat_fnc::heat_conduct(), heat_reader::heat_read(), fem_tools::icond4neumann(), fem_tools::in2global(), decomposer::init_decomp(), feminittools::init_integ(), drutes_init::init_observe(), decomposer::init_subdomain(), re_constitutive::init_zones(), geom_tools::inside(), geom_tools::interpolate(), main(), postpro::make_print(), geom_tools::map1d2dj(), core_tools::mesh_allocater(), drutes_init::open_obs_unit(), drutes_init::parse_globals(), decomp_tools::print_domains(), decomp_tools::print_elements_dd(), postpro::print_scilab(), re_constitutive::rcza_check(), re_constitutive::rcza_check_old(), re_constitutive::re_atmospheric(), re_constitutive::re_dirichlet_height_bc(), re_dual_reader::re_dual_var(), re_dual_pointers::re_fracture(), re_constitutive::re_initcond(), re_dual_pointers::re_matrix(), re_constitutive::re_neumann_bc(), re_pointers::re_rot(), re_pointers::re_std(), read_inputs::read_global(), objfnc::reader(), re_reader::res_read(), re_total::retot_dirichlet_bc(), re_total::retot_dirichlet_height_bc(), re_total::retot_freedrainage(), re_total::retot_initcond(), re_total::retot_seepage(), drutes_init::set_global_vars(), manage_pointers::set_pointers(), readtools::set_tensor(), fem::solve_pde(), femmat::solve_picard(), feminittools::surface_integ(), re_constitutive::tabvalues(), and postpro::write_obs().
  type(configuration), public :: drutes_config
real(kind=rkind), public globals::dtmax
maximal dt
Definition at line 51 of file globals.f90.
Referenced by fem::evol_dt(), fem::exitme(), read_inputs::read_global(), schwarz_dd_time_test::schwarz_picard_tt(), and fem::solve_pde().
  real(kind=rkind), public :: dtmax
real(kind=rkind), public globals::dtmin
minimal dt
Definition at line 49 of file globals.f90.
Referenced by fem::evol_dt(), fem::exitme(), read_inputs::read_global(), and schwarz_dd_time_test::schwarz_picard_tt().
  real(kind=rkind), public :: dtmin
real(kind=rkind), public globals::dtprev
previous time step
Definition at line 143 of file globals.f90.
Referenced by fem::evol_dt(), and fem::terminal_info().
  real(kind=rkind), public :: dtprev
type(element), public globals::elements
Definition at line 106 of file globals.f90.
Referenced by decomp_tools::addlevel(), ade_fnc::ade_dirichlet(), ade_fnc::ade_icond(), ade_fnc::ade_neumann(), ade_reader::ade_read(), femmat::assemble_mat(), boussfnc::bouss_bc(), boussfnc::boussicond(), stiffmat::build_bvect(), stiffmat::build_stiff_np(), re_dual_bc::dual_atmospheric(), re_dual_bc::dual_freedrainage(), dual_por::dual_inicond(), re_dual_bc::dual_neumann_bc(), feminittools::feminit(), geom_tools::find_neighbours(), geom_tools::get_layer(), geom_tools::get_nz(), geom_tools::getcoor(), pde_objs::getgradp1(), pde_objs::getvalp1loc(), heat_fnc::heat_dirichlet(), heat_fnc::heat_icond(), heat_fnc::heat_neumann(), heat_reader::heat_read(), fem_tools::icond4neumann(), capmat::impl_euler_np_diag(), capmat::impl_euler_np_nondiag(), fem_tools::in2global(), re_dual_bc::inf_neumann_bc(), decomp_tools::init_addlevel(), decomposer::init_decomp(), drutes_init::init_observe(), decomposer::init_subdomain(), schwarz_dd::locmat_assembler(), schwarz_dd2subcyc::locmat_assembler(), main(), geom_tools::map1d2d(), geom_tools::map1d2dj(), core_tools::mesh_allocater(), decomp_tools::print_domains(), decomp_tools::print_elements_dd(), postpro::print_gmsh(), postpro::print_pure(), postpro::print_scilab(), re_constitutive::rcza_check(), re_constitutive::re_atmospheric(), re_constitutive::re_dirichlet_bc(), re_constitutive::re_dirichlet_height_bc(), re_constitutive::re_initcond(), re_constitutive::re_neumann_bc(), read_inputs::read_2dmesh_gmsh(), read_inputs::read_2dmesh_t3d(), read_inputs::read_scilab(), re_reader::res_read(), femmat::results_extractor(), re_total::retot_atmospheric(), re_total::retot_dirichlet_bc(), re_total::retot_dirichlet_height_bc(), re_total::retot_freedrainage(), re_total::retot_initcond(), re_total::retot_neumann_bc(), re_total::retot_seepage(), re_total::retot_seepageface(), feminittools::search_bnd_nodes(), subcycling::search_error_cluster(), schwarz_dd::search_error_cluster(), schwarz_dd2subcyc::search_error_cluster(), schwarz_dd_time_test::search_error_cluster_tt(), feminittools::set_boundary(), decomposer::set_subdomains(), re_constitutive::setmatflux(), simegen::simegen1d(), simegen::simegen2d(), feminittools::surface_integ(), and postpro::write_obs().
  type(element), public :: elements
real(kind=rkind), dimension(:), allocatable globals::elnode_prev
Definition at line 175 of file globals.f90.
Referenced by femmat::assemble_mat(), feminittools::feminit(), capmat::impl_euler_np_diag(), capmat::impl_euler_np_nondiag(), schwarz_dd::locmat_assembler(), and schwarz_dd2subcyc::locmat_assembler().
  real(kind=rkind), dimension(:), allocatable :: elnode_prev
real(kind=rkind), public globals::end_time
simulation end time
Definition at line 47 of file globals.f90.
Referenced by drutes_init::init_obstimes(), read_inputs::read_global(), readtools::readbcvals(), fem::solve_pde(), and printtools::time2finish().
  real(kind=rkind), public :: end_time
integer, public globals::file_global
file units ----------------------------------------------------------------------
Definition at line 25 of file globals.f90.
Referenced by drutes_init::parse_globals(), and read_inputs::read_global().
  integer, public :: file_global, file_mesh, file_itcg, file_wwwglob
integer, public globals::file_itcg
Definition at line 25 of file globals.f90.
Referenced by drutes_init::parse_globals(), and femmat::solve_picard().
integer, public globals::file_mesh
Definition at line 25 of file globals.f90.
Referenced by drutes_init::parse_globals(), read_inputs::read_1dmesh_int(), read_inputs::read_2dmesh_gmsh(), read_inputs::read_2dmesh_int(), read_inputs::read_2dmesh_t3d(), and simegen::simegen1d().
integer, public globals::file_wwwglob
Definition at line 25 of file globals.f90.
Referenced by drutes_init::parse_globals(), and read_inputs::read_global().
real(kind=rkind), dimension(:,:), allocatable, public globals::gauss_integ
array of the gauss quadrature formula roots
Definition at line 34 of file globals.f90.
  real(kind=rkind), dimension(:,:), allocatable, public :: gauss_integ
type(integnodes), public globals::gauss_points
points for gauss quadrature on line
 component point is node's coordinate
 component weight is gaussian weight
 this array is derived for the unit length 1 and interval <0,1>, thus it differs from the init_gauss procedure, see init_gauss documentation
Definition at line 116 of file globals.f90.
Referenced by stiffmat::build_bvect(), stiffmat::build_stiff_np(), geom_tools::getcoor(), pde_objs::getvalp1loc(), capmat::impl_euler_np_diag(), capmat::impl_euler_np_nondiag(), feminittools::init_integ(), geom_tools::interpolate(), and postpro::print_scilab().
  type(integnodes), public :: gauss_points
integer(kind=ikind), public globals::global_row_id
current position in the global stiffness matrix
Definition at line 157 of file globals.f90.
  integer(kind=ikind), public :: global_row_id
integer, public globals::info_level
level of informations that are supplied to the user 0 the default level, only information about the time step solution is displayed 1 the detailed information about each iteration is displayed 2 extra detailed, even the information about the iterations of the conjugate gradient solver is displayed
Definition at line 69 of file globals.f90.
  integer, public :: info_level
real(kind=rkind), public globals::init_dt
an intial dt
Definition at line 45 of file globals.f90.
Referenced by read_inputs::read_global(), and fem::solve_pde().
  real(kind=rkind), public :: init_dt
integer(kind=ikind), public globals::integ_method
code defining gauss quadrature integration method 10 - 1 point formula, 20 - 2 point formula 30 - 3 point formula 40 - 4 point formula 50 - 5 point formula 60 - 6 point formula 70 - 7 point formula 90 - 9 point formula (in 2-dimensions derived from 3 point formula, ask Michal Kuraz :)) 120 - 12 point formula
Definition at line 128 of file globals.f90.
Referenced by feminittools::init_integ(), and read_inputs::read_global().
  integer(kind=ikind), public :: integ_method
real(kind=rkind), dimension(:,:), allocatable globals::integnode_now
Definition at line 174 of file globals.f90.
Referenced by feminittools::init_integ().
  real(kind=rkind), dimension(:,:), allocatable :: integnode_now, integnode_prev
real(kind=rkind), dimension(:,:), allocatable globals::integnode_prev
Definition at line 174 of file globals.f90.
Referenced by feminittools::init_integ().
integer(kind=ikind), public globals::itcum
Definition at line 182 of file globals.f90.
Referenced by fem::solve_pde(), and fem::terminal_info().
  integer(kind=ikind), public :: itcum
real(kind=rkind), public globals::iter_criterion
Picard iteration threshold value.
Definition at line 43 of file globals.f90.
Referenced by fem::exitme(), read_inputs::read_global(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarz_picard_tt(), schwarz_dd_time_test::schwarzloc(), subcycling::search_error_cluster(), schwarz_dd::search_error_cluster(), schwarz_dd2subcyc::search_error_cluster(), schwarz_dd_time_test::search_error_cluster_tt(), femmat::solve_picard(), and subcycling::subcyc_schwarz().
  real(kind=rkind), public :: iter_criterion
integer, public globals::logfile
log file unit
Definition at line 27 of file globals.f90.
Referenced by drutes_init::parse_globals(), and core_tools::write_log().
  integer, public :: logfile
integer(kind=ikind), public globals::max_itcount
maximal number of iterations of Picard method for nonlinear problems
Definition at line 41 of file globals.f90.
Referenced by fem::evol_dt(), fem::exitme(), read_inputs::read_global(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarzloc(), femmat::solve_picard(), and subcycling::subcyc_schwarz().
  integer(kind=ikind), public :: max_itcount
real(kind=rkind), public globals::maxpress
maximal pressure to precalculate (tabelarise) the unsaturated hydraulic conductivity value
Definition at line 55 of file globals.f90.
Referenced by dual_tab::dual_tabvalues(), re_constitutive::init_zones(), re_dual_reader::re_dual_var(), re_reader::res_read(), and re_constitutive::tabvalues().
  real(kind=rkind), public :: maxpress
type(measured), dimension(:), allocatable, public globals::measured_pts
the number of points with observation data
Definition at line 82 of file globals.f90.
Referenced by drutes_init::init_measured(), read_inputs::read_global(), and readtools::readbcvals().
  type(measured), dimension(:), allocatable, public :: measured_pts
real(kind=rkind), public globals::minimal_dt
minimal adjusted time step
Definition at line 146 of file globals.f90.
Referenced by main(), and fem::solve_pde().
  real(kind=rkind), public :: minimal_dt
type(node), public globals::nodes
Definition at line 105 of file globals.f90.
Referenced by decomp_tools::addlevel(), ade_fnc::ade_dirichlet(), ade_fnc::ade_icond(), ade_fnc::ade_neumann(), femmat::assemble_mat(), boussfnc::bouss_bc(), boussfnc::boussicond(), re_dual_bc::dual_atmospheric(), dual_por::dual_inicond(), re_dual_bc::dual_neumann_bc(), feminittools::feminit(), geom_tools::get_layer(), geom_tools::get_nz(), geom_tools::getcoor(), pde_objs::getgradp1(), pde_objs::getvalp1loc(), heat_fnc::heat_dirichlet(), heat_fnc::heat_icond(), heat_fnc::heat_neumann(), heat_reader::heat_read(), fem_tools::icond4neumann(), re_total::iconddebouss(), fem_tools::in2global(), re_dual_bc::inf_neumann_bc(), decomposer::init_decomp(), drutes_init::init_measured(), drutes_init::init_observe(), schwarz_dd::locmat_assembler(), schwarz_dd2subcyc::locmat_assembler(), main(), decomposer::make_quadmesh(), geom_tools::map1d2d(), geom_tools::map1d2dj(), core_tools::mesh_allocater(), drutes_init::pde_constructor(), decomp_tools::print_domains(), decomp_tools::print_elements_dd(), postpro::print_gmsh(), postpro::print_pure(), postpro::print_scilab(), re_constitutive::rcza_check(), re_constitutive::re_atmospheric(), re_constitutive::re_dirichlet_bc(), re_constitutive::re_dirichlet_height_bc(), re_constitutive::re_initcond(), re_constitutive::re_neumann_bc(), read_inputs::read_2dmesh_gmsh(), read_inputs::read_2dmesh_t3d(), read_inputs::read_scilab(), readtools::readbcvals(), feminittools::reorder(), femmat::results_extractor(), subcycling::results_extractor(), schwarz_dd::results_extractor(), schwarz_dd_time_test::results_extractor(), re_total::retot_atmospheric(), re_total::retot_dirichlet_bc(), re_total::retot_dirichlet_height_bc(), re_total::retot_initcond(), re_total::retot_neumann_bc(), re_total::retot_seepage(), feminittools::search_bnd_nodes(), feminittools::set_boundary(), decomposer::set_subdomains(), re_constitutive::setmatflux(), simegen::simegen1d(), simegen::simegen2d(), and feminittools::surface_integ().
  type(node), public :: nodes
type(observation), dimension(:), allocatable, public globals::observation_array
the number of observation points each row defines each point, the row is labeled in [observation] structure as [xyz] each row has an integer value, this value defines the element number to which this observation point belongs
Definition at line 80 of file globals.f90.
Referenced by geom_tools::getcoor(), pde_objs::getgradp1(), pde_objs::getvalp1loc(), drutes_init::init_observe(), drutes_init::pde_constructor(), read_inputs::read_global(), objfnc::reader(), and postpro::write_obs().
  type(observation), dimension(:), allocatable, public :: observation_array
type(observe_info_str), public globals::observe_info
Definition at line 73 of file globals.f90.
Referenced by fem::evol_dt(), drutes_init::init_obstimes(), postpro::make_print(), and read_inputs::read_global().
  type(observe_info_str), public :: observe_info
type(observe_time_str), dimension(:), allocatable, public globals::observe_time
observation time array
Definition at line 71 of file globals.f90.
Referenced by fem::evol_dt(), drutes_init::init_obstimes(), read_inputs::read_global(), and fem::solve_pde().
  type(observe_time_str), dimension(:), allocatable, public :: observe_time
logical, public globals::optim =.false.
Definition at line 177 of file globals.f90.
Referenced by fem::exitme(), and drutes_init::get_cmd_options().
  logical, public :: optim=.false.
integer(kind=ikind) globals::outer_boundaries
number of outer boundaries
Definition at line 57 of file globals.f90.
Referenced by drutes_init::init_measured().
  integer(kind=ikind) :: outer_boundaries
integer(kind=ikind), public globals::postpro_dec
the amount of decimal numbers in postproces runs
Definition at line 170 of file globals.f90.
Referenced by postpro::make_print(), and drutes_init::set_global_vars().
  integer(kind=ikind), public :: postpro_dec
integer(kind=ikind), public globals::postpro_run
the amount of postprocess runs
Definition at line 168 of file globals.f90.
Referenced by postpro::make_print(), postpro::print_gmsh(), and drutes_init::set_global_vars().
  integer(kind=ikind), public :: postpro_run
integer(kind=ikind), public globals::print_level
output print level 0 = standard output 1 = screen goes to out/screen.log -1 = does goes to /dev/null, not suitable for m$ hell
Definition at line 63 of file globals.f90.
Referenced by read_inputs::read_global(), and drutes_init::set_global_vars().
  integer(kind=ikind), public :: print_level
integer(kind=ikind), public globals::solver_call
number of linear algebra solver calls
Definition at line 104 of file globals.f90.
Referenced by drutes_init::set_global_vars().
  integer(kind=ikind), public :: solver_call
type(extsmtx), save, public globals::spmatrix
sparse matrix
Definition at line 152 of file globals.f90.
Referenced by femmat::assemble_mat(), feminittools::feminit(), and femmat::solve_picard().
  type(extsmtx), public, save :: spmatrix
type(extsmtx), save, public globals::spmatrix2
sparse matrix
Definition at line 154 of file globals.f90.
  type(extsmtx), public, save :: spmatrix2
real, public globals::start_time
CPU start time value.
Definition at line 101 of file globals.f90.
Referenced by main(), and printtools::time2finish().
  real, public :: start_time
real(kind=rkind), dimension(:,:), allocatable, public globals::stiff_mat
Definition at line 108 of file globals.f90.
Referenced by femmat::assemble_mat(), stiffmat::build_bvect(), stiffmat::build_stiff_np(), feminittools::feminit(), fem_tools::in2global(), schwarz_dd::locmat_assembler(), and schwarz_dd2subcyc::locmat_assembler().
integer, public globals::terminal = 6
terminal ID, the print_level sets its value
Definition at line 31 of file globals.f90.
Referenced by ade_reader::ade_read(), readtools::file_error(), drutes_init::get_cmd_options(), postpro::get_ram_use(), re_constitutive::init_zones(), main(), drutes_init::parse_globals(), debug_tools::print_int_matrix(), debug_tools::print_int_vector(), debug_tools::print_logical_array(), debug_tools::print_quadpnt(), debug_tools::print_real_matrix(), debug_tools::print_real_vector(), debug_tools::print_real_vector4(), debug_tools::print_smartarray_i(), debug_tools::print_smartmatrix_i(), debug_tools::print_sparse_matrix(), printtools::printtime(), printtools::progressbar(), readtools::read_int(), readtools::read_int_array(), readtools::read_int_std(), readtools::read_logical(), readtools::read_real(), readtools::read_real_array(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarz_picard_tt(), schwarz_dd2subcyc::schwarz_subcyc(), schwarz_dd_time_test::schwarzloc(), drutes_init::set_global_vars(), fem::solve_pde(), subcycling::subcyc_schwarz(), fem::terminal_info(), printtools::time2finish(), debug_tools::wait(), and core_tools::write_log().
  integer, public :: terminal = 6
logical, public globals::terminal_assigned = .false.
Definition at line 32 of file globals.f90.
Referenced by drutes_init::get_cmd_options(), and drutes_init::set_global_vars().
  logical, public :: terminal_assigned = .false.
real(kind=rkind), public globals::time
the total time value
Definition at line 137 of file globals.f90.
Referenced by ade_fnc::ade_dirichlet(), ade_fnc::ade_neumann(), boussfnc::bouss_adv(), boussfnc::bouss_bc(), subcycling::domains_solved(), re_dual_bc::dual_atmospheric(), re_dual_bc::dual_neumann_bc(), fem::evol_dt(), pde_objs::getvalp1(), heat_fnc::heat_dirichlet(), heat_fnc::heat_neumann(), re_dual_bc::inf_neumann_bc(), postpro::make_print(), postpro::print_gmsh(), postpro::print_scilab(), re_constitutive::re_atmospheric(), re_constitutive::re_dirichlet_bc(), re_constitutive::re_dirichlet_height_bc(), re_constitutive::re_neumann_bc(), read_inputs::read_scilab(), re_total::retot_atmospheric(), re_total::retot_dirichlet_bc(), re_total::retot_dirichlet_height_bc(), re_total::retot_neumann_bc(), schwarz_dd::schwarz_picard(), schwarz_dd2subcyc::schwarz_subcyc(), schwarz_dd_time_test::schwarzloc(), decomposer::set_subdomains(), fem::solve_pde(), femmat::solve_picard(), subcycling::subcyc_schwarz(), fem::terminal_info(), printtools::time2finish(), and postpro::write_obs().
  real(kind=rkind), public :: time
real(kind=rkind), public globals::time4solve
equals to the actual time level plus time step which is being processed
Definition at line 141 of file globals.f90.
  real(kind=rkind), public :: time4solve
real(kind=rkind), public globals::time_step
time step value
Definition at line 139 of file globals.f90.
Referenced by femmat::assemble_mat(), subcycling::domains_solved(), fem::evol_dt(), fem::exitme(), pde_objs::getvalp1(), fem_tools::in2global(), schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarz_picard_tt(), schwarz_dd2subcyc::schwarz_subcyc(), schwarz_dd_time_test::schwarzloc(), fem::solve_pde(), subcycling::subcyc_schwarz(), fem::terminal_info(), and postpro::write_obs().
  real(kind=rkind), public :: time_step
character(len=5), public globals::time_units
time units
Definition at line 53 of file globals.f90.
Referenced by postpro::print_scilab(), and read_inputs::read_global().
  character(len=5), public :: time_units
type(version), public globals::version_id
version id variable
Definition at line 23 of file globals.f90.
Referenced by drutes_init::get_cmd_options(), and main().
  type(version), public :: version_id
logical, public globals::www = .false.
Definition at line 176 of file globals.f90.
Referenced by fem::exitme(), drutes_init::get_cmd_options(), postpro::make_print(), drutes_init::parse_globals(), read_inputs::read_global(), re_reader::res_read(), fem::terminal_info(), and printtools::time2finish().
  logical, public :: www = .false.