re_globals Module Reference
Data Types
type rcza
rcza structure
type soilpar
Variables
type(soilpar), dimension(:), allocatable, target, public vgmatrix
soil and layer parameters
integer(kind=ikind), public retc_method
formula of the retention curve
real(kind=rkind), dimension(:,:), allocatable, public dual_prop
an array with values of dual richards equation coupling term and the fast domain ratio dual_prop(i,1) = layer i, parameter: omega_f
 dual_prop(i,2) = layer i, parameter:
type(soilpar), dimension(:), allocatable, target, public vgfractures
soil and layer parameters
integer(kind=ikind), public retc_method_f
formula of the retention curve
type(soilpar), dimension(:), pointer, public vgset
depending on current domain, this pointer is pointed to current parameters as if (domain == matrix) vgset => vgmatrix if (domain == fractures) vgset => vgfractures
integer, public file_waterm
Variable Documentation
real(kind=rkind), dimension(:,:), allocatable, public re_globals::dual_prop
an array with values of dual richards equation coupling term and the fast domain ratio dual_prop(i,1) = layer i, parameter: omega_f
 dual_prop(i,2) = layer i, parameter:
Definition at line 46 of file re_globals.f90.
  real(kind=rkind), dimension(:,:), allocatable, public :: dual_prop
integer, public re_globals::file_waterm
Definition at line 57 of file re_globals.f90.
Referenced by re_reader::res_read().
   integer, public :: file_waterm
integer(kind=ikind), public re_globals::retc_method
formula of the retention curve
Definition at line 35 of file re_globals.f90.
  integer(kind=ikind), public :: retc_method
integer(kind=ikind), public re_globals::retc_method_f
formula of the retention curve
Definition at line 50 of file re_globals.f90.
  integer(kind=ikind), public :: retc_method_f
type(soilpar), dimension(:), allocatable, target, public re_globals::vgfractures
soil and layer parameters
Definition at line 48 of file re_globals.f90.
Referenced by re_constitutive::domainswitch().
  type(soilpar), dimension(:), allocatable, target, public :: vgfractures
type(soilpar), dimension(:), allocatable, target, public re_globals::vgmatrix
soil and layer parameters
Definition at line 33 of file re_globals.f90.
Referenced by re_pointers::allrepointers(), re_constitutive::domainswitch(), re_reader::res_read(), and re_constitutive::tabvalues().
  type(soilpar), dimension(:), allocatable, target, public :: vgmatrix
type(soilpar), dimension(:), pointer, public re_globals::vgset
depending on current domain, this pointer is pointed to current parameters as if (domain == matrix) vgset => vgmatrix if (domain == fractures) vgset => vgfractures
Definition at line 55 of file re_globals.f90.
Referenced by ade_fnc::adedispersion(), re_constitutive::dmualem_dh(), re_constitutive::dmualem_dh_tab(), re_constitutive::domainswitch(), re_constitutive::gardner_elast(), re_constitutive::gardner_ks(), re_constitutive::gardner_wc(), re_total::getval_retot(), re_constitutive::init_zones(), re_constitutive::inverse_vangen(), re_constitutive::mualem(), re_constitutive::mualem_tab(), re_constitutive::rcza_check(), re_constitutive::rcza_check_old(), re_constitutive::re_initcond(), re_total::retot_initcond(), re_constitutive::secondder_retc(), re_constitutive::sinkterm(), re_constitutive::tabvalues(), re_analytical::tracy_bc(), re_constitutive::vangen(), re_constitutive::vangen_elast(), re_constitutive::vangen_elast_tab(), and re_constitutive::vangen_tab().
   type(soilpar), dimension(:), pointer, public :: vgset