boussfnc Module Reference
Functions/Subroutines
real(kind=rkind) function, public bouss_elast (pde_loc, layer, quadpnt, x)
subroutine, public bouss_cond (pde_loc, layer, quadpnt, x, tensor, scalar)
subroutine, public bouss_adv (pde_loc, layer, quadpnt, x, vector_in, vector_out, scalar)
real(kind=rkind) function, public boussreact (pde_loc, layer, quadpnt, x)
subroutine, public darcy4bouss (pde_loc, layer, quadpnt, x, grad, flux, flux_length)
subroutine, public boussicond (pde_loc)
subroutine, public bouss_bc (pde_loc, el_id, node_order, value, code)
Function/Subroutine Documentation
subroutine, public boussfnc::bouss_adv (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional vector_in, real(kind=rkind), dimension(:), intent(out), optional vector_out, real(kind=rkind), intent(out), optional scalar)
Parameters
in x pressure head
in vector_in this argument is required by the global vector_fnc procedure pointer, unused in this procedure
out scalar relative unsaturated hydraulic conductivity derivative in respect to h, scalar value
Definition at line 155 of file boussfnc.f90.
References boussglob::bouss_rain, boussglob::bouss_slopes, geom_tools::getcoor(), and globals::time.
Referenced by bousspointers::boussi().
        use typy
        use globals
        use boussglob
        use pde_objs
        use geom_tools
        use global_objs
        use debug_tools
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: layer
        type(integpnt_str), intent(in), optional :: quadpnt
        real(kind=rkind), dimension(:), intent(in), optional :: x
        real(kind=rkind), dimension(:), intent(in), optional :: vector_in
        real(kind=rkind), dimension(:), intent(out), optional :: vector_out
        real(kind=rkind), intent(out), optional :: scalar
        real(kind=rkind), dimension(1) :: coord
        real(kind=rkind) :: rain, h, slope
        real(kind=rkind), dimension(1,1) :: k
        integer(kind=ikind) :: i
        
        if (present(quadpnt) .and. present(x)) then
          print *, "ERROR: the function can be called either with integ point or x value definition, not
       both of them"
          print *, "exited from re_constitutive::dmualem_dh"
          error stop
        else if (.not. present(quadpnt) .and. .not. present(x)) then
          print *, "ERROR: you have not specified either integ point or x value"
          print *, "exited from re_constitutive::dmualem_dh"
          error stop
        end if
        
        if (present(quadpnt)) then
          h = pde_loc%getval(quadpnt)
        else
          if (ubound(x,1) /=1) then
            print *, "ERROR: van Genuchten function is a function of a single variable h"
            print *, " your input data has:", ubound(x,1), "variables"
            print *, "exited from re_constitutive::dmualem_dh"
            error stop
          end if
          h = x(1)
        end if
        
        
        
        
        do i=1, ubound(bouss_rain,1)-1
          if (i == 1 .and. time < bouss_rain(1)%data(i)) then
            rain = bouss_rain(2)%data(i)
          end if
          if (bouss_rain(1)%data(i) <= time .and. bouss_rain(1)%data(i+1) > time) then
            rain = bouss_rain(2)%data(i)
            EXIT
          end if
          if (i == bouss_rain(1)%pos - 1 .and. time >= bouss_rain(1)%data(i+1)) then
            rain = bouss_rain(2)%data(i+1)
          end if
        end do
        
        
        call getcoor(quadpnt, coord)
        
        do i=1, bouss_slopes(1)%pos - 1
          if (coord(1) >= bouss_slopes(1)%data(i) .and. coord(1) < bouss_slopes(1)%data(i+1)) then
            slope = bouss_slopes(2)%data(i)
            EXIT
          end if
          if (i == bouss_slopes(1)%pos - 1 .and. coord(1) >= bouss_slopes(1)%data(i+1)) then
            slope = bouss_slopes(2)%data(i+1)
          end if
        end do
        
        call pde_loc%pde_fnc(1)%dispersion(pde_loc, layer, quadpnt, tensor=k)
        if (present(vector_out)) then
          ! must be negative, because the commnon scheme of the CDE problem has negative convection, but RE
       has positive convection
          vector_out = -(rain*slope - slope*k(1,1))
        end if
! print *, vector_out, rain, slope ; stop
subroutine, public boussfnc::bouss_bc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 408 of file boussfnc.f90.
References globals::elements, globals::nodes, and globals::time.
Referenced by bousspointers::boussi().
        use typy
        use globals
        use global_objs
        use pde_objs
        use geom_tools
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: el_id, node_order
        real(kind=rkind), intent(out), optional :: value
        integer(kind=ikind), intent(out), optional :: code
        
        integer(kind=ikind) :: edge_id, i, j
        
        edge_id = nodes%edge(elements%data(el_id, node_order))
        
        if (present(value)) then
          if (pde_loc%bc(edge_id)%file) then
            do i=1, ubound(pde_loc%bc(edge_id)%series,1)
              if (pde_loc%bc(edge_id)%series(i,1) > time) then
                if (i > 1) then
                  j = i-1
                else
                  j = i
                end if
                value = pde_loc%bc(edge_id)%series(j,2)
                EXIT
              end if
            end do
          else
            value = pde_loc%bc(edge_id)%value
          end if
        end if
        
        
        if (present(code)) then
          code = pde_loc%bc(edge_id)%code
        end if
        
subroutine, public boussfnc::bouss_cond (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:,:), intent(out), optional tensor, real(kind=rkind), intent(out), optional scalar)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
out tensor second order tensor of the unsaturated hydraulic conductivity
out scalar relative hydraulic conductivity, (scalar value)
Definition at line 79 of file boussfnc.f90.
References boussglob::bouss_k, and geom_tools::getcoor().
Referenced by bousspointers::boussi().
        use typy
        use boussglob
        use pde_objs
        use geom_tools
        use debug_tools
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: layer
        real(kind=rkind), dimension(:), intent(in), optional :: x
        type(integpnt_str), intent(in), optional :: quadpnt
        real(kind=rkind), dimension(:,:), intent(out), optional :: tensor
        real(kind=rkind) :: h
        real(kind=rkind), intent(out), optional :: scalar
        real(kind=rkind), dimension(1) :: coord
        integer(kind=ikind) :: i
        if (present(quadpnt) .and. present(x)) then
          print *, "ERROR: the function can be called either with integ point or x value definition, not
       both of them"
          print *, "exited from re_constitutive::mualem"
          error stop
        else if (.not. present(quadpnt) .and. .not. present(x)) then
          print *, "ERROR: you have not specified either integ point or x value"
          print *, "exited from re_constitutive::mualem"
          error stop
        end if
        
        if (present(quadpnt)) then
          h = pde_loc%getval(quadpnt)
        else
          if (ubound(x,1) /=1) then
            print *, "ERROR: van Genuchten function is a function of a single variable h"
            print *, " your input data has:", ubound(x,1), "variables"
            print *, "exited from re_constitutive::mualem"
            error stop
          end if
          h = x(1)
        end if
        
        call getcoor(quadpnt, coord)
        
        
        do i=1, bouss_k(1)%pos - 1
          if (coord(1) >= bouss_k(1)%data(i) .and. coord(1) < bouss_k(1)%data(i+1)) then
            if (present(tensor)) then
              tensor = bouss_k(2)%data(i) * h
            end if
            if (present(scalar)) then
              scalar = bouss_k(2)%data(i) * h
            end if
            EXIT
          end if
          if (i == bouss_k(1)%pos - 1 .and. coord(1) >= bouss_k(1)%data(i+1)) then
            if (present(tensor)) then
              tensor = bouss_k(2)%data(i+1) * h
            end if
            if (present(scalar)) then
              scalar = bouss_k(2)%data(i+1) * h
            end if
          end if
          
        end do
        
        
      
real(kind=rkind) function, public boussfnc::bouss_elast (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting system elasticity
Definition at line 14 of file boussfnc.f90.
References boussglob::bouss_por, boussglob::bouss_slopes, and geom_tools::getcoor().
Referenced by bousspointers::boussi().
        use typy
        use boussglob
        use pde_objs
        use geom_tools
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: layer
        real(kind=rkind), intent(in), dimension(:), optional :: x
        type(integpnt_str), intent(in), optional :: quadpnt
        real(kind=rkind) :: h
        real(kind=rkind) :: e
        real(kind=rkind), dimension(1) :: coord
        real(kind=rkind) :: cos_slope, slope
        integer(kind=ikind) :: i
        
        if (present(quadpnt) .and. present(x)) then
          print *, "ERROR: the function can be called either with integ point or x value definition, not
       both of them"
          print *, "exited from re_constitutive::vangen_elast"
          error stop
        else if (.not. present(quadpnt) .and. .not. present(x)) then
          print *, "ERROR: you have not specified either integ point or x value"
          print *, "exited from re_constitutive::vangen_elast"
          error stop
        end if
        
        if (present(quadpnt)) then
          h = pde_loc%getval(quadpnt)
        else
          if (ubound(x,1) /=1) then
            print *, "ERROR: van Genuchten function is a function of a single variable h"
            print *, " your input data has:", ubound(x,1), "variables"
            error stop
          end if
          if (ubound(x,1) /=1) then
            print *, "ERROR: van Genuchten function is a function of a single variable h"
            print *, " your input data has:", ubound(x,1), "variables"
            print *, "exited from re_constitutive::vangen_elast"
            error stop
          end if
          h = x(1)
        end if
        call getcoor(quadpnt, coord)
        
        do i=1, bouss_slopes(1)%pos - 1
          if (coord(1) >= bouss_slopes(1)%data(i) .and. coord(1) < bouss_slopes(1)%data(i+1)) then
            slope = bouss_slopes(2)%data(i)
            EXIT
          end if
          if (i == bouss_slopes(1)%pos - 1 .and. coord(1) >= bouss_slopes(1)%data(i+1)) then
            slope = bouss_slopes(2)%data(i+1)
          end if
        end do
        cos_slope = cos(atan(slope))
        e = bouss_por/cos_slope
        
subroutine, public boussfnc::boussicond (class(pde_str), intent(inout) pde_loc)
Definition at line 380 of file boussfnc.f90.
References boussglob::bouss_icond, globals::elements, globals::nodes, and pde_objs::pde.
Referenced by bousspointers::boussi().
        use typy
        use globals
        use boussglob
        use global_objs
        use pde_objs
        
        class(pde_str), intent(in out) :: pde_loc
        integer(kind=ikind) :: i, j, k, l, m, layer
        real(kind=rkind) :: value
        
       do i=1, elements%kolik
          layer = elements%material(i,1)
          do j=1, ubound(elements%data,2)
            k = elements%data(i,j)
            l = nodes%edge(k)
            m = pde(1)%permut(k)
            if (m == 0) then
              call pde_loc%bc(l)%value_fnc(pde_loc, i, j, value)
              pde_loc%solution(k) = value
            else
              pde_loc%solution(k) = bouss_icond
            end if
          end do
        end do
      
real(kind=rkind) function, public boussfnc::boussreact (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting reaction
Definition at line 246 of file boussfnc.f90.
References boussglob::bouss_rain.
Referenced by bousspointers::boussi().
        use typy
        use re_globals
        use pde_objs
        use geom_tools
        use boussglob
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: layer
        real(kind=rkind), intent(in), dimension(:), optional :: x
        type(integpnt_str), intent(in), optional :: quadpnt
        real(kind=rkind) :: react
        
        real(kind=rkind) :: rain
        integer(kind=ikind) :: i
        
        do i=1, ubound(bouss_rain,1)-1
          if (i == 1 .and. time < bouss_rain(1)%data(i)) then
            rain = bouss_rain(2)%data(i)
          end if
          if (bouss_rain(1)%data(i) <= time .and. bouss_rain(1)%data(i+1) > time) then
            rain = bouss_rain(2)%data(i)
            EXIT
          end if
          if (i == bouss_rain(1)%pos - 1 .and. time >= bouss_rain(1)%data(i+1)) then
            rain = bouss_rain(2)%data(i+1)
          end if
        end do
        
        react = -rain
         
subroutine, public boussfnc::darcy4bouss (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional grad, real(kind=rkind), dimension(:), intent(out), optional flux, real(kind=rkind), intent(out), optional flux_length)
Parameters
in grad this value is optional, because it is required by the vector_fnc procedure pointer global definition
Definition at line 286 of file boussfnc.f90.
References boussglob::bouss_slopes, and geom_tools::getcoor().
Referenced by bousspointers::boussi().
        use typy
        use pde_objs
        use global_objs
        use geom_tools
        use boussglob
        
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: layer
        type(integpnt_str), intent(in), optional :: quadpnt
        real(kind=rkind), intent(in), dimension(:), optional :: x
        real(kind=rkind), dimension(:), intent(in), optional :: grad
        real(kind=rkind), dimension(:), intent(out), optional :: flux
        real(kind=rkind), intent(out), optional :: flux_length
        real(kind=rkind), dimension(1,1) :: k
        integer :: d
        integer(kind=ikind) :: i
        real(kind=rkind), dimension(:), allocatable, save :: gradh
        real(kind=rkind), dimension(:), allocatable, save :: vct
        real(kind=rkind) :: h, slope
        real(kind=rkind), dimension(1) :: coord
        
        d = drutes_config%dimen
          
        if (.not.(allocated(gradh))) then
          allocate(gradh(1:d))
          allocate(vct(1:d))
        end if
        if (present(quadpnt) .and. (present(grad) .or. present(x))) then
          print *, "ERROR: the function can be called either with integ point or x value definition and
       gradient, not both of them"
          error stop
        else if ((.not. present(grad) .or. .not. present(x)) .and. .not. present(quadpnt)) then
          print *, "ERROR: you have not specified either integ point or x value"
          print *, "exited from re_constitutive::darcy_law"
          error stop
        end if
        
        if (present(quadpnt)) then
          h = pde_loc%getval(quadpnt)
          call pde_loc%getgrad(quadpnt, gradh)
        else
          if (ubound(x,1) /=1) then
            print *, "ERROR: van Genuchten function is a function of a single variable h"
            print *, " your input data has:", ubound(x,1), "variables"
            print *, "exited from re_constitutive::darcy_law"
            error stop
          end if
          h = x(1)
          gradh(1:d) = grad
        end if
        
       call getcoor(quadpnt, coord)
        
        do i=1, bouss_slopes(1)%pos - 1
          if (coord(1) >= bouss_slopes(1)%data(i) .and. coord(1) < bouss_slopes(1)%data(i+1)) then
            slope = bouss_slopes(2)%data(i)
            EXIT
          end if
          if (i == bouss_slopes(1)%pos - 1 .and. coord(1) >= bouss_slopes(1)%data(i+1)) then
            slope = bouss_slopes(2)%data(i+1)
          end if
        end do
        
        
        gradh = gradh + slope
        
        call pde_loc%pde_fnc(1)%dispersion(pde_loc, layer, quadpnt, tensor=k(1:d, 1:d))
      
        
        vct(1:d) = matmul(-k(1:d,1:d), gradh(1:d))
        if (present(flux_length)) then
          select case(d)
            case(1)
                  flux_length = abs(vct(1))
            case(2)
                  flux_length = sqrt(vct(1)*vct(1) + vct(2)*vct(2))
            case(3)
                  flux_length = sqrt(vct(1)*vct(1) + vct(2)*vct(2) + vct(3)*vct(3))
          end select
        end if
        if (present(flux)) then
          flux(1:d) = vct(1:d)
        end if