solvers Module Reference
resice soustav
Data Types
type vrstvy
Functions/Subroutines
subroutine, public jacobi (a, b, x, maxit1, reps1, it, repsfin, l1, l2, countop, ilev1)
Jacobiova metoda.
subroutine, public gs (a, b, x, maxit, reps, it, repsfin, l1, l2, countop, ilev)
Gauss-Seidelova metoda.
subroutine, public ldu (A, LU, info, pivtype, ilev, perm1, perm2)
nedestruktivni LDU rozklad
subroutine, public ldud (A, info, pivtype, ilev, perm1, perm2)
destruktivni LDU rozklad
subroutine, public split (LDU, L, D, U, p1, p2)
rozdeli matici s LDU rozkladem na jednotlive komponenty
subroutine, public lduback (LDU, b, x, p1, p2, oc1, ilevel, errcode)
Zpetny chod po LDU dekompozici. Predpoklada se, ze matice je ctvercova.
subroutine, public sd (A, b, x, itmax1, reps1, ilev1, itfin1, repsfin1, ll1, ll2, cond1, opcnt1, errcode1)
metoda nejvetsiho spadu (Steepest descent) podrobnosti viz `Metoda nejvetsiho spadu`
subroutine, public sdnormal
subroutine, public cg (A, b, x, itmax1, reps1, ilev1, itfin1, repsfin1, ll1, ll2, cond1, opcnt1, errcode1)
metoda sdruzenych gradientu Metoda sdruzenych gradientu
subroutine, public cgnormal (A, b, x, itmax1, reps1, ilev1, itfin1, repsfin1, ll1, ll2, cond1, opcnt1, errcode1)
metoda sdruzenych gradientu pro normalni rovnice Metoda sdruzenych gradientu pro normalni rovnice
subroutine, public pcg (A, Minv, b, x, itmax1, reps1, ilev1, itfin1, repsfin1, ll1, ll2, cond1, opcnt1, errcode1)
metoda sdruzenych gradientu Metoda predpodminenych sdruzenych gradientu
subroutine, public pcgnormal
real(kind=rkind) function, private vycdet (x, a, b, n)
subroutine, private esteig (l1, l2, n, alfa, beta)
subroutine inivrstvy (levelset, A)
inicializuje vrstvy
subroutine firstpoint (levelset, point)
vlozi prvni vrchol, v tomto pripade nepotrebuje matici
subroutine addlevel (A, mapa, levelset)
prida vrstvu, predpoklada se, ze aspon jedna tam uz je
Detailed Description
resice soustav
Function/Subroutine Documentation
subroutine solvers::addlevel (class(matrix), intent(in) A, integer(kind=ikind), dimension(:), intent(inout) mapa, type(vrstvy), intent(inout) levelset)
prida vrstvu, predpoklada se, ze aspon jedna tam uz je
Parameters
in a matice definujici graf
in,out mapa mapa povolujici jdnotlive vrcholy
in,out levelset uktualni sada vrstev
Definition at line 2050 of file solvers.f90.
        use mtx
        class(matrix), intent(in) :: a
        integer(kind=ikind),dimension(:),intent(inout) :: mapa
        type(vrstvy), intent(inout) :: levelset
        if (levelset%nlev == 0) stop "Chybna pouziti addlevel"
        ! posledni vrstva je v od levelset%levstart(nlev) do
        ! levelset%lesvstart(nlev+1)-1
subroutine, public solvers::cg (class(matrix), intent(in) A, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional itmax1, real(kind=rkind), intent(in), optional reps1, integer, intent(in), optional ilev1, integer(kind=ikind), intent(out), optional itfin1, real(kind=rkind), intent(out), optional repsfin1, real(kind=rkind), intent(out), optional ll1, real(kind=rkind), intent(out), optional ll2, real(kind=rkind), intent(out), optional cond1, type(tcount), intent(out), optional opcnt1, integer, intent(out), optional errcode1)
metoda sdruzenych gradientu Metoda sdruzenych gradientu
Parameters
in a matice soustavy
 musi poskytovat getn, getm, mul (nasobeni vektorem)
in b vektor prave strany
in,out x aproximace reseni, postupne menena
in itmax1 maximalni povoleny pocet iteraci, default = n (Rozmer matice)
in reps1 pozadovana relativni zmena rezidua, default = 1e-6
in ilev1 informacni podrobnost
0 ... pracuj tise
1 ... minimalni informace
10 ... maximalni ukecanost
out itfin1 skutecne provedeny pocet iteraci
out repsfin1 skutecne dosazena relativni zmena residua
out ll1 odhad nejvetsiho vlastniho cisla
out ll2 odhad nejmensiho vlastniho cisla
out cond1 odhad cisla podminenosti : cond1 = ll1/ll2
out opcnt1 celkovy pocet provedenych operaci a cas behu
out errcode1 kod pripadne chyby
0 ... OK
1 ... matice neni ctvercova
2 ... nesouhlasi b
3 ... nesouhasi x
4 ... ani jeden z vektoru nesouhlasi
5 ... vycerpan povoleny pocet iteraci
6 ... prestalo klesat residuum i energie
Definition at line 1245 of file solvers.f90.
References esteig().
Referenced by solver_interfaces::cg_face().
        use mtx
        use typy
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(in out) :: x
        integer(kind=ikind), intent(in), optional :: itmax1
        real(kind=rkind), intent(in), optional :: reps1
        integer, intent(in), optional :: ilev1
        integer(kind=ikind), intent(out), optional :: itfin1
        real(kind=rkind), intent(out), optional :: repsfin1
        real(kind=rkind), intent(out), optional :: ll1
        real(kind=rkind), intent(out), optional :: ll2
        real(kind=rkind), intent(out), optional :: cond1
        type(tcount), intent(out), optional :: opcnt1
        integer, intent(out), optional :: errcode1
        integer(kind=ikind) :: itmax, cnt, n
        integer :: ilev,rcount, rcount1, errcode
        real(kind=rkind) :: reps, repsfin, r0, r1, r2,r3,l1,l2,t1,t2
        real(kind=rkind) :: wrk, en, enmin, res2min
        real(kind=rkind), dimension(:), allocatable :: res,p,ap,&
        alfa, beta
        type(tcount) :: opcnt
        call cpu_time(t1)
        errcode = 0
        n = a%getn()
        rcount = 0
        rcount1 = 0
        l1 = 1
        l2 = 1
        if (present(errcode1)) errcode1 = 0
        if (present(ilev1)) then
        ilev = ilev1
        else
            ilev = 0
        end if
        if (present(itmax1)) then
        itmax = itmax1
        else
            itmax = a%getn()
            if (ilev==10) print *,&
            "nastavuji default hodnotu pro itmax na",itmax
        end if
        allocate(alfa(0:itmax), beta(0:itmax))
        if (a%getn() /= a%getm()) then
            if (present(errcode1)) then
                errcode1 = 1
                if (ilev>0) print *,"CG: Matice neni ctvercova"
            return
            else
                stop "CG: Matice neni ctvercova"
            end if
        end if
        if (a%getn() /= ubound(b,1)) then
            if (present(errcode1)) then
                errcode1 = 2
            if (ilev>0) print *,"CG : nesouhlasi delka prave strany"
            else
                stop "CG: Nesouhlasi delka prave strany"
            end if
        end if
        if (a%getm() /= ubound(x,1)) then
            if (present(errcode1)) then
                if (errcode1==0) then
                    errcode1 = 3
                if (ilev>0) print *,"CG: nesouhlasi delka reseni"
                else
                    errcode1 = 4
                    if (ilev>0) print *,"CG: nesouhlasi delky obou vektoru"
                end if
            else
                stop "CG: Nesouhlasi delka vektoru neznamych"
            end if
        end if
        if (present(errcode1)) then
            if (errcode1>0) return
        end if
        if (present(reps1)) then
        reps = reps1
        else
            reps = 1.0e-6
            if (ilev==10) print *,"nastavuji reps na defaultni hodnotu "&
            , reps
        end if
        ! ted uz je snad vyrizeno vsechno ze vstupu
        ! jdu pocitat
        cnt = 0
        !! Step 1
        res = b - a%mul(x,opcnt)
        r2 = dot_product(res,res)
        r0 = r2
        p = res
        opcnt%ad = n-1
        opcnt%mul = n
        !! Step 2
        do
            !! Step 3
            ap =a%mul(p,opcnt)
            r1 = dot_product(p,ap)
            wrk = r2/r1
            if (ilev>0) print *,"alfa=",wrk
            alfa(cnt) = wrk
            ! tenhle usek je jen kvuli vypoctu energie
            en = -dot_product(x,b+res) ! je to vychozi energie
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !! Step 4
            x = x + wrk*p
            !! Step 5
            res = res - wrk*ap
            !! Step 6
            r3 = r2
            r2 = dot_product(res,res)
            wrk = r2/r3
            if (ilev>0) print *,"beta=",wrk
            beta(cnt) = wrk
            !! Step 7
            p = res + wrk*p
            opcnt%ad = opcnt%ad + 4*n-2 + 2*n-1
            opcnt%mul = opcnt%mul + 4*n + n
            opcnt%div = opcnt%div + 1
            !! odhadnout vlastni cisla
            call esteig(l1,l2,cnt,alfa,beta)
            print *, "odhad vl. cisel:",l1,l2
            !! hotovo
            cnt = cnt + 1
            if (cnt==1) then
                enmin = en
                res2min = r2
                if (r0==0.0_rkind) then
                    repsfin=0
                    exit
                end if
            end if
            if (en < enmin) then
                rcount = 0
            enmin = en
            else
                rcount = rcount+1
            end if
            if (r2 < res2min) then
                res2min = r2
            rcount1 = 0
            else
                rcount1 = rcount1+1
            end if
            if (ilev>0) print *, cnt,sqrt(r2), reps, en, enmin
            if (cnt == itmax) then
                errcode = 5
                exit
            end if
            repsfin = sqrt(r2/r0)
            if (repsfin < reps) exit
            if ((rcount1>5) .and. (rcount > 5)) then
                errcode = 6
                exit
            end if
        end do
        call cpu_time(t2)
        opcnt%time = t2-t1
        ! vyridit konec
        if (present(opcnt1)) opcnt1 = opcnt
        if (present(errcode1)) errcode1 = errcode
        if (present(itfin1)) itfin1 = cnt
        if (present(repsfin1)) repsfin1 = repsfin
        if (present(ll1)) ll1 = l1
        if (present(ll2)) ll2 = l2
        if (present(cond1)) cond1 = l1/l2
subroutine, public solvers::cgnormal (class(matrix), intent(in) A, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional itmax1, real(kind=rkind), intent(in), optional reps1, integer, intent(in), optional ilev1, integer(kind=ikind), intent(out), optional itfin1, real(kind=rkind), intent(out), optional repsfin1, real(kind=rkind), intent(out), optional ll1, real(kind=rkind), intent(out), optional ll2, real(kind=rkind), intent(out), optional cond1, type(tcount), intent(out), optional opcnt1, integer, intent(out), optional errcode1)
metoda sdruzenych gradientu pro normalni rovnice Metoda sdruzenych gradientu pro normalni rovnice
Parameters
in a matice soustavy
 musi poskytovat getn, getm, mul (nasobeni vektorem)
in b vektor prave strany
in,out x aproximace reseni, postupne menena
in itmax1 maximalni povoleny pocet iteraci, default = n (Rozmer matice)
in reps1 pozadovana relativni zmena rezidua, default = 1e-6
in ilev1 informacni podrobnost
0 ... pracuj tise
1 ... minimalni informace
10 ... maximalni ukecanost
out itfin1 skutecne provedeny pocet iteraci
out repsfin1 skutecne dosazena relativni zmena residua
out ll1 odhad nejvetsiho vlastniho cisla
out ll2 odhad nejmensiho vlastniho cisla
out cond1 odhad cisla podminenosti : cond1 = ll1/ll2
out opcnt1 celkovy pocet provedenych operaci a cas behu
out errcode1 kod pripadnr chyby
0 ... OK
1 ... matice neni ctvercova
2 ... nesouhlasi b
3 ... nesouhasi x
4 ... ani jeden z vektoru nesouhlasi
5 ... vycerpan povoleny pocet iteraci
6 ... prestalo klesat residuum i energie
Definition at line 1476 of file solvers.f90.
Referenced by solver_interfaces::cg_normal_face().
        use mtx
        use typy
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(in out) :: x
        integer(kind=ikind), intent(in), optional :: itmax1
        real(kind=rkind), intent(in), optional :: reps1
        integer, intent(in), optional :: ilev1
        integer(kind=ikind), intent(out), optional :: itfin1
        real(kind=rkind), intent(out), optional :: repsfin1
        real(kind=rkind), intent(out), optional :: ll1
        real(kind=rkind), intent(out), optional :: ll2
        real(kind=rkind), intent(out), optional :: cond1
        type(tcount), intent(out), optional :: opcnt1
        integer, intent(out), optional :: errcode1
        integer(kind=ikind) :: itmax, cnt, n
        integer :: ilev,rcount, rcount1, errcode
        real(kind=rkind) :: reps, repsfin, r0, r1, r2,r3,l1,l2,t1,t2
        real(kind=rkind) :: wrk, en, enmin, res2min
        real(kind=rkind), dimension(:), allocatable :: res,p,ap,&
        alfa, beta,&
        res1, b1
        type(tcount) :: opcnt
        call cpu_time(t1)
        if (present(errcode1)) errcode1 = 0
        errcode = 0
        n = a%getn()
        rcount = 0
        rcount1 = 0
        l1 = 1
        l2 = 1
        if (present(ilev1)) then
        ilev = ilev1
        else
            ilev = 0
        end if
        if (present(itmax1)) then
        itmax = itmax1
        else
            itmax = a%getn()
            if (ilev==10) print *,&
            "nastavuji default hodnotu pro itmax na",itmax
        end if
        allocate(alfa(0:itmax), beta(0:itmax))
        if (a%getn() /= ubound(b,1)) then
            if (present(errcode1)) then
                errcode1 = 2
            if (ilev>0) print *,"CGnormal : nesouhlasi delka prave strany"
            else
                stop "CGnormal: Nesouhlasi delka prave strany"
            end if
        end if
        if (a%getm() /= ubound(x,1)) then
            if (present(errcode1)) then
                if (errcode1==0) then
                    errcode1 = 3
                if (ilev>0) print *,"CGnormal: nesouhlasi delka reseni"
                else
                    errcode1 = 4
                    if (ilev>0) print *,"CGnormal: nesouhlasi delky obou vektoru"
                end if
            else
                stop "CGnormal: Nesouhlasi delka vektoru neznamych"
            end if
        end if
        if (present(errcode1)) then
            if (errcode1>0) return
        end if
        if (present(reps1)) then
        reps = reps1
        else
            reps = 1.0e-6
            if (ilev==10) print *,"nastavuji reps na defaultni hodnotu "&
            , reps
        end if
        ! ted uz je snad vyrizeno vsechno ze vstupu
        ! jdu pocitat
        cnt = 0
        !! Step 1
        b1 = a%mult(b)
        res = b - a%mul(x,opcnt)
        res = a%mult(res,opcnt)
        r2 = dot_product(res,res)
        r0 = r2
        p = res
        opcnt%ad = n-1
        opcnt%mul = n
        !! Step 2
        do
            !! Step 3
            ap =a%mul(p,opcnt)
            r1 = dot_product(ap,ap)
            wrk = r2/r1
            if (ilev>0) print *,"alfa=",wrk
            alfa(cnt) = wrk
            ! tenhle usek je jen kvuli vypoctu energie
            en = -dot_product(x,b1+res) ! je to vychozi energie
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !! Step 4
            x = x + wrk*p
            !! Step 5
            res = res - wrk*a%mult(ap,opcnt)
            !! Step 6
            r3 = r2
            r2 = dot_product(res,res)
            wrk = r2/r3
            if (ilev>0) print *,"beta=",wrk
            beta(cnt) = wrk
            !! Step 7
            p = res + wrk*p
            opcnt%ad = opcnt%ad + 4*n-2 + 2*n-1
            opcnt%mul = opcnt%mul + 4*n + n
            opcnt%div = opcnt%div + 1
            !! odhadnout vlastni cisla
! call esteig(l1,l2,cnt,alfa,beta)
! print *, "odhad vl. cisel:",l1,l2
            !! hotovo
            cnt = cnt + 1
            if (cnt==1) then
                enmin = en
                res2min = r2
                if (r0==0.0_rkind) then
                    repsfin=0
                    exit
                end if
            end if
            if (en < enmin) then
                rcount = 0
            enmin = en
            else
                rcount = rcount+1
            end if
            if (r2 < res2min) then
                res2min = r2
            rcount1 = 0
            else
                rcount1 = rcount1+1
            end if
            if (ilev>0) print *, cnt,sqrt(r2), reps, en, enmin
            if (cnt == itmax) then
                errcode = 5
                exit
            end if
            repsfin = sqrt(r2/r0)
            if (repsfin < reps) exit
            if ((rcount1>5) .and. (rcount > 5)) then
                errcode = 6
                exit
            end if
        end do
        call cpu_time(t2)
        opcnt%time = t2-t1
        ! vyridit konec
        if (present(opcnt1)) opcnt1 = opcnt
        if (present(errcode1)) errcode1 = errcode
        if (present(itfin1)) itfin1 = cnt
        if (present(repsfin1)) repsfin1 = repsfin
        if (present(ll1)) ll1 = l1 ! tohle zatim nepocita
        if (present(ll2)) ll2 = l2
        if (present(cond1)) cond1 = l1/l2
subroutine, private solvers::esteig (real(kind=rkind), intent(inout) l1, real(kind=rkind), intent(inout) l2, integer(kind=ikind), intent(in) n, real(kind=rkind), dimension(0:), intent(in) alfa, real(kind=rkind), dimension(0:), intent(in) beta) [private]
Definition at line 1952 of file solvers.f90.
References vycdet().
Referenced by cg(), and pcg().
        use typy
        implicit none
        real(kind=rkind), intent(in out) :: l1
        real(kind=rkind), intent(in out) :: l2
        integer(kind=ikind), intent(in) :: n
        real(kind=rkind), dimension(0:), intent(in) :: alfa
        real(kind=rkind), dimension(0:), intent(in) :: beta
        real(kind=rkind) :: x1,x2,x3,y1,y2,y3,d1,d2
        if (n==0) then
            l1 = 1/alfa(0)
        l2 = l1
        else
            !odhadneme nejmensi
            x1 = 0
            y1 = vycdet(x1,alfa,beta,n)
            x2 = l2
            y2 = vycdet(x2,alfa,beta,n)
            if (y1*y2>0) print *, "podivne"
            d1 =x2-x1
            d2 = 2*d1
            do while (d1 < d2)
                d2 = d1
                x3 = (x1+x2)/2
                y3 = vycdet(x3,alfa,beta,n)
                if (y3*y1 > 0) then
                    x1 = x3
                y1 = y3
                else
                    x2 = x3
                    y2 = y3
                end if
                d1 = x2 - x1
            end do
            l2 = x3
            !odhadneme nejvetsi
            x1 = l1
            y1 = vycdet(x1,alfa,beta,n)
            d1 = 0.00000000001
            x2 = x1+d1
            y2 = vycdet(x2,alfa,beta,n)
            do while (y1*y2>0)
                x1 = x2
                y1 = y2
                d1 = d1+d1
                x2 = x1+d1
                y2 = vycdet(x2,alfa,beta,n)
            end do
            d1 =x2-x1
            d2 = 2*d1
            do while (d1 < d2)
                d2 = d1
                x3 = (x1+x2)/2
                y3 = vycdet(x3,alfa,beta,n)
                if (y3*y1 > 0) then
                    x1 = x3
                y1 = y3
                else
                    x2 = x3
                    y2 = y3
                end if
                d1 = x2 - x1
            end do
            l1 = x3
        end if
subroutine solvers::firstpoint (type(vrstvy), intent(inout) levelset, integer(kind=ikind) point)
vlozi prvni vrchol, v tomto pripade nepotrebuje matici
Definition at line 2039 of file solvers.f90.
        implicit none
        type(vrstvy), intent(in out) :: levelset
        integer(kind=ikind) :: point
        levelset%nlev = 1
        levelset%levstart(1) = 1
        levelset%levstart(2) = 2
        levelset%levlist(1) = point
subroutine, public solvers::gs (class(matrix), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in) maxit, real(kind=rkind), intent(in) reps, integer(kind=ikind), intent(out) it, real(kind=rkind), intent(out) repsfin, real(kind=rkind), intent(out) l1, real(kind=rkind), intent(out) l2, type(tcount), intent(inout), optional countop, integer, intent(in), optional ilev)
Gauss-Seidelova metoda.
Parameters
in a matice soustavy
in b prava strana
in,out x pocitane reseni soustavy
in maxit maximalni povoleny pocet iteraci
in reps pozadovane relativni residuum
out it skutecny pocet iteraci
out repsfin skutecne relativni residuum
out l1 odhad rychlosti konvergence pomoci mocninne metody
out l2 odhad rychlosti konvergence pomoci odmocniny
in,out countop pocitadlo operaci
in ilev podrobnost informaci
Definition at line 190 of file solvers.f90.
References typy::norm2().
        use typy
        use mtx
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(inout) :: x
        integer(kind=ikind), intent(in) :: maxit
        real(kind=rkind), intent(in) :: reps
        integer(kind=ikind), intent(out) :: it
        real(kind=rkind), intent(out) :: repsfin
        real(kind=rkind), intent(out) :: l1
        real(kind=rkind), intent(out) :: l2
        type(tcount), intent(inout), optional :: countop
        integer, intent(in), optional :: ilev
        real(kind=rkind) :: r0,r1,r2, wrk
        real(kind=rkind), dimension(:), allocatable :: r,diag
        integer(kind=ikind) :: i,j,k
        type(tcount) :: countop1
        real(kind=rkind) :: t1, t2
        call cpu_time(t1)
        allocate(r(1:a%getn()))
        allocate(diag(1:a%getn()))
        r=b-a%mul(x,countop1)
        r0 = norm2(r)
        countop1%ad = countop1%ad + a%getn()
        do i=1,a%getn()
            diag(i) = a%get(i,i)
        end do
        it = 0
        r1 = r0
        r2 = r0
        do
            !!!!!!!! predelet -
            if (it > maxit) exit
            repsfin = r1/r0
            if (r1 /= 0) then
                l1 = r1/r2
                l2 = repsfin**(1.0_rkind/it)
            end if
            if (ilev > 0) print"(i16,4ES18.10)", it, r0,r1,l1,l2
            if (repsfin < reps) exit
            r2 = r1
            r1 = 0
            do i=1, a%getn()
                wrk =b(i) - a%mulrow(x,i,countop1)
                r1 = r1 + wrk*wrk
                x(i) =x(i) + wrk/diag(i)
            end do
            r1 = sqrt(r1)
            countop1%ad = countop1%ad + a%getn()*2
            countop1%div = countop1%div + a%getn()
            it = it + 1
        end do
        deallocate(r,diag)
        call cpu_time(t2)
        if (present(countop)) then
            countop%ad = countop%ad + countop1%ad
            countop%mul = countop%mul + countop1%mul
            countop%div = countop%div + countop1%div
            countop%time = t2-t1
        end if
subroutine solvers::inivrstvy (type(vrstvy), intent(inout) levelset, class(matrix), intent(in) A)
inicializuje vrstvy
Definition at line 2023 of file solvers.f90.
        use mtx
        implicit none
        type(vrstvy), intent(in out) :: levelset
        class(matrix), intent(in) :: a
        integer(kind=ikind) :: n
        n = a%getn()
        ! jen pridelim pamet, neinicializuji
        allocate(levelset%levlist(1:n))
        allocate(levelset%levstart(1:n+1))
        ! pocet urovni je nula
        levelset%nlev = 0
subroutine, public solvers::jacobi (class(matrix), intent(in) a, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional maxit1, real(kind=rkind), intent(in), optional reps1, integer(kind=ikind), intent(out), optional it, real(kind=rkind), intent(out), optional repsfin, real(kind=rkind), intent(out), optional l1, real(kind=rkind), intent(out), optional l2, type(tcount), intent(inout), optional countop, integer, intent(in), optional ilev1)
Jacobiova metoda.
podrobnejsi popis viz Jacobiova metoda
Parameters
in a matice soustavy
in b prava strana
in,out x pocitane reseni soustavy
in maxit1 maximalni povoleny pocet iteraci
in reps1 pozadovane relativni residuum
out it skutecny pocet iteraci
out repsfin skutecne relativni residuum
out l1 odhad rychlosti konvergence pomoci mocninne metody
out l2 odhad rychlosti konvergence pomoci odmocniny
in,out countop pocitadlo operaci
in ilev1 podrobnost informaci
Definition at line 78 of file solvers.f90.
References typy::norm2(), and typy::r4.
Referenced by solver_interfaces::jacobi_face().
        use typy, r4x=>r4
        use mtx
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(inout) :: x
        integer(kind=ikind), intent(in),optional :: maxit1
        real(kind=rkind), intent(in), optional :: reps1
        integer(kind=ikind), intent(out), optional :: it
        real(kind=rkind), intent(out), optional :: repsfin
        real(kind=rkind), intent(out), optional :: l1
        real(kind=rkind), intent(out), optional :: l2
        type(tcount), intent(inout), optional :: countop
        integer, intent(in), optional :: ilev1
        integer(kind=ikind) :: maxit,it1, ilev
        real(kind=rkind) :: reps
        real(kind=rkind) :: r0,r1,r2, repsfin1
        real(kind=rkind) :: ll1,ll2
        real(kind=rkind), dimension(:), allocatable :: r,diag
        integer(kind=ikind) :: i,n
        type(tcount) :: countop1
        real(kind=rkind) :: t1, t2
        !print *,"jacobi zacina"
        call cpu_time(t1)
        !! vyresime nepovinne parametry
        n = a%getn()
        if (present(maxit1)) then
        maxit = maxit1
        else
            maxit = n
        end if
        if (present(reps1)) then
        reps = reps1
        else
            reps = 1.0e-6
        end if
        if (present(ilev1)) then
        ilev = ilev1
        else
            ilev = 0
        end if
        !print *, "nepovinne vyseny"
        allocate(r(1:a%getn()))
        allocate(diag(1:a%getn()))
        r=b-a%mul(x,countop1)
        r0 = norm2(r)
        countop1%ad = countop1%ad + a%getn()
        do i=1,a%getn()
            diag(i) = a%get(i,i)
        end do
        it1 = 0
        !print *,"pripraveno"
        do
            if (it1 > maxit) exit
            r1 = norm2(r)
            repsfin1 = r1/r0
            if (r1 /= 0) then
                ll1 = r1/r2
                ll2 = repsfin1**(1.0_rkind/it1)
            end if
            if (ilev > 0) print"(i16,4ES18.10)", it1, r0,r1,ll1,ll2
            if (repsfin1 < reps) exit
            do i=1, a%getn()
                x(i) = x(i) + r(i)/diag(i)
            end do
            r=b-a%mul(x,countop1)
            countop1%ad = countop1%ad + 2*a%getn()
            countop1%div = countop1%div + a%getn()
            it1 = it1 + 1
            r2 = r1
        end do
        deallocate(r,diag)
        call cpu_time(t2)
        !print *,"jacobi konci"
        ! vyresime navratove hodnoty
        if (present(countop)) then
            countop%ad = countop%ad + countop1%ad
            countop%mul = countop%mul + countop1%mul
            countop%div = countop%div + countop1%div
            countop%time = t2-t1
        end if
        if (present(it)) it = it1
        if (present(repsfin)) repsfin = repsfin1
        if (present(l1)) l1 = ll1
        if (present(l2)) l2 = ll2
subroutine, public solvers::ldu (class(matrix), intent(in) A, class(matrix), intent(inout) LU, type(tcount), intent(inout), optional info, integer, intent(in), optional pivtype, integer, intent(in), optional ilev, integer(kind=ikind), dimension(:), intent(inout), optional, allocatable perm1, integer(kind=ikind), dimension(:), intent(inout), optional, allocatable perm2)
nedestruktivni LDU rozklad
pro volbu pivota plati nasledujici pravidla
 0 ... zadna
 1 ... uplny vyber hlavniho prvku (nutne obe permutace)
 2 ... sloupcovy vyber hlavniho prvku(nutno perm1)
 3 ... radkovy vyber hlavniho prvku(nutno perm2)
 4 ... diagonalni vyber hlavniho prvku(nutno aspon jedna = obe shodne)
 5 ... diagonalni vyber hlavniho prvku pro minimal degree
 (nutno aspon jedna = obe shodne)
 6 ... rid se predepsanou permutaci
 Pro situace 1 az 6 musi byt pritomny permutacni vektory
 Pokud nejsou pozadavky splneny - zvoli se nejpodobnejsi volba
 pro podrobnost informaci plati
 0 ... tichy chod
 1 ... super podrobne
Parameters
in a rozkladana matice
in,out lu rozlozena matice
in,out info pocty operaci
in pivtype typ pivotaze
in ilev podrobnost informaci
in,out perm1 permutace pro i
in,out perm2 permutace pro j
Definition at line 291 of file solvers.f90.
References ldud().
        use mtx
        use typy
        implicit none
        class(matrix), intent(in) :: a
        class(matrix), intent(inout) :: lu
        type(tcount), intent(inout), optional :: info
        integer, intent(in), optional :: pivtype
        integer, intent(in), optional :: ilev
        integer(kind=ikind), dimension(:), allocatable, &
        intent(inout), optional :: perm1
        integer(kind=ikind), dimension(:), allocatable,&
        intent(inout), optional :: perm2
        integer :: pt1,il1
        integer(kind=ikind),dimension(:),allocatable :: p1,p2
        type(tcount) :: inf1
        if (present(pivtype)) then
        pt1 = pivtype
        else
            pt1 = 0
        end if
        if (present(ilev)) then
        il1 = ilev
        else
            il1 = 0
        end if
        allocate(p1(1:a%getn()))
        allocate(p2(1:a%getm()))
        select case(pt1)
                case (0)
                print *, "nula"
                case (1)
                case (2)
                case (3)
                case (4)
                case (5)
                case (6)
                    if (present(perm1)) then
                    else
                    end if
                case default
                    print *,"chybna volba"
                end select
        call lu%copy(a)
        print *,"zkopirovano"
        call ldud(lu,inf1,pt1,il1,p1,p2)
        if (present(perm1)) perm1 = p1
        if (present(perm2)) perm2 = p2
        if (present(info)) info = inf1
        if (il1 > 0) print *,"LDU konci"
subroutine, public solvers::lduback (class(matrix), intent(in) LDU, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(out) x, integer(kind=ikind), dimension(:), intent(in), optional p1, integer(kind=ikind), dimension(:), intent(in), optional p2, type(tcount), intent(out), optional oc1, integer, intent(in), optional ilevel, integer, intent(out), optional errcode)
Zpetny chod po LDU dekompozici. Predpoklada se, ze matice je ctvercova.
Parameters
in ldu rozlozena matice
in b prava strana
in ilevel info level, nepovinny parametr, default = 0
0 ... pracuj tise
1 ... vse reportuj
out errcode chybovy status, nepovinny. Pokud neni pritomen,tak chyba zpusobi konec programu
0 ... vse OK
1 ... chyba - blize neurcena
2 ... lisi se delka b a pocet radku matice
3 ... lisi se delka x a pocet sloupcu matice
4 ... matice je singularni a soustava je konzistentni
5 ... matice je singularni a soustava nekonzistentni
Definition at line 856 of file solvers.f90.
Referenced by solver_interfaces::ldu_face().
        use typy
        use mtx
        implicit none
        class(matrix), intent(in) :: ldu
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(out) :: x
        integer(kind=ikind), dimension(:), intent(in), optional :: p1
        integer(kind=ikind), dimension(:), intent(in), optional :: p2
        type(tcount), intent(out), optional :: oc1
        integer, intent(in), optional :: ilevel
        integer, intent(out), optional :: errcode
        type(tcount) :: oc
        integer(kind=ikind), dimension(:), allocatable :: perm1, perm2
        integer(kind=ikind), dimension(:), allocatable :: iperm1, iperm2
        integer(kind=ikind) :: n,m,i,j, ip, ip2
        real(kind=rkind), dimension(1:LDU%getn()) :: diag
        real(kind=rkind), dimension(:), allocatable :: v
        integer(kind=ikind), dimension(:), allocatable :: ii
        integer(kind=ikind) :: nelem
        logical, dimension(1:LDU%getn()) :: mask
        integer :: ilv
        if (present(ilevel)) then
        ilv = ilevel
        else
            ilv = 0
        end if
        n = ldu%getn()
        m = ldu%getm()
        ! vyresit optionaly
        if (present(p1)) then
            allocate(perm1(1:n))
        perm1 = p1
        else
            allocate(perm1(1:n))
            do i=1,n
                perm1(i) = i
            end do
        end if
        if (present(p2)) then
            allocate(perm2(1:m))
        perm2 = p2
        else
            allocate(perm2(1:m))
            do i=1,m
                perm2(i) = i
            end do
        end if
        ! konstrukce inverznich permutaci
        allocate(iperm1(1:n),iperm2(1:m))
        do i=1,n
            iperm1(perm1(i))=i
        end do
        do i=1,m
            iperm2(perm2(i))=i
        end do
        if (ubound(b,1) /= n) then
            if (present(errcode)) then
            else
                errcode = 2
                stop "LDUback: Pocet radku matice a prave strany se lisi"
            end if
        end if
        if (ubound(x,1) /= n) then
            if (present(errcode)) then
            else
                errcode = 3
                stop "LDUback: Pocet sloupcu matice a neznamych se lisi"
            end if
        end if
        ! 1. L y = b
        x = b
        if (ilv==1) then
            print *, "LDUback: zacatek"
            print *, "ridici permutace"
            print *, perm1
            print *, perm2
            print *, "Prava strana"
            print *,x
        end if
        diag(perm2(1))=ldu%get(perm1(1),perm2(1))
        mask = .false.
        mask(perm2(1)) = .true.
        do i = 2,n
            ip = perm1(i)
            ip2 = perm2(i)
            diag(ip2)= ldu%get(ip,ip2)
            call ldu%getrow(ip,v,ii,nelem,mask)
            if (ilv==1) then
                print *, "i=",i, ip, nelem, mask
                print *, ii(1:nelem)
                print *, v(1:nelem)
            end if
            do j=1,nelem
                if ((ii(j)) == ip) then
                    ! jsem na diagonale
                diag(ip2) = v(j)
                else
                    if (ilv == 1) then
                        print *, j, x(ip), v(j), x(ii(j)), ii(j)
                    end if
                    x(ip) = x(ip) - v(j)*x(ii(j))
                    if (ilv == 1) then
                        print *, j, x(ip), v(j), x(ii(j)), ii(j)
                    end if
                end if
            end do
            if (ilv == 1) then
                print *,perm1
                print *, perm2
                print *,ip,mask
                print *,ii
                print *,x
            end if
            mask(ip2) = .true.
        end do
        if (ilv == 1) then
            print *, "po primem chodu -------------------------------------"
            print *,x
        end if
        ! 2. D z = y
        x = x/diag ! tady zalezi na poradi, potreba prezkoumat
        if (ilv==1) then
            print *, "po deleni diagonalou --------------------------------"
            print *,x
            print *, diag
        end if
        ! 3. U x = z
        mask = .false.
        mask(perm2(n)) = .true.
        do i=n-1,1,-1
            ip = perm1(i)
            ip2 =perm2(i)
            call ldu%getrow(ip,v,ii,nelem,mask)
            do j=1,nelem
                if (ii(j) == ip2) then
                    ! jsem na diagonale
                diag(ip) = v(j)
                else
                    x(ip) = x(ip) - v(j)*x(ii(j))
                end if
            end do
            if (ilv==1) then
                print *,perm1
                print *,ip,mask
                print *,ii
                print *,x
            end if
            mask(ip2) = .true.
        end do
subroutine, public solvers::ldud (class(matrix), intent(inout) A, type(tcount), intent(inout), optional info, integer, intent(in), optional pivtype, integer, intent(in), optional ilev, integer(kind=ikind), dimension(:), intent(inout), optional, allocatable perm1, integer(kind=ikind), dimension(:), intent(inout), optional, allocatable perm2)
destruktivni LDU rozklad
nahradi vstupni matici jejim LDU rozkladem
 A = L*D*U
 L ... dolni trojuhelnikova matice s jednickami na diagonale
 D ... diagonalni matice
 U ... horni trojuhelnikova matice s jednickami na diagonale
 pro volbu pivota plati nasledujici pravidla
 0 ... zadna
 1 ... uplny vyber hlavniho prvku (nutne obe permutace)
 2 ... sloupcovy vyber hlavniho prvku(nutno perm1)
 3 ... radkovy vyber hlavniho prvku(nutno perm2)
 4 ... diagonalni vyber hlavniho prvku(nutno aspon jedna = obe shodne)
 5 ... diagonalni vyber hlavniho prvku pro minimal degree
 (nutno aspon jedna = obe shodne)
 6 ... rid se predepsanou permutaci
 Pro situace 1 az 6 musi byt pritomny permutacni vektory
 Pokud nejsou pozadavky splneny - zvoli se nejpodobnejsi volba
 pro podrobnost informaci plati
 0 ... tichy chod
 1 ... super podrobne
Parameters
in,out a rozkladana matice, pote s rozkladem
in,out info pocty operaci
in pivtype typ pivotaze
in ilev podrobnost informaci
in,out perm1 permutace pro i
in,out perm2 permutace pro j
Definition at line 377 of file solvers.f90.
References adddegree(), and findpivot().
Referenced by ldu(), and solver_interfaces::ldu_face().
subroutine, public solvers::pcg (class(matrix), intent(in) A, class(matrix), intent(in) Minv, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional itmax1, real(kind=rkind), intent(in), optional reps1, integer, intent(in), optional ilev1, integer(kind=ikind), intent(out), optional itfin1, real(kind=rkind), intent(out), optional repsfin1, real(kind=rkind), intent(out), optional ll1, real(kind=rkind), intent(out), optional ll2, real(kind=rkind), intent(out), optional cond1, type(tcount), intent(out), optional opcnt1, integer, intent(out), optional errcode1)
metoda sdruzenych gradientu Metoda predpodminenych sdruzenych gradientu
Parameters
in a matice soustavy
 musi poskytovat getn, getm, mul (nasobeni vektorem)
in minv matice predpodmineni - ve skutecnosti operator
 musi poskytovat mul (nasobeni vektorem)
in b vektor prave strany
in,out x aproximace reseni, postupne menena
in itmax1 maximalni povoleny pocet iteraci, default = n (Rozmer matice)
in reps1 pozadovana relativni zmena rezidua, default = 1e-6
in ilev1 informacni podrobnost
0 ... pracuj tise
1 ... minimalni informace
10 ... maximalni ukecanost
out itfin1 skutecne provedeny pocet iteraci
out repsfin1 skutecne dosazena relativni zmena residua
out ll1 odhad nejvetsiho vlastniho cisla
out ll2 odhad nejmensiho vlastniho cisla
out cond1 odhad cisla podminenosti : cond1 = ll1/ll2
out opcnt1 celkovy pocet provedenych operaci a cas behu
out errcode1 kod pripadnr chyby
0 ... OK
1 ... matice neni ctvercova
2 ... nesouhlasi b
3 ... nesouhasi x
4 ... ani jeden z vektoru nesouhlasi
5 ... vycerpan povoleny pocet iteraci
6 ... prestalo klesat residuum i energie
Definition at line 1704 of file solvers.f90.
References esteig(), and typy::r4.
        use mtx
        use typy, r4type=>r4
        implicit none
        class(matrix), intent(in) :: a
        class(matrix), intent(in) :: minv
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(in out) :: x
        integer(kind=ikind), intent(in), optional :: itmax1
        real(kind=rkind), intent(in), optional :: reps1
        integer, intent(in), optional :: ilev1
        integer(kind=ikind), intent(out), optional :: itfin1
        real(kind=rkind), intent(out), optional :: repsfin1
        real(kind=rkind), intent(out), optional :: ll1
        real(kind=rkind), intent(out), optional :: ll2
        real(kind=rkind), intent(out), optional :: cond1
        type(tcount), intent(out), optional :: opcnt1
        integer, intent(out), optional :: errcode1
        integer(kind=ikind) :: itmax, cnt, n
        integer :: ilev,rcount, rcount1, errcode
        real(kind=rkind) :: reps, repsfin, r0, r1, r2,r3,r4,l1,l2,t1,t2
        real(kind=rkind) :: wrk, en, enmin, res2min
        real(kind=rkind), dimension(:), allocatable :: res,p,ap,&
        alfa, beta, z
        type(tcount) :: opcnt
        call cpu_time(t1)
        errcode = 0
        if (present(errcode1)) errcode1 = 0
        n = a%getn()
        rcount = 0
        rcount1 = 0
        l1 = 1
        l2 = 1
        if (present(ilev1)) then
        ilev = ilev1
        else
            ilev = 0
        end if
        if (present(itmax1)) then
        itmax = itmax1
        else
            itmax = a%getn()
            if (ilev==10) print *,&
            "nastavuji default hodnotu pro itmax na",itmax
        end if
        allocate(alfa(0:itmax), beta(0:itmax))
        if (a%getn() /= a%getm()) then
            if (present(errcode1)) then
                errcode1 = 1
                if (ilev>0) print *,"CG: Matice neni ctvercova"
            return
            else
                stop "CG: Matice neni ctvercova"
            end if
        end if
        if (a%getn() /= ubound(b,1)) then
            if (present(errcode1)) then
                errcode1 = 2
            if (ilev>0) print *,"CG : nesouhlasi delka prave strany"
            else
                stop "CG: Nesouhlasi delka prave strany"
            end if
        end if
        if (a%getm() /= ubound(x,1)) then
            if (present(errcode1)) then
                if (errcode1==0) then
                    errcode1 = 3
                if (ilev>0) print *,"CG: nesouhlasi delka reseni"
                else
                    errcode1 = 4
                    if (ilev>0) print *,"CG: nesouhlasi delky obou vektoru"
                end if
            else
                stop "CG: Nesouhlasi delka vektoru neznamych"
            end if
        end if
        if (present(errcode1)) then
            if (errcode1>0) return
        end if
        if (present(reps1)) then
        reps = reps1
        else
            reps = 1.0e-6
            if (ilev==10) print *,"nastavuji reps na defaultni hodnotu "&
            , reps
        end if
        ! ted uz je snad vyrizeno vsechno ze vstupu
        ! jdu pocitat
        cnt = 0
        !! Step 1
        res = b - a%mul(x,opcnt)
        z = minv%mul(res)
        r4 = dot_product(res,res)
        r2 = dot_product(res,z)
        r0 = r2
        p = z
        opcnt%ad = n-1
        opcnt%mul = n
        !! Step 2
        do
            !! Step 3
            ap =a%mul(p,opcnt)
            r1 = dot_product(p,ap)
            !!! tady zkontrolovat nulu
            if (r1 == 0.0) then
                ! nasypat vysledky
                ! zatim stopka
                repsfin = 0
                exit
            end if
            wrk = r2/r1
            if (ilev>0) print *,"alfa=",wrk
            alfa(cnt) = wrk
            ! tenhle usek je jen kvuli vypoctu energie
            en = -dot_product(x,b+res) ! je to vychozi energie
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !! Step 4
            x = x + wrk*p
            !! Step 5
            res = res - wrk*ap
            z = minv%mul(res)
            !! Step 6
            r3 = r2
            r4 = dot_product(res,res)
            r2 = dot_product(res,z)
            wrk = r2/r3
            if (ilev>0) print *,"beta=",wrk
            beta(cnt) = wrk
            !! Step 7
            p = res + wrk*p
            opcnt%ad = opcnt%ad + 4*n-2 + 2*n-1
            opcnt%mul = opcnt%mul + 4*n + n
            opcnt%div = opcnt%div + 1
            !! odhadnout vlastni cisla
            call esteig(l1,l2,cnt,alfa,beta)
            print *, "odhad vl. cisel:",l1,l2
            !! hotovo
            cnt = cnt + 1
            if (cnt==1) then
                enmin = en
                res2min = r2
                if (r0==0.0_rkind) then
                    repsfin=0
                    exit
                end if
            end if
            if (en < enmin) then
                rcount = 0
            enmin = en
            else
                rcount = rcount+1
            end if
            if (r2 < res2min) then
                res2min = r2
            rcount1 = 0
            else
                rcount1 = rcount1+1
            end if
            if (ilev>0) print *, cnt,sqrt(r2), reps, en, enmin
            if (cnt == itmax) then
                errcode = 5
                exit
            end if
            repsfin = sqrt(r2/r0)
            if (repsfin < reps) exit
            if ((rcount1>5) .and. (rcount > 5)) then
                errcode = 6
                exit
            end if
        end do
        call cpu_time(t2)
        opcnt%time = t2-t1
        ! vyridit konec
        if (present(opcnt1)) opcnt1 = opcnt
        if (present(errcode1)) errcode1 = errcode
        if (present(itfin1)) itfin1 = cnt
        if (present(repsfin1)) repsfin1 = repsfin
        if (present(ll1)) ll1 = l1
        if (present(ll2)) ll2 = l2
        if (present(cond1)) cond1 = l1/l2
subroutine, public solvers::pcgnormal ()
Definition at line 1919 of file solvers.f90.
subroutine, public solvers::sd (class(matrix), intent(in) A, real(kind=rkind), dimension(:), intent(in) b, real(kind=rkind), dimension(:), intent(inout) x, integer(kind=ikind), intent(in), optional itmax1, real(kind=rkind), intent(in), optional reps1, integer, intent(in), optional ilev1, integer(kind=ikind), intent(out), optional itfin1, real(kind=rkind), intent(out), optional repsfin1, real(kind=rkind), intent(out), optional ll1, real(kind=rkind), intent(out), optional ll2, real(kind=rkind), intent(out), optional cond1, type(tcount), intent(out), optional opcnt1, integer, intent(out), optional errcode1)
metoda nejvetsiho spadu (Steepest descent) podrobnosti viz `Metoda nejvetsiho spadu`
Parameters
in a matice soustavy
 musi poskytovat getn, getm, mul (nasobeni vektorem)
in b vektor prave strany
in,out x aproximace reseni, postupne menena
in itmax1 maximalni povoleny pocet iteraci, default = n (Rozmer matice)
in reps1 pozadovana relativni zmena rezidua, default = 1e-6
in ilev1 informacni podrobnost
0 ... pracuj tise
1 ... minimalni informace
10 ... maximalni ukecanost
out itfin1 skutecne provedeny pocet iteraci
out repsfin1 skutecne dosazena relativni zmena residua
out ll1 odhad nejvetsiho vlastniho cisla
out ll2 odhad nejmensiho vlastniho cisla
out cond1 odhad cisla podminenosti : cond1 = ll1/ll2
out opcnt1 celkovy pocet provedenych operaci a cas behu
out errcode1 kod pripadne chyby
0 ... OK
1 ... matice neni ctvercova
2 ... nesouhlasi b
3 ... nesouhasi x
4 ... ani jeden z vektoru nesouhlasi
5 ... vypocet ukoncen pred dosazenim pozadovane presnosti na itmax
6 ... -||-, ale pro ukonceni poklesu energiie i residua
Definition at line 1037 of file solvers.f90.
References typy::update_info().
        use mtx
        use typy
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), dimension(:), intent(in) :: b
        real(kind=rkind), dimension(:), intent(in out) :: x
        integer(kind=ikind), intent(in), optional :: itmax1
        real(kind=rkind), intent(in), optional :: reps1
        integer, intent(in), optional :: ilev1
        integer(kind=ikind), intent(out), optional :: itfin1
        real(kind=rkind), intent(out), optional :: repsfin1
        real(kind=rkind), intent(out), optional :: ll1
        real(kind=rkind), intent(out), optional :: ll2
        real(kind=rkind), intent(out), optional :: cond1
        type(tcount), intent(out), optional :: opcnt1
        integer, intent(out), optional :: errcode1
        integer(kind=ikind) :: itmax, cnt, n
        integer :: ilev,rcount, rcount1, errcode
        real(kind=rkind) :: reps, repsfin, r0, r1, r2,l1,l2,t1,t2
        real(kind=rkind) :: wrk, en, enmin, res2min
        real(kind=rkind), dimension(:), allocatable :: res
        type(tcount) :: opcnt
        call cpu_time(t1)
        errcode = 0
        n = a%getn()
        rcount = 0
        rcount1 = 0
        l1 = 1
        l2 = 1
        if (present(ilev1)) then
        ilev = ilev1
        else
            ilev = 0
        end if
        if (present(errcode1)) errcode1 = 0
        if (present(itmax1)) then
        itmax = itmax1
        else
            itmax = a%getn()
            if (ilev==10) print *,&
            "nastavuji default hodnotu pro itmax na",itmax
        end if
        if (a%getn() /= a%getm()) then
            if (present(errcode1)) then
                errcode1 = 1
                if (ilev>0) print *,"SD: Matice neni ctvercova"
            return
            else
                stop "SD: Matice neni ctvercova"
            end if
        end if
        if (a%getn() /= ubound(b,1)) then
            if (present(errcode1)) then
                errcode1 = 2
            if (ilev>0) print *,"SD : nesouhlasi delka prave strany"
            else
                stop "SD: Nesouhlasi delka prave strany"
            end if
        end if
        if (a%getm() /= ubound(x,1)) then
            if (present(errcode1)) then
                if (errcode1==0) then
                    errcode1 = 3
                if (ilev>0) print *,"SD: nesouhlasi delka reseni"
                else
                    errcode1 = 4
                    if (ilev>0) print *,"SD: nesouhlasi delky obou vektoru"
                end if
            else
                stop "SD: Nesouhlasi delka vektoru neznamych"
            end if
        end if
        if (present(errcode1)) then
            if (errcode1>0) return
        end if
        if (present(reps1)) then
        reps = reps1
        else
            reps = 1.0e-6
            if (ilev==10) print *,"nastavuji reps na defaultni hodnotu "&
            , reps
        end if
        ! ted uz je snad vyrizeno vsechno ze vstupu
        ! jdu pocitat
        cnt = 0
        if (ilev >0) print *,"SD zacina"
        do
            res = b - a%mul(x,opcnt)
            r1 = dot_product(res,a%mul(res,opcnt))
            r2 = dot_product(res,res)
            wrk = r2/r1
            ! tenhle usek je jen kvuli vypoctu energie
            en = -dot_product(x,b+res) ! je to vychozi energie
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            x = x + wrk * res
            opcnt%ad = opcnt%ad + 4*n-2 +2*n-1
            opcnt%mul = opcnt%mul + 3*n + n
            opcnt%div = opcnt%div + 1
            cnt = cnt + 1
            if (cnt==1) then
                enmin = en
                r0 = r2
                res2min = r2
                if (r0==0.0_rkind) then
                    repsfin=0
                    exit
                end if
            end if
            if (en < enmin) then
                rcount = 0
            enmin = en
            else
                rcount = rcount+1
            end if
            if (r2 < res2min) then
                res2min = r2
            rcount1 = 0
            else
                rcount1 = rcount1+1
            end if
            if (ilev>0) print *, cnt,sqrt(r2), reps, en, enmin
            if (cnt == itmax) then
                errcode = 5
                exit
            end if
            repsfin = sqrt(r2/r0)
            if (repsfin < reps) exit
            if ((rcount1>5) .and. (rcount > 5)) then
                errcode = 6
                exit
            end if
        end do
        call cpu_time(t2)
        opcnt%time = t2-t1
        ! vyridit konec
        if (present(opcnt1)) call update_info(opcnt1,opcnt)
        if (present(errcode1)) errcode1 = errcode
        if (present(itfin1)) itfin1 = cnt
        if (present(repsfin1)) repsfin1 = repsfin
        if (present(ll1)) ll1 = l1 ! tohle zatim nepocita
        if (present(ll2)) ll2 = l2
        if (present(cond1)) cond1 = l1/l2
        if (ilev>0) print *,"SD konci"
subroutine, public solvers::sdnormal ()
Definition at line 1212 of file solvers.f90.
subroutine, public solvers::split (class(matrix), intent(in) LDU, class(matrix), intent(out) L, class(matrix), intent(out) D, class(matrix), intent(out) U, integer(kind=ikind), dimension(:), intent(in) p1, integer(kind=ikind), dimension(:), intent(in) p2)
rozdeli matici s LDU rozkladem na jednotlive komponenty
pokud jsou dodany permutace, tak plati
Parameters
in ldu LDU dekompozice
out l L cast rozkladu
out d D cast rozkladu
out u U cast rozkladu
in p1 Leva permutace
in p2 Prava permutace
Definition at line 812 of file solvers.f90.
        use typy
        use mtx
        class(matrix), intent(in) :: ldu
        class(matrix), intent(out) :: l
        class(matrix), intent(out) :: d
        class(matrix), intent(out) :: u
        integer(Kind=ikind), dimension(:), intent(in) :: p1
        integer(Kind=ikind), dimension(:), intent(in) :: p2
        integer(kind=ikind) :: n,m,i,j,i1,j1
        !print *,"split zacina"
        call l%clone(ldu)
        call d%clone(ldu)
        call u%clone(ldu)
        n=ldu%getn()
        m=ldu%getm()
        do i=1,min(n,m)
            call l%set(1.0_rkind,p1(i),p2(i))
            call u%set(1.0_rkind,p1(i),p2(i))
            call d%set(ldu%get(p1(i),p2(i)),p2(i),p1(i))
            do j=i+1,m
                i1 = p1(i)
                j1 = p2(j)
                call u%set(ldu%get(i1,j1),i1,j1)
            end do
            do j=i+1,n
                i1 = p1(j)
                j1 = p2(i)
                call l%set(ldu%get(i1,j1),i1,j1)
            end do
        end do
real(kind=rkind) function, private solvers::vycdet (real(kind=rkind), intent(in) x, real(kind=rkind), dimension(0:), intent(in) a, real(kind=rkind), dimension(0:), intent(in) b, integer(kind=ikind), intent(in) n) [private]
Definition at line 1922 of file solvers.f90.
Referenced by esteig().
        use typy
        implicit none
        real(kind=rkind), intent(in) :: x
        real(kind=rkind), dimension(0:), intent(in) :: a
        real(kind=rkind), dimension(0:), intent(in) :: b
        integer(kind=ikind), intent(in) :: n
        real(kind=rkind) :: y, f1,f2,f3
        integer(kind=ikind) :: i
        f1 = 1/a(0)-x
        if (n==0) then
            y = f1
            return
        end if
        f2 = f1*(1/a(1)+b(0)/a(0)-x)-b(0)/a(0)/a(0)
        if (n==1) then
            y = f2
            return
        end if
        do i=2,n
            f3 = (1/a(i)+b(i-1)/a(i-1)-x)*f2-b(i-1)/a(i-1)/a(i-1)*f1
            f1 = f2
            f2 = f3
        end do
        y = f3