re_reader Module Reference
Functions/Subroutines
subroutine, public res_read (pde_loc)
opens and reads water.conf/matrix.conf, input data for the Richards equation in single mode, Richards equation with the dual porosity regime - matrix domain
Function/Subroutine Documentation
subroutine, public re_reader::res_read (class(pde_str), intent(inout) pde_loc)
opens and reads water.conf/matrix.conf, input data for the Richards equation in single mode, Richards equation with the dual porosity regime - matrix domain
Definition at line 9 of file re_reader.f90.
References readtools::comment(), globals::drutes_config, globals::elements, readtools::file_error(), re_globals::file_waterm, core_tools::find_unit(), globals::maxpress, readtools::readbcvals(), readtools::set_tensor(), re_globals::vgmatrix, and globals::www.
Referenced by re_pointers::allrepointers().
      use typy
      use global_objs
      use pde_objs
      use globals
      use re_globals
      use core_tools
      use readtools
      
      class(pde_str), intent(in out) :: pde_loc
      integer :: ierr, i, j, filewww
      integer(kind=ikind) :: n
      character(len=1) :: yn
      character(len=4096) :: msg
      real(kind=rkind), dimension(:), allocatable :: tmpdata
      pde_loc%problem_name(1) = "RE_matrix"
      pde_loc%problem_name(2) = "Richards' equation"
      pde_loc%solution_name(1) = "press_head" !nazev vystupnich souboru
      pde_loc%solution_name(2) = "h [L]" !popisek grafu
      pde_loc%flux_name(1) = "flux"
      pde_loc%flux_name(2) = "Darcian flow [L.T^{-1}]"
      pde_loc%mass_name(1) = "theta"
      pde_loc%mass_name(2) = "theta [-]"
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !water.conf/matrix.conf
      call find_unit(file_waterm, 200)
      open(unit=file_waterm, file="drutes.conf/water.conf/matrix.conf", action="read", status="old", iostat
       = ierr)
      if (ierr /= 0) then
        print *, "missing drutes.conf/water.conf/matrix.conf file"
        error stop
      end if
      
      write(msg, *) "define method of evaluation of constitutive functions for the Richards equation",
      new_line("a"), &
        " 0 - direct evaluation (not recommended, extremely resources consuming due to complicated
       exponential functions)", &
        new_line("a"), &
        " 1 - function values are precalculated in program initialization and values between are linearly
       approximated"
      
      call fileread(drutes_config%fnc_method, file_waterm, ranges=(/0_ikind,1_ikind/),errmsg=msg)
      call fileread(maxpress, file_waterm, ranges=(/-huge(0.0_rkind), huge(0.0_rkind)/), &
        errmsg="set some positive nonzero limit for maximal suction pressure (think in absolute values) ")
        maxpress = abs(maxpress)
      call fileread(drutes_config%fnc_discr_length, file_waterm, ranges=(/tiny(0.0_rkind),
      maxpress/), &
        errmsg="the discretization step for precalculating constitutive functions must be positive and
       smaller &
        then the bc")
      
      call fileread(n, file_waterm)
      
      write(msg, fmt=*) "ERROR!! incorrect number of materials in drutes.conf/water.conf/matrix.conf &
        the mesh defines", maxval(elements%material) , "materials, and your input file defines", n,
      "material(s)."
        
      backspace(file_waterm)
     
      call fileread(n, file_waterm, ranges=(/1_ikind*maxval(elements%material),1_ikind*maxval(
      elements%material)/),&
        errmsg=trim(msg))
      if (.not. allocated(vgmatrix)) then
        allocate (vgmatrix(n))
        do i=1, ubound(vgmatrix,1)
          allocate(vgmatrix(i)%Ks_local(drutes_config%dimen))
          allocate(vgmatrix(i)%Ks(drutes_config%dimen, drutes_config%dimen))
          j = max(1,drutes_config%dimen-1)
          allocate(vgmatrix(i)%anisoangle(j))
        end do
      end if
      write(msg, *) "HINT 1 : check number of layers in matrix", new_line("a"), &
         " HINT 2 : have you specified all values in the following order: ", new_line("a"), &
         " alpha n m theta_r theta_s S_s "
      allocate(tmpdata(6))
      do i = 1, ubound(vgmatrix,1)
        call fileread(tmpdata, errmsg=msg, fileid=file_waterm, checklen=.true.)
        vgmatrix(i)%alpha=tmpdata(1)
        vgmatrix(i)%n=tmpdata(2)
        vgmatrix(i)%m=tmpdata(3)
        vgmatrix(i)%thr=tmpdata(4)
        vgmatrix(i)%ths=tmpdata(5)
        vgmatrix(i)%Ss=tmpdata(6)
      end do
      
     
      write(msg, *) "HINT: check number of records of anisothropy description in water.conf/matrix.conf!!",
       &
        new_line("a") , &
        " for 3D problem you must specify exactly Kxx, Kyy and Kzz values.", new_line("a"), &
        " Obviously for 2D problem there must be exactly only Kxx and Kzz value, analogicaly for 1D
       problem", &
        new_line("a") , &
        " for 2D problem supply only 1 angle, for 3D problem supply 2 angles, and", new_line("a"), &
        " for 1D problem the angle value defines the angle between the VERTICAL and the flow
       trajectory", new_line("a"), &
        " (carefull some other softwares consider HORIZONTAL!!)"
        
      deallocate(tmpdata)
      
      select case(drutes_config%dimen)
        case(1,2)
          allocate(tmpdata(drutes_config%dimen+1))
        case(3)
          allocate(tmpdata(drutes_config%dimen+2))
      end select
      
      do i = 1, ubound(vgmatrix,1)
        call fileread(tmpdata, file_waterm, errmsg=msg, checklen=.true.)
        
        if (drutes_config%dimen > 1) then
          vgmatrix(i)%anisoangle(:) = tmpdata(1:drutes_config%dimen-1)
        else
          vgmatrix(i)%anisoangle(:) = tmpdata(1)
        end if
        
        select case(drutes_config%dimen)
          case(1)
            vgmatrix(i)%Ks_local(:) = tmpdata(2)
          case(2)
            vgmatrix(i)%Ks_local(:) = tmpdata(2:3)
          case(3)
            vgmatrix(i)%Ks_local(:) = tmpdata(3:5)
        end select
        call set_tensor(vgmatrix(i)%Ks_local(:), vgmatrix(i)%anisoangle(:),
      vgmatrix(i)%Ks)
      end do
      
      do i=1, ubound(vgmatrix,1)
        call fileread(vgmatrix(i)%sinkterm, file_waterm, errmsg="Have you defined sink term for each
       layer?")
      end do
      
      if (.not. www) then
        do i=1, ubound(vgmatrix,1)
          call comment(file_waterm)
          read(unit=file_waterm, fmt= *, iostat=ierr) vgmatrix(i)%initcond,
      vgmatrix(i)%icondtype, &
                                                        yn, vgmatrix(i)%rcza_set%val
          select case(yn)
            case("y")
              vgmatrix(i)%rcza_set%use = .true.
            case("n")
              vgmatrix(i)%rcza_set%use = .false.
            case default
              write(msg, fmt=*) "type [y/n] value for using the retention curve zone approach at layer:", i
              call file_error(file_waterm, msg)
          end select
          select case(vgmatrix(i)%icondtype)
            case("H_tot", "hpres", "theta","input")
              CONTINUE
            case default
              print *, "you have specified wrong initial condition type keyword"
              print *, "the allowed options are:"
              print *, " H_tot = total hydraulic head"
              print *, " hpres = pressure head"
              print *, " theta = water content"
              print *, " input = read from input file (drutes output file)"
              call file_error(file_waterm)
          end select
          if (ierr /= 0) then
            print *, "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            print *, "HINT: check number of line records of initial conditions in water.conf/matrix.conf!"
            print *, "----------------------------------------"
            call file_error(file_waterm)
          end if
        end do
      else
        do i=1, ubound(vgmatrix,1)
          call comment(file_waterm)
          read(unit=file_waterm, fmt= *, iostat=ierr) vgmatrix(i)%initcond,
      vgmatrix(i)%icondtype
          vgmatrix(i)%rcza_set%use = .false.
          select case(vgmatrix(i)%icondtype)
            case("H_tot", "hpres", "theta","input")
              CONTINUE
            case default
              print *, "you have specified wrong initial condition type keyword"
              print *, "the allowed options are:"
              print *, " H_tot = total hydraulic head"
              print *, " hpres = pressure head"
              print *, " theta = water content"
              print *, " input = read from input file (drutes output file)"
              call file_error(file_waterm)
          end select
          if (ierr /= 0) then
            print *, "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            print *, "HINT: check number of line records of initial conditions in water.conf/matrix.conf!"
            print *, "----------------------------------------"
            call file_error(file_waterm)
          end if
        end do
      end if
   
        
        
      call fileread(n, file_waterm, ranges=(/1_ikind, huge(1_ikind)/), &
        errmsg="at least one boundary must be specified (and no negative values here)")
      call readbcvals(unitw=file_waterm, struct=pde_loc%bc, dimen=n, &
                      dirname="drutes.conf/water.conf/")
                      
        close(file_waterm)