heat_pointers Module Reference
heat conduction based on (Sopohocleous, 1979)
 C\frac{\partial T}{\partial t} = \mathbf{\lambda} \Delta T - C_w \nabla \cdot \vec{q} T 
Functions/Subroutines
subroutine, public heat (pde_loc)
real(kind=rkind) function heat_source (pde_loc, layer, quadpnt, x)
Detailed Description
heat conduction based on (Sopohocleous, 1979)
 C\frac{\partial T}{\partial t} = \mathbf{\lambda} \Delta T - C_w \nabla \cdot \vec{q} T 
Function/Subroutine Documentation
subroutine, public heat_pointers::heat (class(pde_str), intent(inout) pde_loc)
Definition at line 11 of file heat_pointers.f90.
References heat_fnc::heat_conduct(), heat_fnc::heat_convect(), heat_fnc::heat_dirichlet(), heat_fnc::heat_elast(), heat_fnc::heat_flux(), heat_fnc::heat_icond(), heat_fnc::heat_neumann(), heat_reader::heat_read(), heat_fnc::heat_source(), and pde_objs::pde_common.
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use heat_fnc
      use heat_reader
      
      class(pde_str), intent(in out) :: pde_loc
      integer(kind=ikind) :: i
      
      call heat_read(pde_loc)
      
      pde_common%nonlinear = .false.
            
      pde_loc%pde_fnc(pde_loc%order)%dispersion => heat_conduct
      
      pde_loc%pde_fnc(pde_loc%order)%convection => heat_convect
      pde_loc%pde_fnc(pde_loc%order)%elasticity => heat_elast
            
      pde_loc%pde_fnc(pde_loc%order)%zerord => heat_source
      
          
      do i=lbound(pde_loc%bc,1), ubound(pde_loc%bc,1)
        select case(pde_loc%bc(i)%code)
          case(1)
            pde_loc%bc(i)%value_fnc => heat_dirichlet
          case(2)
            pde_loc%bc(i)%value_fnc => heat_neumann
        end select
      end do
        
      pde_loc%flux => heat_flux
      
      pde_loc%initcond => heat_icond
      
    
real(kind=rkind) function heat_pointers::heat_source (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 51 of file heat_pointers.f90.
References ade_globals::adepar, and pde_objs::pde.
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      integer(kind=ikind) :: n, i
      real(kind=rkind) :: theta
      
      if (pde_loc%order == 2) then
        theta = pde(1)%mass(layer, quadpnt)
      else
        theta = adepar(layer)%water_cont
      end if
      
       val = 0.0_rkind
       do i=1, ubound(adepar(layer)%orders,1)
        if (abs(adepar(layer)%orders(i)) < 100*epsilon(1.0_rkind)) then
          val = val + theta*adepar(layer)%lambda(i)
        end if
      end do
      
      