debug_tools Module Reference
Data Types
interface printmtx
Functions/Subroutines
subroutine, private print_quadpnt (quadpnt, filunit, name)
subroutine print_sparse_matrix (A, filunit, name)
subroutine, private print_real_matrix (a, filunit, name)
subroutine, private print_int_matrix (a, filunit, name)
subroutine, private print_real_vector (V, filunit, name)
vytiskne vektor
subroutine, private print_real_vector4 (V, filunit, name)
vytiskne vektor
subroutine, private print_int_vector (V, filunit, name)
subroutine print_smartmatrix_i (array, filunit, name)
subroutine print_smartarray_i (array, filunit, name)
subroutine print_logical_array (array, filunit, name)
subroutine, public wait (ch)
Function/Subroutine Documentation
subroutine, private debug_tools::print_int_matrix (integer(kind=ikind), dimension(:,:), intent(inout) a, integer, intent(in), optional filunit, character(len=*), intent(in), optional name) [private]
Definition at line 184 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
      use typy
      use globals
      use core_tools
      
      integer(kind=ikind), dimension(:,:), intent(in out) :: a
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      integer(kind=ikind) :: i
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
      
      
      do i=lbound(a,1), ubound(a,1)
        write(unit=filloc, fmt=*) i, "|", a(i,:)
      end do
      if (terminal /= filloc) then
        close(filloc)
      else
        call flush(terminal)
      end if
      
subroutine, private debug_tools::print_int_vector (integer(kind=ikind), dimension(:), intent(in) V, integer, intent(in), optional filunit, character(len=*), intent(in), optional name) [private]
Parameters
in v vektor k tisknuti
Definition at line 329 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
    ! vytiskne vektor, pocet sloupcu tisku je nc
      use typy
      use globals
      use core_tools
      
      !parametry
      integer(kind=ikind), dimension(:), intent(in) :: v
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      integer(kind=ikind) :: i
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
      do i=lbound(v,1),ubound(v,1)
         write(unit=filloc, fmt=*) "radek:", i, "hodnota:", v(i)
      end do
  
      if (terminal /= filloc) then
        close(filloc)
      else
        call flush(terminal)
      end if
  
subroutine debug_tools::print_logical_array (logical, dimension(:), intent(in) array, integer, intent(in), optional filunit, character(len=*), intent(in), optional name)
Parameters
in array vektor k tisknuti
Definition at line 464 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
      use typy
      use globals
      use core_tools
      
      !parametry
      logical, dimension(:), intent(in) :: array
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      integer(kind=ikind) :: i
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
      
      do i=1, ubound(array,1)
        write(unit=filloc, fmt=*) i, "|", array(i)
      end do
      
subroutine, private debug_tools::print_quadpnt (type(integpnt_str), intent(in) quadpnt, integer, intent(in), optional filunit, character(len=*), intent(in), optional name) [private]
Definition at line 25 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
      use global_objs
      use core_tools
      use globals
      
      type(integpnt_str), intent(in) :: quadpnt
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      
      integer :: filloc
      integer :: ierr
      logical :: op
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
      
      
      write(unit=filloc, fmt=*) "type:", quadpnt%type_pnt
      
      if (quadpnt%type_pnt == "ndpt" .or. quadpnt%type_pnt == "obpt") then
        write(unit=filloc, fmt=*) "order of point:", quadpnt%order
      end if
      
      if (quadpnt%type_pnt == "gqnd") then
        write(unit=filloc, fmt=*) "order of element:", quadpnt%element
      end if
      
      write(unit=filloc, fmt=*) "column:", quadpnt%column
      
      if (quadpnt%ddlocal) then
        write(unit=filloc, fmt=*) "using subdomain local data"
        write(unit=filloc, fmt=*) "subdomain id", quadpnt%subdom
        if (quadpnt%extended) then
          write(unit=filloc, fmt=*) "node from extended subdomain (see subcycling man)"
        else
          write(unit=filloc, fmt=*) "node inside the subdomain"
        end if
      else
        write(unit=filloc, fmt=*) "using global data"
      end if
      
      if (.not. quadpnt%globtime) then
        write(unit=filloc, fmt=*) "not using the global time, solution will be interpolated"
        write(unit=filloc, fmt=*) "time 4 use:", quadpnt%time4eval
      else
        write(unit=filloc, fmt=*) "using the global time"
      end if
      
  
      if (terminal /= filloc) then
        close(filloc)
      else
        call flush(terminal)
      end if
      
subroutine, private debug_tools::print_real_matrix (real(kind=rkind), dimension(:,:), intent(inout) a, integer, intent(in), optional filunit, character(len=*), intent(in), optional name) [private]
Definition at line 139 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
      use typy
      use globals
      use core_tools
      real(kind=rkind), dimension(:,:), intent(in out) :: a
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      integer(kind=ikind) :: i
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
      
      
      do i=lbound(a,1), ubound(a,1)
        write(unit=filloc, fmt=*) i, "|", a(i,:)
      end do
      if (terminal /= filloc) then
        close(filloc)
      else
        call flush(terminal)
      end if
      
subroutine, private debug_tools::print_real_vector (real(kind=rkind), dimension(:), intent(inout) V, integer, intent(in), optional filunit, character(len=*), intent(in), optional name) [private]
vytiskne vektor
Parameters
in,out v vektor k tisknuti
Definition at line 232 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
    ! vytiskne vektor, pocet sloupcu tisku je nc
      use typy
      use globals
      use core_tools
      
      !parametry
      real(kind=rkind), dimension(:), intent(in out) :: v
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      integer(kind=ikind) :: i
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
     
      do i=lbound(v,1),ubound(v,1)
         write(unit=filloc, fmt=*) "radek:", i, "hodnota:", v(i)
      end do
      if (terminal /= filloc) then
        close(filloc)
      else
        call flush(terminal)
      end if
  
subroutine, private debug_tools::print_real_vector4 (real(4), dimension(:), intent(inout) V, integer, intent(in), optional filunit, character(len=*), intent(in), optional name) [private]
vytiskne vektor
Parameters
in,out v vektor k tisknuti
Definition at line 282 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
    ! vytiskne vektor, pocet sloupcu tisku je nc
      use typy
      use globals
      use core_tools
      
      !parametry
      real(4), dimension(:), intent(in out) :: v
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      integer(kind=ikind) :: i
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
     
      do i=lbound(v,1),ubound(v,1)
         write(unit=filloc, fmt=*) "radek:", i, "hodnota:", v(i)
      end do
      if (terminal /= filloc) then
        close(filloc)
      else
        call flush(terminal)
      end if
  
subroutine debug_tools::print_smartarray_i (class(smartarray_int), intent(in) array, integer, intent(in), optional filunit, character(len=*), intent(in), optional name)
Parameters
in array vektor k tisknuti
Definition at line 422 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
      use typy
      use globals
      use core_tools
      
      !parametry
      class(smartarray_int), intent(in) :: array
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      integer(kind=ikind) :: i
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
      
      do i=1, array%pos
        write(unit=filloc, fmt=*) i, "|", array%data(i)
      end do
      
      call flush(filloc)
      
subroutine debug_tools::print_smartmatrix_i (class(smartarray_int), dimension(:), intent(in) array, integer, intent(in), optional filunit, character(len=*), intent(in), optional name)
Parameters
in array vektor k tisknuti
Definition at line 376 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
      use typy
      use globals
      use core_tools
      
      !parametry
      class(smartarray_int), dimension(:), intent(in) :: array
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      integer(kind=ikind) :: i
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
            
      do i=lbound(array,1),ubound(array,1)
        if (.not. allocated(array(i)%data)) then
          print *, "no values to print at row:", i
        else
          write(unit=filloc, fmt=*) i, "|", array(i)%data(1:array(i)%pos)
          write(unit=filloc, fmt=*) "-----------------------------------------------"
        end if
      end do
      
      call flush(filloc)
      
subroutine debug_tools::print_sparse_matrix (class(smtx), intent(inout) A, integer, intent(in), optional filunit, character(len=*), intent(in), optional name)
Definition at line 97 of file debug_tools.f90.
References core_tools::find_unit(), and globals::terminal.
      use sparsematrix
      use mtxiotools
      use globals
      use core_tools
      class(smtx), intent(in out) :: a
      integer, intent(in), optional :: filunit
      character(len=*), intent(in), optional :: name
      integer :: filloc
      integer :: ierr
      logical :: op
      
      if (present(name)) then
        call find_unit(filloc)
        open(unit=filloc, file=name, action="write", status="replace", iostat=ierr)
        if (ierr /= 0) then
          print *, "unable to open dump file, called from debug_tools::printmtx"
          error stop
        end if
      else if (present(filunit)) then
        filloc = filunit
        inquire(unit=filloc, opened=op)
        if (.not. op) then
          print *, "file not opened, called from debug_tools::printmtx"
          error stop
        end if
      else
        filloc = terminal
      end if
      
      call a%print()
      if (terminal /= filloc) then
        close(filloc)
      else
        call flush(terminal)
      end if
subroutine, public debug_tools::wait (character(len=*), intent(in), optional ch)
Definition at line 506 of file debug_tools.f90.
References globals::terminal.
Referenced by schwarz_dd2subcyc::schwarz_subcyc().
      use globals
      character(len=*), optional, intent(in) :: ch
      
      if (present(ch)) then
        print *, "-------------"
        print *, trim(ch)
        print *, "-------------"
      end if
      print *, "press [ENTER] to continue"
  
      call flush(terminal)
  
      read(*,*)