dual_globals Module Reference
Data Types
type exch_k
exchange parameters
type expar
exchange parameters according to Gerke and van Genuchten (1993)
type soilpar
defining soil parameters
Variables
integer(kind=ikind), public coup_model
coupling model type
real(kind=rkind), public disttozero
distance of top boundary to zero z-coordinate
real(kind=rkind), public infweight
Use-defined infiltration weight for boundary condition.
character(len=50) fracfile
in progress: switching for different input files for fractrue and matrix (not implemented yet)
character(len=50) matfile
type(soilpar), dimension(:), allocatable, public vgmatrix
soil and layer parameters
type(exch_k), dimension(:), allocatable, public vgexchange
type(soilpar), dimension(:), allocatable, public vgfracture
type(expar), dimension(:), allocatable, public exchange
integer(kind=ikind), public retc_method
formula of the retention curve
Variable Documentation
integer(kind=ikind), public dual_globals::coup_model
coupling model type
Definition at line 45 of file Re_dual_globals.f90.
Referenced by dual_coup::dual_coup_min(), dual_coup::dual_coupling(), dual_tab::dual_coupling_tab(), and re_dual_reader::re_dual_var().
  integer(kind=ikind), public :: coup_model
real(kind=rkind), public dual_globals::disttozero
distance of top boundary to zero z-coordinate
Definition at line 47 of file Re_dual_globals.f90.
Referenced by dual_por::dual_inicond(), and re_dual_reader::re_dual_var().
  real(kind=rkind),public :: disttozero
type(expar), dimension(:), allocatable, public dual_globals::exchange
Definition at line 71 of file Re_dual_globals.f90.
Referenced by dual_coup::dual_coup_min(), dual_coup::dual_coupling(), dual_tab::dual_coupling_tab(), dual_por::dual_mualem(), re_dual_bc::dual_neumann_bc(), dual_por::dual_ret_cap(), dual_tab::dual_ret_cap_tab(), re_dual_reader::re_dual_var(), and dual_por::vangen_d().
  type(expar), dimension(:), allocatable, public :: exchange
character(len=50) dual_globals::fracfile
in progress: switching for different input files for fractrue and matrix (not implemented yet)
Definition at line 51 of file Re_dual_globals.f90.
  character(len=50) :: fracfile, matfile
real(kind=rkind), public dual_globals::infweight
Use-defined infiltration weight for boundary condition.
Definition at line 49 of file Re_dual_globals.f90.
Referenced by re_dual_bc::dual_atmospheric(), re_dual_bc::inf_neumann_bc(), re_dual_reader::re_dual_readf(), and re_dual_reader::re_dual_readm().
  real(kind=rkind),public ::infweight
character(len=50) dual_globals::matfile
Definition at line 51 of file Re_dual_globals.f90.
integer(kind=ikind), public dual_globals::retc_method
formula of the retention curve
Definition at line 75 of file Re_dual_globals.f90.
  integer(kind=ikind), public :: retc_method
type(exch_k), dimension(:), allocatable, public dual_globals::vgexchange
Definition at line 69 of file Re_dual_globals.f90.
Referenced by dual_coup::dual_coupling(), dual_coup::dual_coupling_k(), dual_tab::dual_coupling_tab(), and re_dual_reader::re_dual_var().
  type(exch_k), dimension(:), allocatable, public :: vgexchange
type(soilpar), dimension(:), allocatable, public dual_globals::vgfracture
Definition at line 70 of file Re_dual_globals.f90.
Referenced by dual_coup::dual_coup_min(), dual_tab::dual_coupling_tab(), dual_por::dual_inicond(), dual_por::dual_mualem(), dual_tab::dual_mualem_tab(), dual_por::dual_ret_cap(), dual_tab::dual_ret_cap_tab(), dual_tab::dual_tabvalues(), re_dual_reader::re_dual_var(), dual_por::vangen_d(), and dual_tab::vangen_d_tab().
  type(soilpar), dimension(:), allocatable, public :: vgfracture
type(soilpar), dimension(:), allocatable, public dual_globals::vgmatrix
soil and layer parameters
Definition at line 68 of file Re_dual_globals.f90.
Referenced by dual_coup::dual_coup_min(), dual_tab::dual_coupling_tab(), dual_por::dual_inicond(), dual_por::dual_mualem(), dual_tab::dual_mualem_tab(), dual_por::dual_ret_cap(), dual_tab::dual_ret_cap_tab(), dual_tab::dual_tabvalues(), re_dual_reader::re_dual_var(), dual_por::vangen_d(), and dual_tab::vangen_d_tab().
  type(soilpar), dimension(:), allocatable, public :: vgmatrix