simplelinalg Module Reference
Functions/Subroutines
subroutine, public diag_precond (a, x, prmt, mode)
right hand side diagonal preconditioner - preprocessor and postprocesor preforms the diagonal matrix scaling as described in Kuraz & Mayer: Algorithms for solving Darcian flow in structured porous media
subroutine, public invert_matrix (A)
subroutine, that evaluates inverse matrix up to dimension 3
real(kind=rkind) function, private determinant (A)
the matrix dimension must be exactly (2,2) or (3,3)
integer(kind=ikind) function, public factorial (in)
Function/Subroutine Documentation
real(kind=rkind) function, private simplelinalg::determinant (real(kind=rkind), dimension(:,:), intent(in) A) [private]
the matrix dimension must be exactly (2,2) or (3,3)
Definition at line 149 of file simplelinalg.f90.
Referenced by invert_matrix().
      use typy
      real(kind=rkind) :: det
      real(kind=rkind), dimension(:,:), intent(in) :: a
      if (ubound(a,1) /= ubound(a,2)) then
        print *, "ERROR: input matrix is not a square matrix, called from fem_tools::determinant()"
        error stop
      end if
      select case(ubound(a,1))
        case(2)
              det = a(1,1)*a(2,2) - a(1,2)*a(2,1)
        case(3)
              det = a(1,1)*a(2,2)*a(3,3) + a(1,2)*a(2,3)*a(3,1) + a(1,3)*a(2,1)*a(3,2)&
                  - a(1,3)*a(2,2)*a(3,1) - a(1,2)*a(2,1)*a(3,3) - a(1,1)*a(2,3)*a(3,2)
        case default
              print *, "ERROR: incorrect matrix dimension, called from fem_tools::determinant()"
              error stop
      end select
subroutine, public simplelinalg::diag_precond (class(extsmtx), intent(inout) a, real(kind=rkind), dimension(:), intent(inout), optional x, integer(kind=ikind), dimension(:), intent(in), optional prmt, integer, intent(in) mode)
right hand side diagonal preconditioner - preprocessor and postprocesor preforms the diagonal matrix scaling as described in Kuraz & Mayer: Algorithms for solving Darcian flow in structured porous media
the postprocesor performs following operation with the vector of solution
 \mathbf{x} = \mathbf{x} \times \frac{1}{\mathbf{a_{diag}}} 
 where a_diag is a vector of diagonal values in solution matrix
 parameter mode defines the preprocessing or postprocessing mode for this routine
Parameters
in,out a matrix in sparse format
in,out x the solution vector to be passed into zero iteration, it is formed out of the solution in previous time step level
in prmt permut vector, usefull for domain decomposition
Definition at line 19 of file simplelinalg.f90.
References globals::drutes_config.
Referenced by schwarz_dd::schwarz_picard(), schwarz_dd_time_test::schwarzloc(), femmat::solve_picard(), schwarz_dd2subcyc::solve_subdomain(), and subcycling::subcyc_schwarz().
      use typy
      use sparsematrix
      use globals
      use globals2d
      use debug_tools
      class(extsmtx), intent(in out) :: a
      real(kind=rkind), dimension(:), intent(in out), optional :: x
      integer(kind=ikind), dimension(:), intent(in), optional :: prmt
      integer, intent(in) :: mode
      integer(kind=ikind), dimension(:), allocatable, save :: indexes
      integer(kind=ikind) :: i, finn, finm, nelem, j, k, diag_row
      real(kind=rkind), dimension(:), allocatable, save :: values
      real(kind=rkind) :: tmp
      
      finn=a%getn()
      finm=a%getm()
      if (.not. allocated(indexes)) then
        allocate(indexes(2*drutes_config%dimen+1))
        allocate(values(2*drutes_config%dimen+1))
      end if
      if (.not. allocated(a%weight)) then
        allocate(a%weight(finm))
      end if
      
      select case(mode)
        case(1)
            a%weighted = .true.
            do i=1, finm
              if (present(prmt)) then
                diag_row = prmt(i)
              else
                diag_row = i
              end if
              a%weight(i) = 1.0_rkind/a%get(diag_row,i)
            end do
            do i=1, finn
              call a%getrow(i=i, v=values, jj=indexes, nelem=nelem)
              do k=1, nelem
                j = indexes(k)
                tmp = a%get(i,j)
                call a%set(tmp*a%weight(j),i,j)
              end do
            end do
    
            if (present(x)) then
              x(1:finm) = x(1:finm)/a%weight(1:finm)
            end if
  
  ! do i=1, ubound(a%vals,1)
  ! if (a%jj(i) > 0) then
  ! a%vals(i) = a%weight(a%jj(i))*a%vals(i)
  ! end if
  ! end do
  
  !
  ! x(:,4) = x(:,3)/a%weight(1:ubound(x,1))
              
! call printmtx(a) ; stop
        case(-1)
          if (.not. a%weighted) then
            error stop "ERROR the matrix was not priorly diagonalized, called from
       simplelinalg::diag_precond"
          end if
          if (.not. present(x)) then
            print *, "x-vector not present, incorrect function call, called from
       simplelinalg::diag_precond"
            error stop
          end if
          x(1:finm)=x(1:finm)*a%weight
          do i=1, finn
            call a%getrow(i=i, v=values, jj=indexes, nelem=nelem)
            do k=1, nelem
              j = indexes(k)
              tmp = a%get(i,j)
              call a%set(tmp/a%weight(j),i,j)
            end do
          end do
          a%weighted = .false.
        case default
          print *, "RUNTIME error in parameter mode passed into procedure fem_tools::diag_precond"
          error stop
      end select
integer(kind=ikind) function, public simplelinalg::factorial (integer(kind=ikind), intent(in) in)
Definition at line 177 of file simplelinalg.f90.
      use typy
      
      integer(kind=ikind), intent(in) :: in
      integer(kind=ikind) :: fact
      
      integer(kind=ikind) :: i
      
      fact = in
      do i=in-1, 1, -1
        fact = fact*i
      end do
      
subroutine, public simplelinalg::invert_matrix (real(kind=rkind), dimension(:,:), intent(inout) A)
subroutine, that evaluates inverse matrix up to dimension 3
Definition at line 122 of file simplelinalg.f90.
References determinant().
Referenced by fem_tools::icond4neumann().
      use typy
      real(kind=rkind), dimension(:,:), intent(in out) :: a
      real(kind=rkind), dimension(3,3) :: a_loc
      integer(kind=ikind) :: i,j, n
      n = ubound(a,1)
      select case(n)
        case(1)
            a(1,1) = 1.0_rkind/a(1,1)
        case(2)
            a_loc(1:n,1:n) = a
            a(1,1) = 1.0_rkind/determinant(a_loc(1:2,1:2))*a_loc(2,2)
            a(1,2) = -1.0_rkind/determinant(a_loc(1:2,1:2))*a_loc(1,2)
            a(2,1) = -1.0_rkind/determinant(a_loc(1:2,1:2))*a_loc(2,1)
            a(2,2) = 1.0_rkind/determinant(a_loc(1:2,1:2))*a_loc(1,1)
        case(3)
            print *, "no implemented, terminated from fem_tools::invert_matrix"
            error stop
      end select