dual_tab Module Reference
This module writes tabular versions of main functions to enhance computation.
 Tabular versions dispersion: mualem_tab; elastisticty: dual_ret; mass= vangen_tab.
Functions/Subroutines
subroutine, public dual_mualem_tab (pde_loc, layer, quadpnt, x, tensor, scalar)
Tabular versions of dispersion.
real(kind=rkind) function, public vangen_d_tab (pde_loc, layer, quadpnt, x)
Tabular versions of mass.
real(kind=rkind) function, public dual_ret_cap_tab (pde_loc, layer, quadpnt, x)
Tabular versions of elastiocity.
real(kind=rkind) function, public dual_coupling_tab (pde_loc, layer, quadpnt, x)
Tabular versions of coupling term for case(1) and case(2)
real(kind=rkind) function, public dual_coupling_neg_tab (pde_loc, layer, quadpnt, x)
subroutine, public dual_tabvalues (pde_loc, Kfnc, Cfnc, thetafnc, ex_K_fnc)
creates a table of values of constitutive functions for the Richards equation to be linearly approximated
Variables
real(kind=rkind), dimension(:,:), allocatable, public ktab_dm
real(kind=rkind), dimension(:,:), allocatable, public watcontab_dm
real(kind=rkind), dimension(:,:), allocatable, public warecatab_dm
real(kind=rkind), dimension(:,:), allocatable, public couptab
real(kind=rkind), dimension(:,:), allocatable, public ktab_df
real(kind=rkind), dimension(:,:), allocatable, public watcontab_df
real(kind=rkind), dimension(:,:), allocatable, public warecatab_df
Detailed Description
This module writes tabular versions of main functions to enhance computation.
 Tabular versions dispersion: mualem_tab; elastisticty: dual_ret; mass= vangen_tab.
Function/Subroutine Documentation
real(kind=rkind) function, public dual_tab::dual_coupling_neg_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Definition at line 479 of file Re_dual_tab.f90.
References dual_coupling_tab().
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use dual_globals
      use pde_objs
      use core_tools
      use dual_por
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind):: ex_term
      
      if (present(quadpnt)) then
        ex_term=-dual_coupling_tab(pde_loc, layer, quadpnt)
      end if
      if (present(x)) then
        ex_term=-dual_coupling_tab(pde_loc, layer, x=x)
      end if
real(kind=rkind) function, public dual_tab::dual_coupling_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Tabular versions of coupling term for case(1) and case(2)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
resulting system elasticity
Definition at line 280 of file Re_dual_tab.f90.
References dual_globals::coup_model, couptab, dual_coup::dual_coupling_k(), dual_por::dual_mualem(), dual_globals::exchange, ktab_df, ktab_dm, pde_objs::pde, dual_globals::vgexchange, dual_globals::vgfracture, and dual_globals::vgmatrix.
Referenced by dual_coupling_neg_tab(), re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use dual_globals
      use pde_objs
      use core_tools
      use dual_por
          
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind)::beta,a,gam_par
      real(kind=rkind)::ks,weightf,weightm,ksm,ksf
      real(kind=rkind):: ka_f,ka_m,ka,ex_term,ka_fm,ka_mf,ka_mm,ka_ff,ka_fw,ka_mw
      real(kind=rkind):: hm,hf,one,hw
      integer(kind=ikind) :: pos
      real(kind=rkind) :: res, dist
      type(integpnt_str) :: quadpnt_loc
      beta=exchange(layer)%beta
      a=exchange(layer)%a
      gam_par=exchange(layer)%gam_par
      weightm=exchange(layer)%weightm
      weightf=exchange(layer)%weightf
      ksm=vgmatrix(layer)%KS_local(1)
      ksf=vgfracture(layer)%KS_local(1)
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from RE_dual: dual_coupling_tab"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from RE_dual: dual_coupling_tab"
        error stop
      end if
      
        if (present(quadpnt)) then
          quadpnt_loc=quadpnt
          quadpnt_loc%preproc=.true.
          hm = pde(1)%getval(quadpnt_loc)
          hf = pde(2)%getval(quadpnt_loc)
    else
        if (ubound(x,1) /=2) then
          print *, "ERROR: the coupling term is a function of two variables hm and hf"
          print *, " your input data has:", ubound(x,1), "variables"
          error stop
        end if
    if (ubound(x,1) /=2) then
          print *, "ERROR: the coupling term is a function of two variables hm and hf"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from RE_dual::dual_coupling_tab"
          error stop
        end if
           hm = x(1)
           hf = x(2)
    end if
    hw=hm*weightm+hf*weightf
        select case(coup_model)
                case(1:2)
                 ks=vgexchange(layer)%KS_local(1)
                if (hm<0) then
                  if (hm/drutes_config%fnc_discr_length < 0.1*huge(1)) then
                        pos = int(-hm/drutes_config%fnc_discr_length)+1
                        if (abs(pos) <= ubound(couptab,2)-1) then
                          dist = -hm - (pos - 1)*drutes_config%fnc_discr_length
                          ka_m = (couptab(layer,pos+1)-couptab(layer,pos))/
      drutes_config%fnc_discr_length*dist &
                          + couptab(layer,pos)
                        else
                          ka_m= dual_coupling_k(pde_loc,layer,x=[hm])
                        end if
                  else
                        ka_m= dual_coupling_k(pde_loc,layer,x=[hm])
                  end if
                else
                  ka_m= dual_coupling_k(pde_loc,layer,x=[hm])
                end if
        
                if (hf<0) then
                  if (hf/drutes_config%fnc_discr_length < 0.1*huge(1)) then
                        pos = int(-hf/drutes_config%fnc_discr_length)+1
                        if (abs(pos) <= ubound(couptab,2)-1) then
                          dist = -hf - (pos - 1)*drutes_config%fnc_discr_length
                          ka_f = (couptab(layer,pos+1)-couptab(layer,pos))/
      drutes_config%fnc_discr_length*dist&
                           + couptab(layer,pos)
                        else
                          ka_f= dual_coupling_k(pde_loc,layer,x=[hf])
                        end if
                  else
                        ka_f= dual_coupling_k(pde_loc,layer,x=[hf])
                  end if
                else
                  ka_f= dual_coupling_k(pde_loc,layer,x=[hf])
                end if
    case(4)
                if (hm<0) then
                  if (hm/drutes_config%fnc_discr_length < 0.1*huge(1)) then
                        pos = int(-hm/drutes_config%fnc_discr_length)+1
                        if (abs(pos) <= ubound(couptab,2)-1) then
                          dist = -hm - (pos - 1)*drutes_config%fnc_discr_length
                          ka_mm = (ktab_dm(layer,pos+1)-ktab_dm(layer,pos))/
      drutes_config%fnc_discr_length*dist &
                          + ktab_dm(layer,pos)
                          ka_fm= (ktab_df(layer,pos+1)-ktab_df(layer,pos))/
      drutes_config%fnc_discr_length*dist &
                          + ktab_df(layer,pos)
                        else
                          call dual_mualem(pde_loc,layer,x=[hm],scalar=ka_mm)
                          call dual_mualem(pde_loc,layer,x=[hm],scalar=ka_fm)
                        end if
                  else
                        call dual_mualem(pde_loc,layer,x=[hm],scalar=ka_mm)
                        call dual_mualem(pde_loc,layer,x=[hm],scalar=ka_fm)
                  end if
                else
                        call dual_mualem(pde_loc,layer,x=[hm],scalar=ka_mm)
                        call dual_mualem(pde_loc,layer,x=[hm],scalar=ka_fm)
                end if
    
                if (hf<0) then
                  if (hf/drutes_config%fnc_discr_length < 0.1*huge(1)) then
                        pos = int(-hf/drutes_config%fnc_discr_length)+1
                        if (abs(pos) <= ubound(couptab,2)-1) then
                          dist = -hf - (pos - 1)*drutes_config%fnc_discr_length
                          ka_ff = (ktab_df(layer,pos+1)-ktab_df(layer,pos))/
      drutes_config%fnc_discr_length*dist &
                          + ktab_df(layer,pos)
                          ka_mf = (ktab_dm(layer,pos+1)-ktab_dm(layer,pos))/
      drutes_config%fnc_discr_length*dist &
                          + ktab_dm(layer,pos)
                        else
                          call dual_mualem(pde_loc,layer,x=[hf],scalar=ka_mf)
                          call dual_mualem(pde_loc,layer,x=[hf],scalar=ka_ff)
                        end if
                  else
                          call dual_mualem(pde_loc,layer,x=[hf],scalar=ka_mf)
                          call dual_mualem(pde_loc,layer,x=[hf],scalar=ka_ff)
                  end if
                else
                        call dual_mualem(pde_loc,layer,x=[hf],scalar=ka_mf)
                        call dual_mualem(pde_loc,layer,x=[hf],scalar=ka_ff)
                end if
                ka_mm=ka_mm*ksm
                ka_fm=ka_fm*ksf
                ka_mf=ka_mf*ksm
                ka_ff=ka_ff*ksf
        case(5)
                if (hw<0) then
                  if (hw/drutes_config%fnc_discr_length < 0.1*huge(1)) then
                        pos = int(-hw/drutes_config%fnc_discr_length)+1
                        if (abs(pos) <= ubound(couptab,2)-1) then
                          dist = -hw - (pos - 1)*drutes_config%fnc_discr_length
                          ka_fw = (ktab_df(layer,pos+1)-ktab_df(layer,pos))/
      drutes_config%fnc_discr_length*dist &
                          + ktab_df(layer,pos)
                          ka_mw = (ktab_dm(layer,pos+1)-ktab_dm(layer,pos))/
      drutes_config%fnc_discr_length*dist &
                          + ktab_dm(layer,pos)
                        else
                          call dual_mualem(pde_loc,layer,x=[hw],scalar=ka_mw)
                          call dual_mualem(pde_loc,layer,x=[hw],scalar=ka_fw)
                        end if
                  else
                          call dual_mualem(pde_loc,layer,x=[hw],scalar=ka_mw)
                          call dual_mualem(pde_loc,layer,x=[hw],scalar=ka_fw)
                  end if
                else
                        call dual_mualem(pde_loc,layer,x=[hw],scalar=ka_mw)
                        call dual_mualem(pde_loc,layer,x=[hw],scalar=ka_fw)
                end if
                ka_fw=ka_fw*ksf
                ka_mw=ka_mw*ksm
        case(3)
        
        case default
                print *, "ERROR! You have specified an unsupported coupling term model in dual.conf file"
                print *, "the incorrect value specified is:", coup_model
                error stop
  end select
    
    
  select case(coup_model)
         case(1)
           ka=0.5*(ka_f+ka_m)*ks
         case(2)
           ka=(ka_f*ka_m)**0.5*ks
         case(3)
           ka=vgexchange(layer)%KS_local(1)
         case(4)
           ka=minval((/ka_ff,ka_fm,ka_mm,ka_mf/))
         case(5)
           ka=minval((/ka_fw,ka_mw/))
   end select
    
    if(abs(hm-hf)>max(hm,hf)*epsilon(hm)) then
      ex_term=beta/a**2*gam_par*ka
    else
      ex_term=0.0_rkind
    end if
subroutine, public dual_tab::dual_mualem_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:,:), intent(out), optional tensor, real(kind=rkind), intent(out), optional scalar)
Tabular versions of dispersion.
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
out tensor second order tensor of the unsaturated hydraulic conductivity
out scalar relative hydraulic conductivity, (scalar value)
Definition at line 24 of file Re_dual_tab.f90.
References dual_por::dual_mualem(), ktab_df, ktab_dm, dual_globals::vgfracture, and dual_globals::vgmatrix.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use dual_globals
      use pde_objs
      use core_tools
      use debug_tools
      use dual_por
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), dimension(:,:), intent(out), optional :: tensor
      real(kind=rkind), intent(out), optional :: scalar
      real(kind=rkind) :: h
      integer(kind=ikind) :: pos
      real(kind=rkind) :: res, dist, tmp
      type(integpnt_str) :: quadpnt_loc
      
      
      if (present(quadpnt) .and. present(x)) then
                print *, "ERROR: the function can be called either with integ point or x value definition,
       not both of them"
                print *, "exited from Re_dual::mualem_m_tab"
                error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
                print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from Re_dual::mualem_m_tab"
                error stop
      end if
      
     
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
            quadpnt_loc%preproc=.true.
            h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
                        print *, "ERROR: van Genuchten function is a function of a single variable h"
                        print *, " your input data has:", ubound(x,1), "variables"
                        print *, "exited from Re_dual::mualem_m_tab"
                        error stop
                end if
                h = x(1)
      end if
      
      if (h<0) then
        if (-h/drutes_config%fnc_discr_length < 0.1*huge(1)) then
          pos = int(-h/drutes_config%fnc_discr_length)+1
          if (abs(pos) <= ubound(ktab_dm,2)-1) then
            dist = -h - (pos - 1)*drutes_config%fnc_discr_length
            select case (pde_loc%mfswitch)
              case("m")
               tmp = (ktab_dm(layer,pos+1)-ktab_dm(layer,pos))/drutes_config%fnc_discr_length*
      dist &
            + ktab_dm(layer,pos)
              case("f")
            tmp = (ktab_df(layer,pos+1)-ktab_df(layer,pos))/drutes_config%fnc_discr_length*
      dist &
            + ktab_df(layer,pos)
            end select
          else
            if (present(quadpnt)) call dual_mualem(pde_loc, layer, quadpnt, scalar = tmp)
            if (present(x)) call dual_mualem(pde_loc, layer, x=x, scalar = tmp)
          end if
        else
          if (present(quadpnt)) call dual_mualem(pde_loc, layer, quadpnt, scalar = tmp)
          if (present(x)) call dual_mualem(pde_loc, layer, x=x, scalar = tmp)
        end if
      else
        if (present(quadpnt)) call dual_mualem(pde_loc, layer, quadpnt, scalar = tmp)
        if (present(x)) call dual_mualem(pde_loc, layer, x=x, scalar = tmp)
      end if
      if (present(tensor)) then
        select case (pde_loc%mfswitch)
          case("m")
            tensor = tmp*vgmatrix(layer)%Ks
          case("f")
             tensor = tmp*vgfracture(layer)%Ks
        end select
      end if
      if (present(scalar)) then
        scalar = tmp
      end if
real(kind=rkind) function, public dual_tab::dual_ret_cap_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Tabular versions of elastiocity.
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting system elasticity
Definition at line 195 of file Re_dual_tab.f90.
References dual_por::dual_ret_cap(), dual_globals::exchange, dual_globals::vgfracture, dual_globals::vgmatrix, warecatab_df, and warecatab_dm.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use dual_globals
      use pde_objs
      use core_tools
      use debug_tools
      use dual_por
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: e
      integer(kind=ikind) :: pos
      real(kind=rkind) :: res, dist
      type(integpnt_str) :: quadpnt_loc
      
   
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from re_constitutive::vangen_elast_tab"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from re_constitutive::vangen_elast_tab"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::vangen_elast_tab"
          error stop
        end if
        h = x(1)
      end if
     
      if (h<0) then !same as 1104
        if (h/drutes_config%fnc_discr_length < 0.1*huge(1)) then
          pos = int(-h/drutes_config%fnc_discr_length)+1
          if (abs(pos) <= ubound(warecatab_dm,2)-1) then
            dist = -h - (pos - 1)*drutes_config%fnc_discr_length
            select case (pde_loc%mfswitch)
              case("m")
                e = (warecatab_dm(layer,pos+1)-warecatab_dm(layer,pos))/
      drutes_config%fnc_discr_length*dist &
                 + warecatab_dm(layer,pos)
              case("f")
                e = (warecatab_df(layer,pos+1)-warecatab_df(layer,pos))/
      drutes_config%fnc_discr_length*dist &
              + warecatab_df(layer,pos)
            end select
          else
            if (present(quadpnt)) e = dual_ret_cap(pde_loc, layer, quadpnt)
            if (present(x)) e = dual_ret_cap(pde_loc, layer, x=x)
          end if
        else
          if (present(quadpnt)) e = dual_ret_cap(pde_loc, layer, quadpnt)
          if (present(x)) e = dual_ret_cap(pde_loc, layer, x=x)
        end if
        
      else
        select case (pde_loc%mfswitch)
          case("m")
            e = vgmatrix(layer)%Ss*exchange(layer)%weightm
          case("f")
            e = vgfracture(layer)%Ss*exchange(layer)%weightf
        end select
        
      end if
subroutine, public dual_tab::dual_tabvalues (class(pde_str), intent(in) pde_loc, Kfnc, Cfnc, thetafnc, ex_K_fnc)
creates a table of values of constitutive functions for the Richards equation to be linearly approximated
Definition at line 504 of file Re_dual_tab.f90.
References couptab, globals::drutes_config, ktab_df, ktab_dm, globals::maxpress, printtools::progressbar(), dual_globals::vgfracture, dual_globals::vgmatrix, warecatab_df, warecatab_dm, watcontab_df, watcontab_dm, and core_tools::write_log().
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
real(kind=rkind) function, public dual_tab::vangen_d_tab (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Tabular versions of mass.
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting water content
Definition at line 114 of file Re_dual_tab.f90.
References dual_por::vangen_d(), dual_globals::vgfracture, dual_globals::vgmatrix, watcontab_df, and watcontab_dm.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use dual_globals
      use pde_objs
      use core_tools
      use dual_por
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind) :: h
      real(kind=rkind) :: theta
      integer(kind=ikind) :: pos
      real(kind=rkind) :: res, dist
      type(integpnt_str) :: quadpnt_loc
      
      
      if (present(quadpnt) .and. present(x)) then
        print *, "ERROR: the function can be called either with integ point or x value definition, not both
       of them"
        print *, "exited from RE_dual::vangen_tab"
        error stop
      else if (.not. present(quadpnt) .and. .not. present(x)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from RE_dual::vangen_tab"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from re_constitutive::vangen_tab"
          error stop
        end if
        h = x(1)
      end if
     if (h<0) then
        if (h/drutes_config%fnc_discr_length < 0.1*huge(1)) then
          pos = int(-h/drutes_config%fnc_discr_length)+1
          if (abs(pos) <= ubound(watcontab_dm,2)-1) then
            dist = -h - (pos - 1)*drutes_config%fnc_discr_length
            select case (pde_loc%mfswitch)
              case("m")
                theta = (watcontab_dm(layer,pos+1)-watcontab_dm(layer,pos))/
      drutes_config%fnc_discr_length*dist &
            + watcontab_dm(layer,pos)
              case("f")
                theta = (watcontab_df(layer,pos+1)-watcontab_df(layer,pos))/
      drutes_config%fnc_discr_length*dist&
             + watcontab_df(layer,pos)
            end select
          else
            if (present(quadpnt)) theta = vangen_d(pde_loc, layer, quadpnt)
            if (present(x)) theta = vangen_d(pde_loc, layer, x=x)
          end if
        else
          if (present(quadpnt)) theta = vangen_d(pde_loc, layer, quadpnt)
          if (present(x)) theta = vangen_d(pde_loc, layer, x=x)
        end if
    else
      select case (pde_loc%mfswitch)
        case("m")
           theta = vgmatrix(layer)%Ths
        case("f")
           theta = vgfracture(layer)%Ths
        end select
    end if
      
Variable Documentation
real(kind=rkind), dimension(:,:), allocatable, public dual_tab::couptab
Definition at line 17 of file Re_dual_tab.f90.
Referenced by dual_coupling_tab(), and dual_tabvalues().
real(kind=rkind), dimension(:,:), allocatable, public dual_tab::ktab_df
Definition at line 18 of file Re_dual_tab.f90.
Referenced by dual_coupling_tab(), dual_mualem_tab(), and dual_tabvalues().
  real(kind=rkind), dimension(:,:), allocatable, public :: ktab_df,watcontab_df,warecatab_df
real(kind=rkind), dimension(:,:), allocatable, public dual_tab::ktab_dm
Definition at line 17 of file Re_dual_tab.f90.
Referenced by dual_coupling_tab(), dual_mualem_tab(), and dual_tabvalues().
  real(kind=rkind), dimension(:,:), allocatable, public :: ktab_dm,watcontab_dm,warecatab_dm,couptab
real(kind=rkind), dimension(:,:), allocatable, public dual_tab::warecatab_df
Definition at line 18 of file Re_dual_tab.f90.
Referenced by dual_ret_cap_tab(), and dual_tabvalues().
real(kind=rkind), dimension(:,:), allocatable, public dual_tab::warecatab_dm
Definition at line 17 of file Re_dual_tab.f90.
Referenced by dual_ret_cap_tab(), and dual_tabvalues().
real(kind=rkind), dimension(:,:), allocatable, public dual_tab::watcontab_df
Definition at line 18 of file Re_dual_tab.f90.
Referenced by dual_tabvalues(), and vangen_d_tab().
real(kind=rkind), dimension(:,:), allocatable, public dual_tab::watcontab_dm
Definition at line 17 of file Re_dual_tab.f90.
Referenced by dual_tabvalues(), and vangen_d_tab().