re_dual_bc Module Reference
This module contains different boundary definitions for the fracture and matrix domains in the dual permeability model.
Functions/Subroutines
subroutine, public dual_neumann_bc (pde_loc, el_id, node_order, value, code)
Defines Neumann (flux) boundary condition for the dual permeability model.
subroutine, public inf_neumann_bc (pde_loc, el_id, node_order, value, code)
Also defines Neumann type boundary. The weighting for matrix and fracture domains is user defined.
subroutine, public dual_freedrainage (pde_loc, el_id, node_order, value, code)
Assigns free drainage boundary (unit gradient) for dual permeability model.
subroutine, public dual_atmospheric (pde_loc, el_id, node_order, value, code)
Assigns a simple atmospheric boundary based on water content in the soil and potential evaporation and rain for dual permeability model $rain - evap*\theta(h)^{\frac{2}{3}}$.
Detailed Description
This module contains different boundary definitions for the fracture and matrix domains in the dual permeability model.
Function/Subroutine Documentation
subroutine, public re_dual_bc::dual_atmospheric (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Assigns a simple atmospheric boundary based on water content in the soil and potential evaporation and rain for dual permeability model $rain - evap*\theta(h)^{\frac{2}{3}}$.
Parameters
in pde_loc takes the global pde_loc structure
in el_id takes the element id and node order
in node_order takes the element id and node order
out value optional value output of the assigned boundary
out code optional code output. Different codes for different boundaries. Code = 2
Definition at line 207 of file Re_dual_bc.f90.
References globals::elements, dual_globals::infweight, globals::nodes, and globals::time.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use globals
      use global_objs
      use pde_objs
      use dual_globals
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      
      
      
      type(integpnt_str) :: quadpnt
      integer(kind=ikind) :: layer
      real(kind=rkind) :: theta, rain, evap
      integer(kind=ikind) :: i, edge_id, j
      
      
      if (present(code)) then
            code = 2
      end if
      
      if (present(value)) then
        edge_id = nodes%edge(elements%data(el_id, node_order))
        i = pde_loc%permut(elements%data(el_id, node_order))
        if (pde_loc%bc(edge_id)%file) then
          do i=1, ubound(pde_loc%bc(edge_id)%series,1)
            if (pde_loc%bc(edge_id)%series(i,1) > time) then
              if (i > 1) then
                j = i-1
              else
                j = i
              end if
              rain = pde_loc%bc(edge_id)%series(j,2)
              evap = pde_loc%bc(edge_id)%series(j,3)
              EXIT
            end if
          end do
        else
          print *, "atmospheric boundary must be time dependent, check record for the boundary", edge_id
          error stop
        end if
        quadpnt%type_pnt = "ndpt"
        quadpnt%column = 2
        quadpnt%order = elements%data(el_id,node_order)
        layer = elements%material(el_id,1)
        theta = pde_loc%mass(layer, quadpnt)
        select case (pde_loc%mfswitch)
          case("m")
            value = (rain - evap*theta**(2.0_rkind/3.0_rkind))*(1_rkind-
      infweight)
          case("f")
            value = (rain - evap*theta**(2.0_rkind/3.0_rkind))*(infweight)
        end select
      end if
      
subroutine, public re_dual_bc::dual_freedrainage (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Assigns free drainage boundary (unit gradient) for dual permeability model.
Parameters
in pde_loc takes the global pde_loc structure
in el_id takes the element id and node order
in node_order takes the element id and node order
out value optional value output of the assigned boundary
out code optional code output. Different codes for different boundaries. Code = 2
Definition at line 147 of file Re_dual_bc.f90.
References globals::drutes_config, globals::elements, and pde_objs::pde.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use globals
      use global_objs
      use pde_objs
      use dual_globals
      use dual_por
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      real(kind=rkind), dimension(3,3) :: k
      type(integpnt_str) :: quadpnt
      integer(kind=ikind) :: layer, d
      real(kind=rkind), dimension(3) :: gravflux
      
      
      if (present(value)) then
        quadpnt%type_pnt = "ndpt"
        quadpnt%column = 2
        quadpnt%order = elements%data(el_id, node_order)
        layer = elements%material(el_id,1)
        d = drutes_config%dimen
        select case (pde_loc%mfswitch)
          case("m")
            call pde(1)%pde_fnc(1)%dispersion(pde_loc, layer, quadpnt, tensor=k(1:d,1:d))
          case("f")
            call pde(2)%pde_fnc(2)%dispersion(pde_loc, layer, quadpnt, tensor=k(1:d,1:d))
        end select
        
        
        select case(d)
          case(1)
          
            value = k(1,1) * elements%nvect_z(el_id, node_order)
          
          case(2)
            gravflux(1) = sqrt(1-elements%nvect_z(el_id, node_order)*elements%nvect_z(el_id, node_order))*k
      (1,2)
            gravflux(2) = elements%nvect_z(el_id, node_order)*k(2,2)
            value = sqrt(gravflux(1)*gravflux(1) + gravflux(2)*gravflux(2))
        end select
      end if
      
      if (present(code)) then
        code = 2
      end if
      
subroutine, public re_dual_bc::dual_neumann_bc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Defines Neumann (flux) boundary condition for the dual permeability model.
Parameters
in pde_loc takes the global pde_loc structure
in el_id takes the element id and node order
in node_order takes the element id and node order
out value optional value output of the assigned boundary
out code optional code output. Different codes for different boundaries. Code = 2
Definition at line 12 of file Re_dual_bc.f90.
References globals::elements, dual_globals::exchange, globals::nodes, and globals::time.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use globals
      use global_objs
      use pde_objs
      use dual_globals
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
     
      integer(kind=ikind) :: i, edge_id, j,layer
      real(kind=rkind), dimension(3) :: gravflux, bcflux
      real(kind=rkind) :: bcval, gfluxval, weight
      integer :: i1
      
      
      if (present(value)) then
        edge_id = nodes%edge(elements%data(el_id, node_order))
        i = pde_loc%permut(elements%data(el_id, node_order))
        
        if (pde_loc%bc(edge_id)%file) then
          do i=1, ubound(pde_loc%bc(edge_id)%series,1)
            if (pde_loc%bc(edge_id)%series(i,1) > time) then
              if (i > 1) then
                j = i-1
              else
                j = i
              end if
              layer=pde_loc%bc(edge_id)%layer
               
              select case (pde_loc%mfswitch)
                case("m")
                  bcval = pde_loc%bc(edge_id)%series(j,2)*exchange(layer)%weightm
                case("f")
                  bcval = pde_loc%bc(edge_id)%series(j,2)*exchange(layer)%weightf
              end select
              EXIT
            end if
          end do
        else
          layer=pde_loc%bc(edge_id)%layer
          select case (pde_loc%mfswitch)
            case("m")
              bcval = pde_loc%bc(edge_id)%value*exchange(layer)%weightm
            case("f")
              bcval = pde_loc%bc(edge_id)%value*exchange(layer)%weightf
          end select
        end if
    
        value = bcval
      end if
      
      if (present(code)) then
        code = 2
      end if
subroutine, public re_dual_bc::inf_neumann_bc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Also defines Neumann type boundary. The weighting for matrix and fracture domains is user defined.
Parameters
in pde_loc takes the global pde_loc structure
in el_id takes the element id and node order
in node_order takes the element id and node order
out value optional value output of the assigned boundary
out code optional code output. Different codes for different boundaries. Code = 2
Definition at line 83 of file Re_dual_bc.f90.
References globals::elements, dual_globals::infweight, globals::nodes, and globals::time.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use globals
      use global_objs
      use pde_objs
      use dual_globals
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      integer(kind=ikind) :: i, edge_id, j,layer
      real(kind=rkind), dimension(3) :: gravflux, bcflux
      real(kind=rkind) :: bcval, gfluxval, weight
      integer :: i1
      
      select case (pde_loc%mfswitch)
        case("m")
          weight=(1_rkind-infweight)
        case("f")
          weight=infweight
      end select
      if (present(value)) then
        edge_id = nodes%edge(elements%data(el_id, node_order))
        i = pde_loc%permut(elements%data(el_id, node_order))
        
        if (pde_loc%bc(edge_id)%file) then
          do i=1, ubound(pde_loc%bc(edge_id)%series,1)
            if (pde_loc%bc(edge_id)%series(i,1) > time) then
              if (i > 1) then
                j = i-1
              else
                j = i
              end if
              layer=pde_loc%bc(edge_id)%layer
              bcval = pde_loc%bc(edge_id)%series(j,2)*weight
              EXIT
            end if
          end do
        else
          layer=pde_loc%bc(edge_id)%layer
          bcval = pde_loc%bc(edge_id)%value*weight
        end if
        value = bcval
      end if
      
      if (present(code)) then
        code = 2
      end if