global_objs Module Reference
Data Types
type configuration
structure with basic model configuration
type dirglob_str
type element
mesh array type for elements
type extsmtx
type integnodes
type integpnt_str
structure that specifies the point
type measured
type node
mesh array type for node kolik = number of nodes id = id number of node, equal to position data = x,y coordinates bc = boundary condition for current node edge = boundary id number, if the node lies apart from any boundary, default value is 0 results = final iteration at each time step will be copied into this vector
type observation
structure to define observation points
type observe_info_str
type observe_time_str
type smartarray_int
smart array, you don't need to allocate -- usefull if you don't know how many data you will write in, it is simply smart enough, it does all allocations automatically. By default the array data allocates on dimension 2, if the data doesn't fit into this array, then the array is reallocated for a double of its original size
type smartarray_real
For comments and description see smartarray_int.
type version
Functions/Subroutines
subroutine, private ismartfill (array, input, info)
subroutine, private ismartfill_norepeat (array, input, info)
subroutine, private ismartclear (array, full)
logical function, private ismartexist (array, value)
subroutine, private rsmartfill (array, input, info)
subroutine, private rsmartfill_norepeat (array, input, info)
subroutine, private rsmartclear (array, full)
Function/Subroutine Documentation
subroutine, private global_objs::ismartclear (class(smartarray_int), intent(inout) array, logical, intent(in), optional full) [private]
Definition at line 366 of file global_objs.f90.
      class(smartarray_int), intent(in out) :: array
      logical, intent(in), optional :: full
      
      if (present(full) .and. full .and. allocated(array%data)) then
        deallocate(array%data)
      end if
      array%pos = 0
      
logical function, private global_objs::ismartexist (class(smartarray_int), intent(in) array, integer(kind=ikind), intent(in) value) [private]
Definition at line 378 of file global_objs.f90.
      use typy
      class(smartarray_int), intent(in) :: array
      integer(kind=ikind), intent(in) :: value
      logical :: exist
      
      integer(kind=ikind) :: i
      
      exist = .false.
      
      do i=1, array%pos
        if (array%data(i) == value) then
          exist = .true.
          RETURN
        end if
      end do
      
subroutine, private global_objs::ismartfill (class(smartarray_int), intent(inout) array, integer(kind=ikind), intent(in) input, integer(kind=ikind), intent(in), optional info) [private]
Definition at line 273 of file global_objs.f90.
Referenced by ismartfill_norepeat().
      use typy
      class(smartarray_int), intent(in out) :: array
      integer(kind=ikind), intent(in) :: input
      integer(kind=ikind), intent(in), optional :: info
      
      integer(kind=ikind) :: l
      integer(kind=ikind), dimension(:), allocatable :: itmp
      integer(kind=ikind), dimension(:), allocatable :: logtmp
      
      ! check allocations
      if (.not. allocated(array%data)) then
        array%pos = 0
        allocate(array%data(1))
        if (present(info)) then
          array%infopos = 0
          allocate(array%info(1))
        end if
      end if
      
      array%pos = array%pos+1
      
      if (present(info)) then
        array%infopos = array%infopos + 1
        if (array%pos /= array%infopos) then
            print *, "this is a bug in the code"
            print *, "smartarray%data and smartarray%info has different amount of data written"
            print *, "called from global_objs::rsmartfill"
            print *, "contact Michal -> michalkuraz@gmail.com"
            error stop
        end if
      end if
      
      if (ubound(array%data,1) < array%pos) then
        l = ubound(array%data,1)
        allocate(itmp(l))
        itmp = array%data
        deallocate(array%data)
        allocate(array%data(2*l))
        array%data(1:l) = itmp
        deallocate(itmp)
        if (present(info)) then
          allocate (logtmp(l))
          logtmp = array%info
          deallocate(array%info)
          allocate(array%info(2*l))
          array%info(1:l) = logtmp
          deallocate(logtmp)
        end if
      end if
      
      array%data(array%pos) = input
      
      if (present(info)) then
        array%info = info
      end if
      
      
subroutine, private global_objs::ismartfill_norepeat (class(smartarray_int), intent(inout) array, integer(kind=ikind), intent(in) input, integer(kind=ikind), intent(in), optional info) [private]
Definition at line 336 of file global_objs.f90.
References ismartfill().
      use typy
      class(smartarray_int), intent(in out) :: array
      integer(kind=ikind), intent(in) :: input
      integer(kind=ikind), intent(in), optional :: info
      
      integer(kind=ikind) :: i
      logical :: exist
      
      exist = .false.
      if (allocated(array%data)) then
        do i=1, array%pos
          if (array%data(i) == input) then
            exist = .true.
            EXIT
          end if
        end do
       end if
      
      if (.not. exist) then
        if (present(info)) then
          call ismartfill(array, input, info)
        else
          call ismartfill(array, input)
        end if
      end if
    
    
subroutine, private global_objs::rsmartclear (class(smartarray_real), intent(inout) array, logical, intent(in), optional full) [private]
Definition at line 491 of file global_objs.f90.
      class(smartarray_real), intent(in out) :: array
      logical, intent(in), optional :: full
      
      if (present(full) .and. full .and. allocated(array%data)) then
        deallocate(array%data)
      end if
      array%pos = 0
      
subroutine, private global_objs::rsmartfill (class(smartarray_real), intent(inout) array, real(kind=rkind), intent(in) input, integer(kind=ikind), intent(in), optional info) [private]
Definition at line 398 of file global_objs.f90.
Referenced by rsmartfill_norepeat().
      use typy
      class(smartarray_real), intent(in out) :: array
      real(kind=rkind), intent(in) :: input
      integer(kind=ikind), intent(in), optional :: info
      
      integer(kind=ikind) :: l
      real(kind=rkind), dimension(:), allocatable :: rtmp
      integer(kind=ikind), dimension(:), allocatable :: logtmp
      
      ! check allocations
      if (.not. allocated(array%data)) then
        array%pos = 0
        allocate(array%data(1))
        if (present(info)) then
          array%infopos = 0
          allocate(array%info(1))
        end if
      end if
      
      array%pos = array%pos+1
      
      if (present(info)) then
        array%infopos = array%infopos + 1
        if (array%pos /= array%infopos) then
            print *, "this is a bug in the code"
            print *, "smartarray%data and smartarray%info has different amount of data written"
            print *, "called from global_objs::rsmartfill"
            print *, "contact Michal -> michalkuraz@gmail.com"
            error stop
        end if
      end if
      
      if (ubound(array%data,1) < array%pos) then
        l = ubound(array%data,1)
        allocate(rtmp(l))
        rtmp = array%data
        deallocate(array%data)
        allocate(array%data(2*l))
        array%data(1:l) = rtmp
        deallocate(rtmp)
        if (present(info)) then
          allocate (logtmp(l))
          logtmp = array%info
          deallocate(array%info)
          allocate(array%info(2*l))
          array%info(1:l) = logtmp
          deallocate(logtmp)
        end if
      end if
      
      array%data(array%pos) = input
      
      if (present(info)) then
        array%info = info
      end if
      
      
subroutine, private global_objs::rsmartfill_norepeat (class(smartarray_real), intent(inout) array, real(kind=rkind), intent(in) input, integer(kind=ikind), intent(in), optional info) [private]
Definition at line 461 of file global_objs.f90.
References rsmartfill().
      use typy
      class(smartarray_real), intent(in out) :: array
      real(kind=rkind), intent(in) :: input
      integer(kind=ikind), intent(in), optional :: info
      
      integer(kind=ikind) :: i
      logical :: exist
      
      exist = .false.
      if (allocated(array%data)) then
        do i=1, array%pos
          if (abs(array%data(i) - input) < max(abs(array%data(i)), abs(input))*(epsilon(input))) then
            exist = .true.
            EXIT
          end if
        end do
       end if
      
      if (.not. exist) then
        if (present(info)) then
          call rsmartfill(array, input, info)
        else
          call rsmartfill(array, input)
        end if
      end if
    
    