dual_coup Module Reference
This module contains variants of coupling terms of the dual permeability model. Boundary gets assigned mualem parameters in case(2) and (3). Case(1) The exchange term is calculated based on arithmetic mean of $Ka=\frac{Ka(hm)+Ka(hf)}{2}$.
 Case(2) The exchange term is calculated based on geometric mean of $Ka=\sqrt{Ka(hm)*Ka(hf)}$.
 Case(3) The exchange boundary term is constant.
 Case (4) and (5) don't require further parameters.
 Case(4) The exchange term is the minimum of $Ka=min(Km(hm),Kf(hf),Km(hf),Kf(hf))$
 Case(5) The exchange term is the minimum of $Ka=min(Km(hm*weight_m+hf*weight_f),Kf(hm*weight_m+hf*weight_f))$.
Functions/Subroutines
real(kind=rkind) function, public dual_coupling (pde_loc, layer, quadpnt, x)
Coupling defined for case(1), case (2) and case (3) Case(1) The exchange term is calculated based on arithmetic mean of $Ka=\frac{Ka(hm)+Ka(hf)}{2}$.
 Case(2) The exchange term is calculated based on geometric mean of $Ka=\sqrt{Ka(hm)*Ka(hf)}$.
 Case(3) The exchange boundary term is constant.
real(kind=rkind) function, public dual_coupling_neg (pde_loc, layer, quadpnt, x)
neg coupling defined for case(1), case (2) and case (3) for coupled matrix, i.e. matrix part in fracture and fracture part in matrix.
real(kind=rkind) function, public dual_coup_min (pde_loc, layer, quadpnt, x)
The following coupling schemes use the minimum value of case(4) $Ka=min(Km(hm),Kf(hf),Km(hf),Kf(hf))$ and case(5) $Ka=min(Km(hm*weight_m+hf*weight_f),Kf(hm*weight_m+hf*weight_f))$.
 This has the advantage that no extra parameters need to be defined describing the hydraulic properties at the boundary
 This reduces the number of parameters to be estimated by 3: Kas, a, n
 This also assures that the exchange term is always smaller than or equal the fracture and matrix conductivity.
real(kind=rkind) function, public dual_coup_min_neg (pde_loc, layer, quadpnt, x)
neg coupling defined for case(4) and case (5) for coupled matrix, i.e. matrix part in fracture and fracture part in matrix.
real(kind=rkind) function, public dual_coupling_k (pde_loc, layer, quadpnt, x)
coupling conductivity function for tab values
Detailed Description
This module contains variants of coupling terms of the dual permeability model. Boundary gets assigned mualem parameters in case(2) and (3). Case(1) The exchange term is calculated based on arithmetic mean of $Ka=\frac{Ka(hm)+Ka(hf)}{2}$.
 Case(2) The exchange term is calculated based on geometric mean of $Ka=\sqrt{Ka(hm)*Ka(hf)}$.
 Case(3) The exchange boundary term is constant.
 Case (4) and (5) don't require further parameters.
 Case(4) The exchange term is the minimum of $Ka=min(Km(hm),Kf(hf),Km(hf),Kf(hf))$
 Case(5) The exchange term is the minimum of $Ka=min(Km(hm*weight_m+hf*weight_f),Kf(hm*weight_m+hf*weight_f))$.
Function/Subroutine Documentation
real(kind=rkind) function, public dual_coup::dual_coup_min (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
The following coupling schemes use the minimum value of case(4) $Ka=min(Km(hm),Kf(hf),Km(hf),Kf(hf))$ and case(5) $Ka=min(Km(hm*weight_m+hf*weight_f),Kf(hm*weight_m+hf*weight_f))$.
 This has the advantage that no extra parameters need to be defined describing the hydraulic properties at the boundary
 This reduces the number of parameters to be estimated by 3: Kas, a, n
 This also assures that the exchange term is always smaller than or equal the fracture and matrix conductivity.
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
vg and ex parameters, later from conf file
Definition at line 141 of file Re_dual_coupling.f90.
References dual_globals::coup_model, dual_por::dual_mualem(), dual_globals::exchange, pde_objs::pde, dual_globals::vgfracture, and dual_globals::vgmatrix.
Referenced by dual_coup_min_neg(), re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use global_objs
      use pde_objs
      use dual_globals
      use re_dual_reader
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind)::beta,a,gam_par
      real(kind=rkind)::weightf,weightm,ks,ksm,ksf
      real(kind=rkind) :: ka_ff,ka_mf,ka_mm,ka_fm,ka,ex_term,ka_m,ka_f
      real(kind=rkind) :: hm,hf
      type(integpnt_str) :: quadpnt_loc
        
      ksm=vgmatrix(layer)%KS_local(1)
      ksf=vgfracture(layer)%KS_local(1)
            
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        quadpnt_loc%column=1
        hm = pde(1)%getval(quadpnt_loc)
        hf = pde(2)%getval(quadpnt_loc)
      else
            if (ubound(x,1) /=2) then
              print *, "ERROR: exchange term requires two variables h"
              print *, " your input data has:", ubound(x,1), "variables"
              error stop
            end if
        if (ubound(x,1) /=2) then
              print *, "ERROR: exchange term requires two variables h"
              print *, " your input data has:", ubound(x,1), "variables"
              print *, "exited from RE_dual::dual_coupling"
              error stop
           end if
           hm = x(1)
           hf = x(2)
     end if
          
     select case(coup_model)
           case(4)
                 call dual_mualem(pde_loc, layer, x=[hm],scalar=ka_mm)
                 call dual_mualem(pde_loc, layer, x=[hf],scalar=ka_mf)
                 call dual_mualem(pde_loc, layer, x=[hm],scalar=ka_fm)
                 call dual_mualem(pde_loc, layer, x=[hf],scalar=ka_ff)
                 ka_ff=ka_ff*ksf
                 ka_mf=ka_mf*ksm
                 ka_mm=ka_mm*ksm
                 ka_fm=ka_fm*ksf
                 ka=minval((/ka_ff,ka_mf,ka_mm,ka_fm/))
       case(5)
         weightm=exchange(layer)%weightm
         weightf=exchange(layer)%weightf
         call dual_mualem(pde_loc, layer, x=[hm*weightm+hf*weightf],scalar=ka_m)
         call dual_mualem(pde_loc, layer, x=[hm*weightm+hf*weightf],scalar=ka_f)
         ka_m=ka_m*ksm
         ka_f=ka_f*ksf
                 ka=minval((/ka_f,ka_m/))
    end select
    
     beta=exchange(layer)%beta
     a=exchange(layer)%a
     gam_par=exchange(layer)%gam_par
     
     if(abs(hm-hf)>max(hm,hf)*epsilon(hm)) then
       ex_term=beta/a**2*gam_par*ka
     else
       ex_term=0.0_rkind
     end if
real(kind=rkind) function, public dual_coup::dual_coup_min_neg (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
neg coupling defined for case(4) and case (5) for coupled matrix, i.e. matrix part in fracture and fracture part in matrix.
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
vg and ex parameters
Definition at line 221 of file Re_dual_coupling.f90.
References dual_coup_min().
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use global_objs
      use pde_objs
      use dual_globals
      use re_dual_reader
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) ::ex_term
          
            
      if (present(quadpnt)) then
        ex_term=-dual_coup_min(pde_loc, layer, quadpnt)
      end if
      if (present(x)) then
        ex_term=-dual_coup_min(pde_loc, layer, x=x)
      end if
     
real(kind=rkind) function, public dual_coup::dual_coupling (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Coupling defined for case(1), case (2) and case (3) Case(1) The exchange term is calculated based on arithmetic mean of $Ka=\frac{Ka(hm)+Ka(hf)}{2}$.
 Case(2) The exchange term is calculated based on geometric mean of $Ka=\sqrt{Ka(hm)*Ka(hf)}$.
 Case(3) The exchange boundary term is constant.
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
vg and ex parameters, later from conf file
Definition at line 29 of file Re_dual_coupling.f90.
References dual_globals::coup_model, dual_globals::exchange, pde_objs::pde, and dual_globals::vgexchange.
Referenced by dual_coupling_neg(), re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use global_objs
      use pde_objs
      use dual_globals
      use re_dual_reader
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind)::beta,a,gam_par
      real(kind=rkind)::n,m,alpha,ks
      real(kind=rkind) :: ka_f,ka_m,ka,ex_term
      real(kind=rkind) :: hm,hf,one
      type(integpnt_str) :: quadpnt_loc
        
       
            
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        hm = pde(1)%getval(quadpnt_loc)
        hf = pde(2)%getval(quadpnt_loc)
      else
            if (ubound(x,1) /=2) then
              print *, "ERROR: exchange term requires two variables h"
              print *, " your input data has:", ubound(x,1), "variables"
              error stop
            end if
        if (ubound(x,1) /=2) then
              print *, "ERROR: exchange term requires two variables h"
              print *, " your input data has:", ubound(x,1), "variables"
              print *, "exited from RE_dual::dual_coupling"
              error stop
           end if
           hm = x(1)
           hf = x(2)
     end if
     
     alpha=vgexchange(layer)%alpha
     n=vgexchange(layer)%n
     m=vgexchange(layer)%m
     ks=vgexchange(layer)%KS_local(1)
     one=1.0_rkind
     if(hf<0) then
       ka_f=(one-abs(alpha*hf)**(n*m)*(one+abs(alpha*hf)**n)**(-m))**2/(one+abs(alpha*hf)**n)**(m/2)
     else
       ka_f=1.0_rkind
     end if
     if(hm<0) then
       ka_m=(one-abs(alpha*hm)**(n*m)*(one+abs(alpha*hm)**n)**(-m))**2/(one+abs(alpha*hm)**n)**(m/2)
     else
       ka_m=1.0_rkind
     end if
     select case(coup_model)
           case(1)
         ka=0.5*(ka_f+ka_m)*ks
       case(2)
         ka=(ka_f*ka_m)**0.5_rkind*ks
       case(3)
         ka=vgexchange(layer)%KS_local(1)
    end select
    
     beta=exchange(layer)%beta
     a=exchange(layer)%a
     gam_par=exchange(layer)%gam_par
     if(abs(hm-hf)>max(hm,hf)*epsilon(hm)) then
       ex_term=beta/a**2*gam_par*ka
     else
       ex_term=0.0_rkind
     end if
real(kind=rkind) function, public dual_coup::dual_coupling_k (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
coupling conductivity function for tab values
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Definition at line 251 of file Re_dual_coupling.f90.
References dual_globals::vgexchange.
Referenced by dual_tab::dual_coupling_tab(), re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
    use typy
    use global_objs
    use pde_objs
    use dual_globals
    use re_dual_reader
    
    class(pde_str), intent(in) :: pde_loc
    real(kind=rkind), dimension(:), intent(in), optional :: x
    type(integpnt_str), intent(in), optional :: quadpnt
    integer(kind=ikind), intent(in) :: layer
    real(kind=rkind)::ka_c
    real(kind=rkind)::n,m,alpha
    real(kind=rkind):: one,h
    type(integpnt_str) :: quadpnt_loc
          
     if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
     else
         if (ubound(x,1) /=1) then
           print *, "ERROR: van Genuchten function is a function of a single variable h"
           print *, " your input data has:", ubound(x,1), "variables"
           print *, "exited from RE_dual::dual_coupling_K"
           error stop
         end if
           h = x(1)
     end if
    alpha=vgexchange(layer)%alpha
    n=vgexchange(layer)%n
    m=vgexchange(layer)%m
    one=1.0_rkind
    if(h<0) then
      ka_c=(one-(alpha*abs(h))**(n*m)*(one+(alpha*abs(h))**n)**(-m))**2/(one+(alpha*abs(h))**n)**(m/2)
    else
      ka_c=1.0_rkind
    end if
real(kind=rkind) function, public dual_coup::dual_coupling_neg (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
neg coupling defined for case(1), case (2) and case (3) for coupled matrix, i.e. matrix part in fracture and fracture part in matrix.
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
vg and ex parameters, later from conf file
Definition at line 109 of file Re_dual_coupling.f90.
References dual_coupling().
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use global_objs
      use pde_objs
      use dual_globals
      use re_dual_reader
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) ::ex_term
          
            
      if (present(quadpnt)) then
        ex_term=-dual_coupling(pde_loc, layer, quadpnt)
      end if
      if (present(x)) then
        ex_term=-dual_coupling(pde_loc, layer, x=x)
      end if
     