dual_por Module Reference
This module contains governing functions of the dual permeability model and main functions and subroutines.
Functions/Subroutines
real(kind=rkind) function, public getval_retot_dual (pde_loc, quadpnt)
specific function for Richards equation in H-form (total hydraulic head form), replaces pde_objs::getvalp1 in order to distinguish between H and h pointers point to this with pde_locgetval
subroutine, public dual_inicond (pde_loc)
assigns initial condition
subroutine, public dual_mualem (pde_loc, layer, quadpnt, x, tensor, scalar)
defines dispersion functiona according to van Genuchten Mualem model (1980)
real(kind=rkind) function, public dual_ret_cap (pde_loc, layer, quadpnt, x)
defines elasticity or retention functiona according to van Genuchten Mualem model (1980)
real(kind=rkind) function, public vangen_d (pde_loc, layer, quadpnt, x)
defines mass functiona according to van Genuchten Mualem model (1980)
subroutine, public darcy_law_d (pde_loc, layer, quadpnt, x, grad, flux, flux_length)
defines flux function according to Darcy Law (valid for laminar flow)
Detailed Description
This module contains governing functions of the dual permeability model and main functions and subroutines.
Function/Subroutine Documentation
subroutine, public dual_por::darcy_law_d (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional grad, real(kind=rkind), dimension(:), intent(out), optional flux, real(kind=rkind), intent(out), optional flux_length)
defines flux function according to Darcy Law (valid for laminar flow)
Parameters
in grad this value is optional, because it is required by the vector_fnc procedure pointer global definition
Definition at line 349 of file Re_dual_totH.f90.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use pde_objs
      use global_objs
       
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), intent(in), dimension(:), optional :: x
      real(kind=rkind), dimension(:), intent(in), optional :: grad
      real(kind=rkind), dimension(:), intent(out), optional :: flux
      real(kind=rkind), intent(out), optional :: flux_length
      real(kind=rkind), dimension(3,3) :: k
      integer(kind=ikind) :: d
      integer(kind=ikind) :: i
      real(kind=rkind), dimension(:), allocatable, save :: gradh
      real(kind=rkind), dimension(:), allocatable, save :: vct
      real(kind=rkind) :: h
      type(integpnt_str) :: quadpnt_loc
      
      d = drutes_config%dimen
      if (.not.(allocated(gradh))) then
            allocate(gradh(1:d))
            allocate(vct(1:d))
      end if
      if (present(quadpnt) .and. (present(grad) .or. present(x))) then
        print *, "ERROR: the function can be called either with integ point or x value definition and
       gradient, not both of them"
        print *, "exited from Re_dual_totH::darcy_law"
        error stop
      else if ((.not. present(grad) .or. .not. present(x)) .and. .not. present(quadpnt)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from Re_dual_totH::darcy_law"
        error stop
      end if
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
        call pde_loc%getgrad(quadpnt, gradh)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from Re_dual_totH::darcy_law"
          error stop
        end if
        h = x(1)
        gradh(1:d) = grad
      end if
      
      call pde_loc%pde_fnc(pde_loc%order)%dispersion(pde_loc, layer, x=(/h/), tensor=k(1:d, 1:d))
      vct(1:d) = matmul(-k(1:d,1:d), gradh(1:d))
         !print*,vct
      if (present(flux_length)) then
        select case(d)
          case(1)
                flux_length = vct(1)
          case(2)
                flux_length = sqrt(vct(1)*vct(1) + vct(2)*vct(2))
          case(3)
                flux_length = sqrt(vct(1)*vct(1) + vct(2)*vct(2) + vct(3)*vct(3))
        end select
      end if
      if (present(flux)) then
        flux(1:d) = vct(1:d)
      end if
subroutine, public dual_por::dual_inicond (class(pde_str), intent(inout) pde_loc)
assigns initial condition
Definition at line 49 of file Re_dual_totH.f90.
References dual_globals::disttozero, globals::drutes_config, globals::elements, geom_tools::map1d2dj(), globals::nodes, dual_globals::vgfracture, and dual_globals::vgmatrix.
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
        use typy
        use globals
        use global_objs
        use pde_objs
        use dual_globals
        use debug_tools
        use geom_tools
        
        class(pde_str), intent(in out) :: pde_loc
        integer(kind=ikind) :: i, j, k,l, m, layer, d,n
        real(kind=rkind) :: value
        
        d = drutes_config%dimen
        select case (pde_loc%mfswitch)
        case("m")
          select case (vgmatrix(1_ikind)%icondtype)
              case("input")
                call map1d2dj(pde_loc,"drutes.conf/REdual/hinim.in")
          end select
          do i=1, elements%kolik
            layer = elements%material(i,1)
            do j=1, ubound(elements%data,2)
              k = elements%data(i,j)
              l = nodes%edge(k)
              m = pde_loc%permut(k)
              if (m == 0) then
                call pde_loc%bc(l)%value_fnc(pde_loc, i, j, value)
                pde_loc%solution(k) = value
              else
                select case (vgmatrix(layer)%icondtype)
                  case("H_tot")
                    pde_loc%solution(k) = vgmatrix(layer)%initcond+disttozero ! nodes%data(k,D)
                  case("hpres")
                    pde_loc%solution(k) = vgmatrix(layer)%initcond+nodes%data(k,d)
                end select
              end if
            end do
          end do
        case("f")
          select case (vgfracture(1_ikind)%icondtype)
            case("input")
              call map1d2dj(pde_loc,"drutes.conf/REdual/hinif.in")
            end select
          do i=1, elements%kolik
            layer = elements%material(i,1)
            do j=1, ubound(elements%data,2)
              k = elements%data(i,j)
              l = nodes%edge(k)
              m = pde_loc%permut(k)
              if (m == 0) then
                call pde_loc%bc(l)%value_fnc(pde_loc, i, j, value)
                pde_loc%solution(k) = value
              else
                select case (vgfracture(layer)%icondtype)
                  case("H_tot")
                    pde_loc%solution(k) = vgfracture(layer)%initcond+disttozero !- nodes%data(k,D)
                  case("hpres")
                    pde_loc%solution(k) = vgfracture(layer)%initcond+nodes%data(k,d)
                  end select
              end if
            end do
          end do
         case default
                print *, "ERROR! Something is wrong"
                print *, "the error is in dual_por::dual_inicond"
                error stop
        end select
subroutine, public dual_por::dual_mualem (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:,:), intent(out), optional tensor, real(kind=rkind), intent(out), optional scalar)
defines dispersion functiona according to van Genuchten Mualem model (1980)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
out tensor return tensor
out scalar relative scalar value of the nonlinear function
vg parameters, later from conf file
Definition at line 122 of file Re_dual_totH.f90.
References dual_globals::exchange, dual_globals::vgfracture, and dual_globals::vgmatrix.
Referenced by dual_coup::dual_coup_min(), dual_tab::dual_coupling_tab(), dual_tab::dual_mualem_tab(), re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use global_objs
      use pde_objs
      use globals
      use debug_tools
      use dual_globals
      use re_dual_reader
          
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:,:), intent(out), optional :: tensor
      real(kind=rkind), intent(out), optional :: scalar
      real(kind=rkind)::n,m,alpha, weight
      real(kind=rkind) :: h,kr,one
      type(integpnt_str) :: quadpnt_loc
        
          
        if (present(quadpnt)) then
          quadpnt_loc=quadpnt
          quadpnt_loc%preproc=.true.
         h = pde_loc%getval(quadpnt_loc)
        else
          if (ubound(x,1) /=1) then
                print *, "ERROR: van Genuchten function is a function of a single variable h"
                print *, " your input data has:", ubound(x,1), "variables"
                print *, "exited from RE_dual::dual_mualemm"
                error stop
              end if
            h = x(1)
        end if
        select case (pde_loc%mfswitch)
          case("m")
            alpha=vgmatrix(layer)%alpha
            n=vgmatrix(layer)%n
            m=vgmatrix(layer)%m
            weight=exchange(layer)%weightm
          case("f")
            alpha=vgfracture(layer)%alpha
            n=vgfracture(layer)%n
            m=vgfracture(layer)%m
            weight=exchange(layer)%weightf
          case default
            print *, "ERROR! Something is wrong"
            print *, "the error is in dual_por::dual_mualem"
            error stop
        end select
        
        one=1.0_rkind
        if(h < 0.0_rkind) then
          kr=(one-(alpha*abs(h))**(n*m)*(one+(alpha*abs(h))**n)**(-m))**2/(one+(alpha*abs(h))**n)**(m/2)
        else
          kr=1.0_rkind
        end if
        
        if (present(tensor)) then
          select case (pde_loc%mfswitch)
            case("m")
              tensor=vgmatrix(layer)%KS*kr*weight
            case("f")
              tensor=vgfracture(layer)%KS*kr*weight
          end select
        end if
        
        if (present(scalar)) then
          scalar=kr*weight
        end if
real(kind=rkind) function, public dual_por::dual_ret_cap (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
defines elasticity or retention functiona according to van Genuchten Mualem model (1980)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
vg parameters, later from conf file
Definition at line 201 of file Re_dual_totH.f90.
References dual_globals::exchange, dual_globals::vgfracture, and dual_globals::vgmatrix.
Referenced by dual_tab::dual_ret_cap_tab(), re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use pde_objs
      use core_tools
      use dual_globals
      use re_dual_reader
      use debug_tools
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), intent(in), dimension(:), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind)::n,m,alpha,thetas,thetar,weight
      real(kind=rkind)::e,h,c
      type(integpnt_str) :: quadpnt_loc
      
      
      
      if (present(quadpnt)) then
        quadpnt_loc=quadpnt
        quadpnt_loc%preproc=.true.
        h = pde_loc%getval(quadpnt_loc)
      else
        if (ubound(x,1) /=1) then
              print *, "ERROR: van Genuchten function is a function of a single variable h"
              print *, " your input data has:", ubound(x,1), "variables"
              error stop
            end if
        if (ubound(x,1) /=1) then
              print *, "ERROR: van Genuchten function is a function of a single variable h"
              print *, " your input data has:", ubound(x,1), "variables"
              print *, "exited from RE_dual::dual_ret_capm"
              error stop
            end if
            h = x(1)
      end if
      
        select case (pde_loc%mfswitch)
          case("m")
            thetas=vgmatrix(layer)%ThS
            thetar=vgmatrix(layer)%ThR
            alpha=vgmatrix(layer)%alpha
            n=vgmatrix(layer)%n
            m=vgmatrix(layer)%m
            weight=exchange(layer)%weightm
          case("f")
            thetas=vgfracture(layer)%ThS
            thetar=vgfracture(layer)%ThR
            alpha=vgfracture(layer)%alpha
            n=vgfracture(layer)%n
            m=vgfracture(layer)%m
            weight=exchange(layer)%weightf
          case default
            print *, "ERROR! Something is wrong"
            print *, "the error is in dual_por::dual_ret_cap"
            error stop
        end select
     
     
     if(h<0.0_rkind) then
       c=(thetas-thetar)*alpha*m*n*(alpha*abs(h))**(n-1)*((alpha*abs(h))**n+1)**(-m-1)
     else
        select case (pde_loc%mfswitch)
          case("m")
            e=vgmatrix(layer)%Ss*weight
          case("f")
            e=vgfracture(layer)%Ss*weight
        end select
       return
     end if
     
     e=c*weight
real(kind=rkind) function, public dual_por::getval_retot_dual (class(pde_str), intent(in) pde_loc, type(integpnt_str), intent(in) quadpnt)
specific function for Richards equation in H-form (total hydraulic head form), replaces pde_objs::getvalp1 in order to distinguish between H and h pointers point to this with pde_locgetval
Definition at line 20 of file Re_dual_totH.f90.
References geom_tools::getcoor(), and pde_objs::getvalp1().
Referenced by re_dual_pointers::re_fracture(), and re_dual_pointers::re_matrix().
      use typy
      use pde_objs
      use geom_tools
      use dual_globals
      
      class(pde_str), intent(in) :: pde_loc
      type(integpnt_str), intent(in) :: quadpnt
      real(kind=rkind) :: val
      
      real(kind=rkind), dimension(3) :: xyz
      integer(kind=ikind) :: d
      
          
      if (quadpnt%preproc) then
      
        d = drutes_config%dimen
      
        call getcoor(quadpnt, xyz(1:d))
        val = getvalp1(pde_loc, quadpnt) - xyz(d)
      else
        val = getvalp1(pde_loc, quadpnt)
      end if
      
        
real(kind=rkind) function, public dual_por::vangen_d (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
defines mass functiona according to van Genuchten Mualem model (1980)
Parameters
in x pressure head
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
Returns
resulting water content
Definition at line 281 of file Re_dual_totH.f90.
References dual_globals::exchange, dual_globals::vgfracture, and dual_globals::vgmatrix.
Referenced by re_dual_pointers::re_fracture(), re_dual_pointers::re_matrix(), and dual_tab::vangen_d_tab().
  
        use typy
        use dual_globals
        use pde_objs
        class(pde_str), intent(in) :: pde_loc
        integer(kind=ikind), intent(in) :: layer
        real(kind=rkind), intent(in), dimension(:), optional :: x
        type(integpnt_str), intent(in), optional :: quadpnt
        real(kind=rkind) :: h
        real(kind=rkind) :: theta
        real(kind=rkind)::n,m,alpha,thetas,thetar,weight, theta_e
        type(integpnt_str) :: quadpnt_loc
        
      
        if (present(quadpnt)) then
            quadpnt_loc=quadpnt
            quadpnt_loc%preproc=.true.
            h = pde_loc%getval(quadpnt_loc)
        else
            if (ubound(x,1) /=1) then
            print *, "ERROR: van Genuchten function is a function of a single variable h"
            print *, " your input data has:", ubound(x,1), "variables"
            print *, "exited from RE_dual::vangen_d_m"
            error stop
            end if
            h = x(1)
        end if
        select case (pde_loc%mfswitch)
        case("m")
            thetas=vgmatrix(layer)%ThS
            thetar=vgmatrix(layer)%ThR
            alpha=vgmatrix(layer)%alpha
            n=vgmatrix(layer)%n
            m=vgmatrix(layer)%m
            weight=exchange(layer)%weightm
        case("f")
            thetas=vgfracture(layer)%ThS
            thetar=vgfracture(layer)%ThR
            alpha=vgfracture(layer)%alpha
            n=vgfracture(layer)%n
            m=vgfracture(layer)%m
            weight=exchange(layer)%weightf
        case default
            print *, "ERROR! Something is wrong"
            print *, "the error is in dual_por::dual_ret_cap"
            error stop
        end select
        
        if (h >=0.0_rkind) then
        select case (pde_loc%mfswitch)
            case("m")
                theta = vgmatrix(layer)%Ths
            case("f")
                theta = vgfracture(layer)%Ths
            end select
            return
        else
                theta_e = 1/(1+(alpha*(abs(h)))**n)**m
                theta = theta_e*(thetas- thetar)+ thetar
        end if