ade_fnc Module Reference
Functions/Subroutines
subroutine, public adedispersion (pde_loc, layer, quadpnt, x, tensor, scalar)
subroutine, public ade_convection (pde_loc, layer, quadpnt, x, vector_in, vector_out, scalar)
real(kind=rkind) function, public ade_tder_coef (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public ade_tder_cscl (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public ade_tder_cscs (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public ade_mass (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public ade_reaction (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public ade_zerorder (pde_loc, layer, quadpnt, x)
subroutine, public ade_dirichlet (pde_loc, el_id, node_order, value, code)
subroutine, public ade_neumann (pde_loc, el_id, node_order, value, code)
subroutine, public ade_null_bc (pde_loc, el_id, node_order, value, code)
subroutine, public ade_flux (pde_loc, layer, quadpnt, x, grad, flux, flux_length)
subroutine, public ade_icond (pde_loc)
real(kind=rkind) function, public ade_cscs_react (pde_loc, layer, quadpnt, x)
real(kind=rkind) function, public ade_cscl_react (pde_loc, layer, quadpnt, x)
subroutine, public ade_csbc (pde_loc, el_id, node_order, value, code)
subroutine, public adecs_icond (pde_loc)
real(kind=rkind) function, public adecs_mass (pde_loc, layer, quadpnt, x)
Function/Subroutine Documentation
subroutine, public ade_fnc::ade_convection (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional vector_in, real(kind=rkind), dimension(:), intent(out), optional vector_out, real(kind=rkind), intent(out), optional scalar)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
in vector_in input vector
out vector_out output vector
out scalar relative scalar value of the nonlinear function
Definition at line 77 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::ade().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:), intent(in), optional :: vector_in
      real(kind=rkind), dimension(:), intent(out), optional :: vector_out
      real(kind=rkind), intent(out), optional :: scalar
      
      
      if (pde_loc%order == 1) then
        if (present(vector_out)) then
          vector_out = adepar(layer)%convection
        end if
        
        
        if (present(scalar)) then
          scalar = abs(adepar(layer)%convection)
        end if
      else
        if (present(vector_out)) then
          call pde(1)%flux(layer, quadpnt, vector_out=vector_out)
        end if
        
        if (present(scalar)) then
          call pde(1)%flux(layer, quadpnt, scalar=scalar)
        end if
        
      end if
      
      
subroutine, public ade_fnc::ade_csbc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 645 of file ADE_fnc.f90.
      use typy
      use globals
      use global_objs
      use pde_objs
      use debug_tools
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      
      integer(kind=ikind) :: edge_id, i, j, proc
      real(kind=rkind) :: tempval
     
      
      if (present(value)) then
        value = 0.0
      end if
      
      if (present(code)) then
        code = 0
      end if
      
real(kind=rkind) function, public ade_fnc::ade_cscl_react (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 608 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::adekinsorb().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      integer(kind=ikind) :: proc_cl
      real(kind=rkind) :: cl
      
      
      select case(adepar(layer)%sorption%name)
        case("langmu")
          val = adepar(layer)%sorption%adsorb*adepar(layer)%sorption%third
        case("freund")
          if (abs(adepar(layer)%sorption%third - 1.0_rkind) > 10*epsilon(1.0_rkind)) then
            proc_cl = pde_loc%order - 1
            cl = pde(proc_cl)%getval(quadpnt)
            val = adepar(layer)%sorption%adsorb*cl**(1-adepar(layer)%sorption%third)
          else
            val = adepar(layer)%sorption%adsorb
          end if
      end select
      
real(kind=rkind) function, public ade_fnc::ade_cscs_react (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 574 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::adekinsorb().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      integer(kind=ikind) :: proc_cl
      real(kind=rkind) :: cs, cl
      
      proc_cl = pde_loc%order - 1
      
      
      select case(adepar(layer)%sorption%name)
        case("langmu")
          cs = pde_loc%getval(quadpnt)
          cl = pde(proc_cl)%getval(quadpnt)
          val = -adepar(layer)%sorption%adsorb*cl - adepar(layer)%sorption%desorb
        case("freund")
          val = -adepar(layer)%sorption%desorb
      end select
      
      
subroutine, public ade_fnc::ade_dirichlet (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 347 of file ADE_fnc.f90.
References globals::elements, globals::nodes, and globals::time.
Referenced by ade_pointers::ade().
      use typy
      use globals
      use global_objs
      use pde_objs
      use debug_tools
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      
      integer(kind=ikind) :: edge_id, i, j, proc
      real(kind=rkind) :: tempval
      
      edge_id = nodes%edge(elements%data(el_id, node_order))
      
      if (present(value)) then
        if (pde_loc%bc(edge_id)%file) then
          do i=1, ubound(pde_loc%bc(edge_id)%series,1)
            if (pde_loc%bc(edge_id)%series(i,1) > time) then
              if (i > 1) then
                j = i-1
              else
                j = i
              end if
              tempval = pde_loc%bc(edge_id)%series(j,2)
              EXIT
            end if
          end do
        else
          tempval = pde_loc%bc(edge_id)%value
        end if
        value = tempval
      end if
      
      if (present(code)) then
        code = 1
      end if
      
subroutine, public ade_fnc::ade_flux (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:), intent(in), optional grad, real(kind=rkind), dimension(:), intent(out), optional flux, real(kind=rkind), intent(out), optional flux_length)
Parameters
in grad this value is optional, because it is required by the vector_fnc procedure pointer global definition
Definition at line 461 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::ade().
      use typy
      use pde_objs
      use global_objs
      use debug_tools
      use ade_globals
       
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: layer
      type(integpnt_str), intent(in), optional :: quadpnt
      real(kind=rkind), intent(in), dimension(:), optional :: x
      real(kind=rkind), dimension(:), intent(in), optional :: grad
      real(kind=rkind), dimension(:), intent(out), optional :: flux
      real(kind=rkind), intent(out), optional :: flux_length
    
      real(kind=rkind), dimension(:,:), allocatable, save :: dhm
      real(kind=rkind), dimension(:), allocatable, save :: q_w, gradc
      real(kind=rkind) :: c, cmax
      
      
      if (present(quadpnt) .and. (present(grad) .or. present(x))) then
        print *, "ERROR: the function can be called either with integ point or x value definition and
       gradient, not both of them"
        print *, "exited from ADE_fnc::ADE_flux"
        error stop
      else if ((.not. present(grad) .or. .not. present(x)) .and. .not. present(quadpnt)) then
        print *, "ERROR: you have not specified either integ point or x value"
        print *, "exited from ADE_fnc::ADE_flux"
        error stop
      end if
      
      if (.not. allocated(q_w)) allocate(q_w(drutes_config%dimen))
      if (.not. allocated(gradc)) allocate(gradc(drutes_config%dimen))
      
      if (.not. allocated(dhm)) allocate(dhm(drutes_config%dimen, drutes_config%dimen))
      if (present(quadpnt)) then
        c = pde_loc%getval(quadpnt)
        call pde_loc%getgrad(quadpnt, gradc)
      else
        if (ubound(x,1) /=1) then
          print *, "ERROR: van Genuchten function is a function of a single variable h"
          print *, " your input data has:", ubound(x,1), "variables"
          print *, "exited from ADE_fnc::ADE_flux"
          error stop
        end if
        c = x(1)
        gradc = grad
      end if
      
      
      call pde_loc%pde_fnc(1)%dispersion(pde_loc, layer, quadpnt, tensor=dhm)
      select case(pde_loc%order)
        case(1)
          q_w = adepar(layer)%convection
        case(2)
          call pde(1)%flux(layer, quadpnt, vector_out=q_w)
      end select
      
      select case(adepar(layer)%icondtype)
        case("ca")
          cmax = 1.0_rkind
         case("cr")
          cmax = adepar(layer)%cmax
      end select
      
      
      if (present(flux)) then
        flux = cmax*matmul(dhm, gradc) + cmax*q_w*c
      end if
    
subroutine, public ade_fnc::ade_icond (class(pde_str), intent(inout) pde_loc)
Definition at line 536 of file ADE_fnc.f90.
References ade_globals::adepar, globals::drutes_config, globals::elements, and globals::nodes.
Referenced by ade_pointers::ade().
      use typy
      use globals
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in out) :: pde_loc
      integer(kind=ikind) :: i, j, k,l, m, layer, d
      real(kind=rkind) :: value
      
   
      d = drutes_config%dimen
      do i=1, elements%kolik
        layer = elements%material(i,1)
        do j=1, ubound(elements%data,2)
          k = elements%data(i,j)
          l = nodes%edge(k)
          m = pde_loc%permut(k)
          if (m == 0) then
            call pde_loc%bc(l)%value_fnc(pde_loc, i, j, value)
            pde_loc%solution(k) = value
          else
            select case (adepar(layer)%icondtype)
              case("ca")
                pde_loc%solution(k) = adepar(layer)%cinit
              case("cr")
                pde_loc%solution(k) = adepar(layer)%cinit * adepar(layer)%cmax
            end select
          end if
        end do
      end do
    
    
real(kind=rkind) function, public ade_fnc::ade_mass (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 233 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::ade().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      real(kind=rkind) :: theta
      
      if (pde_loc%order == 1) then
        theta = adepar(layer)%water_cont
      else
        theta = pde(1)%mass(layer, quadpnt)
      end if
      
      if (present(quadpnt)) then
        val = theta*pde_loc%getval(quadpnt)
      else
        val = theta * x(1)
      end if
      
subroutine, public ade_fnc::ade_neumann (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 393 of file ADE_fnc.f90.
References globals::elements, globals::nodes, and globals::time.
Referenced by ade_pointers::ade().
      use typy
      use globals
      use global_objs
      use pde_objs
      use debug_tools
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      
      integer(kind=ikind) :: edge_id, i, j, proc
      real(kind=rkind) :: tempval
      
      edge_id = nodes%edge(elements%data(el_id, node_order))
      
      if (present(value)) then
        if (pde_loc%bc(edge_id)%file) then
          do i=1, ubound(pde_loc%bc(edge_id)%series,1)
            if (pde_loc%bc(edge_id)%series(i,1) > time) then
              if (i > 1) then
                j = i-1
              else
                j = i
              end if
              tempval = pde_loc%bc(edge_id)%series(j,2)
              EXIT
            end if
          end do
        else
          tempval = pde_loc%bc(edge_id)%value
        end if
        value = tempval
      end if
      
      if (present(code)) then
        code = 2
      end if
      
subroutine, public ade_fnc::ade_null_bc (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) el_id, integer(kind=ikind), intent(in) node_order, real(kind=rkind), intent(out), optional value, integer(kind=ikind), intent(out), optional code)
Definition at line 439 of file ADE_fnc.f90.
Referenced by ade_pointers::adekinsorb().
      use typy
      use globals
      use global_objs
      use pde_objs
      
      class(pde_str), intent(in) :: pde_loc
      integer(kind=ikind), intent(in) :: el_id, node_order
      real(kind=rkind), intent(out), optional :: value
      integer(kind=ikind), intent(out), optional :: code
      if (present(value)) then
        value = 0.0_rkind
      end if
      if (present(code)) then
        code = 2
      end if
        
real(kind=rkind) function, public ade_fnc::ade_reaction (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 264 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::ade().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      integer(kind=ikind) :: n, i
      real(kind=rkind) :: theta, cl
      
     
      if (pde_loc%order == 2) then
        theta = pde(1)%mass(layer, quadpnt)
      else
        theta = adepar(layer)%water_cont
      end if
      
      val = 0.0_rkind
      
      do i=1, ubound(adepar(layer)%orders,1)
        n = 10
        if (abs(adepar(layer)%orders(i) - 1.0_rkind) < 100*epsilon(1.0_rkind)) n = 1
        if (abs(adepar(layer)%orders(i)) < 100*epsilon(1.0_rkind)) n = 0
        select case(n)
          case(0)
            CONTINUE
          case(1)
            val = val + theta*adepar(layer)%lambda(i)
          case default
            cl = pde_loc%getval(quadpnt)
            val = theta*adepar(layer)%lambda(i)*cl**(adepar(layer)%orders(i)-1)
        end select
      end do
        
          
      
      
real(kind=rkind) function, public ade_fnc::ade_tder_coef (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 121 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::ade().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      real(kind=rkind) :: theta, n, ka, kd, csmax, cl
      
      
      if (pde_loc%order == 2) then
        theta = pde(1)%mass(layer, quadpnt)
      else
        theta = adepar(layer)%water_cont
      end if
      
      
      if (.not. adepar(layer)%sorption%kinetic) then
        ka = adepar(layer)%sorption%adsorb
        kd = adepar(layer)%sorption%desorb
        if (ka > 10*epsilon(ka) .and. kd > 10*epsilon(kd)) then
          select case(adepar(layer)%sorption%name)
            case("freund")
              n = adepar(layer)%sorption%third
              if (abs(n-1.0_rkind)>10*epsilon(n)) then
                cl = pde_loc%getval(quadpnt)
                val = theta+(1-theta)*ka/kd*adepar(layer)%bd*cl**(n-1)
              else
                val = theta+(1-theta)*ka/kd*adepar(layer)%bd
              end if
            
            case("langmu")
              cl = pde_loc%getval(quadpnt)
              csmax = adepar(layer)%sorption%third
              val = theta + (1-theta)*adepar(layer)%bd*(ka*csmax)/(kd+ka*cl)
            case default
              print *, "unsupported sorption type, runtime error, called from ADE_fnc::ADE_tder_coef"
              error stop
            
          end select
        else
          val = theta
        end if
        
      else
        val = theta
      end if
     
      
    
real(kind=rkind) function, public ade_fnc::ade_tder_cscl (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 183 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::adekinsorb().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      real(kind=rkind) :: theta
      
      if (pde_loc%order == 2) then
        theta = pde(1)%mass(layer, quadpnt)
      else
        theta = adepar(layer)%water_cont
      end if
      
      val = 1.0_rkind-theta
      
real(kind=rkind) function, public ade_fnc::ade_tder_cscs (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 212 of file ADE_fnc.f90.
Referenced by ade_pointers::adekinsorb().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      val = 1.0_rkind
    
real(kind=rkind) function, public ade_fnc::ade_zerorder (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 312 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
Referenced by ade_pointers::ade().
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      
      integer(kind=ikind) :: n, i
      real(kind=rkind) :: theta
      
      if (pde_loc%order == 2) then
        theta = pde(1)%mass(layer, quadpnt)
      else
        theta = adepar(layer)%water_cont
      end if
      
       val = 0.0_rkind
       do i=1, ubound(adepar(layer)%orders,1)
        if (abs(adepar(layer)%orders(i)) < 100*epsilon(1.0_rkind)) then
          val = val + theta*adepar(layer)%lambda(i)
        end if
      end do
      
      
subroutine, public ade_fnc::adecs_icond (class(pde_str), intent(inout) pde_loc)
Definition at line 675 of file ADE_fnc.f90.
Referenced by ade_pointers::adekinsorb().
      use typy
      use pde_objs
      
      class(pde_str), intent(in out) :: pde_loc
      
      pde_loc%solution = 0.0_rkind
    
real(kind=rkind) function, public ade_fnc::adecs_mass (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
Returns
return value
Definition at line 687 of file ADE_fnc.f90.
References ade_globals::adepar, and pde_objs::pde.
      use typy
      use global_objs
      use pde_objs
      use ade_globals
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind) :: val
      real(kind=rkind) :: theta
      
      if (pde_loc%order == 2) then
        theta = adepar(layer)%water_cont
      else
        theta = pde(1)%mass(layer, quadpnt)
      end if
      
      if (present(quadpnt)) then
        val = pde_loc%getval(quadpnt)*(1-theta)
      else
        print *, "exited from ADE_fnc::ADEcs_mass"
        error stop
      end if
    
subroutine, public ade_fnc::adedispersion (class(pde_str), intent(in) pde_loc, integer(kind=ikind), intent(in) layer, type(integpnt_str), intent(in), optional quadpnt, real(kind=rkind), dimension(:), intent(in), optional x, real(kind=rkind), dimension(:,:), intent(out), optional tensor, real(kind=rkind), intent(out), optional scalar)
Parameters
in x value of the nonlinear function
in quadpnt Gauss quadrature point structure (element number and rank of Gauss quadrature point)
in layer material ID
out tensor return tensor
out scalar relative scalar value of the nonlinear function
Definition at line 13 of file ADE_fnc.f90.
References ade_globals::adepar, globals::drutes_config, pde_objs::pde, and re_globals::vgset.
Referenced by ade_pointers::ade().
      use typy
      use global_objs
      use pde_objs
      use globals
      use ade_globals
      use re_globals
      use debug_tools
      
      class(pde_str), intent(in) :: pde_loc
      real(kind=rkind), dimension(:), intent(in), optional :: x
      type(integpnt_str), intent(in), optional :: quadpnt
      integer(kind=ikind), intent(in) :: layer
      real(kind=rkind), dimension(:,:), intent(out), optional :: tensor
      real(kind=rkind), intent(out), optional :: scalar
      
      real(kind=rkind), dimension(3,3) :: identity
      real(kind=rkind), dimension(3) :: q_w
      real(kind=rkind) :: theta, q_abs, tortuo, ths
      integer(kind=ikind) :: d, i
      
     
      d = drutes_config%dimen
      identity = 0.0
      do i=1, d
        identity(i,i) = 1.0
      end do
      
      select case(drutes_config%name)
        case("ADEstd", "ADEstd_kinsorb")
          q_w = adepar(layer)%convection
          theta = adepar(layer)%water_cont
          ths = adepar(layer)%water_cont
        case default
          theta = pde(1)%mass(layer, quadpnt)
          call pde(1)%flux(layer, quadpnt, vector_out = q_w(1:d))
          ths = vgset(layer)%ths
      end select
      
      q_abs = 0.0
      do i=1, d
        q_abs =q_abs + q_w(i)*q_w(i)
      end do
      q_abs = sqrt(q_abs)
      tortuo = theta**(10.0/3.0)/(ths*ths)
      
      
      if (present(tensor)) then
        tensor = theta * (adepar(layer)%diff*q_abs + adepar(layer)%difmol*identity(1:d, 1:d))
      end if
      
      
      
    