core_tools Module Reference
Functions/Subroutines
character(len=:) function, allocatable, public cut (ch)
dummy functions, the pointer procedure is set to this function in case if not being considered
subroutine, public write_log (text, real1, int1, text2, real2, int2, text3, real3, int3, hidden)
real(kind=rkind) function, public avg (a, b)
subroutine, public mesh_allocater ()
allocates structures for nodes and elements
subroutine, public find_unit (iunit, start_id)
Function/Subroutine Documentation
real(kind=rkind) function, public core_tools::avg (real(kind=rkind), intent(in) a, real(kind=rkind), intent(in) b)
Definition at line 132 of file core_tools.f90.
Referenced by simegen::simegen1d().
      use typy
      real(kind=rkind), intent(in) :: a
      real(kind=rkind), intent(in) :: b
      real(kind=rkind) :: c
      c = (a+b)/2.0_rkind
character(len=:) function, allocatable, public core_tools::cut (character(len=*), intent(in) ch)
dummy functions, the pointer procedure is set to this function in case if not being considered
Definition at line 30 of file core_tools.f90.
Referenced by geom_tools::map1d2d(), and geom_tools::map1d2dj().
  
    character(len=*), intent(in) :: ch
    character(len=:), allocatable :: out_ch
    
    allocate(character(len=len(adjustl(trim(ch)))) :: out_ch)
    
    out_ch=adjustl(trim(ch))
    
subroutine, public core_tools::find_unit (integer, intent(out) iunit, integer, intent(in), optional start_id)
Definition at line 177 of file core_tools.f90.
Referenced by ade_reader::ade_read(), boussread::boussreader(), drutes_init::get_cmd_options(), postpro::get_ram_use(), heat_reader::heat_read(), re_total::iconddebouss(), decomposer::init_decomp(), drutes_init::init_observe(), main(), postpro::make_print(), geom_tools::map1d2d(), geom_tools::map1d2dj(), drutes_init::parse_globals(), decomp_tools::print_domains(), decomp_tools::print_elements_dd(), debug_tools::print_int_matrix(), debug_tools::print_int_vector(), debug_tools::print_logical_array(), debug_tools::print_quadpnt(), debug_tools::print_real_matrix(), debug_tools::print_real_vector(), debug_tools::print_real_vector4(), debug_tools::print_smartarray_i(), debug_tools::print_smartmatrix_i(), debug_tools::print_sparse_matrix(), re_dual_reader::re_dual_readf(), re_dual_reader::re_dual_readm(), re_dual_reader::re_dual_var(), read_inputs::read_2dmesh_gmsh(), decomposer::read_coarse_mesh(), read_inputs::read_scilab(), readtools::readbcvals(), re_reader::res_read(), drutes_init::set_global_vars(), fem::solve_pde(), and printtools::time2finish().
      integer, intent(out) :: iunit
      integer, intent(in), optional :: start_id
      logical :: op
      if (present(start_id)) then
        iunit = start_id*1 + 1
      else
        iunit = 100 ! the lower values are often reserved
      end if
      do
        inquire(unit=iunit,opened=op)
        if (.not.op) then
          exit
        end if
        iunit = iunit + 1
        if (iunit >= huge(iunit) - 1) then
          error stop "SYSTEM PANIC, unable to find any free unit"
          exit
        end if
      end do
  
subroutine, public core_tools::mesh_allocater ()
allocates structures for nodes and elements
Definition at line 143 of file core_tools.f90.
References globals::drutes_config, globals::elements, globals::nodes, and pde_objs::pde_common.
Referenced by read_inputs::read_2dmesh_gmsh(), read_inputs::read_2dmesh_t3d(), simegen::simegen1d(), and simegen::simegen2d().
      use typy
      use global_objs
      use pde_objs
      use globals
      integer :: n
      allocate(nodes%id(nodes%kolik))
      allocate(nodes%edge(nodes%kolik))
      allocate(nodes%data(nodes%kolik,drutes_config%dimen))
      allocate(nodes%boundary(nodes%kolik))
      allocate(nodes%el2integ(nodes%kolik))
      allocate(nodes%element(nodes%kolik))
      allocate(elements%length(elements%kolik,drutes_config%dimen + 1))
      allocate(elements%nvect_z(elements%kolik,drutes_config%dimen + 1))
      allocate(elements%id(elements%kolik))
      allocate(elements%data(elements%kolik, drutes_config%dimen+1))
      allocate(elements%areas(elements%kolik))
      allocate(elements%ders(elements%kolik, drutes_config%dimen+1,
      drutes_config%dimen))
      allocate(elements%border(elements%kolik))
      
      n = pde_common%processes
      allocate(elements%material(elements%kolik, n))
      
      allocate(elements%neighbours(elements%kolik, ubound(elements%data,2)))
      allocate(nodes%boundary_order(nodes%kolik))
      
subroutine, public core_tools::write_log (character(len=*), intent(in) text, real(kind=rkind), intent(in), optional real1, integer(kind=ikind), intent(in), optional int1, character(len=*), intent(in), optional text2, real(kind=rkind), intent(in), optional real2, integer(kind=ikind), intent(in), optional int2, character(len=*), intent(in), optional text3, real(kind=rkind), intent(in), optional real3, integer(kind=ikind), intent(in), optional int3, logical, optional hidden)
character to store the time info
the character to store the date info
Definition at line 41 of file core_tools.f90.
References globals::logfile, and globals::terminal.
Referenced by decomposer::clear_subdomain(), re_constitutive::dmualem_dh_tab(), dual_tab::dual_tabvalues(), fem::evol_dt(), fem::exitme(), feminittools::feminit(), postpro::get_ram_use(), fem_tools::icond4neumann(), decomposer::init_decomp(), re_constitutive::intoverflow(), re_constitutive::inverse_vangen(), main(), postpro::make_print(), decomposer::make_quadmesh(), re_constitutive::mualem_tab(), drutes_init::parse_globals(), read_inputs::read_2dmesh_gmsh(), decomposer::read_coarse_mesh(), objfnc::reader(), decomposer::set_subdomains(), geom_tools::solve_bisect(), fem::solve_pde(), feminittools::surface_integ(), re_constitutive::tabvalues(), re_constitutive::vangen_elast_tab(), and re_constitutive::vangen_tab().
    use typy
    use globals
    character(len=*), intent(in) :: text
    real(kind=rkind), intent(in), optional :: real1, real2, real3
    integer(kind=ikind), intent(in), optional :: int1, int2, int3
    character(len=*), intent(in), optional :: text2, text3
    character(len=10) :: timer
    character(len=8) :: dater
    character(len=1024) :: ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8
    logical, optional :: hidden
    if (present(real1)) then
      write(unit=ch1, fmt=*) real1
    else
      write(unit=ch1, fmt=*) ""
    end if
    if (present(int1)) then
      write(unit=ch2, fmt=*) int1
    else
      write(unit=ch2, fmt=*) ""
    end if
    if (present(text2)) then
      write(unit=ch3, fmt=*) text2
    else
      write(unit=ch3, fmt=*) ""
    end if
    if (present(real2)) then
      write(unit=ch4, fmt=*) real2
    else
      write(unit=ch4, fmt=*) ""
    end if
    if (present(int2)) then
      write(unit=ch5, fmt=*) int2
    else
      write(unit=ch5, fmt=*) ""
    end if
    
    if (present(text3)) then
      write(unit=ch6, fmt=*) text3
    else
      write(unit=ch6, fmt=*) ""
    end if
    if (present(real3)) then
      write(unit=ch7, fmt=*) real3
    else
      write(unit=ch7, fmt=*) ""
    end if
    if (present(int3)) then
      write(unit=ch8, fmt=*) int3
    else
      write(unit=ch8, fmt=*) ""
    end if
    call date_and_time(dater, timer)
    write(unit=logfile, fmt = *) "---------------------------------------------------------------"
    write(unit=logfile, fmt = *) timer(1:2), "hrs", " : ", timer(3:4), "min"," : ", timer(5:10), "s", " -
        ", dater(1:4), &
       "/", dater(5:6), "/", dater(7:8), " ", trim(text), trim(ch1), trim(ch2), trim(ch3), trim(ch4),
      trim(ch5), &
            trim(ch6), trim(ch7), trim(ch8)
    if (.not. present(hidden)) then
      write(unit=terminal, fmt=*) trim(text), trim(ch1), trim(ch2), trim(ch3), trim(ch4), trim(ch5), &
                      trim(ch6), trim(ch7), trim(ch8)
    else
      if (.not. hidden) then
        write(unit=terminal, fmt=*) trim(text), trim(ch1), trim(ch2), trim(ch3), trim(ch4), trim(ch5), &
              trim(ch6), trim(ch7), trim(ch8)
      end if
    end if
      
 
! if (present(time)) then
! write(unit=logfile, fmt = *) "simulation time=", time
! end if
    call flush(logfile)