mtx Module Reference
Data Types
interface geti
interface pro ziskani prvku
type matrix
obecna matice
interface seti
interface pro nastaveni prvku
Functions/Subroutines
subroutine setverbosity (A, level)
nastavi podrobnost behovych reportu
subroutine addmatrix (a, r, i, j)
pricte k prvku - kandidat reimplementace v potomkovi
subroutine initmatrix (a, n, m)
rutina pro inicializaci
pure integer(kind=ikind) function getnmatrix (a)
vrati pocet radku
pure integer(kind=ikind) function getmmatrix (a)
vrati pocet sloupcu
subroutine getrowmatrix (a, i, v, jj, nelem, mask)
ziska radek z matice - univerzal - kandidat reimplementace v potomkovi
subroutine getcolmatrix (a, j, v, ii, nelem, mask)
ziska sloupec z matice - kandidat reimplementace v potomkovi
subroutine spymatrix (a)
napodoba matlabovske spy
subroutine printmatrix (a, ncol, width, caption)
vytiskne matici
subroutine dumpmatrix (a)
zakladni dump
integer(kind=ikind) function nzmatrix (a)
vrati pocet nenul v matici - tady n*m
real(kind=rkind) function, dimension(:), allocatable mulmatrix (a, x, count)
nasobi matici vektorem
real(kind=rkind) function, dimension(:), allocatable mulmatrixt (a, x, count)
nasobi transponovanou matici vektorem
subroutine copymatrix (A, B)
zkopiruje matici - kandidat reimplementace v potomkovi
subroutine clonematrix (A, B)
vytvori prazdnou kopii
subroutine mulmatrixmatrix (A, B, C, info)
A = B*C !!!!!prepsat.
subroutine addmatrixmatrix (A, B)
subroutine submatrixmatrix (A, B)
A = A - B.
real(kind=rkind) function normfmatrix (A)
spocte Frobeniovu normu matice
class(matrix) function, allocatable smatrix (A, ii, jj)
vybere submatici
subroutine read (A, name)
subroutine write (A, name)
real(kind=rkind) function mulrow (A, x, i, count)
spocita skalarni soucin i-teho radku matice a vektoru
subroutine, public mtxtest (A)
testy maticovych operaci vstupni parametr slouzi jen jako sablona pro volbu potomka
subroutine transpose (A, B)
v A vrati transpozici matice B
integer(kind=ikind) function, dimension(:), allocatable nzrowsmatrix (A)
vytvori seznam radku matice obsahujicich aspon jeden prvek
subroutine, public estimeigvalues (A, lmin, lmax)
spocita nejvetsi a nejmensi vlastni cislo uziva mocninnou metodu, tedy tichy predpoklad je symetrie
Function/Subroutine Documentation
subroutine mtx::addmatrix (class(matrix), intent(inout) a, real(kind=rkind), intent(in) r, integer(kind=ikind), intent(in) i, integer(kind=ikind), intent(in) j) [private]
pricte k prvku - kandidat reimplementace v potomkovi
Parameters
in,out a matice
in i souradnice
in j souradnice
in r hodnota
Definition at line 159 of file mtx.f90.
        use typy
        class(matrix), intent(in out) :: a
        integer(kind=ikind), intent(in) :: i,j
        real(kind=rkind), intent(in) :: r
        real(kind=rkind) :: v
        v=a%get(i,j)
        v = v + r
        call a%set(v,i,j)
subroutine mtx::addmatrixmatrix (class(matrix), intent(inout) A, class(matrix), intent(in) B)
Definition at line 636 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in out) :: a
        class(matrix), intent(in) :: b
        integer(kind=ikind) :: i,j,n,m
        real(kind=rkind) :: w1,w2
        real(kind=rkind), dimension(:), allocatable :: rb
        integer(kind=ikind), dimension(:), allocatable :: rib
        integer(kind=ikind) :: nrb
        logical, dimension(:), allocatable :: mask
        n = a%getn()
        m = a%getm()
        allocate(mask(1:m))
        mask = .true.
        do i=1,n
            call b%getrow(i,rb,rib,nrb,mask)
            do j=1,nrb
                call a%add(rb(j),i,rib(j))
            end do
        end do
subroutine mtx::clonematrix (class(matrix), intent(inout) A, class(matrix), intent(in) B) [private]
vytvori prazdnou kopii
Parameters
in,out a cil
in b zdroj
Definition at line 567 of file mtx.f90.
        class(matrix), intent(inout) :: a
        class(matrix), intent(in) :: b
        call a%init(b%getn(),b%getm())
subroutine mtx::copymatrix (class(matrix), intent(inout) A, class(matrix), intent(in) B) [private]
zkopiruje matici - kandidat reimplementace v potomkovi
Parameters
in,out a cil
in b zdroj
Definition at line 540 of file mtx.f90.
        !use pmatools
        implicit none
        class(matrix), intent(inout) :: a
        class(matrix), intent(in) :: b
        integer(kind=ikind) :: i,j
        real(kind=rkind), dimension(:), allocatable :: v
        integer(kind=ikind), dimension(:), allocatable :: ii
        integer(kind=ikind) :: nelem
        call a%init(b%getn(),b%getm())
        do i=1,b%getn()
            call b%getrow(i,v,ii,nelem)
            do j=1,nelem
                call a%set(v(j),i,ii(j))
            end do
            !do j=1,B%getm()
            ! wrk = B%get(i,j)
            ! call A%set(wrk,i,j)
            !end do
        end do
subroutine mtx::dumpmatrix (class(matrix), intent(in) a)
zakladni dump
Parameters
in a dumpovana matice
Definition at line 452 of file mtx.f90.
        implicit none
        class(matrix), intent(in) :: a
        print *, "dump matice pro matrix - v zasade k nicemu"
        print *, "n=",a%n," m=",a%m
subroutine, public mtx::estimeigvalues (class(matrix), intent(in) A, real(kind=rkind), intent(out) lmin, real(kind=rkind), intent(out) lmax)
spocita nejvetsi a nejmensi vlastni cislo uziva mocninnou metodu, tedy tichy predpoklad je symetrie
dominantni vlastni vektor
dominantni vlastni vektor, druha kopie
minimalni vlastni vektor
minimalni vlastni vektor, druha kopie
Definition at line 926 of file mtx.f90.
Referenced by mtx::seti::seti().
        use typy
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), intent(out) :: lmin,lmax
        real(kind=rkind), dimension(:), allocatable :: v1
        real(kind=rkind), dimension(:), allocatable :: v2
        real(kind=rkind), dimension(:), allocatable :: v3
        real(kind=rkind), dimension(:), allocatable :: v4
        integer(kind=ikind) :: n, i, cnt, it, rc
        real(kind=rkind) :: lmax1, lmin1, w, w1, df, df1
        n=a%getn()
        if (a%getm()/=n) stop "estimeigvalue: matice neni ctvercova"
        allocate(v1(1:n))
        allocate(v2(1:n))
        allocate(v3(1:n))
        allocate(v4(1:n))
        v1 = 1
        v1(1)=3
        v3 = v1
        lmax = 1
        lmin = 1
        cnt = 0
        it = 0
        rc = 0
        do
            cnt = cnt + 1
            it = it + 1
            v2 = v1
            v1 = a%mul(v2)
            v4 = v3
            w = 0
            w1 = 0
            do i=1,n
                w = w + v1(i)*v2(i)
                w1 = w1 + v2(i)*v2(i)
            end do
            v1 = v1/sqrt(w1)
            lmax1 = lmax
            lmax = w/w1
            v3 = lmax*v4-a%mul(v4)
            w = 0
            w1 = 0
            do i=1,n
                w = w + v4(i)*v3(i)
                w1 = w1 + v4(i)*v4(i)
            end do
            v3 = v3/sqrt(w1)
            lmin1 = lmin
            lmin = lmax-w/w1
            if (cnt == 10) then
                print *, it, lmin,lmax, rc
                cnt = 0
            end if
            df = (lmax-lmax1)**2+(lmin-lmin1)**2
            if (it==2) then
                df1 = df
            rc = 0
            else
                if (df<df1) then
                    df1 = df
                rc = 0
                else
                    rc = rc + 1
                end if
            end if
            if (rc==20000) exit
        end do
subroutine mtx::getcolmatrix (class(matrix), intent(in) a, integer(kind=ikind), intent(in) j, real(kind=rkind), dimension(:), intent(inout), allocatable v, integer(kind=ikind), dimension(:), intent(inout), allocatable ii, integer(kind=ikind), intent(out) nelem, logical, dimension(:), intent(in), optional mask)
ziska sloupec z matice - kandidat reimplementace v potomkovi
Parameters
in a matice
in j identifikace sloupce
in,out v hodnoty prvku
in,out ii radkove indexy
out nelem pocet prvku vybraneho sloupce
in mask seznam povolenych indexu
Definition at line 290 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in) :: a
        integer(kind=ikind), intent(in) :: j
        real(kind=rkind), dimension(:), allocatable, intent(inout) :: v
        integer(kind=ikind), dimension(:), allocatable, intent(inout) :: ii
        integer(kind=ikind), intent(out) :: nelem
        logical, dimension(:), optional, intent(in) :: mask
        integer(kind=ikind) :: i
        real(kind=rkind) :: w
        ! dvoufazove
        ! spocitat kolik jich bude
        nelem = 0
        if (present(mask)) then
            do i = 1,a%n
                if (a%get(i,j) /= 0 .and. mask(i)) then
                    nelem = nelem + 1
                end if
            end do
        else
            do i = 1,a%n
                if (a%get(i,j) /= 0) then
                    nelem = nelem + 1
                end if
            end do
        end if
        ! overit misto
        if (.not. allocated(v)) then
        allocate(v(1:nelem))
        else
            if (nelem > ubound(v,1)) then
                deallocate(v)
                allocate(v(1:nelem))
            end if
        end if
        if (.not. allocated(ii)) then
        allocate(ii(1:nelem))
        else
            if (nelem > ubound(ii,1)) then
                deallocate(ii)
                allocate(ii(1:nelem))
            end if
        end if
        ! opravdu naplnit
        nelem = 0
        if (present(mask)) then
            do i = 1,a%n
                w = a%get(i,j)
                if (w /= 0 .and. mask(i)) then
                    nelem = nelem + 1
                    v(nelem) = w
                    ii(nelem) = i
                end if
            end do
        else
            do i = 1,a%n
                w = a%get(i,j)
                if (w /= 0) then
                    nelem = nelem + 1
                    v(nelem) = w
                    ii(nelem) = i
                end if
            end do
        end if
pure integer(kind=ikind) function mtx::getmmatrix (class(matrix), intent(in) a)
vrati pocet sloupcu
Parameters
in a matice
Definition at line 201 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in) :: a
        integer(kind=ikind) :: res
        res = a%m
pure integer(kind=ikind) function mtx::getnmatrix (class(matrix), intent(in) a)
vrati pocet radku
Parameters
in a matice
Definition at line 190 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in) :: a
        integer(kind=ikind) :: res
        res = a%n
subroutine mtx::getrowmatrix (class(matrix), intent(in) a, integer(kind=ikind), intent(in) i, real(kind=rkind), dimension(:), intent(inout), allocatable v, integer(kind=ikind), dimension(:), intent(inout), allocatable jj, integer(kind=ikind), intent(out) nelem, logical, dimension(:), intent(in), optional mask)
ziska radek z matice - univerzal - kandidat reimplementace v potomkovi
vrati jen nenulove prvky z radku, v pripade potreby prealokuje prostor
Parameters
in a matice
in i pozadovany radek
in,out v nenulove hodnoty z radku
in,out jj sloupcove indexy nenulovych prvku radku
out nelem pocet nenulovych prvku v radku
in mask seznam povolenych indexu
Definition at line 214 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in) :: a
        integer(kind=ikind), intent(in) :: i
        real(kind=rkind), dimension(:), allocatable, intent(inout) :: v
        integer(kind=ikind), dimension(:), allocatable, intent(inout) :: jj
        integer(kind=ikind), intent(out) :: nelem
        logical, dimension(:), optional, intent(in) :: mask
        integer(kind=ikind) :: j
        real(kind=rkind) :: w
        ! dvoufazove
        ! spocitat kolik jich bude
        nelem = 0
        if (present(mask)) then
            do j = 1,a%m
                if (a%get(i,j) /= 0 .and. mask(j)) then
                    nelem = nelem + 1
                end if
            end do
        else
            do j = 1,a%m
                if (a%get(i,j) /= 0) then
                    nelem = nelem + 1
                end if
            end do
        end if
        ! overit misto
        if (.not. allocated(v)) then
        allocate(v(1:nelem))
        else
            if (nelem > ubound(v,1)) then
                deallocate(v)
                allocate(v(1:nelem))
            end if
        end if
        if (.not. allocated(jj)) then
        allocate(jj(1:nelem))
        else
            if (nelem > ubound(jj,1)) then
                deallocate(jj)
                allocate(jj(1:nelem))
            end if
        end if
        ! opravdu naplnit
        nelem = 0
        if (present(mask)) then
            do j = 1,a%m
                w = a%get(i,j)
                if (w /= 0 .and. mask(j)) then
                    nelem = nelem + 1
                    v(nelem) = w
                    jj(nelem) = j
                end if
            end do
        else
            do j = 1,a%m
                w = a%get(i,j)
                if (w /= 0) then
                    nelem = nelem + 1
                    v(nelem) = w
                    jj(nelem) = j
                end if
            end do
        end if
subroutine mtx::initmatrix (class(matrix), intent(inout) a, integer(kind=ikind), intent(in) n, integer(kind=ikind), intent(in) m)
rutina pro inicializaci
Parameters
in,out a matice
in n rozmery
in m rozmery
Definition at line 175 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in out) :: a
        integer(kind=ikind), intent(in) :: n,m
        a%n = n
        a%m = m
        !print *,"initmatrix: konci"
subroutine, public mtx::mtxtest (class(matrix), intent(in) A)
testy maticovych operaci vstupni parametr slouzi jen jako sablona pro volbu potomka
Definition at line 820 of file mtx.f90.
Referenced by mtx::seti::seti().
        implicit none
        class(matrix), intent(in) :: a
        class(matrix), allocatable :: l,d,u,ldu
        integer(kind=ikind), dimension(3) :: ii
        integer(kind=ikind), dimension(2) :: jj
        print *,"zacinaji testy matic"
        allocate(l,source=a)
        allocate(d,source=a)
        allocate(u,source=a)
        allocate(ldu,source=a)
        call l%setverbosity(10)
        call d%setverbosity(10)
        ii = (/ 1 ,3, 5 /)
        jj = (/2,4/)
        call l%init(4_ikind,4_ikind)
        call d%init(4_ikind,4_ikind)
        call u%init(4_ikind,4_ikind)
        call ldu%init(4_ikind,4_ikind)
        call u%set(1.0_rkind,1_ikind,1_ikind)
        call u%set(2.0_rkind,1_ikind,2_ikind)
        call u%set(-5.0_rkind,1_ikind,3_ikind)
        call u%set(7.0_rkind,1_ikind,4_ikind)
        call u%set(1.0_rkind,2_ikind,2_ikind)
        call u%set(4.0_rkind,2_ikind,3_ikind)
        call u%set(-16.0_rkind,2_ikind,4_ikind)
        call u%set(1.0_rkind,3_ikind,3_ikind)
        call u%set(25.0_rkind,3_ikind,4_ikind)
        call u%set(1.0_rkind,4_ikind,4_ikind)
        call l%set(1.0_rkind,1_ikind,1_ikind)
        call l%set(-1.0_rkind,2_ikind,1_ikind)
        call l%set(1.0_rkind,2_ikind,2_ikind)
        call l%set(2.0_rkind,3_ikind,1_ikind)
        call l%set(7.0_rkind,3_ikind,2_ikind)
        call l%set(1.0_rkind,3_ikind,3_ikind)
        call l%set(16.0_rkind,4_ikind,1_ikind)
        call l%set(-8.0_rkind,4_ikind,2_ikind)
        call l%set(-5.0_rkind,4_ikind,3_ikind)
        call l%set(1.0_rkind,4_ikind,4_ikind)
        call d%set(2.0_rkind,1_ikind,1_ikind)
        call d%set(3.0_rkind,2_ikind,2_ikind)
        call d%set(-1.0_rkind,3_ikind,3_ikind)
        call d%set(17.0_rkind,4_ikind,4_ikind)
        call l%print(caption = "L")
        call d%print(caption = "D")
        call u%print(caption = "U")
real(kind=rkind) function, dimension(:), allocatable mtx::mulmatrix (class(matrix), intent(in) a, real(kind=rkind), dimension(:), intent(in) x, type(tcount), intent(inout), optional count)
nasobi matici vektorem
Parameters
in a matice
in x vektor
Returns
vysledek
Parameters
in,out count pocet operaci
Definition at line 472 of file mtx.f90.
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), dimension(:), intent(in) :: x
        real(kind=rkind), dimension(:), allocatable :: y
        type(tcount), intent(inout), optional :: count
        integer(kind=ikind) :: i,j,nelem
        real(kind=rkind), dimension(:), allocatable :: v
        integer(kind=ikind), dimension(:), allocatable :: ii
        allocate(y(1:a%n))
        y = 0
        do i=1,a%n
            call a%getrow(i,v,ii,nelem)
            do j=1,nelem
                y(i) = y(i) + v(j)*x(ii(j))
            end do
            !do j=1,a%m
            ! y(i) = y(i) + a%get(i,j)*x(j)
            !end do
            if (present(count)) then
                count%ad = count%ad + nelem
                count%mul = count%mul + nelem
            end if
        end do
subroutine mtx::mulmatrixmatrix (class(matrix), intent(inout) A, class(matrix), intent(in) B, class(matrix), intent(in) C, type(tcount), intent(inout), optional info) [private]
A = B*C !!!!!prepsat.
Parameters
A vysledna matice
B levy operand
C pravy operand
Definition at line 581 of file mtx.f90.
References typy::update_info().
        use typy
        implicit none
        class(matrix), intent(in out) :: a
        class(matrix), intent(in) :: b
        class(matrix), intent(in) :: c
        type(tcount), intent(in out), optional :: info
        integer(kind=ikind) :: n,m,p,i,j,k
        real(kind=rkind) :: wrk
        real(kind=rkind), dimension(:), allocatable :: rd, sl
        integer(kind=likind), dimension(:), allocatable :: rdi, sli
        integer(kind=ikind) :: nrd, nsl
        type(tcount) :: inf1
        real :: t1,t2
        n = b%getn()
        m = c%getm()
        p = b%getm()
        i = c%getn()
        j = n
        k = m
        call cpu_time(t1)
        call a%init(j,k)
        if ((p/=i) .or. (j/=n) .or. (m/=k)) print *,"nesedi rozmery"
        ! do i=1,n
        ! do j=1,m
        ! call A%set(0.0_rkind,i,j)
        ! wrk = 0
        ! do k=1,p
        ! w1 = B%get(i,k)
        ! w2 = C%get(k,j)
        ! wrk = wrk + w1*w2
        ! end do
        ! call A%set(wrk,i,j)
        ! end do
        ! end do
        do k=1,p
            call b%GetCol(k,sl,sli,nsl)
            call c%GetRow(k,rd,rdi,nrd)
            !! pricist opravu
            do i=1,nrd
                do j=1,nsl
                    wrk = sl(j)*rd(i)
                    call a%add(wrk, sli(j), rdi(i))
                end do
            end do
            call cpu_time(t2)
            inf1%ad = inf1%ad + nrd*nsl
            inf1%mul = inf1%mul + nrd*nsl
            inf1%time = inf1%time + t2 - t1
        end do
        if (present(info)) call update_info(info,inf1)
real(kind=rkind) function, dimension(:), allocatable mtx::mulmatrixt (class(matrix), intent(in) a, real(kind=rkind), dimension(:), intent(in) x, type(tcount), intent(inout), optional count) [private]
nasobi transponovanou matici vektorem
Parameters
in a matice
in x vektor
Returns
vysledek
Parameters
in,out count pocet operaci
Definition at line 505 of file mtx.f90.
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), dimension(:), intent(in) :: x
        real(kind=rkind), dimension(:), allocatable :: y
        type(tcount), intent(inout), optional :: count
        integer(kind=ikind) :: i,j,nelem
        real(kind=rkind), dimension(:), allocatable :: v
        integer(kind=ikind), dimension(:), allocatable :: ii
        allocate(y(1:a%m))
        y = 0
        do i=1,a%n
            call a%getrow(i,v,ii,nelem)
            do j = 1, nelem
                y(ii(j)) = y(ii(j)) + v(j)*x(i)
            end do
            !do j=1,a%m
            ! y(j) = y(j) + a%get(i,j)*x(i)
            !end do
            if (present(count)) then
                count%ad = count%ad + nelem
                count%mul = count%mul + nelem
            end if
        end do
real(kind=rkind) function mtx::mulrow (class(matrix), intent(in) A, real(kind=rkind), dimension(:), intent(in) x, integer(kind=ikind), intent(in) i, type(tcount), intent(inout), optional count) [private]
spocita skalarni soucin i-teho radku matice a vektoru
Definition at line 793 of file mtx.f90.
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind), dimension(:), intent(in) :: x
        integer(kind=ikind), intent(in) :: i
        real(kind=rkind) :: y
        type(tcount), intent(inout), optional :: count
        real(kind=rkind), dimension(:), allocatable :: vls
        integer(kind=ikind), dimension(:), allocatable :: jj
        integer(kind=ikind) :: nelem, j
        call a%getrow(i,vls,jj,nelem)
        y = 0
        do j = 1,nelem
           y = y + vls(j)*x(jj(j))
        end do
        if (present(count)) then
           count%ad = count%ad + nelem
           count%mul = count%mul + nelem
        end if
real(kind=rkind) function mtx::normfmatrix (class(matrix), intent(in) A)
spocte Frobeniovu normu matice
Parameters
A zkoumana matice
Returns
hledana norma
Definition at line 688 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in) :: a
        real(kind=rkind) :: y
        real(kind=rkind), dimension(:), allocatable :: rb
        integer(kind=ikind), dimension(:), allocatable :: rib
        integer(kind=ikind) :: nrb,i,j
        y = 0
        print *,"normF zacina"
        do i=1,a%getn()
            call a%getrow(i,rb,rib,nrb)
            do j=1,nrb
                y = y + rb(j)*rb(j)
            end do
        end do
        y = sqrt(y)
        print *,"normF konci"
integer(kind=ikind) function mtx::nzmatrix (class(matrix), intent(in) a) [private]
vrati pocet nenul v matici - tady n*m
Parameters
in a matice
Definition at line 461 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in) :: a
        integer(kind=ikind) :: res
        res = a%n*a%m
integer(kind=ikind) function, dimension(:), allocatable mtx::nzrowsmatrix (class(matrix), intent(in) A) [private]
vytvori seznam radku matice obsahujicich aspon jeden prvek
Definition at line 900 of file mtx.f90.
        class(matrix), intent(in) :: a
        integer(kind=ikind), dimension(:), allocatable :: lst
        integer(kind=ikind) :: i, cnt, run, nelem
        real(kind=rkind), dimension(:), allocatable :: v
        integer(kind=ikind), dimension(:), allocatable :: jj
        ! napred spocitame kolik toho bude run == 1
        ! pak to udelame run == 2
        do run = 1,2
            cnt = 0
            do i = 1, a%getn()
                call a%getrow(i,v,jj,nelem)
                if (nelem /= 0) then
                    cnt = cnt + 1
                    if (run==2) lst(cnt) = i
                end if
            end do
            if (run==1) allocate(lst(1:cnt))
        end do
subroutine mtx::printmatrix (class(matrix), intent(in) a, integer(kind=ikind), intent(in), optional ncol, integer(kind=ikind), intent(in), optional width, character(len=*), intent(in), optional caption)
vytiskne matici
Parameters
in a matice
in ncol pozadovany pocet sloupcu tisku, nepovinne
in width pozadovane sirka sloupce, nepovinne
in caption nadpis, nepovinne
Definition at line 393 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in) :: a
        integer(kind=ikind), intent(in), optional :: ncol
        integer(kind=ikind), intent(in), optional :: width
        character(len=*), intent(in), optional :: caption
        character(len=100) :: cpt,fmts
        integer(kind=ikind) :: nc
        integer(kind=ikind) :: wd
        integer(kind=ikind) :: i,j, col1,col2
        real(kind=rkind), dimension(:), allocatable :: data
        if (present(ncol)) then
        nc = ncol
        else
            nc = 5
        end if
        if (present(width)) then
        wd = width
        else
            wd = 15
        end if
        if (present(caption)) then
        cpt = adjustl(caption)
        else
            cpt ="matice"
        end if
        allocate(data(1:nc))
        print *, trim(cpt)
        print *, " pocet radku=",a%n, " pocet sloupcu=", a%m
        !write(fmts,fmt="(i3,a2,i3,a2,i3,a2)") ncol,"(es",width,".",width-8,",a)"
        write(unit=fmts,fmt="(A1,I0,A2,I0,A1,I0,A1)") "(",nc,"Es",wd+8,".",wd,")"
        !print *,fmts
        col1 = 1
        col2 = min(nc,a%getm())
        do
            print *,"tisknu sloupce ",col1," az ",col2
            do i=1,a%getn()
                do j=col1,col2
                    data(j-col1+1) = a%get(i,j)
                end do
                print fmts, data(1:col2-col1+1)
            end do
            col1 = col2+1
            col2 = min(col2+nc,a%getm())
            if (col1>a%getm()) exit
        end do
subroutine mtx::read (class(matrix), intent(inout) A, character(len=*), intent(in) name) [private]
Definition at line 752 of file mtx.f90.
        implicit none
        class(matrix), intent(in out) :: a
        character(len=*), intent(in) :: name
        integer :: fil
        integer(kind=ikind) :: i,n,m,nz
        real(kind=rkind) :: wrk
        open(newunit=fil,file=name)
        read(fil,*) n,m,nz
        !print *, n, m, nz
        call a%init(n,m)
        do i=1,nz
            read(fil,*) n,m,wrk
            call a%set(wrk,n,m)
        end do
        close(fil)
        !call A%print()
subroutine mtx::setverbosity (class(matrix), intent(inout) A, integer, intent(in) level)
nastavi podrobnost behovych reportu
Parameters
A ovlivnena matice
level pozadovana uroven podrobnosti
0 .... tise
10 .... maximalni ukecanost
Definition at line 149 of file mtx.f90.
        class(matrix), intent(in out) :: a
        integer, intent(in) :: level
        a%verbosity = max(0,min(level,10))
class(matrix) function, allocatable mtx::smatrix (class(matrix), intent(in) A, integer(kind=ikind), dimension(:), intent(in) ii, integer(kind=ikind), dimension(:), intent(in) jj)
vybere submatici
Parameters
A matice
ii radkove indexy
jj sloupcove indexy
Returns
vybrana submatice
Definition at line 716 of file mtx.f90.
        implicit none
        class(matrix), intent(in) :: a
        class(matrix), allocatable :: b
        integer(kind=ikind), dimension(:), intent(in) :: ii
        integer(kind=ikind), dimension(:), intent(in) :: jj
        integer(kind=ikind) :: n,m,i,j
        real(kind=rkind), dimension(:), allocatable :: v
        integer(kind=ikind), dimension(:), allocatable :: is, invi
        integer(kind=ikind) :: nelem
        logical, dimension(:), allocatable :: mask
        print *, "zacina konstrukce submatice"
        n = size(ii,1)
        m = size(jj,1)
        allocate(b,source=a)
        call b%init(n,m)
        allocate(mask(1:a%getm()))
        allocate(invi(1:a%getm()))
        mask = .false.
        mask(jj) = .true.
        invi = 0
        do i = 1,m
            invi(jj(i)) = i
        end do
        do i=1,n
            call a%GetRow(ii(i),v,is,nelem)
            do j = 1,nelem
                if (mask(is(j))) then
                    call b%set(v(j),i,invi(is(j)))
                end if
            end do
        end do
subroutine mtx::spymatrix (class(matrix), intent(in) a)
napodoba matlabovske spy
Parameters
in a matice
Definition at line 365 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in) :: a
        integer(kind=ikind) :: i,j, nz
        character(len=a%getm()) :: radek
        character(len=8) :: fmts
        nz = 0
        write(fmts,fmt="(a2,i5,a1)") "(a",a%m,")"
        do i=1,a%getn()
            do j=1,a%getm()
                if (a%get(i,j) == 0.0_rkind) then
                radek(j:j) = '.'
                else
                    radek(j:j) = 'X'
                    nz = nz + 1
                end if
            end do
            print fmts,radek
        end do
        print *, " pocet radek=", a%getn()
        print *, " pocet sloupcu",a%getm()
        print *,"celkovy pocet nenul=",nz
subroutine mtx::submatrixmatrix (class(matrix), intent(inout) A, class(matrix), intent(in) B)
A = A - B.
Definition at line 662 of file mtx.f90.
        use typy
        implicit none
        class(matrix), intent(in out) :: a
        class(matrix), intent(in) :: b
        integer(kind=ikind) :: i,j,n,m
        real(kind=rkind), dimension(:), allocatable :: rb
        integer(kind=ikind), dimension(:), allocatable :: rib
        integer(kind=ikind) :: nrb
        logical, dimension(:), allocatable :: mask
        n = a%getn()
        m = a%getm()
        do i=1,n
            call b%getrow(i,rb,rib,nrb)
            do j=1,nrb
                call a%add(-rb(j),i,rib(j))
            end do
        end do
subroutine mtx::transpose (class(matrix), intent(inout) A, class(matrix), intent(in) B) [private]
v A vrati transpozici matice B
Definition at line 879 of file mtx.f90.
        class(matrix), intent(in out) :: a
        class(matrix), intent(in) :: b
        integer(kind=ikind) :: n,m,i, nelem, j
        integer(kind=ikind), dimension(:), allocatable :: ii
        real(kind=rkind), dimension(:), allocatable :: v
        n = b%getn()
        m = b%getm()
        call a%init(m,n)
        do i=1,n
            call b%getrow(i,v,ii,nelem)
            do j=1, nelem
                call a%set(v(j),ii(j),i)
            end do
        end do
subroutine mtx::write (class(matrix), intent(in) A, character(len=*), intent(in) name) [private]
Definition at line 772 of file mtx.f90.
        implicit none
        class(matrix), intent(in) :: a
        character(len=*), intent(in) :: name
        integer :: fil
        integer(kind=ikind) :: n,m
        real(kind=rkind) :: wrk
        open(newunit=fil,file=name)
        write(fil,*) a%getn(),a%getm(),a%nonzero()
        do n=1,a%getn()
            do m=1,a%getm()
                wrk = a%get(n,m)
                if (wrk /= 0.0) write(fil,*) n,m,wrk
            end do
        end do
        close(fil)
        !call A%print()