typy Module Reference
Data Types
type funroot
koren pro funkce
type stringlist
seznam retezcu
type tcount
pocitadlo operaci
type tident
typ pro retezec s promennou delkou
Functions/Subroutines
subroutine, public print_info (info)
vytiskne udaje o pocitani
subroutine, public update_info (info1, info2)
pricte info2 k info1
real(kind=rkind) function evalr (r, x)
complex(kind=rkind) function evalc (r, x)
real(kind=rkind) function derevalr (r, x)
complex(kind=rkind) function derevalc (r, x)
real(kind=rkind) function, public norm2 (v)
spocte L2 normu vektoru
Variables
integer, parameter, public lowikind =selected_int_kind(5)
integer, parameter, public dprec =selected_real_kind(15, 99)
integer, parameter, public sprec =selected_real_kind(8, 9)
integer, parameter, public rkind = selected_real_kind(15, 99)
real number specification
integer, parameter, public ikind = selected_int_kind(10)
integer number specification
integer, parameter, public likind = selected_int_kind(16)
long integers
integer, parameter, public chkind =selected_char_kind(`default`)
unicode char type
integer, parameter r4 = selected_real_kind(5, 10)
4byte real
integer, parameter r8 = selected_real_kind(12, 20)
8byte real
integer, parameter r16 = selected_real_kind(30)
16byte real
integer, parameter, public maxlen = 200
integer, parameter, public strmax = 1024
maximalni delka retezce jedne polozky beznych dat
Function/Subroutine Documentation
complex(kind=rkind) function typy::derevalc (class(funroot), intent(in) r, complex(kind=rkind), intent(in) x)
Definition at line 151 of file typy.f90.
        implicit none
        class(funroot), intent(in) :: r
        complex(kind=rkind), intent(in) :: x
        complex(kind=rkind) :: y
        stop "Neimplentovana funkcionalita"
real(kind=rkind) function typy::derevalr (class(funroot), intent(in) r, real(kind=rkind), intent(in) x)
Definition at line 143 of file typy.f90.
        implicit none
        class(funroot), intent(in) :: r
        real(kind=rkind), intent(in) :: x
        real(kind=rkind) :: y
        stop "Neimplentovana funkcionalita"
complex(kind=rkind) function typy::evalc (class(funroot), intent(in) r, complex(kind=rkind), intent(in) x)
Definition at line 134 of file typy.f90.
        implicit none
        class(funroot), intent(in) :: r
        complex(kind=rkind), intent(in) :: x
        complex(kind=rkind) :: y
        y = 0
        stop "Neimplentovana funkcionalita"
real(kind=rkind) function typy::evalr (class(funroot), intent(in) r, real(kind=rkind), intent(in) x)
Definition at line 125 of file typy.f90.
        implicit none
        class(funroot), intent(in) :: r
        real(kind=rkind), intent(in) :: x
        real(kind=rkind) :: y
        y = 0
        stop "Neimplentovana funkcionalita"
real(kind=rkind) function, public typy::norm2 (real(kind=rkind), dimension(:), intent(in) v)
spocte L2 normu vektoru
Definition at line 161 of file typy.f90.
Referenced by typy::funroot::dereval(), solvers::gs(), heat_fnc::heat_convect(), heat_fnc::heat_flux(), solvers::jacobi(), read_inputs::read_scilab(), schwarz_dd::schwarz_picard(), and femmat::solve_picard().
        implicit none
        real(kind=rkind), dimension(:), intent(in) :: v
        real(kind=rkind) :: y
        integer :: i
        y=0
        do i = lbound(v,1), ubound(v,1)
            y = y + v(i)*v(i)
        end do
        y = sqrt(y)
subroutine, public typy::print_info (type(tcount), intent(in) info)
vytiskne udaje o pocitani
Parameters
in info data o spotrebe prace
Definition at line 103 of file typy.f90.
Referenced by typy::funroot::dereval().
        implicit none
        type(tcount), intent(in) :: info
        print *, "pocty operaci aditivni:",info%ad," nasobeni:",info%mul,&
        " deleni:",info%div, " cas:",info%time
subroutine, public typy::update_info (type(tcount), intent(inout) info1, type(tcount), intent(in) info2)
pricte info2 k info1
Definition at line 112 of file typy.f90.
Referenced by typy::funroot::dereval(), mtx_int::mulmatrixmatrix(), mtx::mulmatrixmatrix(), and solvers::sd().
        implicit none
        type(tcount), intent(inout) :: info1
        type(tcount), intent(in) :: info2
        info1%ad = info1%ad + info2%ad
        info1%mul = info1%mul + info2%mul
        info1%div = info1%div + info2%div
        info1%time = info1%time + info2%time
Variable Documentation
integer, parameter, public typy::chkind =selected_char_kind(`default`)
unicode char type
Definition at line 32 of file typy.f90.
    integer, parameter, public :: chkind=selected_char_kind("default")!"ASCII")!"ISO_10646")
integer, parameter, public typy::dprec =selected_real_kind(15, 99)
Definition at line 21 of file typy.f90.
    integer, parameter, public :: dprec=selected_real_kind(15,99)
integer, parameter, public typy::ikind = selected_int_kind(10)
integer number specification
Definition at line 28 of file typy.f90.
    integer, parameter, public :: ikind = selected_int_kind(10)
integer, parameter, public typy::likind = selected_int_kind(16)
long integers
Definition at line 30 of file typy.f90.
    integer, parameter, public :: likind = selected_int_kind(16)
integer, parameter, public typy::lowikind =selected_int_kind(5)
Definition at line 19 of file typy.f90.
    integer, parameter, public :: lowikind=selected_int_kind(5)
integer, parameter, public typy::maxlen = 200
Definition at line 42 of file typy.f90.
    integer, parameter, public :: maxlen = 200
integer, parameter typy::r16 = selected_real_kind(30)
16byte real
Definition at line 39 of file typy.f90.
    integer, parameter :: r16 = selected_real_kind(30)
integer, parameter typy::r4 = selected_real_kind(5, 10)
4byte real
Definition at line 35 of file typy.f90.
Referenced by solvers::jacobi(), and solvers::pcg().
    integer, parameter :: r4 = selected_real_kind(5,10)
integer, parameter typy::r8 = selected_real_kind(12, 20)
8byte real
Definition at line 37 of file typy.f90.
    integer, parameter :: r8 = selected_real_kind(12,20)
integer, parameter, public typy::rkind = selected_real_kind(15, 99)
real number specification
Definition at line 26 of file typy.f90.
Referenced by objfnc::reader().
    integer, parameter, public :: rkind = selected_real_kind(15,99)
integer, parameter, public typy::sprec =selected_real_kind(8, 9)
Definition at line 23 of file typy.f90.
    integer, parameter, public :: sprec=selected_real_kind(8,9)
integer, parameter, public typy::strmax = 1024
maximalni delka retezce jedne polozky beznych dat
Definition at line 68 of file typy.f90.
    integer, parameter, public :: strmax = 1024