ade_pointers Module Reference
Functions/Subroutines
subroutine, public ade (pde_loc)
subroutine, public adekinsorb (pde_loc)
Function/Subroutine Documentation
subroutine, public ade_pointers::ade (class(pde_str), intent(inout) pde_loc)
Definition at line 8 of file ADE_pointers.f90.
References ade_fnc::ade_convection(), ade_fnc::ade_dirichlet(), ade_fnc::ade_flux(), ade_fnc::ade_icond(), ade_fnc::ade_mass(), ade_fnc::ade_neumann(), ade_fnc::ade_reaction(), ade_reader::ade_read(), ade_fnc::ade_tder_coef(), ade_fnc::ade_zerorder(), and ade_fnc::adedispersion().
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use ade_fnc
      use ade_reader
      
      class(pde_str), intent(in out) :: pde_loc
      integer(kind=ikind) :: i
      
      call ade_read(pde_loc)
            
      pde_loc%pde_fnc(pde_loc%order)%dispersion => adedispersion
      
      pde_loc%pde_fnc(pde_loc%order)%convection => ade_convection
      pde_loc%pde_fnc(pde_loc%order)%elasticity => ade_tder_coef
      pde_loc%mass => ade_mass
      pde_loc%pde_fnc(pde_loc%order)%reaction => ade_reaction
            
      pde_loc%pde_fnc(pde_loc%order)%zerord => ade_zerorder
          
      do i=lbound(pde_loc%bc,1), ubound(pde_loc%bc,1)
        select case(pde_loc%bc(i)%code)
          case(1)
            pde_loc%bc(i)%value_fnc => ade_dirichlet
          case(2)
            pde_loc%bc(i)%value_fnc => ade_neumann
        end select
      end do
        
      pde_loc%flux => ade_flux
      
      pde_loc%initcond => ade_icond
      
    
subroutine, public ade_pointers::adekinsorb (class(pde_str), intent(inout) pde_loc)
Definition at line 49 of file ADE_pointers.f90.
References ade_fnc::ade_cscl_react(), ade_fnc::ade_cscs_react(), ade_fnc::ade_null_bc(), ade_fnc::ade_tder_cscl(), ade_fnc::ade_tder_cscs(), ade_fnc::adecs_icond(), ade_reader::adecs_read(), and pde_objs::pde.
Referenced by manage_pointers::set_pointers().
      use typy
      use globals
      use global_objs
      use pde_objs
      use ade_fnc
      use ade_reader
      
      class(pde_str), intent(in out) :: pde_loc
      integer(kind=ikind) :: i
      
      call adecs_read(pde_loc)
      
      pde_loc%pde_fnc(pde_loc%order)%elasticity => ade_tder_cscs
      
      pde(pde_loc%order-1)%pde_fnc(pde_loc%order)%elasticity => ade_tder_cscl
      
      pde_loc%pde_fnc(pde_loc%order-1)%reaction => ade_cscl_react
      
      pde_loc%pde_fnc(pde_loc%order)%reaction => ade_cscs_react
      
      allocate(pde_loc%bc(lbound(pde(pde_loc%order-1)%bc,1) : (ubound(pde(pde_loc%order-1)%bc,1))))
      do i=lbound(pde_loc%bc,1), ubound(pde_loc%bc,1)
        pde_loc%bc(i)%code = 2
        pde_loc%bc(i)%value_fnc => ade_null_bc
      end do
      
      pde_loc%initcond => adecs_icond
      
    