typy::funroot Type Reference
koren pro funkce
Public Member Functions
procedure evalc
vycisleni funkce v komplexnim oboru
procedure evalr
vycisleni funkce v realnem oboru
generic eval => evalr, evalc
pretizena verze vycisleni funkce
procedure derevalc
vycisli derivaci funkce, komplexni
procedure derevalr
vycisli derivaci funkce, realna
generic dereval => derevalc, derevalr
vycisli derivaci funkce, pretizena
Detailed Description
koren pro funkce
Definition at line 81 of file typy.f90.
Member Function/Subroutine Documentation
generic typy::funroot::dereval ()
vycisli derivaci funkce, pretizena
Definition at line 94 of file typy.f90.
References typy::norm2(), typy::print_info(), and typy::update_info().
procedure typy::funroot::derevalc ()
vycisli derivaci funkce, komplexni
Definition at line 90 of file typy.f90.
procedure typy::funroot::derevalr ()
vycisli derivaci funkce, realna
Definition at line 92 of file typy.f90.
generic typy::funroot::eval ()
pretizena verze vycisleni funkce
Definition at line 88 of file typy.f90.
procedure typy::funroot::evalc ()
vycisleni funkce v komplexnim oboru
Definition at line 84 of file typy.f90.
procedure typy::funroot::evalr ()
vycisleni funkce v realnem oboru
Definition at line 86 of file typy.f90.
The documentation for this type was generated from the following file:
src/core/typy.f90