var hierarchy =
[
    [ "pde_objs::basic_subrt", "interfacepde__objs_1_1basic__subrt.html", null ],
    [ "pde_objs::bc_fnc", "interfacepde__objs_1_1bc__fnc.html", null ],
    [ "pde_objs::boundary_vals", "structpde__objs_1_1boundary__vals.html", null ],
    [ "decomp_vars::cluster", "structdecomp__vars_1_1cluster.html", null ],
    [ "global_objs::configuration", "structglobal__objs_1_1configuration.html", null ],
    [ "globals2d::crossection", "structglobals2d_1_1crossection.html", null ],
    [ "decomp_vars::ddinfo_str", "structdecomp__vars_1_1ddinfo__str.html", null ],
    [ "global_objs::dirglob_str", "structglobal__objs_1_1dirglob__str.html", null ],
    [ "decomp_vars::disjoint_nd_str", "structdecomp__vars_1_1disjoint__nd__str.html", null ],
    [ "global_objs::element", "structglobal__objs_1_1element.html", null ],
    [ "sparsematrix::elemt", "structsparsematrix_1_1elemt.html", null ],
    [ "sparsematrix_int::elemt_int", "structsparsematrix__int_1_1elemt__int.html", null ],
    [ "dual_globals::exch_k", "structdual__globals_1_1exch__k.html", null ],
    [ "dual_globals::expar", "structdual__globals_1_1expar.html", null ],
    [ "readtools::fileread", "interfacereadtools_1_1fileread.html", null ],
    [ "integral::formulka", "structintegral_1_1formulka.html", null ],
    [ "typy::funroot", "structtypy_1_1funroot.html", null ],
    [ "mtx::geti", "interfacemtx_1_1geti.html", null ],
    [ "mtx_int::geti", "interfacemtx__int_1_1geti.html", null ],
    [ "pde_objs::getval_str", "interfacepde__objs_1_1getval__str.html", null ],
    [ "heat_globals::heatpars_str", "structheat__globals_1_1heatpars__str.html", null ],
    [ "pde_objs::icond_fnc", "interfacepde__objs_1_1icond__fnc.html", null ],
    [ "global_objs::integnodes", "structglobal__objs_1_1integnodes.html", null ],
    [ "global_objs::integpnt_str", "structglobal__objs_1_1integpnt__str.html", null ],
    [ "pde_objs::logical_fnc", "interfacepde__objs_1_1logical__fnc.html", null ],
    [ "mtx::matrix", "structmtx_1_1matrix.html", [
      [ "fullmatrix::fullmtx", "structfullmatrix_1_1fullmtx.html", null ],
      [ "sparsematrix::smtx", "structsparsematrix_1_1smtx.html", [
        [ "global_objs::extsmtx", "structglobal__objs_1_1extsmtx.html", null ]
      ] ]
    ] ],
    [ "mtx_int::matrix_int", "structmtx__int_1_1matrix__int.html", [
      [ "sparsematrix_int::smtx_int", "structsparsematrix__int_1_1smtx__int.html", null ]
    ] ],
    [ "pde_objs::matrix_solver", "interfacepde__objs_1_1matrix__solver.html", null ],
    [ "global_objs::node", "structglobal__objs_1_1node.html", null ],
    [ "global_objs::observation", "structglobal__objs_1_1observation.html", [
      [ "global_objs::measured", "structglobal__objs_1_1measured.html", null ]
    ] ],
    [ "global_objs::observe_info_str", "structglobal__objs_1_1observe__info__str.html", null ],
    [ "global_objs::observe_time_str", "structglobal__objs_1_1observe__time__str.html", null ],
    [ "pde_objs::pde_common_str", "structpde__objs_1_1pde__common__str.html", null ],
    [ "pde_objs::pde_fnc", "structpde__objs_1_1pde__fnc.html", null ],
    [ "pde_objs::pde_str", "structpde__objs_1_1pde__str.html", null ],
    [ "objfnc::point_str", "structobjfnc_1_1point__str.html", null ],
    [ "debug_tools::printmtx", "interfacedebug__tools_1_1printmtx.html", null ],
    [ "objfnc::ram_limit_str", "structobjfnc_1_1ram__limit__str.html", null ],
    [ "re_globals::rcza", "structre__globals_1_1rcza.html", null ],
    [ "mtxiotools::read_vector", "interfacemtxiotools_1_1read__vector.html", null ],
    [ "pmatools::readint", "interfacepmatools_1_1readint.html", null ],
    [ "decomp_vars::resvct_str", "structdecomp__vars_1_1resvct__str.html", null ],
    [ "pde_objs::scalar_fnc", "interfacepde__objs_1_1scalar__fnc.html", null ],
    [ "mtx::seti", "interfacemtx_1_1seti.html", null ],
    [ "mtx_int::seti", "interfacemtx__int_1_1seti.html", null ],
    [ "global_objs::smartarray_int", "structglobal__objs_1_1smartarray__int.html", null ],
    [ "global_objs::smartarray_real", "structglobal__objs_1_1smartarray__real.html", null ],
    [ "dual_globals::soilpar", "structdual__globals_1_1soilpar.html", null ],
    [ "re_globals::soilpar", "structre__globals_1_1soilpar.html", null ],
    [ "ade_globals::solutexsoil", "structade__globals_1_1solutexsoil.html", null ],
    [ "ade_globals::sorption_str", "structade__globals_1_1sorption__str.html", null ],
    [ "typy::stringlist", "structtypy_1_1stringlist.html", null ],
    [ "decomp_vars::subdomain_str", "structdecomp__vars_1_1subdomain__str.html", null ],
    [ "typy::tcount", "structtypy_1_1tcount.html", null ],
    [ "pde_objs::tensor_fnc", "interfacepde__objs_1_1tensor__fnc.html", null ],
    [ "typy::tident", "structtypy_1_1tident.html", null ],
    [ "pde_objs::time_check", "interfacepde__objs_1_1time__check.html", null ],
    [ "pde_objs::timeint_fnc", "interfacepde__objs_1_1timeint__fnc.html", null ],
    [ "pde_objs::treat_pde_subrt", "interfacepde__objs_1_1treat__pde__subrt.html", null ],
    [ "pde_objs::vector_fnc", "interfacepde__objs_1_1vector__fnc.html", null ],
    [ "global_objs::version", "structglobal__objs_1_1version.html", null ],
    [ "solvers::vrstvy", "structsolvers_1_1vrstvy.html", null ],
    [ "mtxiotools::write_vector", "interfacemtxiotools_1_1write__vector.html", null ]
];