#                             _____________________  _______________________
#                             ___  __ \__  __ \_  / / /_  /___  ____/_  ___/
#                             __  / / /_  /_/ /  / / /_  __/_  __/  _____ \ 
#                             _  /_/ /_  _, _// /_/ / / /_ _  /___  ____/ / 
#                             /_____/ /_/ |_| \____/  \__/ /_____/  /____/  
#                                                                           
# 
#---------------------------------------------D R U t E S-----------------------------------------
#                             (Dual Richards' Unsaturated Equation Solver)
#
#--------------------d r u t e s . c o n f / m e s h / n e t c d f . c o n f ---------------
#-------------------------------------------------------------------------------------------------
#
#model start time
#year month day 
2010 1 1

#
## dispersivity for the large scale model
20000.0


#define minimal discharge treshold to separate river channel
500.0

##define initial condition (at the moment constatnt for the entire watershed
1.0



# boundary ID       boundary type       use bc.dat [y/n]   value         
#-------------------------------------------------------------------------------
101                       1                   y                1.0
102                       1                   n                0.0      
